CREATE TABLE "USER_R" ("U_ID" NUMBER(5, 0), "U_A_NAME" VARCHAR2(100) NOT NULL ENABLE,
 "U_E_NAME" VARCHAR2(100), "U_MNG" NUMBER(5, 0), "GROUP_NO" NUMBER(5, 0), "PASSWORD"
 VARCHAR2(20) NOT NULL ENABLE, "PASSWORD2" VARCHAR2(20), "S_SDATE" DATE, "S_EDATE" DATE,
 "S_STIME" VARCHAR2(10), "S_ETIME" VARCHAR2(10), "LGN_METHOD" NUMBER(1, 0), "DAYACTIVE"
 NUMBER(3, 0), "INACTIVE" NUMBER(1, 0), "INACTIVE_DATE" DATE, "INACTIVE_U_ID" NUMBER(5,
 0), "INACTIVE_RES" VARCHAR2(250), "A_CODE" VARCHAR2(30), "USER_TYPE" NUMBER(2, 0),
 "ADMIN_USER" NUMBER(1, 0), "CHNG_PASSWD_AFTR_LGN" NUMBER(1, 0), "USER_ONLINE" NUMBER(1,
 0), "CONN_WEB_SYS" NUMBER(1, 0), "UPD_PWD_CNT" NUMBER(10, 0), "SCR_THEME_NO" NUMBER,
 "PRINTER_BARCODE_DFLT_NM" VARCHAR2(250), "PRINTER_BARCODE_PATH" VARCHAR2(250),
 "HRS_USER_WEB_SYSTEM" NUMBER(1, 0), "TRMNL_NAME" VARCHAR2(50), "TRMNL_LGN" VARCHAR2(50),
 "OCCUPATION" VARCHAR2(30), "LOGIN" VARCHAR2(30), "LOGOUT" VARCHAR2(30), "LOGGED_ON"
 NUMBER(1, 0), "LOGIN_CNT" NUMBER(38, 0), "CONN_BRN_NO" NUMBER(6, 0), "CONNECTION_TYPE"
 NUMBER(1, 0), "MACHINE_NO" NUMBER(5, 0), "W_CODE_DEF" NUMBER(10, 0), "CC_CODE_DEF"
 VARCHAR2(30), "CASH_NO_DEF" NUMBER(10, 0), "CASH_NO" NUMBER(10, 0), "EMP_NO" NUMBER(10,
 0), "REP_CODE" VARCHAR2(15), "LOAN_A_CODE" VARCHAR2(30), "LOAN_A_CODE_DTL" VARCHAR2(15),
 "INHRT_U_ID" NUMBER(5, 0), "USE_RSLTN_SCR" NUMBER(1, 0), "WCODE_KEEPER" NUMBER(1, 0),
 "COL_NO" NUMBER(10, 0), "VRFCTN_TYP" NUMBER(1, 0), "PDA_NM" VARCHAR2(50), "WORD_PATH"
 VARCHAR2(250), "EXCEL_PATH" VARCHAR2(250), "RMS_USR_TYP" NUMBER(1, 0), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "LOW_LVL_PRICE" NUMBER(3, 0), "HIGH_LVL_PRICE" NUMBER(3, 0), "DFLT_LVL_PRICE" NUMBER(3,
 0), "RMS_USR_DFLT_BILL_DOC_TYP" NUMBER, "RMS_DFLT_HALL" NUMBER(6, 0), "IMG_EDTR_PATH"
 VARCHAR2(250), "EXPROLR_PATH" VARCHAR2(250), "DFLT_CLC_VAT_PRICE_TYP" NUMBER(1, 0),
 "MOBILE_NO" VARCHAR2(30), "CSS_USR_FLG" NUMBER(1, 0), "DRIVER_NO" NUMBER(10, 0),
 "EXCSS_A_CODE" VARCHAR2(30), "EXCSS_A_CODE_DTL" VARCHAR2(15))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_USER_HEAD" ("U_ID" NUMBER(5, 0), "BRN_YEAR" NUMBER(4, 0), "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "CMP_ANAME"
 VARCHAR2(40) NOT NULL ENABLE, "CMP_ENAME" VARCHAR2(40), "BRN_ADES" VARCHAR2(40) NOT NULL
 ENABLE, "BRN_EDES" VARCHAR2(40), "BRN_AADD" VARCHAR2(40), "BRN_EADD" VARCHAR2(40),
 "BRN_ATELE" VARCHAR2(40), "BRN_ETELE" VARCHAR2(40), "BRN_AFAX" VARCHAR2(40), "BRN_EFAX"
 VARCHAR2(40), "BRN_ABOX" VARCHAR2(40), "BRN_EBOX" VARCHAR2(40), "CMP_IMG" VARCHAR2(30),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE,
 "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "RPRT_HDR_TYP" NUMBER(2, 0), "RPRT_HDR_IMG"
 BLOB, "RPRT_HDR_IMG_NM" VARCHAR2(200), "RPRT_HDR_IMG_NM_H" VARCHAR2(200))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING
 NOCOMPRESS LOB ("RPRT_HDR_IMG") STORE AS BASICFILE  (TABLESPACE "IAS_ADM_DATA" ENABLE
 STORAGE IN ROW CHUNK 8192 RETENTION  NOCACHE LOGGING  STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));

CREATE TABLE "IAS_USER_GROUP" ("GROUP_NO" NUMBER(5, 0), "GROUP_A_NAME" VARCHAR2(100) NOT
 NULL ENABLE, "GROUP_E_NAME" VARCHAR2(100), "ADMIN_USER" NUMBER(1, 0), "REST_GRP"
 NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "PRIVILEGE" ("U_ID" NUMBER(5, 0), "FORM_NO" NUMBER(5, 0), "INCLUDE_FLAG"
 NUMBER(1, 0), "AD_FLAG" NUMBER(1, 0), "DEL_FLAG" NUMBER(1, 0), "MOD_FLAG" NUMBER(1, 0),
 "VIEW_FLAG" NUMBER(1, 0), "PRINT_FLAG" NUMBER(1, 0), "VWREP_FLAG" NUMBER(1, 0),
 "VRFY_FLAG" NUMBER(1, 0), "PST_FLAG" NUMBER(1, 0), "F_ORDER_NO" NUMBER(5, 0), "AD_DATE"
 DATE, "AD_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING
 NOCOMPRESS;

CREATE TABLE "PRIVILEGE_CC" ("U_ID" NUMBER(5, 0), "CC_CODE" VARCHAR2(30), "ADD_FLAG"
 NUMBER(1, 0), "VIEW_FLAG" NUMBER(1, 0), "AD_DATE" DATE, "AD_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "PRIVILEGE_FIXED" ("U_ID" NUMBER(5, 0), "CRLIMIT_TYPE" NUMBER(1, 0),
 "PMANUAL" NUMBER(1, 0), "INV_DIS_LMT" NUMBER, "HIDE_COST" NUMBER(1, 0), "PLIMIT_TYPE"
 NUMBER(1, 0), "PAY_AVL_QTY" NUMBER(1, 0), "PAY_ITM_MIN_QTY" NUMBER(1, 0), "INV_REP"
 NUMBER(1, 0), "L_PRICE" NUMBER(1, 0), "H_PRICE" NUMBER(1, 0), "SHOW_MAIN_ACC_REP"
 NUMBER(1, 0), "AR_UPDATE_FREE_QTY" NUMBER(1, 0), "AR_UPDATE_ITM_ALLOW_DISC" NUMBER(1, 0)
, "USE_SO_IN_SI" NUMBER(1, 0), "UPDATE_BILLS_DATA" NUMBER(1, 0), "UPDATE_KIMB_AMT"
 NUMBER(1, 0), "PRINT_DOC" NUMBER(1, 0), "USER_VIEW_DOC_ENTR" NUMBER(1, 0),
 "SHOW_AR_REP_DAY" NUMBER(5, 0), "ALLOW_BILL_FQTY_ONLY" NUMBER(1, 0),
 "ALLOW_ENTER_ZERO_COST" NUMBER(1, 0), "PRICE_LMT_PRV" NUMBER(1, 0),
 "CHECK_CREDIT_PERIOD" NUMBER(1, 0), "FILL_OUTBILLS_ONCE" NUMBER(1, 0), "SLCT_DOC_TYPE"
 NUMBER(1, 0), "ACC_LMT_PRV" NUMBER(1, 0), "SHOW_STKCOST_INQTY_DISC_FQTY" NUMBER(1, 0),
 "PAY_VCHR_MST_AC_PRV" NUMBER(1, 0), "RCV_VCHR_MST_AC_PRV" NUMBER(1, 0),
 "ALLOW_MOD_FLD_NAME" NUMBER(1, 0), "CHECK_CST_BLK_LST" NUMBER(1, 0), "MOD_ITM_DISC"
 NUMBER(1, 0), "MAX_DISC_ITM_PER" NUMBER, "UPD_DOC_HRS_PRD" NUMBER, "UPD_DOC_DAY_PRD"
 NUMBER(3, 0), "DEL_DOC_HRS_PRD" NUMBER, "DEL_DOC_DAY_PRD" NUMBER(3, 0), "ALLOW_IMP_XLS"
 NUMBER(1, 0), "ALLOW_CALL_REP_BTN" NUMBER(1, 0), "AR_UPDATE_ITM_NOT_ALLOW_DISC" NUMBER(1
, 0), "INV_ADD_DIS_LMT" NUMBER, "CHK_PRIV_ACS_REP" NUMBER(1, 0), "CHK_PRIV_CCS_REP"
 NUMBER(1, 0), "CHK_PRIV_PJS_REP" NUMBER(1, 0), "CHK_PRIV_BRN_REP" NUMBER(1, 0),
 "CHECK_RET_PER" NUMBER(1, 0), "UPD_SI_PAY_TYPE" NUMBER(1, 0), "CHANGE_PRICE_PI" NUMBER(1
, 0), "ADD_DISC_IN_CR_PRD_ONLY" NUMBER(1, 0), "CHK_PRIV_ACS_ASTMNT" NUMBER(1, 0),
 "CHK_PRIV_CCS_ASTMNT" NUMBER(1, 0), "CHK_PRIV_PJS_ASTMNT" NUMBER(1, 0),
 "ALLOW_PRNTDOC_BFR_AUDIT_REF" NUMBER(1, 0), "ALLOW_CANCEL_AUDIT_REF" NUMBER(1, 0),
 "USE_INSTALL_JV" NUMBER(1, 0), "USE_INSTALL_RCPT" NUMBER(1, 0), "USE_INSTALL_PYMNT"
 NUMBER(1, 0), "ALLOW_UPDATE_AUTO_DATE" NUMBER(1, 0), "ALLOW_UPDATE_ORDR_PRICE_INBILL"
 NUMBER(1, 0), "SHOW_AVL_QTY_IN_REQ" NUMBER(1, 0), "SHOW_AVL_QTY_IN_TR" NUMBER(1, 0),
 "ALLOW_SHOW_JRNL" NUMBER(1, 0), "INV_DIS_LMT_ITM" NUMBER, "USE_RET_WHTRNS" NUMBER(1, 0),
 "CHK_PRIV_ACTV_ASTMNT" NUMBER(1, 0), "CHK_PRIV_ACTV_REP" NUMBER(1, 0),
 "EXCD_AMT_CNTRCT_IN_BILL" NUMBER(1, 0), "AR_SHOW_STK_CST_REP" NUMBER(1, 0),
 "ALLOW_DEL_ITM_FROM_POS_BILL" NUMBER(1, 0), "AR_ALLOW_SALES_DUE_DR" NUMBER(1, 0),
 "AR_ALLOW_SALES_PRV_DR" NUMBER(1, 0), "AR_CHK_PRD_AFTR_DUE" NUMBER(1, 0),
 "USE_BALANCED_ACY_JV" NUMBER(1, 0), "ALLOW_COPY_PRICE_LVL" NUMBER(1, 0),
 "ALLOW_CHANGE_POS_QTY" NUMBER(1, 0), "AP_ALLOW_UPDAE_FILL_QTY" NUMBER(1, 0),
 "PLIMIT_PER" NUMBER, "CRLIMIT_PER" NUMBER, "ALLOW_HUNG_BILLS" NUMBER(1, 0),
 "USE_UNDO_CTRLU" NUMBER(1, 0), "RTN_BILL_NO" NUMBER(1, 0), "PRINT_PREV_BILL" NUMBER(1,
 0), "CHK_PRIV_BRN_ASTMNT" NUMBER(1, 0), "PAYMNT_FOR_VNDR_ZERO_CR" NUMBER(1, 0),
 "NOT_ALLW_MOD_DTL_DOC_AFTR_SAVE" NUMBER(1, 0), "FILL_STKCOST_INTO_PRICE_SI" NUMBER(1, 0)
, "ALLOW_UPD_DISC_RTBILL" NUMBER(1, 0), "SHOW_GL_CASH_REP_DAY" NUMBER(5, 0),
 "SHW_AMT_QTY_STATC_AR_REP" NUMBER(1, 0), "ALLOW_UPD_QTY_WT" NUMBER(1, 0),
 "AR_ENTR_PRICE_MANUAL_SR" NUMBER(1, 0), "AR_ALLOW_DISC_ITM_QUT_PRM_SI" NUMBER(1, 0),
 "ALLOW_FILL_SERIALNO" NUMBER(1, 0), "BGT_LMT_PRV" NUMBER(1, 0), "ALLOW_UNAPPROVED"
 NUMBER(1, 0), "USE_HIDE_PRICE_ITM_BARCODE" NUMBER(1, 0), "AR_MAX_INSTLMNT" NUMBER(2, 0),
 "ALLOW_MOD_PRCNT_PRICE_FROM_CST" NUMBER(1, 0), "AR_MAX_ADD_FREE_QTY_ITM_PER" NUMBER,
 "AR_AUTO_PRNT_SI_AFTR_SAVE" NUMBER(1, 0), "AR_AUTO_PRNT_SR_AFTR_SAVE" NUMBER(1, 0),
 "USR_SHW_MSG_B4SAVE" NUMBER(1, 0), "USE_WO_IN_SI" NUMBER(1, 0),
 "ALLW_UPD_STANDBY_SI_ONLY" NUMBER(1, 0), "DSPLY_PRV_AC_STMNT" NUMBER(1, 0),
 "ALLW_UPD_CST_SEQ" NUMBER(1, 0), "MOD_MBL_VCHR_RCV_DOC" NUMBER(1, 0),
 "ALLOW_UPD_VAT_PER" NUMBER(1, 0), "USE_TRL_LOAD_IN_SI" NUMBER(1, 0),
 "ALLOW_EXCD_VNDR_PRICE" NUMBER(1, 0), "USE_FREE_RMS_INVC" NUMBER(1, 0),
 "ALLW_CHNG_DLVRY_SRVC_AMT" NUMBER, "UPD_MAX_LMT_PSBL" NUMBER(1, 0),
 "ALLW_CHNG_RNT_PRICE" NUMBER(1, 0), "ALLOW_UNPST_RNT" NUMBER(1, 0), "ALLOW_PST_RNT_PRD"
 NUMBER(1, 0), "ALLOW_UPD_DSCHRG_DATE" NUMBER(1, 0), "ALLOW_UPD_TRNSFR_DATE" NUMBER(1, 0)
, "ALLOW_OUT_PTNT_NO_ZERO_BLNC" NUMBER(1, 0), "ALLOW_CNCL_DSCHRG_PTNT" NUMBER(1, 0),
 "ALLOW_OUT_PTNT_NO_ORDR_EXC" NUMBER(1, 0), "ALLOW_PRNT_RSLT_UNVRFD" NUMBER(1, 0),
 "ALLOW_UPD_PYMNT_IN_ADMT" NUMBER(1, 0), "NOT_SHW_KIT_ITM_CNTNT" NUMBER(1, 0), "AD_DATE"
 DATE, "AD_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_CNT" NUMBER(10
, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "USE_STAFF_FEEDING_RMS_INVC" NUMBER(1, 0), "USE_DAMGE_RMS_INVC" NUMBER(1, 0),
 "USE_HSPTLTY_RMS_INVC" NUMBER(1, 0), "ALLOW_DEL_HUNG_BILLS" NUMBER,
 "NOT_ALLOW_UP_C_CODE_PTNT_BILLS" NUMBER(1, 0), "ALLW_APRVD_POS_RTBILL" NUMBER,
 "ALLW_PRNT_LAST_BILL" NUMBER, "ALLW_CHNG_PI_PRC_CNCT_INCM" NUMBER(1, 0),
 "ALLOW_OUT_BILL_CST_LRGR_BLNC" NUMBER(1, 0), "ALLOW_UPD_BED_PRICE" NUMBER(1, 0),
 "SHOW_DCTR_PRCNT_IN_BILL" NUMBER(1, 0), "ALLW_ENTR_WGHT_MNUL_SO" NUMBER(1, 0),
 "ALLW_UPD_STK_EX_RATE_IN_TRNS" NUMBER(1, 0), "ALLW_EXCD_MAX_PRD_RTRN_INSRNC" NUMBER(1,
 0), "ALLW_PRNT_LST_RMS_INVC" NUMBER(1, 0), "UPD_PI_PAY_TYPE" NUMBER(1, 0),
 "SHOW_PRICE_IN_OUTBILL" NUMBER(1, 0), "ALLOW_DEL_ITM_FROM_RMS_BILL" NUMBER(1, 0),
 "SHOW_AVL_QTY_IN_MAN_INV" NUMBER(1, 0), "ALLOW_DRG_ORDR_WITHOUT_QTY_CHK" NUMBER(1, 0),
 "CHK_BLNC_PTNT_ADMT_CSH_IN_BILL" NUMBER(1, 0), "ALLW_RTRN_BILL_OTHR_CSHR" NUMBER(1, 0),
 "REM_ALLW_UPDT_VCHR_DSC" NUMBER(1, 0), "OPN_SYS_MORE_ONCE" NUMBER,
 "GLS_SHW_BLNC_IN_TRNS" NUMBER(1, 0), "ALLW_MOD_DOC_AFTR_PRNT" NUMBER(1, 0),
 "ALLW_DEL_DOC_AFTR_PRNT" NUMBER(1, 0), "USE_RSRV_SLS_QTY_NO_OUT_IN_INV" NUMBER(1, 0),
 "MRP_MPS_ISU_EXTRNL_WO" NUMBER(1, 0), "MRP_CRT_MULTI_RCV_TRNS" NUMBER(1, 0),
 "MRP_SFC_ISU_EXTRNL_TRN" NUMBER(1, 0), "MRP_MPS_PR_WO_APPROVE" NUMBER(1, 0),
 "MRP_SFC_PR_MRQ_APPROVE" NUMBER(1, 0), "MRP_SFC_PR_MRC_APPROVE" NUMBER(1, 0),
 "MRP_SFC_PR_SFC_APPROVE" NUMBER(1, 0), "MRP_SFC_PR_MDV_APPROVE" NUMBER(1, 0),
 "MRP_SFC_PR_MRT_APPROVE" NUMBER(1, 0), "RMS_LMT_TM_CNCL_ORDR" NUMBER(5, 0),
 "RMS_ALLW_MINUS_CHF_QTY" NUMBER(1, 0), "RMS_ALLW_CNCL_UNDR_PRCSS_QTY" NUMBER(1, 0),
 "ALLW_UPDT_PO_TO_BILL_TYP" NUMBER, "ALLW_UPDT_QUOT_TO_PO_TYP" NUMBER,
 "PUR_BY_PUR_UNIT_ONLY" NUMBER, "SHW_ITM_DISC_AVG_AP_SI" NUMBER(1, 0),
 "ALLW_SAL_NEW_EXPDATE" NUMBER(1, 0), "ALLW_ENTR_FREE_QTY_SO" NUMBER(1, 0),
 "SHW_STKCST_PRFT_MRGN_SAL" NUMBER(1, 0), "USE_SRCH_ITM_NM_ARABIC" NUMBER(1, 0),
 "SRCH_ITM_CRTRIA" NUMBER(1, 0), "USE_ARCHV_FILE_IN_DB" NUMBER(1, 0),
 "ALLW_FILL_ALL_ITM_TO_RTBILL" NUMBER(1, 0), "PRNT_CNT_FOR_BILL" NUMBER(2, 0),
 "ALLW_EXCD_LMT_SAL_ITM" NUMBER(1, 0), "SHW_BLNC_IN_CSH_INVNTRY" NUMBER(1, 0),
 "GLS_ALLW_UPDT_REPRS_COMM" NUMBER(1, 0), "GLS_STMNT_HIDE_OPN_BLNC" NUMBER(1, 0),
 "MRP_VARY_PRDCT_CST_PRIV" NUMBER(1, 0), "SHW_ALRT_SCR_AFTR_LGN" NUMBER(1, 0),
 "ALLW_PRNT_PRICE_WITH_TAX" NUMBER(1, 0), "H_ADD_PER_CMPNS_QTY" NUMBER(3, 0),
 "ALLW_DECRS_QTY" NUMBER, "MRP_SFC_ALLW_ACT_PRD_LESS_STD" NUMBER(1, 0), "ALLOW_EXP_XLS"
 NUMBER(1, 0), "OUT_ITM_SRL_WITH_BARCODE" NUMBER(1, 0), "MNDTRY_BILL_NO_PAYMNT" NUMBER(1,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "PRIVILEGE_GC" ("U_ID" NUMBER(5, 0), "G_CODE" VARCHAR2(10), "ADD_FLAG"
 NUMBER(1, 0), "VIEW_FLAG" NUMBER(1, 0), "AD_DATE" DATE, "AD_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "PRIVILEGE_WH" ("U_ID" NUMBER(5, 0), "W_CODE" NUMBER(10, 0), "ADD_FLAG"
 NUMBER(1, 0), "VIEW_FLAG" NUMBER(1, 0), "AD_DATE" DATE, "AD_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "TRNSFR_WCODE_FLG" NUMBER(1, 0))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_USR_LGN_HSTRY" ("U_ID" NUMBER(5, 0) NOT NULL ENABLE, "TRMNL_NM"
 VARCHAR2(30), "LGN_TYP" NUMBER(1, 0), "LGN_OUT_DATE" DATE NOT NULL ENABLE, "LNG_NO"
 NUMBER(3, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL
 ENABLE, "BRN_YEAR" NUMBER(4, 0) NOT NULL ENABLE, "BRN_USR" NUMBER(3, 0) NOT NULL ENABLE,
 "APPL_NO" NUMBER, "HSTRY_NO" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_HISTORY" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_USER_HEAD" ("U_ID" NUMBER(5, 0), "BRN_YEAR" NUMBER(4, 0), "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "CMP_ANAME"
 VARCHAR2(40) NOT NULL ENABLE, "CMP_ENAME" VARCHAR2(40), "BRN_ADES" VARCHAR2(40) NOT NULL
 ENABLE, "BRN_EDES" VARCHAR2(40), "BRN_AADD" VARCHAR2(40), "BRN_EADD" VARCHAR2(40),
 "BRN_ATELE" VARCHAR2(40), "BRN_ETELE" VARCHAR2(40), "BRN_AFAX" VARCHAR2(40), "BRN_EFAX"
 VARCHAR2(40), "BRN_ABOX" VARCHAR2(40), "BRN_EBOX" VARCHAR2(40), "CMP_IMG" VARCHAR2(30),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE,
 "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "RPRT_HDR_TYP" NUMBER(2, 0), "RPRT_HDR_IMG"
 BLOB, "RPRT_HDR_IMG_NM" VARCHAR2(200), "RPRT_HDR_IMG_NM_H" VARCHAR2(200))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING
 NOCOMPRESS LOB ("RPRT_HDR_IMG") STORE AS BASICFILE  (TABLESPACE "IAS_ADM_DATA" ENABLE
 STORAGE IN ROW CHUNK 8192 RETENTION  NOCACHE LOGGING  STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));

