CREATE TABLE "WAREHOUSE_DETAILS" ("W_CODE" NUMBER(10, 0), "W_NAME" VARCHAR2(100) NOT NULL
 ENABLE, "W_E_NAME" VARCHAR2(100), "LOCATION" VARCHAR2(100), "TEL_NO" VARCHAR2(30),
 "INACTIVE" NUMBER(1, 0), "WH_KEEPER" VARCHAR2(100), "WHG_CODE" NUMBER(10, 0), "W_TYPE"
 NUMBER(1, 0), "USE_BOE" NUMBER(1, 0), "NO_SALE" NUMBER(1, 0), "CHK_AVL_QTY" NUMBER(1, 0)
, "TR_A_CODE" VARCHAR2(30), "CC_CODE" VARCHAR2(30), "CNTRY_NO" NUMBER(4, 0), "GPS"
 VARCHAR2(100), "PROV_NO" NUMBER(10, 0), "CITY_NO" NUMBER(10, 0), "R_CODE" NUMBER(10, 0),
 "W_SER" NUMBER(5, 0), "CONN_BRN_NO" NUMBER(6, 0), "ACTIVITY_NO" NUMBER(5, 0),
 "MAIN_WCODE" NUMBER, "DB_LINK_NAME" VARCHAR2(250), "USE_AUTO_REC_WHTRNS" NUMBER(1, 0),
 "PRICE_LVL" NUMBER(3, 0), "SRVC_FLG" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE"
 DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10
, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "LATITUDE" VARCHAR2(100),
 "LONGITUDE" VARCHAR2(100), "GLN_CODE" VARCHAR2(500), "W_L_ADDRS" VARCHAR2(1000),
 "W_F_ADDRS" VARCHAR2(1000), "SHO_WC_TYP" NUMBER(1, 0), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "SO_DSC" VARCHAR2(1000), "SO_TYPE" NUMBER(5, 0), "SC_NO" NUMBER(3, 0),
 "BANK_NO" NUMBER(10, 0), "REP_CODE" VARCHAR2(15), "COL_NO" NUMBER(10, 0), "C_CODE"
 VARCHAR2(30), "CLC_TYP_NO_TAX" NUMBER(5, 0), "C_GROUP_CODE" NUMBER(10, 0), "SHO_SYS_TYP"
 NUMBER(2, 0), "USE_PRPRTN_FLG" NUMBER(1, 0), "USE_BIN_MOV" NUMBER(1, 0), "WH_CST_LMT"
 NUMBER(38, 0), "FOR_DMGD_ITM" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS
 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "WAREHOUSE_GROUP" ("WHG_CODE" NUMBER(10, 0), "WHG_A_NAME" VARCHAR2(100) NOT
 NULL ENABLE, "WHG_E_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITM_MST" ("I_CODE" VARCHAR2(30), "I_NAME" VARCHAR2(100) NOT NULL ENABLE
, "I_E_NAME" VARCHAR2(100), "G_CODE" VARCHAR2(10) NOT NULL ENABLE, "GRP_CLASS_CODE"
 VARCHAR2(20), "MNG_CODE" VARCHAR2(10), "SUBG_CODE" VARCHAR2(10), "ITEM_SIZE" NUMBER,
 "ITEM_TYPE" NUMBER(5, 0), "PRIMARY_COST" NUMBER, "I_CWTAVG" NUMBER, "I_DESC"
 VARCHAR2(2000), "ALTER_CODE" VARCHAR2(30), "MANF_CODE" VARCHAR2(30), "BLOCKED" NUMBER(1,
 0), "INACTIVE" NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(250), "INACTIVE_DATE" DATE,
 "INACTIVE_U_ID" NUMBER(5, 0), "SERVICE_ITM" NUMBER(1, 0), "CASH_SALE" NUMBER(1, 0),
 "NO_RETURN_SALE" NUMBER(1, 0), "RETURN_PERIOD" NUMBER(5, 0), "KIT_ITM" NUMBER(1, 0),
 "USE_EXP_DATE" NUMBER(1, 0), "USE_BATCH_NO" NUMBER(1, 0), "USE_SERIALNO" NUMBER(1, 0),
 "USE_ATTCH" NUMBER(1, 0), "VAT_TYPE" NUMBER(1, 0), "VAT_PER" NUMBER(7, 4), "ALLOW_DISC"
 NUMBER(1, 0), "DISC_PER" NUMBER(7, 4), "ALLOW_DISC_PI" NUMBER(1, 0), "REST_ITM" NUMBER(1
, 0), "DISC_PER_PI" NUMBER(7, 4), "ALLOW_FREE_QTY" NUMBER(1, 0), "FREE_QTY_PER" NUMBER(7,
 4), "USE_QTY_FRACTION" NUMBER(1, 0), "UNDER_SELLING" NUMBER(1, 0), "GROUP_NO" NUMBER(5,
 0), "ILEV_NO" NUMBER(3, 0), "I_IMG" VARCHAR2(30), "DAY_ITM_EXPIRE" NUMBER(3, 0),
 "MIN_LMT_COST_PER" NUMBER(3, 0), "MAX_LMT_COST_PER" NUMBER(3, 0), "FIELD1"
 VARCHAR2(1000), "FIELD2" VARCHAR2(1000), "FIELD3" VARCHAR2(1000), "FIELD4"
 VARCHAR2(1000), "FIELD5" VARCHAR2(1000), "FIELD6" VARCHAR2(1000), "FIELD7"
 VARCHAR2(1000), "FIELD8" VARCHAR2(1000), "FIELD9" VARCHAR2(1000), "FIELD10"
 VARCHAR2(1000), "ASSISTANT_NO" VARCHAR2(10), "DETAIL_NO" VARCHAR2(10), "LENGTH_ITM"
 NUMBER, "WIDTH_ITM" NUMBER, "HEIGHT_ITM" NUMBER, "SIZE_ITM" NUMBER, "AREA_ITM" NUMBER,
 "WEIGHT_ITM" NUMBER, "SEASON_ITM" VARCHAR2(60), "ORE_ITM" VARCHAR2(60), "MARK_ITM"
 VARCHAR2(60), "COMPANY_ITM" VARCHAR2(60), "COUNTRY_ITM" VARCHAR2(60), "INCOME_DATE" DATE
, "REQUIREMENT" NUMBER(1, 0), "ITEM_STORE" NUMBER(1, 0), "ASSETS" NUMBER(1, 0),
 "HAS_COMM" NUMBER(1, 0), "COMM_TYPE" NUMBER(1, 0), "COMM_AMT" NUMBER, "ACTIVITY_NO"
 NUMBER(5, 0), "V_CODE" VARCHAR2(15), "VNDR_A_CY" VARCHAR2(7), "VNDR_PRICE" NUMBER,
 "VNDR_I_CODE" VARCHAR2(30), "HOT_KEY" NUMBER(10, 0), "LOW_LMT_PRNT_FRST" NUMBER(5, 0),
 "LOW_LMT_PRNT_SCND" NUMBER(5, 0), "LOW_LMT_APP_REQ_ATTCH" NUMBER(5, 0),
 "LOW_LMT_NOT_APP_REQ_ATTCH" NUMBER(5, 0), "IMP_XLS" NUMBER(1, 0), "DOC_TYPE_REF"
 NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0), "WEIGHTED"
 NUMBER(1, 0), "BALANCE_NO" NUMBER, "RET_ITM_BEFOR_EXP_PRD" NUMBER(3, 0), "MSUR_UNT_REP"
 VARCHAR2(10), "PI_BILL_NO" NUMBER, "USE_GRANT" NUMBER(1, 0), "GRANT_PERIOD" NUMBER(3, 0)
, "ITM_COLOR" VARCHAR2(60), "ITM_MEASURE" VARCHAR2(60), "USE_WEIGHT" NUMBER(1, 0),
 "CONN_ITM_SO_INC" NUMBER(1, 0), "LNK_BRCHR" VARCHAR2(255), "LNK_YOUTUBE" VARCHAR2(255),
 "USE_EMP_FLG" NUMBER(1, 0), "ALTR_MLT_FLG" NUMBER(1, 0), "I_F_DESC" VARCHAR2(2000),
 "REST_ITM_COMBO" NUMBER(1, 0), "USED_ITM" NUMBER(1, 0), "MRP_ITM" NUMBER(1, 0),
 "MRP_ITM_CLSS" NUMBER(2, 0), "CST_PER" NUMBER(1, 0), "PRFT_MRGN_PRCNT" NUMBER,
 "CHK_AVL_QTY_IN_RES" NUMBER(1, 0), "FOOD_GRP_NO" VARCHAR2(7),
 "USE_AUTO_PST_RMS_DATA_TO_INV" NUMBER(1, 0), "HPS_ITM" NUMBER(1, 0), "GNR_ITM_FLG"
 NUMBER(1, 0), "PRCDR_TYP" NUMBER(5, 0), "HSN_CODE" VARCHAR2(30), "CST_STANDR" NUMBER,
 "CST_LAST_PROD" NUMBER, "ITM_ORDR_NO" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(6, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "SHRT_ITM_L_NM" VARCHAR2(100),
 "SHRT_ITM_F_NM" VARCHAR2(100), "ITM_MIN_QTY" NUMBER, "ITM_MAX_QTY" NUMBER,
 "SUB_FOOD_GRP_NO" VARCHAR2(7), "SMPL_TYP" NUMBER(5, 0), "RNT_SRVC" NUMBER(1, 0),
 "PST_WITH_ADMT" NUMBER(1, 0), "PST_WITH_RNT" NUMBER(1, 0), "HAS_PRCNT" NUMBER(1, 0),
 "BRTH_SRVC" NUMBER(1, 0), "EQPMNT_SRVC" NUMBER(1, 0), "SRGRY_CLSS" NUMBER(5, 0),
 "SRVC_SORT" NUMBER, "CSSD_FLG" NUMBER(1, 0), "LNDRY_FLG" NUMBER(1, 0), "USE_QR_CODE"
 NUMBER(1, 0), "ITM_MIN_LMT_QTY" NUMBER, "ITM_MAX_LMT_QTY" NUMBER, "ITM_ROL_LMT_QTY"
 NUMBER, "DFLT_ASM_ORD_QTY" NUMBER, "FILL_ITM_CMPNNT_IN_RMS_INVC" NUMBER(1, 0),
 "USE_PRICE_EXPIRE_DATE_OPTIONAL" NUMBER(1, 0), "USE_PRICE_BATCH_NO_OPTIONAL" NUMBER(1,
 0), "PRCHS_SRVC_AC_CODE" VARCHAR2(30), "FEED_ITM_FLG" NUMBER(1, 0), "INSRNC_FLG"
 NUMBER(1, 0), "GTIN_CODE" VARCHAR2(100), "USE_SRLNO_TYPE" NUMBER(1, 0),
 "USE_QR_CODE_TYPE" NUMBER(1, 0), "QR_CODE_MTHD_NO" NUMBER(1, 0),
 "USE_BATCH_NO_AUTO_SQ_FLG" NUMBER(1, 0), "BATCH_NO_MTHD_NO_SQ" NUMBER(10, 0), "EXEC_TAT"
 NUMBER, "EXEC_TAT_UNT" NUMBER(5, 0), "HIDE_ITM_CHF_SCR_FLG" NUMBER(1, 0),
 "KIT_ITM_CLSSFCTN_TYP" NUMBER(1, 0), "STATCL_CLSS" NUMBER(5, 0),
 "GET_AVL_QTY_FROM_CMPNNT_FLG" NUMBER(1, 0), "KIT_ITEM_RANK" NUMBER, "LMT_QTY_SAL_CST"
 NUMBER, "WGHT_VAL_ITM" NUMBER(5, 0), "USE_ITM_IN_CSS_SYS_FLG" NUMBER(1, 0),
 "INIT_PRIMARY_COST" NUMBER, "CHK_ITM_PCS_MNDTRY_FLG" NUMBER(1, 0), "EXCD_PER" NUMBER(10,
 0), "USED_IN_KIT_ITM" NUMBER(1, 0), "MWS_CHK_FLG" NUMBER(1, 0), "DFLT_TIME_MNT"
 NUMBER(10, 0), "LOST_PRCNT_IN_PRCHS" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS
 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_GRP_ITM_LVL" ("GRP_CODE" VARCHAR2(20), "GRP_L_NAME" VARCHAR2(100) NOT
 NULL ENABLE, "GRP_F_NAME" VARCHAR2(100), "GRP_CODE_PARENT" VARCHAR2(20),
 "AFFECTED_BY_TRANS" NUMBER(1, 0), "G_CODE" VARCHAR2(30), "ACTIVITY_NO" NUMBER(5, 0),
 "DFLT_PRC_PRCNT_FROM_PRIM_COST" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_GRP_ITM_LVL_TREE" ("GRP_CODE" VARCHAR2(20), "GRP_CODE_TREE"
 VARCHAR2(20), "GRP_NAME" VARCHAR2(60), "GRP_LVL" NUMBER(5, 0), "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_ITM_LVL_MEASURE" ("ILEV_NO" NUMBER(3, 0), "FLG_VALUE" NUMBER,
 "FLG_CODE" VARCHAR2(30), "COMP_TYPE" NUMBER, "ARG_TYPE" NUMBER(2, 0), "FROM_AMT_PER"
 NUMBER, "TO_AMT_PER" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5,
 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITM_LVL_MEASURE_DTL" ("FLG_VALUE" NUMBER, "DOC_NO" NUMBER(15, 0) NOT
 NULL ENABLE, "DOC_SER" NUMBER(38, 0) NOT NULL ENABLE, "USED" NUMBER(1, 0), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP"
 LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITM_MEASUR_MST" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "DOC_DATE" DATE NOT NULL ENABLE, "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CST" NUMBER(1, 0), "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITM_MEASUR_DTL" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "ITM_UNT"
 VARCHAR2(10), "P_SIZE" NUMBER, "ILEV_NO" NUMBER(3, 0), "ITM_RATIO" NUMBER,
 "ITM_RATIO_DEG" NUMBER(4, 0), "PROFIT_MARGIN_RATE" NUMBER, "PROFIT_MARGIN_RATE_DEG"
 NUMBER(4, 0), "DAILY_SALES_RATE" NUMBER, "DAILY_SALES_RATE_DEG" NUMBER(4, 0),
 "GEN_SALES_RATE" NUMBER, "GEN_SALES_RATE_DEG" NUMBER(4, 0), "NET_SALES_QTY" NUMBER,
 "NET_SALES_QTY_DEG" NUMBER(4, 0), "NET_SALES_AMT" NUMBER, "NET_SALES_AMT_DEG" NUMBER(4,
 0), "SALE_RATE_F_INC" NUMBER, "SALE_RATE_F_INC_DEG" NUMBER(4, 0), "AD_U_ID" NUMBER(5, 0)
, "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "MEASUREMENT" ("MEASURE_CODE" VARCHAR2(10), "MEASURE" VARCHAR2(30),
 "MEASURE_F_NM" VARCHAR2(30), "MEASURE_TYPE" NUMBER(1, 0), "MEASURE_WT_TYPE" NUMBER(2, 0)
, "MEASURE_WT_CONN" NUMBER(1, 0), "DFLT_SIZE" NUMBER(10, 0), "ALLOW_UPD" NUMBER(1, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "MEASURE_CODE_GB" VARCHAR2(10))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS
 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITM_BATCH" ("I_CODE" VARCHAR2(30), "COL_NO1" NUMBER(1, 0),
 "BATCH_DESC_NO1" VARCHAR2(15), "COL_NO2" NUMBER(1, 0), "BATCH_DESC_NO2" VARCHAR2(15),
 "COL_NO3" NUMBER(1, 0), "BATCH_DESC_NO3" VARCHAR2(15), "COL_NO4" NUMBER(1, 0),
 "BATCH_DESC_NO4" VARCHAR2(15), "COL_NO5" NUMBER(1, 0), "BATCH_DESC_NO5" VARCHAR2(15),
 "BATCH_NO" VARCHAR2(30), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL
 ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "PR_REP" NUMBER(6, 0), "UP_CNT"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_ITM_UNT_BARCODE" ("I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10) NOT
 NULL ENABLE, "P_SIZE" NUMBER NOT NULL ENABLE, "BARCODE" VARCHAR2(30), "BATCH_NO"
 VARCHAR2(30), "EXPIRE_DATE" DATE, "NO_SALE" NUMBER(1, 0), "NO_PRINT" NUMBER(1, 0),
 "FLEX_NO" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "DEAL_WITH_PRCHS_FLG" NUMBER(1, 0),
 "BARCODE_L_DSC" VARCHAR2(250), "BARCODE_F_DSC" VARCHAR2(250), "MAIN_BARCODE" NUMBER(1,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITEM_PRICE" ("LEV_NO" NUMBER(3, 0), "I_CODE" VARCHAR2(30), "ITM_UNT"
 VARCHAR2(10) NOT NULL ENABLE, "P_SIZE" NUMBER, "W_CODE" NUMBER(10, 0), "FROM_QTY"
 NUMBER(15, 0), "TO_QTY" NUMBER(15, 0), "I_PRICE" NUMBER(24, 9), "IMP_XLS" NUMBER(1, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "DCTR_PRICE" NUMBER,
 "MIN_ITM_PRICE" NUMBER, "MAX_ITM_PRICE" NUMBER, "EXPIRE_DATE" DATE NOT NULL ENABLE,
 "BATCH_NO" VARCHAR2(30) NOT NULL ENABLE)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_ITEM_PRICE_HISTORY" ("AUD_NO" NUMBER(38, 0), "AUD_TYPE" NUMBER(1, 0),
 "LEV_NO" NUMBER(3, 0), "I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10), "P_SIZE" NUMBER,
 "W_CODE" NUMBER(10, 0), "FROM_QTY" NUMBER(15, 0), "TO_QTY" NUMBER(15, 0), "I_PRICE"
 NUMBER(24, 9), "PREV_I_PRICE" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "AUD_U_ID" NUMBER(5, 0), "AUD_DATE" DATE, "DOC_NO"
 NUMBER(38, 0), "DOC_DATE" DATE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "EXPIRE_DATE" DATE NOT NULL ENABLE, "BATCH_NO" VARCHAR2(30) NOT NULL
 ENABLE, "MIN_ITM_PRICE" NUMBER, "MAX_ITM_PRICE" NUMBER, "PREV_MAX_ITM_PRICE" NUMBER,
 "PREV_MIN_ITM_PRICE" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_AUDIT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PRICING_LEVELS" ("LEV_NO" NUMBER(3, 0), "LEV_A_NAME" VARCHAR2(60) NOT
 NULL ENABLE, "LEV_E_NAME" VARCHAR2(60), "A_CY" VARCHAR2(7), "LEV_LOW" NUMBER(1, 0),
 "LEV_HIGH" NUMBER(1, 0), "LEV_DEFLT" NUMBER(1, 0), "BILL_DOC_TYPE" NUMBER(1, 0),
 "PRCNT_PRICE_FROM_COST" NUMBER, "DEC_NO" NUMBER(2, 0), "CST_TYPE" NUMBER(1, 0),
 "CST_PRCNT" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "INACTIVE" NUMBER(1, 0), "INACTIVE_RES"
 VARCHAR2(250), "INACTIVE_DATE" DATE, "INACTIVE_U_ID" NUMBER(5, 0))  PCTFREE 10 PCTUSED
 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "ITEM_MOVEMENT" ("DOC_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "BILL_DOC_TYPE"
 NUMBER(5, 0), "DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "I_CODE" VARCHAR2(30) NOT NULL
 ENABLE, "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE,
 "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER, "PF_QTY" NUMBER, "I_DATE" DATE NOT NULL
 ENABLE, "I_COST" NUMBER, "W_CODE" NUMBER(10, 0) NOT NULL ENABLE, "WHG_CODE" NUMBER(10,
 0), "STK_COST" NUMBER, "VAT_AMT" NUMBER, "DIS_AMT" NUMBER, "A_CY" VARCHAR2(7), "AC_RATE"
 NUMBER, "STK_RATE" NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "C_CODE"
 VARCHAR2(15), "V_CODE" VARCHAR2(15), "A_DESC" VARCHAR2(1000), "GR_NO" NUMBER(15, 0),
 "EXPIRE_DATE" DATE NOT NULL ENABLE, "BATCH_NO" VARCHAR2(30) NOT NULL ENABLE, "RCRD_NO"
 NUMBER(10, 0), "SERIAL" NUMBER, "REF_NO" VARCHAR2(30), "DOC_SER" NUMBER(38, 0) NOT NULL
 ENABLE, "OUT_NO" NUMBER(15, 0), "OUT_GR_SER" NUMBER(38, 0), "DOC_SEQUENCE" NUMBER(38, 0)
 NOT NULL ENABLE, "BARCODE" VARCHAR2(30), "RT_TYPE" NUMBER(1, 0), "IN_OUT" NUMBER(1, 0)
 CONSTRAINT "ITMMOV_NN_INOUT" NOT NULL ENABLE, "EXTERNAL_POST" NUMBER(5, 0), "I_LENGTH"
 NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "WT_QTY" NUMBER,
 "WT_UNT" VARCHAR2(10), "ARGMNT_NO" NUMBER, "AD_DATE" DATE, "UP_DATE" DATE, "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4
, 0), "BRN_USR" NUMBER(3, 0), "FREE_TYP" NUMBER(1, 0), "LEV_NO" NUMBER(3, 0),
 "I_PRICE_VAT" NUMBER, "EMP_NO" NUMBER(10, 0), "DIS_AMT_MST_VAT" NUMBER, "DIS_PER" NUMBER
, "DIS_AMT_DTL" NUMBER, "DIS_AMT_DTL_VAT" NUMBER, "DIS_PER2" NUMBER, "DIS_AMT_DTL2"
 NUMBER, "DIS_AMT_DTL2_VAT" NUMBER, "DIS_PER3" NUMBER, "DIS_AMT_DTL3" NUMBER,
 "DIS_AMT_DTL3_VAT" NUMBER, "OTHR_AMT" NUMBER, "VAT_AMT_OTHR" NUMBER, "VAT_PER" NUMBER,
 "DIS_AMT_MST" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_IM" LOGGING NOCOMPRESS;

CREATE TABLE "STK_ADJUSTMENT" ("STK_TYPE" NUMBER(5, 0), "ADJUST_TYPE" NUMBER(2, 0) NOT
 NULL ENABLE, "DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER" NUMBER(38, 0), "DOC_DATE"
 DATE, "REF_NO" VARCHAR2(15), "STK_DESC" VARCHAR2(100), "A_CODE" VARCHAR2(30), "V_CODE"
 VARCHAR2(15), "A_CY" VARCHAR2(7), "STK_ACC_RATE" NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "STK_POST" NUMBER(1, 0), "PR_REP" NUMBER(10, 0),
 "HUNG" NUMBER(1, 0), "FILL_TYPE" NUMBER(2, 0), "DOC_BRN_NO" NUMBER(6, 0), "AUDIT_REF"
 NUMBER(1, 0), "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0),
 "AUDIT_REF_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE,
 "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "AC_CODE_DTL" VARCHAR2(30),
 "AC_DTL_TYP" NUMBER(2, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STK_ADJUSTMENT_DET" ("ADJUST_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "DOC_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER" NUMBER(38, 0) NOT NULL ENABLE, "I_CODE"
 VARCHAR2(30) NOT NULL ENABLE, "W_CODE" NUMBER(10, 0), "EXPIRE_DATE" DATE, "BATCH_NO"
 VARCHAR2(30), "BARCODE" VARCHAR2(30), "WTAVG" NUMBER, "AVL_QTY" NUMBER, "PLS_MINS"
 NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY"
 NUMBER, "USE_SERIALNO" NUMBER(1, 0), "RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE" NUMBER(38,
 0) NOT NULL ENABLE, "ITEM_DESC" VARCHAR2(1000), "MAN_P_QTY" NUMBER, "MAN_AVL_PQTY"
 NUMBER, "PI_PRICE" NUMBER, "PI_I_QTY" NUMBER, "PR_I_QTY" NUMBER, "BILL_DISC" NUMBER,
 "DOC_TYPE_REF" NUMBER(2, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0),
 "V_CODE" VARCHAR2(15), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "INC_QTY" NUMBER, "INC_COST" NUMBER, "BAL_QTY" NUMBER, "REAL_COST" NUMBER,
 "I_LENGTH" NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "POST_CODE"
 VARCHAR2(10), "WT_QTY" NUMBER, "WT_UNT" VARCHAR2(10), "ARGMNT_NO" NUMBER, "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4
, 0), "BRN_USR" NUMBER(3, 0) NOT NULL ENABLE, "UP_CNT" NUMBER(10, 0), "DOC_SEQUENCE_REF"
 NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "BIN_DETAILS" ("B_CODE" VARCHAR2(20), "W_CODE" NUMBER(10, 0), "B_A_NAME"
 VARCHAR2(100) NOT NULL ENABLE, "B_E_NAME" VARCHAR2(100), "EXTERNAL_POST" NUMBER(5, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP"
 NUMBER(6, 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "CPM" NUMBER, "WGT" NUMBER, "DEFLT_FLG" NUMBER(1, 0))  PCTFREE 10 PCTUSED
 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "ITEM_BIN" ("I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10), "P_SIZE" NUMBER,
 "W_CODE" NUMBER(10, 0), "B_CODE" VARCHAR2(20), "EXPIRE_DATE" DATE, "BATCH_NO"
 VARCHAR2(30), "EXTERNAL_POST" NUMBER(5, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "DEFLT_FLG" NUMBER(1, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_INV_MANAGEMENT" ("DOC_NO" NUMBER(38, 0), "DOC_DATE" DATE, "I_CODE"
 VARCHAR2(30), "I_NAME" VARCHAR2(100), "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "P_SIZE"
 NUMBER, "W_CODE" NUMBER(10, 0), "BATCH_NO" VARCHAR2(30) NOT NULL ENABLE, "OP_QTY" NUMBER
, "INC_QTY" NUMBER, "SALE_QTY" NUMBER, "POS_QTY" NUMBER, "NET_SALE" NUMBER, "AVL_QTY"
 NUMBER, "AVG_SALE_DAY" NUMBER, "AVG_SALE_GEN" NUMBER, "PER_SALE_QTY" NUMBER,
 "ITM_SALE_AGE" NUMBER, "ITM_SALE_AGE_PRD" NUMBER, "ITM_AGE" NUMBER, "ITM_RATIO" NUMBER,
 "ITM_SALE_RATIO" NUMBER, "TR_NOT_REC_QTY" NUMBER, "SUM_INC_QTY" NUMBER, "QTY_FROM_WH"
 NUMBER, "QTY_TO_WH" NUMBER, "AVG_QTY_PRD" NUMBER, "G_CODE" VARCHAR2(10),
 "GRP_CLASS_CODE" VARCHAR2(20), "MNG_CODE" VARCHAR2(10), "SUBG_CODE" VARCHAR2(10),
 "ASSISTANT_NO" VARCHAR2(10), "DETAIL_NO" VARCHAR2(10), "ACTIVITY_NO" NUMBER(5, 0),
 "INCOME_DATE" DATE, "ITEM_TYPE" NUMBER(5, 0), "CITY_NO" NUMBER(10, 0), "R_CODE"
 NUMBER(10, 0), "ITM_ORDR" NUMBER, "PRD_DAY" NUMBER, "PROCESSED" NUMBER(1, 0), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "CMP_NO" NUMBER(3,
 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0),
 "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_TMP_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_INV_MANAGEMENT_TMP" ("I_CODE" VARCHAR2(30), "I_NAME" VARCHAR2(100),
 "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "W_CODE" NUMBER(10, 0), "BATCH_NO" VARCHAR2(30)
 NOT NULL ENABLE, "OP_QTY" NUMBER, "INC_QTY" NUMBER, "SALE_QTY" NUMBER, "POS_QTY" NUMBER,
 "NET_SALE" NUMBER, "AVL_QTY" NUMBER, "AVG_SALE_DAY" NUMBER, "AVG_SALE_GEN" NUMBER,
 "PER_SALE_QTY" NUMBER, "ITM_SALE_AGE" NUMBER, "ITM_SALE_AGE_PRD" NUMBER, "ITM_AGE"
 NUMBER, "ITM_RATIO" NUMBER, "ITM_SALE_RATIO" NUMBER, "TR_NOT_REC_QTY" NUMBER(38, 0),
 "SUM_INC_QTY" NUMBER(38, 0), "QTY_FROM_WH" NUMBER(38, 0), "QTY_TO_WH" NUMBER(38, 0),
 "AVG_QTY_PRD" NUMBER(38, 0), "G_CODE" VARCHAR2(10), "GRP_CLASS_CODE" VARCHAR2(20),
 "MNG_CODE" VARCHAR2(10), "SUBG_CODE" VARCHAR2(10), "ASSISTANT_NO" VARCHAR2(10),
 "DETAIL_NO" VARCHAR2(10), "ACTIVITY_NO" NUMBER(5, 0), "INCOME_DATE" DATE, "ITEM_TYPE"
 NUMBER(5, 0), "CITY_NO" NUMBER(10, 0), "R_CODE" NUMBER(10, 0), "ITM_ORDR" NUMBER(6, 0),
 "PRD_DAY" NUMBER(6, 0), "DOC_NO" NUMBER(38, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "CMP_NO" NUMBER(3, 0), "BRN_NO" NUMBER(6, 0),
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_TMP_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "KIT_ITEMS" ("KIT_ITEM_NO" VARCHAR2(30), "I_CODE" VARCHAR2(30), "ITM_UNT"
 VARCHAR2(10) NOT NULL ENABLE, "P_SIZE" NUMBER NOT NULL ENABLE, "I_QTY" NUMBER, "P_QTY"
 NUMBER, "PER_COST_FROM_KIT_ITM" NUMBER, "ITM_MIN_QTY" NUMBER, "ITM_MAX_QTY" NUMBER,
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "CHK_AVL_QTY_IN_RMS" NUMBER(1, 0), "NOTE" VARCHAR2(1000),
 "USE_RMS_SLS_TYP" VARCHAR2(10), "EXCD_ITM_QTY" NUMBER(1, 0), "ALLW_DEL_ITM" NUMBER(1,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_KIT"
 LOGGING NOCOMPRESS;

CREATE TABLE "KIT_ITEMS_DETAIL" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "KIT_ITEM_NO" VARCHAR2(30), "I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10)
 NOT NULL ENABLE, "P_SIZE" NUMBER NOT NULL ENABLE, "I_QTY" NUMBER, "P_QTY" NUMBER,
 "STNDRD_QTY" NUMBER, "AVL_QTY" NUMBER, "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30),
 "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "I_COST" NUMBER, "KIT_QTY" NUMBER,
 "SUM_QTY" NUMBER, "PSUM_QTY" NUMBER, "RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE" NUMBER(38,
 0), "POST_CODE" VARCHAR2(10), "EXPIRE_DATE" DATE, "BATCH_NO" VARCHAR2(30), "RCRD_SQ"
 NUMBER, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "I_PRICE"
 NUMBER, "DOC_SEQUENCE_M" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_KIT" LOGGING NOCOMPRESS;

CREATE TABLE "ASSEMBLE_KIT_ITEMS" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE NOT NULL ENABLE, "FROM_WH" NUMBER(10, 0), "TO_WH"
 NUMBER(10, 0), "EXP_AMT_TYPE" NUMBER(1, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15)
, "ACTV_NO" VARCHAR2(15), "STK_RATE" NUMBER, "DOC_DESC" VARCHAR2(250), "REF_NO"
 VARCHAR2(15), "EXP_AMT" NUMBER, "PROCESSED" NUMBER(1, 0), "HUNG" NUMBER(1, 0),
 "DOC_POST" NUMBER(1, 0), "EMP_NO" NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE,
 "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE" DATE, "AUDIT_REF" NUMBER(1, 0),
 "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE,
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "TYP_NO" NUMBER(5, 0), "PRD_DOC"
 NUMBER(1, 0), "DOC_SEQUENCE_M" NUMBER, "ADD_EXP_TYPE" NUMBER(1, 0))  PCTFREE 10 PCTUSED
 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_KIT" LOGGING NOCOMPRESS;

CREATE TABLE "ASSEMBLE_KIT_ITEMS_DET" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "KIT_ITEM_NO" VARCHAR2(30), "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE,
 "P_SIZE" NUMBER, "I_QTY" NUMBER, "F_W_CODE" NUMBER(10, 0), "T_W_CODE" NUMBER(10, 0),
 "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "KIT_COST" NUMBER,
 "EXP_AMT" NUMBER, "RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE" NUMBER(38, 0) NOT NULL ENABLE,
 "POST_CODE" VARCHAR2(10), "EXPIRE_DATE" DATE, "BATCH_NO" VARCHAR2(30), "CMP_NO" NUMBER(3
, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0),
 "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "I_PRICE" NUMBER, "DOC_TYPE_REF" NUMBER,
 "DOC_NO_REF" NUMBER, "DOC_SER_REF" NUMBER, "DOC_SEQUENCE_REF" NUMBER, "DOC_SEQUENCE_M"
 NUMBER, "RCRD_SQ" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_KIT" LOGGING NOCOMPRESS;

CREATE TABLE "DISASSEMBLE_KIT_ITEMS" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE NOT NULL ENABLE, "FROM_WH" NUMBER(10, 0), "TO_WH"
 NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15),
 "STK_RATE" NUMBER, "DOC_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15), "AS_DOC_NO" NUMBER(9
, 0), "AS_DOC_SER" NUMBER(38, 0), "DOC_POST" NUMBER(1, 0), "HUNG" NUMBER(1, 0), "EMP_NO"
 NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0),
 "UNPOST_DATE" DATE, "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC" VARCHAR2(500),
 "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50)
, "UP_TRMNL_NM" VARCHAR2(50), "TYP_NO" NUMBER(5, 0), "DOC_SEQUENCE_M" NUMBER)  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_KIT" LOGGING
 NOCOMPRESS;

CREATE TABLE "DISASSEMBLE_KIT_ITEMS_DET" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE,
 "DOC_SER" NUMBER(38, 0), "AS_DOC_NO" NUMBER(15, 0), "AS_DOC_SER" NUMBER(38, 0),
 "KIT_ITEM_NO" VARCHAR2(30), "ITM_UNT" VARCHAR2(10), "P_SIZE" NUMBER, "I_QTY" NUMBER,
 "F_W_CODE" NUMBER(10, 0), "T_W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "KIT_COST" NUMBER, "RCRD_NO" NUMBER(10, 0),
 "DOC_SEQUENCE" NUMBER(38, 0) NOT NULL ENABLE, "POST_CODE" VARCHAR2(10), "EXPIRE_DATE"
 DATE, "BATCH_NO" VARCHAR2(30), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6,
 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10,
 0), "DOC_SEQUENCE_REF" NUMBER, "DOC_SEQUENCE_M" NUMBER, "RCRD_SQ" NUMBER)  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_KIT" LOGGING
 NOCOMPRESS;

CREATE TABLE "DIS_KIT_ITEMS_DETAIL" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "AS_DOC_NO" NUMBER(15, 0), "AS_DOC_SER" NUMBER(38, 0), "KIT_ITEM_NO"
 VARCHAR2(30), "I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "P_SIZE"
 NUMBER NOT NULL ENABLE, "I_QTY" NUMBER, "P_QTY" NUMBER, "STNDRD_QTY" NUMBER, "AVL_QTY"
 NUMBER, "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "I_COST" NUMBER, "KIT_QTY" NUMBER, "SUM_QTY" NUMBER, "PSUM_QTY" NUMBER,
 "WT_AVG_BEFORE" NUMBER, "WT_AVG_AFTER" NUMBER, "RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE"
 NUMBER(38, 0), "POST_CODE" VARCHAR2(10), "EXPIRE_DATE" DATE, "BATCH_NO" VARCHAR2(30),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PER_COST_FROM_KIT_ITM"
 NUMBER, "DOC_SEQUENCE_M" NUMBER, "RCRD_SQ" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_KIT" LOGGING NOCOMPRESS;

CREATE TABLE "COMPOUND_ITEMS" ("I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10) NOT NULL
 ENABLE, "P_SIZE" NUMBER, "DI_CODE" VARCHAR2(30), "DI_NAME" VARCHAR2(100), "QTY" NUMBER,
 "DITM_UNT" VARCHAR2(10), "DP_SIZE" NUMBER, "OPTIONAL" NUMBER(1, 0), "ITM_MIN_QTY" NUMBER
, "ITM_MAX_QTY" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_TRANSFER_IN_SUB_MAIN_TMP" ("TR_SER" NUMBER)  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_TMP_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_TRANSFER_OUT_SUB_MAIN_TMP" ("TR_SER" NUMBER)  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_TMP_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "INV_WRHS_TRNSFR_EXPNS" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "TR_INOUT_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "DOC_DESC"
 VARCHAR2(500), "REF_NO" VARCHAR2(250), "A_CODE" VARCHAR2(30) NOT NULL ENABLE,
 "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7) NOT NULL
 ENABLE, "AC_RATE" NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "AMT" NUMBER, "INV_AMT" NUMBER, "EXTERNAL_POST" NUMBER(5, 0), "RCRD_NO"
 NUMBER(5, 0), "BRN_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "CMP_NO" NUMBER(2, 0) NOT NULL ENABLE, "DOC_BRN_NO" NUMBER(6, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_INV_DATA_TRNS"
 LOGGING NOCOMPRESS;

CREATE TABLE "INV_WRHS_TRNSFR_EXPNS_BR" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE,
 "DOC_SER" NUMBER(38, 0) NOT NULL ENABLE, "TR_INOUT_TYPE" NUMBER(2, 0) NOT NULL ENABLE,
 "DOC_DESC" VARCHAR2(500), "REF_NO" VARCHAR2(250), "A_CODE" VARCHAR2(30) NOT NULL ENABLE,
 "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7) NOT NULL
 ENABLE, "AC_RATE" NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "AMT" NUMBER, "INV_AMT" NUMBER, "EXTERNAL_POST" NUMBER(5, 0), "RCRD_NO"
 NUMBER(5, 0), "DOC_BRN_NO" NUMBER(6, 0), "BRN_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "CMP_NO" NUMBER(2, 0) NOT NULL ENABLE) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_DATA_TRNS" LOGGING NOCOMPRESS;

