CREATE TABLE "SALES_ORDER" ("SO_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "ORDER_NO" NUMBER(15,
 0) NOT NULL ENABLE, "ORDER_SER" NUMBER(38, 0), "ORDER_DATE" DATE NOT NULL ENABLE,
 "QUOT_NO" NUMBER(15, 0), "QUOT_SER" NUMBER(38, 0), "ORDER_CUR" VARCHAR2(7) NOT NULL
 ENABLE, "CUR_RATE" NUMBER, "C_CODE" VARCHAR2(15), "C_NAME" VARCHAR2(100), "A_DESC"
 VARCHAR2(1000), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15),
 "W_CODE" NUMBER(10, 0), "REP_CODE" VARCHAR2(15), "PROCESED" NUMBER(1, 0), "STAND_BY"
 NUMBER(1, 0), "LOADED" NUMBER(1, 0), "REF_DOC_NO" VARCHAR2(15), "REF_DOC_DATE" DATE,
 "DISC_AMT" NUMBER, "DISC_AMT_MST" NUMBER, "DISC_AMT_DTL" NUMBER, "DISC_AMT_MST_VAT"
 NUMBER, "VAT_AMT_DISC_MST" NUMBER, "APPROVED" NUMBER(1, 0), "APRV_U_ID" NUMBER(5, 0),
 "APRV_DATE" DATE, "APRV_DSC" VARCHAR2(500), "PREPARE_DATE" DATE, "REC_DEALER_DATE" DATE,
 "DELIVERY_DATE" DATE, "REPEAT_USE_IN_BILLS" NUMBER(1, 0), "INACTIVE" NUMBER(1, 0),
 "INACTIVE_RES" VARCHAR2(250), "INACTIVE_DATE" DATE, "INACTIVE_U_ID" NUMBER(5, 0),
 "PAPER_NO" NUMBER, "PAPER_SERIAL" NUMBER, "R_CODE" NUMBER(10, 0), "PRM_CODE"
 VARCHAR2(15), "DRIVER_NO" NUMBER(10, 0), "BILL_DOC_TYPE" NUMBER(2, 0), "BILL_DUE_DATE"
 DATE, "ORDER_EXPIRE_DATE" DATE, "CHEQUE_DUE_DATE" DATE, "EXTERNAL_POST" NUMBER(5, 0),
 "PROCESS_INC_FLG" NUMBER(1, 0), "PROCESS_WRHS_TRNSFR_FLG" NUMBER(1, 0),
 "APPROVED_SALES_MNG" NUMBER(1, 0), "APRV_SALES_MNG_U_ID" NUMBER(5, 0),
 "APRV_SALES_MNG_DATE" DATE, "TRANSFER_PRODUCT" NUMBER(1, 0), "EXPORT" NUMBER(1, 0),
 "VAT_AMT" NUMBER, "ORDER_AMT" NUMBER, "EMP_NO" NUMBER(10, 0), "OTHR_AMT" NUMBER,
 "SI_TYPE" NUMBER(5, 0), "CLC_TYP_NO_TAX" NUMBER(5, 0), "FIELD1" VARCHAR2(250), "FIELD2"
 VARCHAR2(250), "FIELD3" VARCHAR2(250), "FIELD4" VARCHAR2(250), "FIELD5" VARCHAR2(250),
 "FIELD6" VARCHAR2(250), "FIELD7" VARCHAR2(250), "FIELD8" VARCHAR2(250), "FIELD9"
 VARCHAR2(250), "FIELD10" VARCHAR2(250), "FIELD11" VARCHAR2(250), "FIELD12" VARCHAR2(250)
, "FIELD13" VARCHAR2(250), "FIELD14" VARCHAR2(250), "INSRNCE_CMP_NO" NUMBER(10, 0),
 "INSRNCE_BNF_NO" NUMBER(5, 0), "INSRNCE_PRSON_NM" VARCHAR2(100), "INSRNCE_CARD_NO"
 VARCHAR2(60), "INSRNCE_CARD_NO_FMLY" VARCHAR2(60), "INSRNCE_RLTN_TYP" NUMBER(2, 0),
 "INSRNCE_CLSS_NO" VARCHAR2(5), "INSRNCE_LOAD_PER" NUMBER, "INSRNCE_DIAGNOSIS"
 VARCHAR2(500), "INSRNCE_MDCL_NO" NUMBER(5, 0), "INSRNCE_APPRVD_CODE" VARCHAR2(60),
 "INSRNCE_CSH_AMT" NUMBER, "C_CODE_CSH" VARCHAR2(15), "C_ADDRESS" VARCHAR2(500),
 "C_MOBILE" VARCHAR2(30), "NT_TRANSFR_PATH" VARCHAR2(250), "LATITUDE" VARCHAR2(20),
 "LONGITUDE" VARCHAR2(20), "CASH_NO" NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE"
 DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10
, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "VAT_AMT_OTHR" NUMBER, "DIFF_ACUTL_WGHT_SO_QTY" NUMBER,
 "TARE_WGHT" NUMBER, "TARE_WGHT_DATE" DATE, "TARE_WGHT_U_ID" NUMBER(5, 0), "GROSS_WGHT"
 NUMBER, "GROSS_WGHT_DATE" DATE, "GROSS_WGHT_U_ID" NUMBER(5, 0), "DOC_SER_EXTRNL"
 VARCHAR2(256), "CR_CARD_NO" NUMBER(5, 0), "DISC_AMT_AFTR_VAT" NUMBER,
 "CLC_VAT_PRICE_TYP" NUMBER(1, 0), "CNTRCT_NO" VARCHAR2(30), "CNTRCT_BTCH_NO" NUMBER(30,
 0), "CNTRCT_DATE" DATE, "COL_NO" NUMBER(10, 0), "STOCK_RATE" NUMBER, "PROCESS_OUT_FLG"
 NUMBER(1, 0), "POINT_CALC_TYP_NO" NUMBER(1, 0), "POINT_CNT" NUMBER, "POINT_CNT_ALL"
 NUMBER, "POINT_RPLC_AMT" NUMBER, "POINT_RPLC_CNT" NUMBER, "POINT_TYP_NO" NUMBER(5, 0),
 "MOBILE_NO" NUMBER(20, 0), "PROCESS_MRP_FLG" NUMBER(1, 0), "NOT_USE_QUT_PRM" NUMBER(1,
 0), "QT_PRM_SER" NUMBER(38, 0), "QT_PRM_RCRD_NO" NUMBER(10, 0), "QT_PRM_NO" NUMBER(15,
 0), "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0), "INSRNCE_ADD_LMT_MST" NUMBER, "AD_DATE_CLK"
 DATE, "SHO_SYS_TYP" NUMBER(2, 0), "ORDR_STAT_TYP" NUMBER(2, 0), "ORDR_TND" VARCHAR2(9),
 "CST_SPCLST_NM" VARCHAR2(200), "ORDR_NO_MUNL" VARCHAR2(50), "INSRNCE_ADD_LMT_DOC" NUMBER
, "INSRNCE_ADD_LMT_DTL" NUMBER, "INSRNCE_LMT_AMT_LOC_DOC" NUMBER, "PTNT_NO" VARCHAR2(15),
 "DCTR_NO" VARCHAR2(15), "PTNT_TYP" NUMBER(1, 0), "DOC_NO_ADMSON" NUMBER(15, 0),
 "DOC_SRL_ADMSON" NUMBER(38, 0), "DOC_M_SQ" NUMBER, "CST_ACCPT_TYP" NUMBER(1, 0),
 "CST_ACCPT_U_ID" NUMBER(5, 0), "CST_ACCPT_DATE" DATE, "CST_ACCPT_DSC" VARCHAR2(500),
 "PROCESS_REQ_AUTO" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "ORDER_DETAIL" ("SO_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "ORDER_NO" NUMBER(15
, 0) NOT NULL ENABLE, "ORDER_SER" NUMBER(38, 0), "I_CODE" VARCHAR2(30) NOT NULL ENABLE,
 "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "P_SIZE"
 NUMBER NOT NULL ENABLE, "P_QTY" NUMBER, "I_PRICE" NUMBER, "RES_DATE" DATE, "RES_QTY"
 NUMBER, "W_CODE" NUMBER(10, 0), "RESERVED" NUMBER(1, 0), "RCRD_NO" NUMBER, "BARCODE"
 VARCHAR2(30), "USE_ATTCH" NUMBER(1, 0), "REC_ATTCH" NUMBER(10, 0), "ITEM_DESC"
 VARCHAR2(1000), "EXTERNAL_POST" NUMBER(5, 0), "CANCELED" NUMBER(1, 0), "EXPIRE_DATE"
 DATE, "BATCH_NO" VARCHAR2(30), "VAT_PER" NUMBER, "VAT_AMT" NUMBER, "I_LENGTH" NUMBER,
 "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "WT_UNT" VARCHAR2(10), "WT_QTY"
 NUMBER, "DIS_AMT" NUMBER, "DIS_AMT_MST" NUMBER, "DIS_PER" NUMBER, "DIS_AMT_DTL" NUMBER,
 "DIS_PER2" NUMBER, "DIS_AMT_DTL2" NUMBER, "DIS_PER3" NUMBER, "DIS_AMT_DTL3" NUMBER,
 "DIS_AMT_DTL_VAT" NUMBER, "DIS_AMT_MST_VAT" NUMBER, "VAT_AMT_DIS_DTL_VAT" NUMBER,
 "VAT_AMT_AFTR_DIS" NUMBER, "VAT_AMT_BFR_DIS" NUMBER, "VAT_AMT_DIS_MST_VAT" NUMBER,
 "DOC_SEQ" NUMBER, "EMP_NO" NUMBER(10, 0), "SUB_C_CODE" VARCHAR2(15), "FIELD_DTL1"
 VARCHAR2(60), "FIELD_DTL2" VARCHAR2(60), "FIELD_DTL3" VARCHAR2(60), "PKG_UNT"
 VARCHAR2(10), "PKG_UNT_SIZE" NUMBER(10, 0), "PKG_QTY" NUMBER, "PKG_LENGTH" NUMBER,
 "PKG_WIDTH" NUMBER, "PKG_HEIGHT" NUMBER, "PKG_SIZE" NUMBER, "PKG_WEIGHT" NUMBER,
 "SI_TYPE" NUMBER(5, 0), "OTHR_AMT" NUMBER, "INSRNCE_LOAD_PER" NUMBER, "INSRNCE_LOAD_AMT"
 NUMBER, "INSRNCE_ADD_LMT" NUMBER, "INSRNCE_APPRVD_CODE" VARCHAR2(60), "I_PRICE_VAT"
 NUMBER, "MEASUR_PRICE" NUMBER, "DOC_TYPE_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0),
 "DOC_SER_REF" NUMBER(38, 0), "DOC_SEQUENCE_REF" NUMBER(38, 0), "CC_CODE" VARCHAR2(30),
 "STK_COST" NUMBER, "USED_ITM" NUMBER(1, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "ARGMNT_NO" NUMBER, "UP_CNT" NUMBER(10, 0), "OTHR_AMT_DISC" NUMBER, "VAT_AMT_OTHR"
 NUMBER, "F_TIME" VARCHAR2(15), "T_TIME" VARCHAR2(15), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "DIS_AMT_AFTR_VAT" NUMBER, "DIS_AMT_DTL2_VAT" NUMBER, "DIS_AMT_DTL3_VAT"
 NUMBER, "VAT_AMT_DIS_DTL2_VAT" NUMBER, "VAT_AMT_DIS_DTL3_VAT" NUMBER, "PO_NO" NUMBER(15,
 0), "PO_SER" NUMBER, "FIELD_DTL4" VARCHAR2(60), "FIELD_DTL5" VARCHAR2(60), "FIELD_DTL6"
 VARCHAR2(60), "FIELD_DTL7" VARCHAR2(60), "FIELD_DTL8" VARCHAR2(60), "FIELD_DTL9"
 VARCHAR2(60), "FIELD_DTL10" VARCHAR2(60), "LEV_NO" NUMBER(3, 0), "I_PRICE_LEV_NO" NUMBER
, "BILL_DOC_TYPE" NUMBER(2, 0), "DIS_PER_QT_PRM" NUMBER, "DIS_AMT_DTL_QT_PRM_VAT" NUMBER,
 "DIS_AMT_DTL_QT_PRM" NUMBER, "DOC_SEQ_TMP" NUMBER, "PRM_GRP_NO" NUMBER(5, 0),
 "QT_PRM_SER" NUMBER(38, 0), "QT_PRM_RCRD_NO" NUMBER(10, 0), "QT_PRM_NO" NUMBER(15, 0),
 "OTHR_AMT_ITM" NUMBER, "INSRNCE_ADD_LMT_MST" NUMBER, "FREE_TYP" NUMBER(1, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING
 NOCOMPRESS;

CREATE TABLE "QUOTATION" ("QT_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "QUOT_NO" NUMBER(15, 0)
, "QUOT_SER" NUMBER(38, 0), "QUOT_DATE" DATE NOT NULL ENABLE, "QUOT_CUR" VARCHAR2(7) NOT
 NULL ENABLE, "C_CODE" VARCHAR2(15), "C_NAME" VARCHAR2(100), "CC_CODE" VARCHAR2(30),
 "W_CODE" NUMBER(10, 0), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "A_DESC"
 VARCHAR2(1000), "QUOT_TEND" VARCHAR2(9), "QUOT_TEND_DATE" DATE, "REF_NO" VARCHAR2(15),
 "REF_DATE" DATE, "PORT_OF_DEP" VARCHAR2(100), "REQ_DAYS" NUMBER(5, 0), "PAY_TERMS"
 VARCHAR2(500), "DISC_AMT" NUMBER, "PROCESSED" NUMBER(1, 0), "APPROVED" NUMBER(1, 0),
 "APRV_DATE" DATE, "APRV_DSC" VARCHAR2(500), "APRV_U_ID" NUMBER(5, 0), "OTHR_AMT" NUMBER,
 "SI_TYPE" NUMBER(5, 0), "QUOT_AMT" NUMBER, "INACTIVE" NUMBER(1, 0), "INACTIVE_RES"
 VARCHAR2(250), "INACTIVE_DATE" DATE, "INACTIVE_U_ID" NUMBER(5, 0), "EXTERNAL_POST"
 NUMBER(5, 0), "COST_TYPE" VARCHAR2(5), "REP_CODE" VARCHAR2(15), "EXPORT" NUMBER(1, 0),
 "QUOT_EXPIRE_DATE" DATE, "CUR_RATE" NUMBER, "CHEQUE_DUE_DATE" DATE, "DISC_AMT_MST"
 NUMBER, "DISC_AMT_DTL" NUMBER, "DISC_AMT_MST_VAT" NUMBER, "VAT_AMT_DISC_MST" NUMBER,
 "VAT_AMT" NUMBER, "QUOT_DOC_TYPE" NUMBER(2, 0), "QUOT_DUE_DATE" DATE, "CST_ACCPT_TYP"
 NUMBER(1, 0), "CST_ACCPT_DATE" DATE, "CST_ACCPT_DSC" VARCHAR2(500), "CLC_TYP_NO_TAX"
 NUMBER(5, 0), "FIELD1" VARCHAR2(250), "FIELD2" VARCHAR2(250), "FIELD3" VARCHAR2(250),
 "FIELD4" VARCHAR2(250), "FIELD5" VARCHAR2(250), "FIELD6" VARCHAR2(250), "FIELD7"
 VARCHAR2(250), "FIELD8" VARCHAR2(250), "FIELD9" VARCHAR2(250), "FIELD10" VARCHAR2(250),
 "AD_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "VAT_AMT_OTHR" NUMBER,
 "DOC_SER_EXTRNL" VARCHAR2(256), "CLC_VAT_PRICE_TYP" NUMBER(1, 0), "CLC_TAX_FREE_QTY_FLG"
 NUMBER(1, 0), "AD_DATE_CLK" DATE, "CNTRCT_BTCH_NO" NUMBER, "CNTRCT_DATE" DATE,
 "CNTRCT_NO" VARCHAR2(30), "DELIVERY_DATE" DATE)  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "QUOTATION_DETAIL" ("QT_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "QUOT_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "QUOT_SER" NUMBER(38, 0) NOT NULL ENABLE, "I_CODE"
 VARCHAR2(30) NOT NULL ENABLE, "I_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE,
 "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER, "I_PRICE" NUMBER(24, 9), "W_CODE"
 NUMBER(10, 0), "VAT_PER" NUMBER, "VAT_AMT" NUMBER, "RCRD_NO" NUMBER(10, 0), "BARCODE"
 VARCHAR2(30), "USE_ATTCH" NUMBER(1, 0), "FREE_QTY" NUMBER, "REC_ATTCH" NUMBER(10, 0),
 "I_LENGTH" NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "WT_UNT"
 VARCHAR2(10), "WT_QTY" NUMBER, "ITEM_DESC" VARCHAR2(1000), "DIS_PER" NUMBER,
 "DIS_AMT_DTL" NUMBER, "DIS_PER2" NUMBER, "DIS_AMT_DTL2" NUMBER, "DIS_PER3" NUMBER,
 "DIS_AMT_DTL3" NUMBER, "DIS_AMT_MST" NUMBER, "DIS_AMT" NUMBER, "DIS_AMT_DTL_VAT" NUMBER,
 "DIS_AMT_MST_VAT" NUMBER, "VAT_AMT_DIS_DTL_VAT" NUMBER, "VAT_AMT_AFTR_DIS" NUMBER,
 "VAT_AMT_BFR_DIS" NUMBER, "VAT_AMT_DIS_MST_VAT" NUMBER, "OTHR_AMT" NUMBER, "I_PRICE_VAT"
 NUMBER, "SI_TYPE" NUMBER(5, 0), "FIELD_DTL1" VARCHAR2(60), "FIELD_DTL2" VARCHAR2(60),
 "FIELD_DTL3" VARCHAR2(60), "EXTERNAL_POST" NUMBER(5, 0), "EXPIRE_DATE" DATE, "BATCH_NO"
 VARCHAR2(30), "ARGMNT_NO" NUMBER, "STK_COST" NUMBER, "USED_ITM" NUMBER(1, 0),
 "DOC_SEQUENCE" NUMBER(38, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6,
 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10,
 0), "OTHR_AMT_DISC" NUMBER, "VAT_AMT_OTHR" NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "DIS_AMT_DTL2_VAT" NUMBER, "DIS_AMT_DTL3_VAT"
 NUMBER, "VAT_AMT_DIS_DTL2_VAT" NUMBER, "VAT_AMT_DIS_DTL3_VAT" NUMBER, "FIELD_DTL4"
 VARCHAR2(60), "FIELD_DTL5" VARCHAR2(60), "FIELD_DTL6" VARCHAR2(60), "FIELD_DTL7"
 VARCHAR2(60), "FIELD_DTL8" VARCHAR2(60), "FIELD_DTL9" VARCHAR2(60), "FIELD_DTL10"
 VARCHAR2(60), "LEV_NO" NUMBER(3, 0), "I_PRICE_LEV_NO" NUMBER, "OTHR_AMT_ITM" NUMBER,
 "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0), "DOC_TYPE_REF" NUMBER(5, 0),
 "FREE_TYP" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_BILL_MST" ("BILL_DOC_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "BILL_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "BILL_SER" NUMBER(38, 0) NOT NULL ENABLE, "BILL_DATE"
 DATE NOT NULL ENABLE, "BILL_CURRENCY" VARCHAR2(7) NOT NULL ENABLE, "BILL_RATE" NUMBER
 NOT NULL ENABLE, "STOCK_RATE" NUMBER, "C_CODE" VARCHAR2(15), "C_NAME" VARCHAR2(100),
 "A_CODE" VARCHAR2(30), "CHEQUE_NO" NUMBER(20, 0), "NOTE_NO" VARCHAR2(30), "CHEQUE_AMT"
 NUMBER, "CHEQUE_DUE_DATE" DATE, "BILL_DUE_DATE" DATE, "BILL_POST" NUMBER(1, 0),
 "DISC_AMT" NUMBER, "DISC_AMT_MST" NUMBER, "DISC_AMT_DTL" NUMBER, "DISC_AMT_MST_VAT"
 NUMBER, "VAT_AMT_DISC_MST" NUMBER, "OTHR_AMT" NUMBER, "VAT_AMT" NUMBER, "BILL_AMT"
 NUMBER, "CPN_AMT" NUMBER, "W_CODE" NUMBER(10, 0), "R_CODE" NUMBER(10, 0), "REP_CODE"
 VARCHAR2(15), "EMP_NO" NUMBER(10, 0), "REF_NO" VARCHAR2(15), "CASH_NO" NUMBER(10, 0),
 "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "CR_CARD_NO"
 NUMBER(5, 0), "CR_CARD_AMT" NUMBER, "CREDIT_CARD" NUMBER(1, 0), "SI_TYPE" NUMBER(5, 0),
 "ATTACH_CNT" NUMBER(3, 0), "EXPORT" NUMBER(1, 0), "STAND_BY" NUMBER(1, 0), "COL_NO"
 NUMBER(10, 0), "CASH_AC_FCC" VARCHAR2(30), "CASH_NO_FCC" NUMBER(10, 0), "A_DESC"
 VARCHAR2(1000), "COMM_PER" NUMBER, "PR_REP" NUMBER(10, 0), "PROCESSED" NUMBER(1, 0),
 "BILL_PY" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0), "LOAD_NO" NUMBER(10, 0),
 "LOAD_SER" NUMBER(38, 0), "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC" VARCHAR2(500),
 "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "BILL_NO_CONN" NUMBER(15, 0),
 "BILL_SER_CONN" NUMBER(38, 0), "CLC_TYP_NO_TAX" NUMBER(5, 0), "AC_AMT" NUMBER, "FIELD1"
 VARCHAR2(250), "FIELD2" VARCHAR2(250), "FIELD3" VARCHAR2(250), "FIELD4" VARCHAR2(250),
 "FIELD5" VARCHAR2(250), "FIELD6" VARCHAR2(250), "FIELD7" VARCHAR2(250), "FIELD8"
 VARCHAR2(250), "FIELD9" VARCHAR2(250), "FIELD10" VARCHAR2(250), "FIELD11" VARCHAR2(250),
 "FIELD12" VARCHAR2(250), "FIELD13" VARCHAR2(250), "FIELD14" VARCHAR2(250), "C_TEL"
 VARCHAR2(20), "C_ADDRESS" VARCHAR2(500), "RECEIVE_NM" VARCHAR2(100), "DOC_NO_PDA"
 NUMBER(15, 0), "PDA_NM" VARCHAR2(50), "CR_CARD_NO_SCND" NUMBER(5, 0), "CR_CARD_AMT_SCND"
 NUMBER, "CR_CARD_NO_THRD" NUMBER(5, 0), "CR_CARD_AMT_THRD" NUMBER, "DRIVER_NO" NUMBER(10
, 0), "ADD_DISC_AMT_MST" NUMBER, "ADD_DISC_AMT_DTL" NUMBER, "OTHR_AMT_DISC" NUMBER,
 "PAID_AMT" NUMBER, "PAID_BILL" NUMBER(1, 0), "PAID_U_ID" NUMBER(5, 0), "PAID_DATE" DATE,
 "REC_INV_BILL" NUMBER(1, 0), "REC_INV_U_ID" NUMBER(5, 0), "REC_INV_DATE" DATE,
 "BILL_VALUED" NUMBER(1, 0), "VALUE_DATE" DATE, "POS_POST" NUMBER(1, 0), "CR_DOC_NO_REF"
 NUMBER(15, 0), "BILL_WITHOUT_AUTO_OTHR_AMT" NUMBER(1, 0), "CR_VALUED" NUMBER(1, 0),
 "CR_VALUED_SCND" NUMBER(1, 0), "CR_VALUED_THRD" NUMBER(1, 0), "CR_DOC_NO_REF_SCND"
 NUMBER(15, 0), "CR_DOC_NO_REF_THRD" NUMBER(15, 0), "CR_VALUE_DATE" DATE,
 "CR_VALUE_DATE_SCND" DATE, "CR_VALUE_DATE_THRD" DATE, "CR_CARD_COMM_PER" NUMBER,
 "CR_CARD_COMM_PER_SCND" NUMBER, "CR_CARD_COMM_PER_THRD" NUMBER, "QT_PRM_NO" NUMBER(15,
 0), "QT_PRM_SER" NUMBER(38, 0), "QT_PRM_RCRD_NO" NUMBER(10, 0), "PRM_CODE" VARCHAR2(15),
 "DOC_BRN_NO" NUMBER(6, 0), "CMPNY_NO" NUMBER(5, 0), "MOBILE_NO" NUMBER(20, 0),
 "SEND_TEL_SUCCESS" NUMBER, "SEND_TEL_RESULTCODE" NUMBER, "NOT_USE_QUT_PRM" NUMBER(1, 0),
 "INSRNCE_CMP_NO" NUMBER(10, 0), "INSRNCE_BNF_NO" NUMBER(5, 0), "INSRNCE_PRSON_NM"
 VARCHAR2(100), "INSRNCE_CARD_NO" VARCHAR2(60), "INSRNCE_CARD_NO_FMLY" VARCHAR2(60),
 "INSRNCE_RLTN_TYP" NUMBER(2, 0), "INSRNCE_CLSS_NO" VARCHAR2(10), "INSRNCE_LOAD_PER"
 NUMBER, "INSRNCE_DIAGNOSIS" VARCHAR2(500), "INSRNCE_MDCL_NO" NUMBER(5, 0),
 "INSRNCE_APPRVD_CODE" VARCHAR2(60), "INSRNCE_CSH_AMT" NUMBER, "COMM_AMT_DTL" NUMBER,
 "CONN_SI_WITH_OUTGONG" NUMBER(1, 0), "C_CODE_CSH" VARCHAR2(15), "CPN_FLG" NUMBER(1, 0),
 "CST_GCC" NUMBER(1, 0), "REC_NOTE" VARCHAR2(500), "TANK_CODE" VARCHAR2(30),
 "POINT_RPLC_AMT" NUMBER, "VAT_AMT_OTHR" NUMBER, "C_TAX_CODE" VARCHAR2(20), "CNTRCT_DATE"
 DATE, "CNTRCT_NO" VARCHAR2(30), "CRD_NO_DISC" VARCHAR2(60), "CRD_DISC_PER" NUMBER,
 "DOC_SRL_CNTRCT" NUMBER(38, 0), "CNTRCT_BTCH_NO" NUMBER(30, 0), "POINT_TYP_NO" NUMBER(5,
 0), "POINT_CALC_TYP_NO" NUMBER(1, 0), "POINT_CNT" NUMBER, "POINT_CNT_ALL" NUMBER,
 "POINT_RPLC_CNT" NUMBER, "ASS_AMT" NUMBER, "DISC_AMT_AFTR_VAT" NUMBER,
 "CLC_INSRNCE_LOAD_AMT_MTHD" NUMBER(1, 0), "AC_CODE" VARCHAR2(30), "AC_CODE_DTL"
 VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "PYMNT_AC" NUMBER, "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE"
 DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "CLC_TAX_INSRNC_CMPNY_FLG" NUMBER(1, 0), "PTNT_NO"
 VARCHAR2(15), "DCTR_NO" VARCHAR2(15), "PTNT_TYP" NUMBER(1, 0), "DOC_NO_ADMSON" NUMBER(15
, 0), "DOC_SRL_ADMSON" NUMBER(38, 0), "DOC_SER_EXTRNL" VARCHAR2(256), "CNCL_FLG" NUMBER(1
, 0), "CLC_VAT_PRICE_TYP" NUMBER(1, 0), "OUT_BILL_TYP" NUMBER(1, 0), "SFDA_DCTR_NO"
 VARCHAR2(15), "SFDA_PTNT_ID" VARCHAR2(20), "SFDA_PRSPCT_NO" VARCHAR2(15),
 "SFDA_PRSPCT_DATE" DATE, "RMS_BILL_DOC_TYPE" NUMBER(2, 0), "RMS_FREE_FLG" NUMBER(1, 0),
 "CR_CARD_MAX_COMM_AMT" NUMBER, "CR_CARD_MAX_COMM_AMT_SCND" NUMBER,
 "CR_CARD_MAX_COMM_AMT_THRD" NUMBER, "HRS_DOC_NO_REF" NUMBER, "HRS_DOC_TYPE_REF" NUMBER,
 "HRS_DOC_SER_REF" NUMBER, "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0), "INSRNCE_ADD_LMT_MST"
 NUMBER, "INSRNCE_MDCN_CHRONIC_FLG" NUMBER(1, 0), "DOC_M_SQ" NUMBER,
 "ADVNC_PYMNT_PRCNT_CNTRCT" NUMBER, "CR_CARD_CST_NO" VARCHAR2(60), "CR_CARD_CST_NO_SCND"
 VARCHAR2(60), "CR_CARD_CST_NO_THRD" VARCHAR2(60), "CR_CARD_DOC_NO_REF" NUMBER(15, 0),
 "CR_CARD_DOC_NO_REF_SCND" NUMBER(15, 0), "CR_CARD_DOC_NO_REF_THRD" NUMBER(15, 0),
 "CR_CARD_DSC" VARCHAR2(500), "CR_CARD_DSC_SCND" VARCHAR2(500), "CR_CARD_DSC_THRD"
 VARCHAR2(500), "AD_DATE_CLK" DATE, "BILL_STAT_TYP" NUMBER(2, 0), "INSRNCE_ADD_LMT_DOC"
 NUMBER, "INSRNCE_ADD_LMT_DTL" NUMBER, "INSRNCE_LMT_AMT_LOC_DOC" NUMBER,
 "WEB_SRVC_TRNSFR_DATA_FLG" NUMBER(1, 0), "WEB_SRVC_UUID" VARCHAR2(100))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_BILLS" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_BILL_DTL" ("BILL_DOC_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "BILL_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "BILL_SER" NUMBER(38, 0) NOT NULL ENABLE, "I_CODE"
 VARCHAR2(30) NOT NULL ENABLE, "I_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE,
 "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER NOT NULL ENABLE, "I_PRICE" NUMBER,
 "STK_COST" NUMBER, "OUT_QTY" NUMBER, "OUT_FREE_QTY" NUMBER, "W_CODE" NUMBER(10, 0) NOT
 NULL ENABLE, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15),
 "EXPIRE_DATE" DATE NOT NULL ENABLE, "BATCH_NO" VARCHAR2(30) NOT NULL ENABLE, "FREE_QTY"
 NUMBER, "DIS_PER" NUMBER(20, 17), "DIS_AMT" NUMBER, "DIS_AMT_MST" NUMBER, "DIS_AMT_DTL"
 NUMBER, "DIS_AFTR_VAT_MST" NUMBER, "DIS_AMT_DTL_VAT" NUMBER, "DIS_AMT_MST_VAT" NUMBER,
 "VAT_AMT_DIS_DTL_VAT" NUMBER, "VAT_AMT_AFTR_DIS" NUMBER, "VAT_AMT_BFR_DIS" NUMBER,
 "VAT_AMT_DIS_MST_VAT" NUMBER, "DIS_AMT_AFTR_VAT" NUMBER, "OTHR_AMT_DISC" NUMBER,
 "VAT_PER" NUMBER, "VAT_AMT" NUMBER, "OTHR_AMT" NUMBER, "USE_SERIALNO" NUMBER(1, 0),
 "SERVICE_ITEM" NUMBER(1, 0), "RCRD_NO" NUMBER(10, 0) NOT NULL ENABLE, "DOC_SEQUENCE"
 NUMBER(38, 0) NOT NULL ENABLE, "ITEM_DESC" VARCHAR2(1000), "SI_TYPE" NUMBER(5, 0),
 "BARCODE" VARCHAR2(30), "SO_NO" NUMBER(15, 0), "SO_SER" NUMBER(38, 0), "DOC_TYPE_REF"
 NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0), "EXTERNAL_POST"
 NUMBER(5, 0), "BILL_PY" NUMBER(1, 0), "USE_ATTCH" NUMBER(1, 0), "REC_ATTCH" NUMBER(10,
 0), "ADD_DIS_AMT_MST" NUMBER, "ADD_DIS_AMT_DTL" NUMBER, "DIS_PER2" NUMBER,
 "DIS_AMT_DTL2" NUMBER, "DIS_PER3" NUMBER, "DIS_AMT_DTL3" NUMBER, "RCRD_NO_REF" NUMBER(10
, 0), "EMP_NO" NUMBER(10, 0), "I_LENGTH" NUMBER, "I_PRICE_VAT" NUMBER, "I_WIDTH" NUMBER,
 "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "WT_UNT" VARCHAR2(10), "WT_QTY" NUMBER,
 "POST_CODE" VARCHAR2(10), "QT_PRM_NO" NUMBER(15, 0), "QT_PRM_SER" NUMBER(38, 0),
 "QT_PRM_RCRD_NO" NUMBER(10, 0), "INSRNCE_LOAD_PER" NUMBER, "INSRNCE_LOAD_AMT" NUMBER,
 "INSRNCE_ADD_LMT" NUMBER, "INSRNCE_APPRVD_CODE" VARCHAR2(60), "SUB_C_CODE" VARCHAR2(15),
 "I_PRICE_OUTGONG" NUMBER, "PKG_UNT" VARCHAR2(10), "PKG_UNT_SIZE" NUMBER(10, 0),
 "PKG_QTY" NUMBER, "PKG_LENGTH" NUMBER, "PKG_WIDTH" NUMBER, "PKG_HEIGHT" NUMBER,
 "PKG_SIZE" NUMBER, "PKG_WEIGHT" NUMBER, "FIELD_DTL1" VARCHAR2(60), "FIELD_DTL2"
 VARCHAR2(60), "FIELD_DTL3" VARCHAR2(60), "MEASUR_PRICE" NUMBER, "ARGMNT_NO" NUMBER,
 "CPN_QTY" NUMBER, "DOC_SEQ_TMP" NUMBER(38, 0), "USED_ITM" NUMBER(1, 0), "VAT_AMT_OTHR"
 NUMBER, "PRM_GRP_NO" NUMBER(5, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "COMM_PER" NUMBER, "COMM_AMT_DTL" NUMBER, "DOC_SEQUENCE_REF" NUMBER(38, 0), "UP_CNT"
 NUMBER(10, 0), "DIS_PER_QT_PRM" NUMBER, "DIS_AMT_DTL_QT_PRM" NUMBER,
 "DIS_AMT_DTL_QT_PRM_VAT" NUMBER, "DIS_AMT_DTL2_VAT" NUMBER, "DIS_AMT_DTL3_VAT" NUMBER,
 "VAT_AMT_DIS_DTL2_VAT" NUMBER, "VAT_AMT_DIS_DTL3_VAT" NUMBER, "FIELD_DTL4" VARCHAR2(60),
 "FIELD_DTL5" VARCHAR2(60), "FIELD_DTL6" VARCHAR2(60), "FIELD_DTL7" VARCHAR2(60),
 "FIELD_DTL8" VARCHAR2(60), "FIELD_DTL9" VARCHAR2(60), "FIELD_DTL10" VARCHAR2(60),
 "LEV_NO" NUMBER(3, 0), "I_PRICE_LEV_NO" NUMBER, "OTHR_AMT_ITM" NUMBER, "OUT_QTY_YR"
 NUMBER, "OUT_FREE_QTY_YR" NUMBER, "INSRNCE_ADD_LMT_MST" NUMBER, "FREE_TYP" NUMBER(1, 0))
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 131072 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_BILLS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_RET_BILL_MST" ("RET_NO" NUMBER(15, 0) NOT NULL ENABLE, "RET_SER"
 NUMBER(38, 0), "RT_BILL_DOC_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "RT_BILL_NO" NUMBER(15,
 0) NOT NULL ENABLE, "RT_BILL_SER" NUMBER(38, 0) NOT NULL ENABLE, "RET_DATE" DATE NOT
 NULL ENABLE, "SR_TYPE" NUMBER(5, 0), "A_CY" VARCHAR2(7) NOT NULL ENABLE, "AC_RATE"
 NUMBER, "STK_RATE" NUMBER, "C_CODE" VARCHAR2(15), "C_NAME" VARCHAR2(150), "A_CODE"
 VARCHAR2(30) NOT NULL ENABLE, "RET_POST" NUMBER(1, 0), "W_CODE" NUMBER(10, 0), "REF_NO"
 VARCHAR2(15), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15),
 "CASH_NO" NUMBER(10, 0), "DOC_DESC" VARCHAR2(1000), "PR_REP" NUMBER(10, 0), "ATTACH_CNT"
 NUMBER(3, 0), "RT_TYPE" NUMBER(1, 0), "BILL_SER" NUMBER(38, 0), "BILL_NO" NUMBER(15, 0),
 "R_CODE" NUMBER(10, 0), "DOC_BRN_NO" NUMBER(6, 0), "EXTERNAL_POST" NUMBER(5, 0),
 "RET_AMT" NUMBER, "STAND_BY" NUMBER(1, 0), "FIELD1" VARCHAR2(250), "FIELD2"
 VARCHAR2(250), "FIELD3" VARCHAR2(250), "FIELD4" VARCHAR2(250), "FIELD5" VARCHAR2(250),
 "FIELD6" VARCHAR2(250), "FIELD7" VARCHAR2(250), "FIELD8" VARCHAR2(250), "FIELD9"
 VARCHAR2(250), "FIELD10" VARCHAR2(250), "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC"
 VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "AD_U_ID" NUMBER(5,
 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE"
 DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "RET_BILL_TYP" NUMBER(1, 0), "AD_DATE_CLK" DATE)  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_RTBI" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_RET_BILL_DTL" ("RET_NO" NUMBER(15, 0) NOT NULL ENABLE, "RET_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "RT_BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "RT_BILL_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "SR_TYPE" NUMBER(5, 0), "I_CODE" VARCHAR2(30) NOT NULL
 ENABLE, "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE,
 "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER, "I_PRICE" NUMBER, "STK_COST" NUMBER,
 "W_CODE" NUMBER(10, 0) NOT NULL ENABLE, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15),
 "ACTV_NO" VARCHAR2(15), "EXPIRE_DATE" DATE, "BATCH_NO" VARCHAR2(30), "USE_SERIALNO"
 NUMBER(1, 0), "DIS_AMT" NUMBER, "DIS_PER" NUMBER(20, 17), "RCRD_NO" NUMBER(10, 0),
 "VAT_AMT" NUMBER, "VAT_PER" NUMBER, "RT_RCRD_NO" NUMBER(10, 0), "BARCODE" VARCHAR2(30),
 "BILL_NO" NUMBER(15, 0), "BILL_SER" NUMBER(38, 0), "OUT_NO" NUMBER(15, 0), "OUT_SER"
 NUMBER(38, 0), "SI_RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE" NUMBER(38, 0) NOT NULL ENABLE,
 "DOC_SEQUENCE_SI" NUMBER(38, 0), "USE_ATTCH" NUMBER(1, 0), "REC_ATTCH" NUMBER(10, 0),
 "I_LENGTH" NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "WT_UNT"
 VARCHAR2(10), "WT_QTY" NUMBER, "POST_CODE" VARCHAR2(10), "ITEM_DESC" VARCHAR2(1000),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "ARGMNT_NO" NUMBER, "UP_CNT" NUMBER(10, 0),
 "EXTERNAL_POST" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_RTBI" LOGGING NOCOMPRESS;

CREATE TABLE "SALES_CHARGES" ("SC_NO" NUMBER(3, 0), "SC_NAME" VARCHAR2(100), "A_CODE"
 VARCHAR2(30), "A_CY" VARCHAR2(7), "AC_RATE" NUMBER, "AMT_TYPE" NUMBER(1, 0), "SC_TYPE"
 NUMBER(1, 0), "AMT" NUMBER, "FILL_AUTO" NUMBER(1, 0), "CALC_TYPE" NUMBER(1, 0),
 "INV_ITEM" NUMBER(1, 0), "ALLOW_RETURN" NUMBER(1, 0), "SC_QTY_TYPE" NUMBER(1, 0),
 "POSTED_TO_SALES" NUMBER(1, 0), "SC_RET_WITHOUT_BILLNO" NUMBER(1, 0), "ADD_TO_BILL_DISC"
 NUMBER(1, 0), "BILL_DOC_TYPE" NUMBER(2, 0), "VAT_PER" NUMBER, "USE_VAT" NUMBER(1, 0),
 "AMT_TYP_VAL" NUMBER(1, 0), "SC_POST_WITH_ACY" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "SC_ADD_FRC_INVOICE" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "SALES_CHARGES_ITEMS" ("SC_NO" NUMBER(3, 0), "C_CLASS" NUMBER(3, 0),
 "C_CODE" VARCHAR2(15), "I_CODE" VARCHAR2(30) CONSTRAINT "SCI_NN_ICODE" NOT NULL ENABLE,
 "ITM_UNT" VARCHAR2(10), "P_SIZE" NUMBER, "G_CODE" VARCHAR2(10), "AMT" NUMBER, "PER_AMT"
 NUMBER, "W_CODE" NUMBER(10, 0), "SI_TYPE" NUMBER(5, 0), "F_DATE" DATE, "T_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "SALES_DISC" ("BILL_DOC_TYPE" NUMBER(2, 0), "G_CODE" VARCHAR2(10), "C_CODE"
 VARCHAR2(15), "C_CLASS" NUMBER(3, 0), "I_CODE" VARCHAR2(30), "P_SIZE" NUMBER, "ITM_UNT"
 VARCHAR2(10), "AMT_TYPE" NUMBER(1, 0), "AMT" NUMBER(24, 9), "A_CY" VARCHAR2(7),
 "AC_RATE" NUMBER, "W_CODE" NUMBER(10, 0), "WHG_CODE" NUMBER(10, 0), "F_DATE" DATE,
 "T_DATE" DATE, "LEV_NO" NUMBER(3, 0), "F_QTY" NUMBER, "T_QTY" NUMBER, "BATCH_NO"
 VARCHAR2(30), "I_PRICE" NUMBER, "STK_COST" NUMBER, "AVLQTY" NUMBER, "DOC_DESC"
 VARCHAR2(250), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10,
 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "AMT2" NUMBER, "AMT3" NUMBER
, "CST_GRP_CODE" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "SALES_FREE_QTY" ("G_CODE" VARCHAR2(10), "C_CODE" VARCHAR2(15), "C_CLASS"
 NUMBER(3, 0), "I_CODE" VARCHAR2(30), "P_SIZE" NUMBER, "ITM_UNT" VARCHAR2(10), "PAY_TYPE"
 NUMBER(1, 0), "LOW_QTY" NUMBER, "PER_QTY" NUMBER, "W_CODE" NUMBER(10, 0), "WHG_CODE"
 NUMBER(10, 0), "BILL_DOC_TYPE" NUMBER(2, 0), "RCRD_NO" NUMBER(11, 0), "F_QTY" NUMBER,
 "T_QTY" NUMBER, "F_DATE" DATE, "T_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER" ("C_CODE" VARCHAR2(15), "C_A_NAME" VARCHAR2(100) NOT NULL ENABLE,
 "C_E_NAME" VARCHAR2(100), "C_A_CODE" VARCHAR2(30) NOT NULL ENABLE, "CST_SEQ" NUMBER(38,
 0), "C_GROUP_CODE" NUMBER(10, 0), "C_TAX_CODE" VARCHAR2(20), "C_BOX_CODE" VARCHAR2(20),
 "C_ADDRESS" VARCHAR2(500), "CNTRY_NO" NUMBER(4, 0), "PROV_NO" NUMBER(10, 0), "CITY_NO"
 NUMBER(10, 0), "R_CODE" NUMBER(10, 0), "REP_CODE" VARCHAR2(15), "ROUTE_NO" NUMBER(10, 0)
, "SORTINROUTE" NUMBER(10, 0), "GPS" VARCHAR2(100), "COL_NO" NUMBER(10, 0), "CC_CODE"
 VARCHAR2(30), "CREDIT_PERIOD" NUMBER(3, 0), "C_PHONE" VARCHAR2(16), "C_FAX" VARCHAR2(16)
, "C_BOX" VARCHAR2(60), "C_PERSON" VARCHAR2(40), "C_E_MAIL" VARCHAR2(60), "C_WEB_SITE"
 VARCHAR2(30), "C_CLASS" NUMBER(3, 0), "C_DEGREE" NUMBER(3, 0), "C_MOBILE" VARCHAR2(16),
 "C_SINCE" DATE, "INACTIVE" NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(250), "INACTIVE_DATE"
 DATE, "C_VENDOR" VARCHAR2(15), "C_NOTE" VARCHAR2(100), "DISC_PER" NUMBER,
 "CONF_LAST_DATE" DATE, "CONN_REM_SYS" NUMBER(1, 0), "INACTIVE_SALES" NUMBER(1, 0),
 "G_NAME" VARCHAR2(60), "G_ADDRESS" VARCHAR2(60), "G_START_DATE" DATE, "G_EXPIRE_DATE"
 DATE, "G_TYPE" NUMBER(1, 0), "G_AMT" NUMBER, "G_STATUS" NUMBER(1, 0), "G_FIN_CENTER"
 VARCHAR2(60), "G_WORK" VARCHAR2(60), "G_DOC_DATE" DATE, "G_REG_COURT" VARCHAR2(30),
 "G_REG_TRADA" VARCHAR2(30), "G_FILE_TRADA" VARCHAR2(30), "G_TEL" VARCHAR2(30), "G_FAX"
 VARCHAR2(30), "BLK_LST" NUMBER(1, 0), "BLK_LST_RES" VARCHAR2(250), "C_SALES_MAN"
 NUMBER(1, 0), "LICENSE_NO" VARCHAR2(30), "LICENSE_OWNER" VARCHAR2(60), "RESPONS_PERSON"
 VARCHAR2(60), "SIGN_AUTH_PERSON" VARCHAR2(60), "SERIALNO" NUMBER, "DRIVER_NO" NUMBER(10,
 0), "AC_OP_NO" NUMBER(15, 0), "IMP_XLS" NUMBER(1, 0), "C_PARENT" VARCHAR2(15),
 "CONN_BRN_NO" NUMBER(6, 0), "SEND_MSG" NUMBER(1, 0), "LATITUDE" VARCHAR2(20),
 "LONGITUDE" VARCHAR2(20), "GPS_COLOR" VARCHAR2(20), "FAV_AC" NUMBER(1, 0), "F_ACTV_DATE"
 DATE, "T_ACTV_DATE" DATE, "SECRET_KEY" VARCHAR2(30), "ALLOW_PRD_AFTR_DUE" NUMBER(3, 0),
 "BLK_LST_DATE" DATE, "C_AGE" VARCHAR2(30), "C_GENDER" NUMBER(1, 0), "INSURANCE_NO"
 VARCHAR2(60), "APPROVAL_NO" VARCHAR2(60), "C_INSURANCE" NUMBER(1, 0), "C_CODE_TRGT"
 VARCHAR2(15), "INSRNCE_CST" NUMBER(1, 0), "INSRNCE_CMP_NO" NUMBER(10, 0), "NTNLTY_NO"
 NUMBER(5, 0), "TYP_CRD" NUMBER(3, 0), "CRD_NO" VARCHAR2(30), "CRD_ISSUSE_PLAC"
 VARCHAR2(60), "CRD_ISSUSE_DATE" DATE, "CRD_END_DATE" DATE, "C_PROFF" NUMBER(30, 0),
 "AGNT_FLG" NUMBER(1, 0), "CR_NO" VARCHAR2(60), "ACTVTY_NM" VARCHAR2(100), "C_CODE_LGN"
 VARCHAR2(10), "NIS_NO" VARCHAR2(60), "NAI_DSC" VARCHAR2(60), "CSH_CST" NUMBER(1, 0),
 "EQ_CPTL" VARCHAR2(60), "RESPONS_PERSON_JOB" VARCHAR2(60), "CST_CR_LMT_LOCAL" NUMBER,
 "CST_INV_LMT_LOCAL" NUMBER, "CST_LMT_TYP" NUMBER(1, 0), "CST_LMT_PER" NUMBER,
 "CRD_END_DATE_AH" DATE, "CRD_ISSUSE_DATE_AH" DATE, "BRTH_DATE" DATE, "BRTH_DATE_AH" DATE
, "BRTH_PLC" VARCHAR2(200), "WORK_PLC" VARCHAR2(200), "SRC_INC" VARCHAR2(200),
 "SRC_INC_RATE" NUMBER, "MRTL_STAT" NUMBER(2, 0), "CMPNY_WORK" VARCHAR2(200),
 "C_FINSCAN_STATUS" NUMBER(1, 0), "OPN_FILE_DATE" DATE, "END_FILE_DATE" DATE,
 "HOME_ADDRESS" VARCHAR2(60), "SIGN_IMG_NM" VARCHAR2(100), "PASS_NO" VARCHAR2(30),
 "PASS_ISSUSE_PLAC" VARCHAR2(60), "PASS_ISSUSE_DATE" DATE, "PASS_END_DATE" DATE,
 "NAME_IN_PASS" VARCHAR2(150), "ADD_INCM_SRCE" NUMBER(2, 0), "ADD_INCM_RATE" NUMBER(10,
 0), "CNT_REM_MNTH_EXPCT" NUMBER(5, 0), "OTHR_CMP_BNK" VARCHAR2(150), "COMM_REG_NO"
 VARCHAR2(30), "REG_ISSUSE_PLAC" VARCHAR2(60), "REG_ISSUSE_DATE" DATE, "REG_END_DATE"
 DATE, "CMP_ACTIV" VARCHAR2(150), "CST_GCC" NUMBER(1, 0), "CST_FILE_UP_DATE" DATE,
 "CST_BNF_TYPE" NUMBER(5, 0), "CST_MAIN_IMG_NM" VARCHAR2(300), "CST_VAT_GRP_FLG" NUMBER(1
, 0), "CST_DEAL_FLG" NUMBER(1, 0), "CST_EXCPT_QT_PRM_FLG" NUMBER(1, 0), "CST_EXCH_FLG"
 NUMBER(1, 0), "C_CLASS_TYP" NUMBER(5, 0), "C_BUS_SEC" NUMBER(10, 0), "C_PER_FEE"
 NUMBER(3, 0), "C_ACCT_FEE" VARCHAR2(30), "AUTO_APPRVD" NUMBER(1, 0) NOT NULL ENABLE,
 "DISC_PER_DFLT" NUMBER, "ALLOW_UPD_FIXED_PRICE" NUMBER(1, 0), "FIELD1" VARCHAR2(1000),
 "FIELD2" VARCHAR2(1000), "FIELD3" VARCHAR2(1000), "FIELD4" VARCHAR2(1000), "FIELD5"
 VARCHAR2(1000), "FIELD6" VARCHAR2(1000), "FIELD7" VARCHAR2(1000), "FIELD8"
 VARCHAR2(1000), "FIELD9" VARCHAR2(1000), "FIELD10" VARCHAR2(1000), "FIELD11"
 VARCHAR2(60), "FIELD12" VARCHAR2(60), "FIELD13" VARCHAR2(60), "FIELD14" VARCHAR2(60),
 "FIELD15" VARCHAR2(60), "FIELD16" VARCHAR2(60), "FIELD17" VARCHAR2(60), "FIELD18"
 VARCHAR2(60), "FIELD19" VARCHAR2(60), "FIELD20" VARCHAR2(60), "AD_U_PHOTO" NUMBER(5, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "CST_RGSTR_TYP" NUMBER(2, 0), "CONN_HPS_SYS" NUMBER, "SCTR_TYP" NUMBER(1,
 0), "PLTCL_RLTN_FLG" NUMBER(1, 0), "PLTCL_RLTN_WITH" VARCHAR2(1000), "CLC_TYP_NO_TAX"
 NUMBER(5, 0), "C_BARCODE" VARCHAR2(30), "VST_OPN_TYP" NUMBER(2, 0), "CLC_VAT_PRICE_TYP"
 NUMBER(1, 0), "GLN_CODE" VARCHAR2(500), "C_MOB_DEV_SRL" VARCHAR2(50), "C_SAV_LOGIN_DATA"
 NUMBER(1, 0), "C_REST_PASS" NUMBER(1, 0), "C_VERFY_SMS_CODE" VARCHAR2(20),
 "WEB_SRVC_USE_AUTO_SYNC_CST" NUMBER, "WEB_SRVC_EXTRNL_C_CODE" VARCHAR2(30),
 "WEB_SRVC_USR_NO" VARCHAR2(30), "WEB_SRVC_PASSWRD" VARCHAR2(30), "WEB_SRVC_LNK"
 VARCHAR2(30), "PRM_CODE" VARCHAR2(15), "EMP_NO" NUMBER(10, 0), "DUE_TYPE" NUMBER(1, 0),
 "AGENT_CST_NO_SER" VARCHAR2(15), "PRD_DAY" NUMBER(5, 0), "RPT_QTY_LMT_CNT" NUMBER(5, 0),
 "LMT_ITM_QTY_TYP" NUMBER(1, 0), "CNFRM_NOTE" VARCHAR2(200), "USE_HOLSTR" NUMBER(1, 0),
 "CMPNS_TYP" NUMBER(5, 0), "EXTERNAL_POST" NUMBER(5, 0), "CSTMR_LGHT_FLG" NUMBER(1, 0),
 "BUILDING_NO" VARCHAR2(200), "STREET" VARCHAR2(200))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_GROUP" ("C_GROUP_CODE" NUMBER(10, 0), "C_GROUP_A_NAME"
 VARCHAR2(100) NOT NULL ENABLE, "C_GROUP_E_NAME" VARCHAR2(100), "C_A_CODE" VARCHAR2(30)
 NOT NULL ENABLE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_CLASS" ("C_CLASS" NUMBER(3, 0), "C_CLASS_NAME" VARCHAR2(100) NOT
 NULL ENABLE, "C_CLASS_E_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_CLASS_TYP" ("C_CLASS_TYP" NUMBER(3, 0), "C_CLASS_TYP_NM"
 VARCHAR2(100), "C_CLASS_TYP_F_NM" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(6, 0), "UP_CNT" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_CURR" ("C_CODE" VARCHAR2(15), "A_CY" VARCHAR2(7), "CR_LIMIT"
 NUMBER(24, 9), "INV_LIMIT" NUMBER(24, 9), "CST_LMT_PER" NUMBER, "CST_LMT_TYP" NUMBER(1,
 0), "LEV_NO" NUMBER(3, 0), "INACTIVE" NUMBER(1, 0), "CNFRM_LST_DATE" DATE, "LEV_NO_CSH"
 NUMBER(3, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(10, 0), "EXTERNAL_POST" NUMBER(5, 0), "INACTIVE_SALES" NUMBER(1,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT"
 LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_CURR_RQ" ("C_CODE" VARCHAR2(15), "A_CY" VARCHAR2(7), "CR_LIMIT"
 NUMBER(24, 9), "INV_LIMIT" NUMBER(24, 9), "LEV_NO" NUMBER(3, 0), "CNFRM_LST_DATE" DATE,
 "INACTIVE" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "CST_LMT_TYP" NUMBER(1, 0), "CST_LMT_PER" NUMBER, "UP_CNT" NUMBER(10, 0)
, "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_BNK_ACCNT" ("C_CODE" VARCHAR2(15), "BNK_A_CODE" VARCHAR2(30),
 "A_CY" VARCHAR2(7), "DFLT_FLG" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_DEGREE" ("C_DEGREE" NUMBER(3, 0), "C_DEGREE_A_NAME" VARCHAR2(100)
 NOT NULL ENABLE, "C_DEGREE_E_NAME" VARCHAR2(100), "DEGREE_VALUE" NUMBER, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP"
 LOGGING NOCOMPRESS;

CREATE TABLE "CUSTOMER_RQ" ("C_CODE" VARCHAR2(15), "C_A_NAME" VARCHAR2(100) NOT NULL
 ENABLE, "C_E_NAME" VARCHAR2(100), "C_A_CODE" VARCHAR2(30) NOT NULL ENABLE, "CST_SEQ"
 NUMBER(38, 0), "C_GROUP_CODE" NUMBER(10, 0) NOT NULL ENABLE, "C_TAX_CODE" VARCHAR2(20),
 "C_BOX_CODE" VARCHAR2(20), "C_ADDRESS" VARCHAR2(500), "CNTRY_NO" NUMBER(4, 0), "PROV_NO"
 NUMBER(10, 0), "CITY_NO" NUMBER(10, 0), "R_CODE" NUMBER(10, 0), "REP_CODE" VARCHAR2(15),
 "ROUTE_NO" NUMBER(10, 0), "SORTINROUTE" NUMBER(10, 0), "GPS" VARCHAR2(100), "COL_NO"
 NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "CREDIT_PERIOD" NUMBER(3, 0), "C_PHONE"
 VARCHAR2(16), "C_FAX" VARCHAR2(16), "C_BOX" VARCHAR2(60), "C_PERSON" VARCHAR2(40),
 "C_E_MAIL" VARCHAR2(60), "C_WEB_SITE" VARCHAR2(30), "C_CLASS" NUMBER(3, 0), "C_DEGREE"
 NUMBER(3, 0), "C_MOBILE" VARCHAR2(16), "C_SINCE" DATE, "INACTIVE" NUMBER(1, 0),
 "INACTIVE_RES" VARCHAR2(250), "INACTIVE_DATE" DATE, "C_VENDOR" VARCHAR2(15), "C_NOTE"
 VARCHAR2(100), "DISC_PER" NUMBER, "CONN_REM_SYS" NUMBER(1, 0), "INACTIVE_SALES" NUMBER(1
, 0), "G_NAME" VARCHAR2(60), "G_ADDRESS" VARCHAR2(60), "G_START_DATE" DATE,
 "G_EXPIRE_DATE" DATE, "G_TYPE" NUMBER(1, 0), "G_AMT" NUMBER, "G_STATUS" NUMBER(1, 0),
 "G_FIN_CENTER" VARCHAR2(60), "G_WORK" VARCHAR2(60), "G_DOC_DATE" DATE, "G_REG_COURT"
 VARCHAR2(30), "G_REG_TRADA" VARCHAR2(30), "G_FILE_TRADA" VARCHAR2(30), "G_TEL"
 VARCHAR2(30), "G_FAX" VARCHAR2(30), "BLK_LST" NUMBER(1, 0), "BLK_LST_RES" VARCHAR2(250),
 "C_SALES_MAN" NUMBER(1, 0), "LICENSE_NO" VARCHAR2(30), "LICENSE_OWNER" VARCHAR2(60),
 "RESPONS_PERSON" VARCHAR2(60), "SIGN_AUTH_PERSON" VARCHAR2(60), "SERIALNO" NUMBER,
 "DRIVER_NO" NUMBER(10, 0), "AC_OP_NO" NUMBER(15, 0), "IMP_XLS" NUMBER(1, 0), "C_PARENT"
 VARCHAR2(15), "CONN_BRN_NO" NUMBER(6, 0), "SEND_MSG" NUMBER(1, 0), "APRV_U_ID" NUMBER(5,
 0), "APRV_DSC" VARCHAR2(500), "APRV_DATE" DATE, "APPROVED" NUMBER, "DOC_SRL" NUMBER(38,
 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3,
 0), "CSH_CST" NUMBER(1, 0), "RESPONS_PERSON_JOB" VARCHAR2(60), "CST_CR_LMT_LOCAL" NUMBER
, "CST_INV_LMT_LOCAL" NUMBER, "CST_LMT_TYP" NUMBER(1, 0), "CST_LMT_PER" NUMBER,
 "CRD_END_DATE_AH" DATE, "CRD_ISSUSE_DATE_AH" DATE, "BRTH_DATE" DATE, "BRTH_DATE_AH" DATE
, "BRTH_PLC" VARCHAR2(200), "WORK_PLC" VARCHAR2(200), "SRC_INC" VARCHAR2(200),
 "SRC_INC_RATE" NUMBER, "MRTL_STAT" NUMBER(2, 0), "CMPNY_WORK" VARCHAR2(200),
 "C_FINSCAN_STATUS" NUMBER(1, 0), "OPN_FILE_DATE" DATE, "END_FILE_DATE" DATE,
 "HOME_ADDRESS" VARCHAR2(60), "SIGN_IMG_NM" VARCHAR2(100), "PASS_NO" VARCHAR2(30),
 "PASS_ISSUSE_PLAC" VARCHAR2(60), "PASS_ISSUSE_DATE" DATE, "PASS_END_DATE" DATE,
 "NAME_IN_PASS" VARCHAR2(150), "ADD_INCM_SRCE" NUMBER(2, 0), "ADD_INCM_RATE" NUMBER(10,
 0), "CNT_REM_MNTH_EXPCT" NUMBER(5, 0), "OTHR_CMP_BNK" VARCHAR2(150), "COMM_REG_NO"
 VARCHAR2(30), "REG_ISSUSE_PLAC" VARCHAR2(60), "REG_ISSUSE_DATE" DATE, "REG_END_DATE"
 DATE, "CMP_ACTIV" VARCHAR2(150), "CST_GCC" NUMBER(1, 0), "CST_FILE_UP_DATE" DATE,
 "CST_BNF_TYPE" NUMBER(5, 0), "CST_MAIN_IMG_NM" VARCHAR2(300), "AD_U_PHOTO" NUMBER(5, 0),
 "CST_VAT_GRP_FLG" NUMBER(1, 0), "CST_DEAL_FLG" NUMBER(1, 0) NOT NULL ENABLE,
 "CST_EXCPT_QT_PRM_FLG" NUMBER(1, 0), "CST_EXCH_FLG" NUMBER(1, 0) NOT NULL ENABLE,
 "C_CLASS_TYP" NUMBER(5, 0), "C_RISK" NUMBER(5, 0), "C_BUS_SEC" NUMBER(10, 0),
 "C_PER_FEE" NUMBER(3, 0), "C_ACCT_FEE" VARCHAR2(30), "AUTO_APPRVD" NUMBER(1, 0) NOT NULL
 ENABLE, "APRV_RSK_U_ID" NUMBER(5, 0), "APRV_RSK_DSC" VARCHAR2(500), "APRV_RSK_DATE" DATE
, "APPRVD_RSK" NUMBER, "FIELD1" VARCHAR2(60), "FIELD2" VARCHAR2(60), "FIELD3"
 VARCHAR2(60), "FIELD4" VARCHAR2(60), "FIELD5" VARCHAR2(60), "FIELD6" VARCHAR2(60),
 "FIELD7" VARCHAR2(60), "FIELD8" VARCHAR2(60), "FIELD9" VARCHAR2(60), "FIELD10"
 VARCHAR2(60), "FIELD11" VARCHAR2(60), "FIELD12" VARCHAR2(60), "FIELD13" VARCHAR2(60),
 "FIELD14" VARCHAR2(60), "FIELD15" VARCHAR2(60), "FIELD16" VARCHAR2(60), "FIELD17"
 VARCHAR2(60), "FIELD18" VARCHAR2(60), "FIELD19" VARCHAR2(60), "FIELD20" VARCHAR2(60),
 "LATITUDE" VARCHAR2(20), "LONGITUDE" VARCHAR2(20), "GPS_COLOR" VARCHAR2(20), "FAV_AC"
 NUMBER(1, 0), "F_ACTV_DATE" DATE, "T_ACTV_DATE" DATE, "SECRET_KEY" VARCHAR2(30),
 "ALLOW_PRD_AFTR_DUE" NUMBER(3, 0), "BLK_LST_DATE" DATE, "C_AGE" VARCHAR2(30), "C_GENDER"
 NUMBER(1, 0), "INSURANCE_NO" VARCHAR2(60), "APPROVAL_NO" VARCHAR2(60), "C_INSURANCE"
 NUMBER(1, 0), "C_CODE_TRGT" VARCHAR2(15), "INSRNCE_CST" NUMBER(1, 0), "INSRNCE_CMP_NO"
 NUMBER(10, 0), "NTNLTY_NO" NUMBER(5, 0), "TYP_CRD" NUMBER(3, 0), "CRD_NO" VARCHAR2(30),
 "CRD_ISSUSE_PLAC" VARCHAR2(60), "CRD_ISSUSE_DATE" DATE, "CRD_END_DATE" DATE, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "CR_NO" VARCHAR2(60), "ACTVTY_NM" VARCHAR2(100), "NIS_NO" VARCHAR2(60), "NAI_DSC"
 VARCHAR2(60), "EQ_CPTL" VARCHAR2(60), "AGNT_FLG" NUMBER(1, 0) NOT NULL ENABLE,
 "C_ID_PLACE" VARCHAR2(50), "C_ID" VARCHAR2(30), "C_ID_ISS_DATE" DATE, "C_ID_EXP_DATE"
 DATE, "C_PROFF" NUMBER(30, 0), "C_ID_TYPE" NUMBER(30, 0), "INSRTD_FLG" NUMBER(1, 0),
 "PLTCL_RLTN_FLG" NUMBER(1, 0), "PLTCL_RLTN_WITH" VARCHAR2(1000))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "ARS_CST_TRNS_GPS" ("DOC_TYP" NUMBER(10, 0), "DOC_SRL" NUMBER(38, 0),
 "C_CODE" VARCHAR2(15), "GPS_LNGT_X" VARCHAR2(50), "GPS_LAT_Y" VARCHAR2(50), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "SUB_CUSTOMER" ("C_CODE" VARCHAR2(15), "SUB_C_CODE" VARCHAR2(15),
 "SUB_C_L_NM" VARCHAR2(100), "SUB_C_F_NM" VARCHAR2(100), "DPRTMNT_NM" VARCHAR2(100),
 "JOB_NAME" VARCHAR2(100), "C_ADDRESS" VARCHAR2(250), "C_BOX" VARCHAR2(30), "C_FAX"
 VARCHAR2(30), "C_PHONE" VARCHAR2(30), "C_MOBILE" VARCHAR2(30), "CNTRY_NO" NUMBER(4, 0),
 "CITY_NO" NUMBER(10, 0), "R_CODE" NUMBER(10, 0), "INACTIVE" NUMBER(1, 0),
 "INACTIVE_DATE" DATE, "INACTIVE_RES" VARCHAR2(250), "INACTIVE_U_ID" NUMBER(5, 0),
 "CARD_NO" VARCHAR2(60), "CARD_TYP" NUMBER(2, 0), "CARD_JOB_NO" VARCHAR2(60), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(6,
 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "MEASUR_DATE" DATE, "IMP_XLS" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS
 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CSTMR_CNTCT_US" ("DOC_NO" NUMBER(38, 0), "DOC_DATE" DATE, "DOC_SUBJCT"
 VARCHAR2(250), "DOC_DSC" VARCHAR2(500), "CUST_CODE" VARCHAR2(15), "CUST_L_NM"
 VARCHAR2(60), "MOBILE_NO" VARCHAR2(16), "TEL_NO" VARCHAR2(16), "E_MAIL" VARCHAR2(30),
 "ADDRESS" VARCHAR2(100))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_USR_LGN_HSTRY" ("U_ID" NUMBER(5, 0) NOT NULL ENABLE, "TRMNL_NM"
 VARCHAR2(30), "LGN_TYP" NUMBER(1, 0), "LGN_OUT_DATE" DATE NOT NULL ENABLE, "LNG_NO"
 NUMBER(3, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL
 ENABLE, "BRN_YEAR" NUMBER(4, 0) NOT NULL ENABLE, "BRN_USR" NUMBER(3, 0) NOT NULL ENABLE,
 "APPL_NO" NUMBER, "HSTRY_NO" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_HISTORY" LOGGING NOCOMPRESS;

CREATE TABLE "ARS_BILL_FLLWUP_MOVMNT" ("TRNS_TYP" NUMBER(1, 0) NOT NULL ENABLE, "TRNS_NO"
 NUMBER(5, 0) NOT NULL ENABLE, "DOC_NO" NUMBER NOT NULL ENABLE, "DOC_SER" NUMBER NOT NULL
 ENABLE, "CNFRM_TYP" NUMBER(1, 0), "CNFRM_U_ID" NUMBER(5, 0), "CNFRM_DATE" DATE,
 "CNFRM_DSC" VARCHAR2(250), "ORDR_NO" NUMBER(5, 0), "CMP_NO" NUMBER(3, 0), "BRN_NO"
 NUMBER(6, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "DRIVER_NO" NUMBER(10, 0), "REC_INV_DATE" DATE)  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_BILLS" LOGGING
 NOCOMPRESS;

