CREATE TABLE "IAS_MEASUR_DSC_ITM_MST" ("I_CODE" VARCHAR2(30), "MEASUR_NO" NUMBER(5, 0),
 "MEASUR_L_NM" VARCHAR2(100), "MEASUR_F_NM" VARCHAR2(100), "DOC_SEQ" NUMBER, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(6,
 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "MEASUR_DSC" VARCHAR2(250), "MEASUR_IMG" VARCHAR2(250), "INACTIVE" NUMBER(1, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT"
 LOGGING NOCOMPRESS;

CREATE TABLE "IAS_MEASUR_DSC_ITM_DTL" ("I_CODE" VARCHAR2(30), "MEASUR_NO" NUMBER(5, 0),
 "MEASUR_L_NM" VARCHAR2(100), "MEASUR_F_NM" VARCHAR2(100), "DOC_SEQ" NUMBER, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(6,
 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "MEASUR_NO_REF" NUMBER(5, 0), "MEASUR_IMG" VARCHAR2(250))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_UNTS_CONV" ("MSUR_MAN_NO" NUMBER(15, 0), "MSUR_MAN_CODE" VARCHAR2(10),
 "MSUR_OBS_CODE" VARCHAR2(10), "ARGMNT_NO" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE
, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CONN_ITM_MSUR_UNT" ("I_CODE" VARCHAR2(30), "ITM_UNT" VARCHAR2(10),
 "P_SIZE" NUMBER, "DFLT_UNIT" NUMBER(1, 0), "MSUR_WT_CODE" VARCHAR2(10), "ARGMNT_NO"
 NUMBER, "MSUR_QTY_CODE" VARCHAR2(10), "MIN_UNT" NUMBER(1, 0), "FACTOR" VARCHAR2(1),
 "USE_FRACTION" NUMBER(1, 0), "UPD_FLG" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE"
 DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10
, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

