public class PeriodExchangeRate
{
    public short? PrdNo { get; private set; }
    public string? ACy { get; private set; }
    public int? CurRate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public DateTime? TDate { get; private set; }
    public string? ACy { get; private set; }
    public int? CurRate { get; private set; }
    public int BrnNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short BillDocType { get; private set; }
    public long BillNo { get; private set; }
    public long BillSer { get; private set; }
    public string ICode { get; private set; }
    public string? INm { get; private set; }
    public int? IQty { get; private set; }
    public int? FreeQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int PQty { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public int? IncQty { get; private set; }
    public int? IncFreeQty { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public int? DisAmtMst { get; private set; }
    public decimal? DisPer { get; private set; }
    public int? DisAmtDtl { get; private set; }
    public decimal? DisPer2 { get; private set; }
    public int? DisAmtDtl2 { get; private set; }
    public decimal? DisPer3 { get; private set; }
    public int? DisAmtDtl3 { get; private set; }
    public int? DisAmt { get; private set; }
    public int? VatPer { get; private set; }
    public int? VatAmt { get; private set; }
    public int? AddAmt { get; private set; }
    public int? OthrAmt { get; private set; }
    public bool? UseSerialno { get; private set; }
    public long RcrdNo { get; private set; }
    public long DocSequence { get; private set; }
    public long? DocSequenceGrnPo { get; private set; }
    public string? ItemDesc { get; private set; }
    public string? Barcode { get; private set; }
    public long? PoNo { get; private set; }
    public long? PoSer { get; private set; }
    public long? GrnNo { get; private set; }
    public long? GrnSer { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public int? DisAmtNotEffect { get; private set; }
    public int? AddDisAmtMst { get; private set; }
    public int? AddDisAmtDtl { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public string? PostCode { get; private set; }
    public int? UnitSize { get; private set; }
    public int? UQty { get; private set; }
    public string? GrRef { get; private set; }
    public int? DocType { get; private set; }
    public int? DocSequencePo { get; private set; }
    public string? PoOrderNo { get; private set; }
    public string? PoOrderSer { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public bool? ServiceItm { get; private set; }
    public int? FreeQtyProft { get; private set; }
    public int? IPriceVat { get; private set; }
    public string? CntrctNo { get; private set; }
    public string? CntnrNo { get; private set; }
    public string? CntrctSer { get; private set; }
    public long? CntrctBtchNo { get; private set; }
    public string? FreightNo { get; private set; }
    public string? FreightSer { get; private set; }
    public long? FreightDocSequence { get; private set; }
    public int? OthrAmtDisc { get; private set; }
    public int? VatAmtOthr { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public int? DocTypRef { get; private set; }
    public long? DocSequenceRef { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? ArgmntNo { get; private set; }
    public int? OthrAmtItm { get; private set; }
    public string? PkgUnt { get; private set; }
    public long? PkgUntSize { get; private set; }
    public int? PkgQty { get; private set; }
    public int? PkgLength { get; private set; }
    public int? PkgWidth { get; private set; }
    public int? PkgHeight { get; private set; }
    public int? PkgSize { get; private set; }
    public int? PkgWeight { get; private set; }
    public long? UpCnt { get; private set; }
    public int? SalePrice { get; private set; }
    public string? FieldDtl1 { get; private set; }
    public string? FieldDtl2 { get; private set; }
    public string? FieldDtl3 { get; private set; }
    public string? FieldDtl4 { get; private set; }
    public string? FieldDtl5 { get; private set; }
    public string? FieldDtl6 { get; private set; }
    public string? FieldDtl7 { get; private set; }
    public string? FieldDtl8 { get; private set; }
    public string? FieldDtl9 { get; private set; }
    public string? FieldDtl10 { get; private set; }
    public bool? BarcodePrnt { get; private set; }
    public int? LastIncomePrice { get; private set; }
    public int? ActulQty { get; private set; }
    public int? LosQty { get; private set; }
}