public class ParameterAP
{
    public bool? ParaNo { get; private set; }
    public bool DocGenAp { get; private set; }
    public bool AllowDocDelNo { get; private set; }
    public bool? DateGenAp { get; private set; }
    public bool DateSettingAp { get; private set; }
    public short VendorLength { get; private set; }
    public bool VendorDType { get; private set; }
    public bool ApAcLinkType { get; private set; }
    public bool ApUseFreeQty { get; private set; }
    public bool ShowDiscPerItemsAp { get; private set; }
    public bool? ItmDiscType { get; private set; }
    public bool DiscCount { get; private set; }
    public bool? ApCsType { get; private set; }
    public bool ApPjType { get; private set; }
    public bool? ApActvType { get; private set; }
    public bool ApWcType { get; private set; }
    public bool? ApLinkInv { get; private set; }
    public short NoOfDecimalAp { get; private set; }
    public bool? LcType { get; private set; }
    public bool LcStatus { get; private set; }
    public bool? PurchaseDiscType { get; private set; }
    public bool PurFreeQtyCosting { get; private set; }
    public bool ShowGName { get; private set; }
    public bool UseLocGrn { get; private set; }
    public bool UseDelAp { get; private set; }
    public bool UseModAp { get; private set; }
    public bool ApPreqSerial { get; private set; }
    public bool ApPoSerial { get; private set; }
    public bool GrnSerial { get; private set; }
    public bool ApPiSerial { get; private set; }
    public bool ApPriSerial { get; private set; }
    public bool UseBoe { get; private set; }
    public bool ConnPrPoPi { get; private set; }
    public bool? ShowIDescAp { get; private set; }
    public bool ShowItemDesc { get; private set; }
    public bool RequestRefnoAp { get; private set; }
    public bool RequestDescAp { get; private set; }
    public bool ShowWcodeInPreq { get; private set; }
    public bool UserApprovedInPreq { get; private set; }
    public bool InsrtVndrItm { get; private set; }
    public bool FillLcInJv { get; private set; }
    public bool PaidInstllmntMan { get; private set; }
    public bool UsePinoRtPrPy { get; private set; }
    public bool? Disc1NotEffectVndTrns { get; private set; }
    public bool? Disc2NotEffectVndTrns { get; private set; }
    public bool? Disc3NotEffectVndTrns { get; private set; }
    public bool? ApDiscType { get; private set; }
    public bool? VendorSerial { get; private set; }
    public int? ShowSumQty { get; private set; }
    public bool? AllowDuplItm { get; private set; }
    public bool? PurManMandtry { get; private set; }
    public bool? UseSrvcBill { get; private set; }
    public int? NotifyItmPrqstNotPrcss { get; private set; }
    public int? NotifyItmPordrNotPrcss { get; private set; }
    public bool? UseApCheckQty { get; private set; }
    public bool? UseKimbAp { get; private set; }
    public bool? EffctKimbVndr { get; private set; }
    public bool? CalcVatAmtTypeAp { get; private set; }
    public bool? ConnItmWithMoreVndr { get; private set; }
    public bool? AddItmPriceFromBill { get; private set; }
    public bool? ApUseSrvcItm { get; private set; }
    public bool? PoChkMaxLmtCost { get; private set; }
    public bool? ShowTotAmt { get; private set; }
    public bool? ConnCntrctPoType { get; private set; }
    public bool? ChkItmConnByVndr { get; private set; }
    public int? UseApOthrChrg { get; private set; }
    public bool? ShowItmBarcodeAp { get; private set; }
    public bool? BillDueDateLastMnth { get; private set; }
    public short? ShwAddFldDtlCnt { get; private set; }
    public bool? ShwCstInPrqstOrdr { get; private set; }
    public bool? UseRtBillRqst { get; private set; }
    public bool? UseLocGrnMoreOne { get; private set; }
    public bool? RequestVndrBillNo { get; private set; }
    public bool? UseAssgnToUsr { get; private set; }
    public bool? ShowFreeQtyProft { get; private set; }
    public bool? ClcDiscWithoutItmDisc { get; private set; }
    public bool? ShwTotItmPriceByNet { get; private set; }
    public bool? RqrdCntnrNo { get; private set; }
    public bool? NotChkLcBlncInBillCst { get; private set; }
    public bool? ConnPoPiTyp { get; private set; }
    public bool? UseVndrVatType { get; private set; }
    public bool? PriceVndrItmUntTyp { get; private set; }
    public int? AllwUpdtVndrInbill { get; private set; }
    public bool? AutoUpdateVndrPrice { get; private set; }
    public bool? UseRetWithoutPiBillno { get; private set; }
    public bool? ApItemChrgCalcType { get; private set; }
    public bool? ApItemChrgWcodeType { get; private set; }
    public bool? ApItemChrgUsePrd { get; private set; }
    public bool? AllwdRePurSerialno { get; private set; }
    public int? UseShpngLst { get; private set; }
    public int? ApDiscPrd { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpdateQtPrmSal { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? ApItemChrgCalcAmtType { get; private set; }
    public bool? UsePostTaxDue { get; private set; }
    public int? UseVndrPriceLst { get; private set; }
    public int? ShwItemSize { get; private set; }
    public int? ConnVndrPricePo { get; private set; }
    public bool? AddFrcInvoicePi { get; private set; }
    public bool? UseArbicSrchIcode { get; private set; }
    public bool? UseSalPriceAsPurPrice { get; private set; }
    public short? LvlNoPrice { get; private set; }
    public bool? UseVndrClaim { get; private set; }
    public bool? RetPiFreeQtyPer { get; private set; }
    public bool? UsePiClcTaxFreeQty { get; private set; }
    public bool? AddItmPriceFromPo { get; private set; }
    public bool? UseDeliverd { get; private set; }
    public bool? ShowIcodeVndrAp { get; private set; }
}