public class ArsAnswrQuestnnrDtl
{
    public int? RcrdNo { get; private set; }
    public int ModlNo { get; private set; }
    public long AnswrNo { get; private set; }
    public string AnswrLName { get; private set; }
    public string? AnswrFName { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? ModlLName { get; private set; }
    public string? ModlFName { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long DocSrl { get; private set; }
    public string ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? IQty { get; private set; }
    public long? DocSrl { get; private set; }
    public string? CCode { get; private set; }
    public long? DocSrlRef { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? PrcssFlg { get; private set; }
    public DateTime? DocDate { get; private set; }
    public long? DocNoRef { get; private set; }
    public int TrnsNo { get; private set; }
    public int DocNo { get; private set; }
    public int DocSer { get; private set; }
    public bool? CnfrmTyp { get; private set; }
    public int? CnfrmUId { get; private set; }
    public DateTime? CnfrmDate { get; private set; }
    public string? CnfrmDsc { get; private set; }
    public int? OrdrNo { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? DriverNo { get; private set; }
    public DateTime? RecInvDate { get; private set; }
    public int? CodeNo { get; private set; }
    public string CodeLNm { get; private set; }
    public string? CodeFNm { get; private set; }
    public long? OrdrNo { get; private set; }
    public string? Notes { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? InactiveUId { get; private set; }
    public int AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string TypLNm { get; private set; }
    public string TypFNm { get; private set; }
    public long? OrdrNo { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public bool? Inactive { get; private set; }
}