public class CcGrouping
{
    public int? GroupNo { get; private set; }
    public string GroupName { get; private set; }
    public string? GroupEName { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? WCode { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public string CityAName { get; private set; }
    public string? CityEName { get; private set; }
    public long? ProvNo { get; private set; }
    public short? CntryNo { get; private set; }
    public string? CityShrt { get; private set; }
    public short? ZoneNo { get; private set; }
    public int? CitySer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string CntryAName { get; private set; }
    public string? CntryEName { get; private set; }
    public string? CntryShrt { get; private set; }
    public string? CntryCntnt { get; private set; }
    public short? CurNo { get; private set; }
    public string? CurCode { get; private set; }
    public string? CntryAntion { get; private set; }
    public string? CntryEntion { get; private set; }
    public string? NtionShrt { get; private set; }
    public short? ZoneNo { get; private set; }
    public bool? NotAllwDealWth { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? PhoneKey { get; private set; }
}