public class DateLock
{
    public DateTime? Ufd { get; private set; }
    public DateTime? Utd { get; private set; }
    public DateTime? Lfd { get; private set; }
    public DateTime? Ltd { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public short? BillDocType { get; private set; }
    public string? ICode { get; private set; }
    public int? IQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? WCode { get; private set; }
    public int? PQty { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public int? GrItemType { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int InvType { get; private set; }
    public long? InvSer { get; private set; }
    public string ICode { get; private set; }
    public string ItmUnt { get; private set; }
    public long? WCode { get; private set; }
    public int? IQty { get; private set; }
    public int PSize { get; private set; }
    public int? PQty { get; private set; }
    public string? BCode { get; private set; }
    public string? Barcode { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public int? AvlQty { get; private set; }
    public long? RcrdNo { get; private set; }
    public bool? UseAttch { get; private set; }
    public string? ItemDesc { get; private set; }
    public int? AttchNo1 { get; private set; }
    public int? AttchNo2 { get; private set; }
    public int? AttchNo3 { get; private set; }
    public int? AttchNo4 { get; private set; }
    public int? AttchNo5 { get; private set; }
    public int? AttchDescNo1 { get; private set; }
    public int? AttchDescNo2 { get; private set; }
    public int? AttchDescNo3 { get; private set; }
    public int? AttchDescNo4 { get; private set; }
    public int? AttchDescNo5 { get; private set; }
    public long? FlexNo { get; private set; }
    public int? DocTypeRef { get; private set; }
    public int? DocJvTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public int? ExternalPost { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public bool? ProcessedAdj { get; private set; }
    public int? ArgmntNo { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? KitItm { get; private set; }
    public int? MinQty { get; private set; }
}