public class GnrWebSrvcClmn
{
    public long SrvcNo { get; private set; }
    public int? ClmnOrdr { get; private set; }
    public string? ClmnNm { get; private set; }
    public string? ClmnNmOnyx { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? DocTyp { get; private set; }
    public string? SrvcQry { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? SrvcLDsc { get; private set; }
    public string? SrvcFDsc { get; private set; }
    public string? SrvcUrl { get; private set; }
    public string? SrvcMthd { get; private set; }
    public bool? SrvcSynchrnz { get; private set; }
    public bool? SrvcTyp { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? RqustBodyTmplt { get; private set; }
    public string? CntntType { get; private set; }
    public string? HttpSuccesRspnsCode { get; private set; }
    public string? TxtSuccesRspns { get; private set; }
    public string? UserName { get; private set; }
    public string? Password { get; private set; }
    public string? AuthType { get; private set; }
    public int DocTyp { get; private set; }
    public string? WaltPath { get; private set; }
    public string? WaltPwd { get; private set; }
    public string? RootObjName { get; private set; }
    public string? NonArrayObjs { get; private set; }
    public int? ESysNo { get; private set; }
}