public class GrDetail
{
    public int PiType { get; private set; }
    public long? GrNo { get; private set; }
    public long? GSer { get; private set; }
    public int? IncomType { get; private set; }
    public DateTime? GrDate { get; private set; }
    public string ICode { get; private set; }
    public int? IQty { get; private set; }
    public int? FreeQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int? PQty { get; private set; }
    public int? CpQty { get; private set; }
    public long? WCode { get; private set; }
    public long? WhgCode { get; private set; }
    public int? CPrice { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public int? StkRate { get; private set; }
    public string ACy { get; private set; }
    public int? AcRate { get; private set; }
    public int? WtAvgBefore { get; private set; }
    public int? WtAvgAfter { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? PiNo { get; private set; }
    public short? PurType { get; private set; }
    public long? DocSer { get; private set; }
    public int? DocTypeRef { get; private set; }
    public int? DocJvTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public long? DocSequenceRef { get; private set; }
    public string? VCode { get; private set; }
    public int? DisAmt { get; private set; }
    public int? VatPer { get; private set; }
    public int? VatAmt { get; private set; }
    public int? DiffAmt { get; private set; }
    public bool? UseSerialno { get; private set; }
    public long? RcrdNo { get; private set; }
    public long RecNo { get; private set; }
    public long DocSequence { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public string? ItemDesc { get; private set; }
    public string? Barcode { get; private set; }
    public bool? UnderSelling { get; private set; }
    public int? ExternalPost { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public string? PostCode { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public int? ArgmntNo { get; private set; }
    public string? CntnrNo { get; private set; }
    public int? OthrAmtDisc { get; private set; }
    public int? VatAmtOthr { get; private set; }
    public short? CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public int? OthrAmtItm { get; private set; }
    public bool? WebSrvcTrnsfrDataFlg { get; private set; }
    public string? WebSrvcTrnsfrDataDsc { get; private set; }
    public int? DisAmtNotEffect { get; private set; }
    public int? AvlQtyBefore { get; private set; }
    public int? InvCmltvBlnc { get; private set; }
    public int? InvWtavgFrc { get; private set; }
    public bool? InvCmltvDiffFlg { get; private set; }
    public int? InvCmltvDiff { get; private set; }
}