public class GrnDetail
{
    public long GrNo { get; private set; }
    public long? GSer { get; private set; }
    public int GrnType { get; private set; }
    public long? PoNo { get; private set; }
    public long? PoSer { get; private set; }
    public string ICode { get; private set; }
    public int? IQty { get; private set; }
    public int? FreeQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int PQty { get; private set; }
    public int? IPrice { get; private set; }
    public string? CcCode { get; private set; }
    public long? WCode { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public string? ItemDesc { get; private set; }
    public string? Barcode { get; private set; }
    public bool? UseSerialno { get; private set; }
    public long? RcrdNo { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public long? DocSequence { get; private set; }
    public long? DocSequencePo { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public int? IPriceVat { get; private set; }
    public int? ArgmntNo { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? FieldDtl1 { get; private set; }
    public string? FieldDtl2 { get; private set; }
    public string? FieldDtl3 { get; private set; }
    public string? FieldDtl4 { get; private set; }
    public string? FieldDtl5 { get; private set; }
    public string? FieldDtl6 { get; private set; }
    public string? FieldDtl7 { get; private set; }
    public string? FieldDtl8 { get; private set; }
    public string? FieldDtl9 { get; private set; }
    public string? FieldDtl10 { get; private set; }
}