public class GrNoteBr
{
    public int PiType { get; private set; }
    public long? GrNo { get; private set; }
    public long? GSer { get; private set; }
    public short? IncomType { get; private set; }
    public DateTime? GrDate { get; private set; }
    public string? ACode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public string? ACy { get; private set; }
    public int? AcRate { get; private set; }
    public int? StkRate { get; private set; }
    public int? GrAmt { get; private set; }
    public long? PiNo { get; private set; }
    public string? VCode { get; private set; }
    public string? CCode { get; private set; }
    public string? LcNo { get; private set; }
    public bool? CFlag { get; private set; }
    public int? WCode { get; private set; }
    public long? CshBnkNo { get; private set; }
    public bool? GrPost { get; private set; }
    public string? RefNo { get; private set; }
    public string? ADesc { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public short? AttachCnt { get; private set; }
    public bool? Pending { get; private set; }
    public short? PurType { get; private set; }
    public string? DriverName { get; private set; }
    public string? CarNo { get; private set; }
    public bool? WorkShop { get; private set; }
    public long? DocSer { get; private set; }
    public long? DocNo { get; private set; }
    public bool? RtOut { get; private set; }
    public string? OutDiffACode { get; private set; }
    public string? OutDiffACy { get; private set; }
    public int? OutDiffAmt { get; private set; }
    public string? BoeNo { get; private set; }
    public bool? UseVat { get; private set; }
    public int? VatAmt { get; private set; }
    public int? PrRep { get; private set; }
    public short? PiDocType { get; private set; }
    public int? ExternalPost { get; private set; }
    public bool? Hung { get; private set; }
    public long? MrpMtSq { get; private set; }
    public string? MrpMtOrder { get; private set; }
    public short? MrpMtType { get; private set; }
    public bool? UnderSelling { get; private set; }
    public short? DocBrnNo { get; private set; }
    public DateTime? DocDueDate { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public bool? OnnWithPi { get; private set; }
    public int? VatAmtOthr { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public short? CmpNo { get; private set; }
    public short? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}