public class IasAcExpenseDist
{
    public long? RcrdNo { get; private set; }
    public string? ACode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public int? ExpPer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long DocSer { get; private set; }
    public short? DocTypeRef { get; private set; }
    public string? VCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? ACy { get; private set; }
    public long DocNoRef { get; private set; }
    public long DocSerRef { get; private set; }
    public long INo { get; private set; }
    public int? PaidAmtDoc { get; private set; }
    public int? RcrdNo { get; private set; }
    public bool? IPy { get; private set; }
    public int? PaidAmt { get; private set; }
    public int? IAmt { get; private set; }
    public DateTime? IDate { get; private set; }
    public short? CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
}