public class IasAudLmtExd
{
    public long? AudNo { get; private set; }
    public short? AudType { get; private set; }
    public int? DocType { get; private set; }
    public long? JvType { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public string? ACode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public string? ACy { get; private set; }
    public int? Amt { get; private set; }
    public int? Amtf { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? CCode { get; private set; }
    public string? VCode { get; private set; }
    public string? ADesc { get; private set; }
    public string? RefNo { get; private set; }
    public long? CashNo { get; private set; }
    public long? ChequeNo { get; private set; }
    public DateTime? ValueDate { get; private set; }
    public int? ExternalPost { get; private set; }
    public string? TrmnlName { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? ACodeLmt { get; private set; }
    public string? CcCodeLmt { get; private set; }
    public string? ACyLmt { get; private set; }
    public int? AmtLmt { get; private set; }
    public bool? ExceedLmt { get; private set; }
    public int? AudUId { get; private set; }
    public DateTime? AudDate { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short CmpNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
}