public class IasApCntrctMst
{
    public string CntrctNo { get; private set; }
    public string CntrctSer { get; private set; }
    public DateTime CntrctDate { get; private set; }
    public DateTime? CntrctFDate { get; private set; }
    public DateTime? CntrctTDate { get; private set; }
    public string? VCode { get; private set; }
    public string? VName { get; private set; }
    public int? CntrctAmt { get; private set; }
    public string? CntrctACy { get; private set; }
    public int? CntrctRate { get; private set; }
    public bool? CntrctType { get; private set; }
    public string? CntrctDesc { get; private set; }
    public string? CntrctNote { get; private set; }
    public int? CntrctRenewAmt { get; private set; }
    public int? AmtRemNotify { get; private set; }
    public int? DayExpirNotify { get; private set; }
    public bool? AlowExcdAmt { get; private set; }
    public int? PerExcd { get; private set; }
    public string? RefNo { get; private set; }
    public int? DiscAmt { get; private set; }
    public int? DiscAmtMst { get; private set; }
    public int? DiscAmtDtl { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public bool? Processed { get; private set; }
    public bool? Inactive { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? InactiveRes { get; private set; }
    public bool? Approved { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? AprvDsc { get; private set; }
    public string? CntrctNoRenew { get; private set; }
    public string? CntrctSerRenew { get; private set; }
    public int? VatAmt { get; private set; }
    public bool? UseVat { get; private set; }
    public int? ClcVatPriceTyp { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? ClcTaxFreeQtyFlg { get; private set; }
}