public class IasAudPrntRep
{
    public int FormNo { get; private set; }
    public string RepNm { get; private set; }
    public int AudUId { get; private set; }
    public DateTime? AudDate { get; private set; }
    public string? TrmnlName { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public short? BrnYear { get; private set; }
    public string? RepWhr { get; private set; }
    public string? RepTitle { get; private set; }
    public string? RepWhr1 { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short? PostType { get; private set; }
    public short? GroupType { get; private set; }
    public short? GroupBy { get; private set; }
    public bool? SumDtl { get; private set; }
    public short? RepType { get; private set; }
    public int? RepSer { get; private set; }
    public string? RepName { get; private set; }
    public string? ClmnMst { get; private set; }
    public string? ClmnMst0 { get; private set; }
    public string? ClmnMst1 { get; private set; }
    public string? ClmnMst2 { get; private set; }
    public string? ClmnMst3 { get; private set; }
    public string? ClmnMst4 { get; private set; }
    public string? ClmnMst5 { get; private set; }
    public string? ClmnMst6 { get; private set; }
    public string? ClmnMst7 { get; private set; }
    public string? ClmnMst8 { get; private set; }
    public string? ClmnMst9 { get; private set; }
    public string? PFromMst { get; private set; }
    public string? PWhereMst { get; private set; }
    public string? PGroupby { get; private set; }
    public string? ClmnDtl { get; private set; }
    public string? ClmnDtl0 { get; private set; }
    public string? ClmnDtl1 { get; private set; }
    public string? ClmnDtl2 { get; private set; }
    public string? ClmnDtl3 { get; private set; }
    public string? ClmnDtl4 { get; private set; }
    public string? ClmnDtl5 { get; private set; }
    public string? ClmnDtl6 { get; private set; }
    public string? ClmnDtl7 { get; private set; }
    public string? ClmnDtl8 { get; private set; }
    public string? ClmnDtl9 { get; private set; }
    public string? ClmnDtl10 { get; private set; }
    public string? ClmnDtl11 { get; private set; }
    public string? ClmnDtl12 { get; private set; }
    public string? ClmnDtl13 { get; private set; }
    public string? ClmnDtl14 { get; private set; }
    public string? ClmnDtl15 { get; private set; }
    public string? ClmnDtl16 { get; private set; }
    public string? ClmnDtl17 { get; private set; }
    public string? ClmnDtl18 { get; private set; }
    public string? ClmnDtl19 { get; private set; }
    public string? ClmnDtl20 { get; private set; }
    public string? PFromDtl { get; private set; }
    public string? PWhereDtl { get; private set; }
    public string? PTableDtl { get; private set; }
    public string? RepSlct1 { get; private set; }
    public string? RepSlct2 { get; private set; }
    public string? RepSlct3 { get; private set; }
    public string? RepSlct4 { get; private set; }
    public long? PrRep { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? CmpNo { get; private set; }
    public short? BrnUsr { get; private set; }
}