public class IasArchivesMst
{
    public long? FileNo { get; private set; }
    public DateTime? FileDate { get; private set; }
    public string? FileDesc { get; private set; }
    public string? FileNote { get; private set; }
    public int? DocType { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PrRep { get; private set; }
    public long DocNo { get; private set; }
    public short? DocJvType { get; private set; }
    public long? PumpOprtorNo { get; private set; }
    public int? PouringType { get; private set; }
    public long? PumpNo { get; private set; }
    public int? LabSrvc { get; private set; }
    public long? LocNo { get; private set; }
    public int? AgrcltrTyp { get; private set; }
    public int? WtrPrfNo { get; private set; }
    public string? Screed { get; private set; }
    public string? CarNo { get; private set; }
    public long? StnNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? DocType { get; private set; }
    public DateTime CntrctBtchDate { get; private set; }
    public string CntrctNo { get; private set; }
    public long? DocNo { get; private set; }
    public long DocSrl { get; private set; }
    public int? RcrdNo { get; private set; }
    public int Amt { get; private set; }
    public bool? Processed { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? AdvncPymnt { get; private set; }
    public bool? PrcssdFlgGls { get; private set; }
}