public class IasApKimbMst
{
    public int DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public short KmType { get; private set; }
    public long? BillNo { get; private set; }
    public long? BillSer { get; private set; }
    public string? LcNo { get; private set; }
    public long? LcSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string? ACode { get; private set; }
    public string? VCode { get; private set; }
    public int? AcRate { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public int? BillAcAmt { get; private set; }
    public string? BillAcCur { get; private set; }
    public long? BankNo { get; private set; }
    public string? CommACode { get; private set; }
    public int? CommAmt { get; private set; }
    public string? BkExpACode { get; private set; }
    public int? BkExpAmt { get; private set; }
    public string? BkExpCur { get; private set; }
    public string? MarginACode { get; private set; }
    public int? MarginAmt { get; private set; }
    public string? MarginCur { get; private set; }
    public bool? MarginRcvred { get; private set; }
    public bool? ExpAfctTyp { get; private set; }
    public int? NoDays { get; private set; }
    public int? KCnt { get; private set; }
    public DateTime? BillDate { get; private set; }
    public bool? DocPost { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public int? MarginRate { get; private set; }
    public int? BkExpRate { get; private set; }
    public string? DocDesc { get; private set; }
    public string? RefNo { get; private set; }
    public short? JvType { get; private set; }
    public long? JDocNo { get; private set; }
    public long? JSer { get; private set; }
    public string? KimACode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}