public class IasApChargesItems
{
    public short? ChrgNo { get; private set; }
    public short? VClass { get; private set; }
    public string? VCode { get; private set; }
    public string? ICode { get; private set; }
    public string? GCode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public int? Amt { get; private set; }
    public int? PerAmt { get; private set; }
    public long? WCode { get; private set; }
    public int? BillTypeNo { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public string? MngCode { get; private set; }
    public string? SubgCode { get; private set; }
    public string? GroupNo { get; private set; }
    public string? AssistantNo { get; private set; }
    public string? DetailNo { get; private set; }
    public string? GrpClassCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? SlcNo { get; private set; }
    public int? FAmt { get; private set; }
    public int? TAmt { get; private set; }
    public int? SclcPanAmt { get; private set; }
    public int? SclcNoPanAmt { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public DateTime CntrctBtchDate { get; private set; }
    public string CntrctNo { get; private set; }
    public string CntrctSer { get; private set; }
    public int RcrdNo { get; private set; }
    public int Amt { get; private set; }
    public bool? Processed { get; private set; }
    public int? Inactive { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? InactiveRes { get; private set; }
    public short? CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}