public class IasBillMstAddDisc
{
    public bool AddDiscType { get; private set; }
    public long DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string ACode { get; private set; }
    public string? DiscACode { get; private set; }
    public string ACy { get; private set; }
    public int DocRate { get; private set; }
    public string? RefNo { get; private set; }
    public long? BillNo { get; private set; }
    public long? BillSer { get; private set; }
    public DateTime? BillDate { get; private set; }
    public string? CCode { get; private set; }
    public long? WCode { get; private set; }
    public long? CashNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? ColNo { get; private set; }
    public int? ExternalPost { get; private set; }
    public string? RepCode { get; private set; }
    public int? AddDiscAmtDtl { get; private set; }
    public int? AddDiscAmtMst { get; private set; }
    public int? AddDiscAmtMstPrev { get; private set; }
    public int? AddDiscount { get; private set; }
    public int? AddVatAmt { get; private set; }
    public int? RetAmt { get; private set; }
    public string? DocDesc { get; private set; }
    public bool? DocPost { get; private set; }
    public int? DocBrnNo { get; private set; }
    public long? RCode { get; private set; }
    public bool? StandBy { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public int? SiAddDiscType { get; private set; }
    public long? RqSer { get; private set; }
    public int? DocTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public short? BillDocType { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public short? BrnYear { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PrRep { get; private set; }
    public long? RcrdNoRef { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public bool? ClcVatPriceTyp { get; private set; }
    public string? PtntNo { get; private set; }
    public bool? ClcTaxFreeQtyFlg { get; private set; }
    public DateTime? AdDateClk { get; private set; }
    public bool? WebSrvcTrnsfrDataFlg { get; private set; }
    public string? WebSrvcUuid { get; private set; }
}