public class IasBdgtBlncClmnDtl
{
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public string? ACode { get; private set; }
    public string? ACy { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? AmtL1 { get; private set; }
    public long? AmtL2 { get; private set; }
    public long? AmtL3 { get; private set; }
    public long? AmtL4 { get; private set; }
    public long? AmtL5 { get; private set; }
    public long? AmtL6 { get; private set; }
    public long? AmtL7 { get; private set; }
    public long? AmtL8 { get; private set; }
    public long? AmtL9 { get; private set; }
    public long? AmtL10 { get; private set; }
    public long? AmtL11 { get; private set; }
    public long? AmtL12 { get; private set; }
    public string? DocDesc { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? RcrdNo { get; private set; }
    public int? BdgtType { get; private set; }
    public int? BdgtPrdType { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public bool? BdgtPrdType { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public int PrdNo { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public string? ACode { get; private set; }
    public string ACy { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? AmtL { get; private set; }
    public long? AmtF { get; private set; }
    public long? AmtLAddMov { get; private set; }
    public long? AmtFAddMov { get; private set; }
    public long? AmtLDiscMov { get; private set; }
    public long? AmtFDiscMov { get; private set; }
    public long? AcRate { get; private set; }
    public string? DocDesc { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public long? AmtLAdd { get; private set; }
    public long? AmtFAdd { get; private set; }
    public long? AmtLDisc { get; private set; }
    public long? AmtFDisc { get; private set; }
    public long? DocSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string ACy { get; private set; }
    public string? DocDesc { get; private set; }
    public string? DocNote { get; private set; }
    public string? RefNo { get; private set; }
    public bool? BdgtPrdType { get; private set; }
    public bool? BdgtType { get; private set; }
    public bool? Approved { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? AprvDsc { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public bool? Dflt { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}