public class IasBillExpireDtl
{
    public long? BillNo { get; private set; }
    public long? BillSer { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public long? WCode { get; private set; }
    public string? IName { get; private set; }
    public int? IQty { get; private set; }
    public int? PQty { get; private set; }
    public decimal? IPrice { get; private set; }
    public long? RcrdNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? VCode { get; private set; }
    public long? BillSer { get; private set; }
    public DateTime? BillDate { get; private set; }
    public int? BillAmt { get; private set; }
    public long? WCode { get; private set; }
    public string? ACy { get; private set; }
    public bool? GateFlag { get; private set; }
    public string? ADesc { get; private set; }
    public string? RefNo { get; private set; }
    public long? RecVNo { get; private set; }
    public bool? Processed { get; private set; }
    public bool? Approved { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public int? AprvUId { get; private set; }
    public string? AprvDsc { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}