public class IasCashCustmr
{
    public string CustCode { get; private set; }
    public string CustLNm { get; private set; }
    public string? CustFNm { get; private set; }
    public int? CustGrpCode { get; private set; }
    public string MobileNo { get; private set; }
    public int? PointTypNo { get; private set; }
    public DateTime? PointTypActvDate { get; private set; }
    public string? TelNo { get; private set; }
    public string? FaxNo { get; private set; }
    public string? Pbox { get; private set; }
    public string? EMail { get; private set; }
    public string? WebSite { get; private set; }
    public long? RCode { get; private set; }
    public long? CityNo { get; private set; }
    public string? RepCode { get; private set; }
    public string? Address { get; private set; }
    public DateTime? BirthDate { get; private set; }
    public DateTime? FirstDealDate { get; private set; }
    public int? ExternalPost { get; private set; }
    public string? CBoxCode { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? CrdNoDisc { get; private set; }
    public int BrnNo { get; private set; }
    public short CmpNo { get; private set; }
    public string? CCmpnyNm { get; private set; }
    public int? CActvtyTyp { get; private set; }
    public long? CActvtnCode { get; private set; }
    public bool? CActvtnFlg { get; private set; }
    public bool? BlkLst { get; private set; }
    public string? BlkLstRes { get; private set; }
    public DateTime? BlkLstDate { get; private set; }
    public int? RgnNo { get; private set; }
    public string? CstmrBuildNo { get; private set; }
    public string? CstmrFloorNo { get; private set; }
    public string? CstmrAprtmntNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short? CntryNo { get; private set; }
    public long? ProvNo { get; private set; }
    public string? CPwd { get; private set; }
}