public class IasCstItmLmtSal
{
    public long? RcrdNo { get; private set; }
    public string? CCode { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public int? IQty { get; private set; }
    public int? RptQtyCnt { get; private set; }
    public string? LmtDsc { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public int? PrdDay { get; private set; }
    public string? CCode { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public string? ACy { get; private set; }
    public int? Amt { get; private set; }
    public string? LmtDsc { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public long? LocNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long DocSer { get; private set; }
    public string CCode { get; private set; }
    public short? CDegree { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? SalesAmt { get; private set; }
    public long? SalesQty { get; private set; }
    public long? NetSalesAmt { get; private set; }
    public long? NetSalesQty { get; private set; }
    public long? ProfitMarginPer { get; private set; }
    public long? DailySalesRate { get; private set; }
    public long? ManthlySalesRate { get; private set; }
    public long? IndebtednessRate { get; private set; }
    public long? IndebtednessReceivePer { get; private set; }
    public long? SalesRtPer { get; private set; }
    public short? SalesAmtDeg { get; private set; }
    public short? SalesQtyDeg { get; private set; }
    public short? NetSalesAmtDeg { get; private set; }
    public short? NetSalesQtyDeg { get; private set; }
    public short? ProfitMarginPerDeg { get; private set; }
    public short? DailySalesRateDeg { get; private set; }
    public short? ManthlySalesRateDeg { get; private set; }
    public short? IndebtednessRateDeg { get; private set; }
    public short? IndebtednessReceivePerDeg { get; private set; }
    public short? SalesRtPerDeg { get; private set; }
    public long? UpCnt { get; private set; }
    public long DocSer { get; private set; }
    public DateTime DocDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public bool? UpCst { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}