public class IasCrCardTypes
{
    public short? CrCardType { get; private set; }
    public string CardAName { get; private set; }
    public string? CardEName { get; private set; }
    public string? CardScAddres { get; private set; }
    public string? CardScTel { get; private set; }
    public string? CardScEmail { get; private set; }
    public int? VatPer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? CrCardTypeCode { get; private set; }
    public int? GroupNo { get; private set; }
    public int? CstmrRgnNo { get; private set; }
    public string? CstmrBuildNo { get; private set; }
    public string? CstmrFloorNo { get; private set; }
    public string? CstmrAprtmntNo { get; private set; }
    public string? Note { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? Latitude { get; private set; }
    public string? Longitude { get; private set; }
    public long DocSer { get; private set; }
    public short FlgValue { get; private set; }
    public bool? Used { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string? DocSubjct { get; private set; }
    public string? DocDsc { get; private set; }
    public string? CustCode { get; private set; }
    public string? CustLNm { get; private set; }
    public string? MobileNo { get; private set; }
    public string? TelNo { get; private set; }
    public string? EMail { get; private set; }
    public string? Address { get; private set; }
    public string? CCode { get; private set; }
    public string? ACode { get; private set; }
    public short? AcTyp { get; private set; }
    public bool? Inactive { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? InactiveRes { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}