public class IasCstClaimVst
{
    public int BrnNo { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public int? VisitNo { get; private set; }
    public DateTime? VisitDate { get; private set; }
    public long? ColNo { get; private set; }
    public string? VisitDsc { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? UpCnt { get; private set; }
    public long? ColNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? CcCode { get; private set; }
    public string? ItmCode { get; private set; }
    public string? ItmUnt { get; private set; }
    public long? DocNo { get; private set; }
    public string? CCode { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public short? BillDocTyp { get; private set; }
    public int? CommAmt { get; private set; }
    public string? CommDsc { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? CommPer { get; private set; }
    public int? NetSalesAmt { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? GCode { get; private set; }
    public string? CommICode { get; private set; }
    public int? ItemType { get; private set; }
    public int? GroupNo { get; private set; }
    public int? CClassTyp { get; private set; }
    public int? DocSeq { get; private set; }
    public int? CommIQty { get; private set; }
    public int? NetSalesQty { get; private set; }
    public int? PayPrcnt { get; private set; }
    public int? PayAmt { get; private set; }
    public long? DocNo { get; private set; }
    public DateTime? DocDate { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? CommTyp { get; private set; }
    public long? PlanNo { get; private set; }
    public string? RefNo { get; private set; }
    public string? DocDsc { get; private set; }
    public int? PrcssdFlg { get; private set; }
    public int? Approved { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public int? AprvUId { get; private set; }
    public string? AprvDsc { get; private set; }
    public int? PlanSer { get; private set; }
    public int AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? PrRep { get; private set; }
}