public class IasChkDocInoutQtyMst
{
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public DateTime DocDate { get; private set; }
    public string? ACode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public string? AcNm { get; private set; }
    public string? DocDsc { get; private set; }
    public string? RefNo { get; private set; }
    public int? DocTypeRef { get; private set; }
    public int? DocJvTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public int? ExternalPost { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public bool? PrcssdFlg { get; private set; }
    public bool? Approved { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? AprvDsc { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public short? PrType { get; private set; }
    public short? TypNo { get; private set; }
    public bool? ChkQtyFlg { get; private set; }
    public long? UsdDocNo { get; private set; }
    public long? UsdDocSer { get; private set; }
    public int? UsdDocType { get; private set; }
    public long? WCode { get; private set; }
    public long? DocNoPrptnRef { get; private set; }
    public long? DocSerPrptnRef { get; private set; }
    public bool? BillTyp { get; private set; }
}