public class IasCollectionPlan
{
    public long ColNo { get; private set; }
    public string? CCode { get; private set; }
    public DateTime? ColDate { get; private set; }
    public short? Mnth { get; private set; }
    public int? CBalAmt { get; private set; }
    public int? TargetPer { get; private set; }
    public int? TargetAmt { get; private set; }
    public string? ColDesc { get; private set; }
    public short PlanPrdType { get; private set; }
    public long PlanNo { get; private set; }
    public int PlanSer { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int PlanNo { get; private set; }
    public int PlanSer { get; private set; }
    public long ColNo { get; private set; }
    public string? ColDesc { get; private set; }
    public string? ACy { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? CstCode { get; private set; }
    public long? DocNo { get; private set; }
    public long? ColNo { get; private set; }
    public long? CGroupCode { get; private set; }
    public short? CClass { get; private set; }
    public long? RCode { get; private set; }
    public int? CommPer { get; private set; }
    public int? CommAmt { get; private set; }
    public string? CommDsc { get; private set; }
    public int? ColAmt { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? DocNo { get; private set; }
    public DateTime? DocDate { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? CommTyp { get; private set; }
    public long? PlanNo { get; private set; }
    public string? RefNo { get; private set; }
    public string? DocDsc { get; private set; }
    public int? DocSeq { get; private set; }
    public int? PrcssdFlg { get; private set; }
    public int? Approved { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public int? AprvUId { get; private set; }
    public string? AprvDsc { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? PrRep { get; private set; }
    public int? PlanSer { get; private set; }
}