public class IasCmpnsQtyClcDtl
{
    public long? DocSrl { get; private set; }
    public long? DocNo { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public int? ItemType { get; private set; }
    public int? ActivityNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? ActvNo { get; private set; }
    public string? PjNo { get; private set; }
    public int? BrnNo { get; private set; }
    public long? WCode { get; private set; }
    public int? CmpnsQty { get; private set; }
    public string? CmpnsDsc { get; private set; }
    public int? CmpnsPer { get; private set; }
    public int? NetSalesAmt { get; private set; }
    public int? NetSalesQty { get; private set; }
    public long? RcrdNo { get; private set; }
    public int? DocSeq { get; private set; }
    public string? GCode { get; private set; }
    public int? BillNo { get; private set; }
    public int? BillSer { get; private set; }
    public int? ColAmt { get; private set; }
    public short? BillDocType { get; private set; }
    public int? PrvQty { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public int? DocSequence { get; private set; }
    public long? UpCnt { get; private set; }
    public short? CmpNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? DocNo { get; private set; }
    public DateTime? DocDate { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? CmpnsTyp { get; private set; }
    public string? RefNo { get; private set; }
    public string? DocDsc { get; private set; }
    public int? PrcssdFlg { get; private set; }
    public int? Approved { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public int? AprvUId { get; private set; }
    public string? AprvDsc { get; private set; }
    public long? PrRep { get; private set; }
    public int? FDocNo { get; private set; }
    public int? TDocNo { get; private set; }
    public string? CCode { get; private set; }
    public int? RqNo { get; private set; }
    public int? RqSrl { get; private set; }
    public string? ACode { get; private set; }
    public string? ACy { get; private set; }
    public int? DocRate { get; private set; }
    public int? StockRate { get; private set; }
    public bool? DocPost { get; private set; }
    public bool? AuditRef { get; private set; }
    public bool? StandBy { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public int? DocBrnNo { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? PostUId { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? UpCnt { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
}