public class IasDateLockUser
{
    public int? UId { get; private set; }
    public DateTime? Ufd { get; private set; }
    public DateTime? Utd { get; private set; }
    public DateTime? Lfd { get; private set; }
    public DateTime? Ltd { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? FormNo { get; private set; }
    public DateTime? Ufd { get; private set; }
    public DateTime? Utd { get; private set; }
    public DateTime? Lfd { get; private set; }
    public DateTime? Ltd { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? AcCode { get; private set; }
    public string DescADoc { get; private set; }
    public string? DescEDoc { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? MngCode { get; private set; }
    public string? SubgCode { get; private set; }
    public string? AssistantNo { get; private set; }
    public string? DetailNo { get; private set; }
    public string DetailAName { get; private set; }
    public string? DetailEName { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public bool? SynchrnzToWebFlg { get; private set; }
}