public class IasExchCurMst
{
    public long DocNo { get; private set; }
    public long? DocSrl { get; private set; }
    public string AcCode { get; private set; }
    public string CurCode { get; private set; }
    public DateTime DocDate { get; private set; }
    public string? DocDsc { get; private set; }
    public string? RefNo { get; private set; }
    public int? DocAmtL { get; private set; }
    public int? DocAmtF { get; private set; }
    public int CurRate { get; private set; }
    public bool? DocPost { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? TypNo { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public bool? PrdcFlg { get; private set; }
    public int? CshBnkSrl { get; private set; }
    public bool? StndbyFlg { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public int? ExternalPost { get; private set; }
    public int? DocSq { get; private set; }
    public int AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? StandBy { get; private set; }
    public short? AttachNo { get; private set; }
    public int? DocBrnNo { get; private set; }
    public string AcCodeDtl { get; private set; }
}