public class IasGnrCrdIdntty
{
    public string TypCode { get; private set; }
    public short TypNo { get; private set; }
    public short IdnttyTyp { get; private set; }
    public string IdnttyNo { get; private set; }
    public string? IssuePlc { get; private set; }
    public DateTime? IssueDate { get; private set; }
    public DateTime? IssueDateAh { get; private set; }
    public DateTime? ExpDate { get; private set; }
    public DateTime? ExpDateAh { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? RcrdNo { get; private set; }
    public string? GrNo { get; private set; }
    public long? DocNo { get; private set; }
    public long DocSrl { get; private set; }
    public int? DocTyp { get; private set; }
    public short? GrAcTyp { get; private set; }
    public string AcCode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public string? AcCodeDtlSub { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public string? CurCode { get; private set; }
    public string? DocDsc { get; private set; }
    public int CurRate { get; private set; }
    public int? AmtL { get; private set; }
    public int? AmtF { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? LcNo { get; private set; }
    public string? RefNo { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? RepCode { get; private set; }
    public long? ColNo { get; private set; }
    public DateTime? DocDueDate { get; private set; }
    public long? BillNo { get; private set; }
    public long? BillSer { get; private set; }
    public long? INo { get; private set; }
    public long? WoNo { get; private set; }
    public long? WoSer { get; private set; }
    public long? ChequeNo { get; private set; }
    public string? NoteNo { get; private set; }
    public int? ExternalPost { get; private set; }
    public int? DocBrnNo { get; private set; }
    public long? DocSq { get; private set; }
    public long? DocTypRef { get; private set; }
    public long? DocJvTypRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSrlRef { get; private set; }
    public long? DocSqRef { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
}