public class IasGlReqMst
{
    public int? DocType { get; private set; }
    public short? JvType { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public long? CashNo { get; private set; }
    public int? DocRate { get; private set; }
    public string? ACode { get; private set; }
    public string? ACy { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public int? CheqType { get; private set; }
    public int? DocAmt { get; private set; }
    public int? DocAmtF { get; private set; }
    public string? RefNo { get; private set; }
    public short? AttachNo { get; private set; }
    public string? BenName { get; private set; }
    public string? RecName { get; private set; }
    public string? DocDesc { get; private set; }
    public string? ReqSide { get; private set; }
    public string? ReqRes { get; private set; }
    public bool? Procesed { get; private set; }
    public bool? Approved { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? AprvDsc { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? ExternalPost { get; private set; }
    public short? VTypeNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}