public class IasItmWtavgTmp
{
    public string? ICode { get; private set; }
    public int? ICwtavg { get; private set; }
    public long? WCode { get; private set; }
    public long? WhgCode { get; private set; }
    public long? DocSer { get; private set; }
    public short? OrdrNo { get; private set; }
    public int? FormNo { get; private set; }
    public short? OrdrType { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? FldName { get; private set; }
    public int? FDgt { get; private set; }
    public int? TDgt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? DocSer { get; private set; }
    public short? OrdrType { get; private set; }
    public int? FormNo { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string? DrCnfg { get; private set; }
    public string? CrCnfg { get; private set; }
    public string? DrSmbl { get; private set; }
    public string? CrSmbl { get; private set; }
    public bool? Dflt { get; private set; }
    public string? TDesc { get; private set; }
    public long? PrRep { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? DocType { get; private set; }
    public long? KNo { get; private set; }
    public int? AdjAmt { get; private set; }
    public DateTime? AdjDate { get; private set; }
    public long? DocSer { get; private set; }
    public long? AdjSer { get; private set; }
    public int? DocNo { get; private set; }
    public string? CCode { get; private set; }
    public int? DocAmt { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string? DocACy { get; private set; }
    public string? CcCode { get; private set; }
    public long? KSer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? KitItemNo { get; private set; }
    public string? ICode { get; private set; }
    public int? Kitrank { get; private set; }
    public int? PostDocType { get; private set; }
    public bool? InptCntrBrTyp { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? DocType { get; private set; }
    public long? DocSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public DateTime? LogDate { get; private set; }
    public string? LogDesc { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? PrdCode { get; private set; }
    public long? WCode { get; private set; }
    public int? PrdDay { get; private set; }
    public int? AvgDay { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? MachineNoBank { get; private set; }
    public string? BankAc { get; private set; }
    public string? CommAc { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? InactiveUId { get; private set; }
    public long? WCode { get; private set; }
    public string? AcodeRecLetter { get; private set; }
    public long? BankNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? ConnBrnNo { get; private set; }
    public string? ConnTrmnlNm { get; private set; }
}