public class IasIncoutDtl
{
    public long DocNo { get; private set; }
    public long DocSer { get; private set; }
    public int DocType { get; private set; }
    public string ICode { get; private set; }
    public int? IQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int PQty { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public long WCode { get; private set; }
    public string? CcCode { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public int? ExpAmt { get; private set; }
    public bool? UseSerialno { get; private set; }
    public long RcrdNo { get; private set; }
    public long DocSequence { get; private set; }
    public string? ItemDesc { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public long? IncNo { get; private set; }
    public int? FreeQty { get; private set; }
    public bool? AllowFreeQty { get; private set; }
    public bool? UseQtyFrc { get; private set; }
    public int? OutQty { get; private set; }
    public int? OutFreeQty { get; private set; }
    public int? RtQty { get; private set; }
    public int? RtFreeQty { get; private set; }
    public int? DocTypeRef { get; private set; }
    public int? DocJvTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public int? ArgmntNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short CmpNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? RcrdNoRef { get; private set; }
}