public class IasItemSerialDesc
{
    public int? DescNo { get; private set; }
    public string? DescAName { get; private set; }
    public string? DescEName { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? DocNo { get; private set; }
    public int? DocType { get; private set; }
    public long? DocJvType { get; private set; }
    public long? DocSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public int? IQty { get; private set; }
    public string? DocDesc { get; private set; }
    public string? RefNo { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public int? PerNo { get; private set; }
    public string? TrmnlName { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? FWCode { get; private set; }
    public long? TWCode { get; private set; }
    public string BatchNo { get; private set; }
    public int? ItmOrdr { get; private set; }
    public int? DistDay { get; private set; }
    public int? FQty { get; private set; }
    public int? TQty { get; private set; }
    public int? AvgSaleDay { get; private set; }
    public int? PerSaleQty { get; private set; }
    public int? PrdDay { get; private set; }
    public int? Speed { get; private set; }
    public long? DocNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
}