public class IasNoteTypes
{
    public bool NoteType { get; private set; }
    public short? NoteTypeNo { get; private set; }
    public string NoteAName { get; private set; }
    public string? NoteEName { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? RCode { get; private set; }
    public long? WCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short? CntryNo { get; private set; }
    public long? ProvNo { get; private set; }
    public long? CityNo { get; private set; }
    public long? RCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? IQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int? PQty { get; private set; }
    public string? Barcode { get; private set; }
    public long WCode { get; private set; }
    public long? WhgCode { get; private set; }
    public int? StkCost { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public bool? UseSerialno { get; private set; }
    public string? VCode { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? DocSequence { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public int? ArgmntNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? MovPyFlg { get; private set; }
}