public class IasOutgoingMst
{
    public long OutNo { get; private set; }
    public long OutSer { get; private set; }
    public int OutType { get; private set; }
    public DateTime? OutDate { get; private set; }
    public string ACy { get; private set; }
    public int AcRate { get; private set; }
    public int? StockRate { get; private set; }
    public string? ACode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public string? CCode { get; private set; }
    public string? VCode { get; private set; }
    public DateTime? OutDueDate { get; private set; }
    public bool? OutPost { get; private set; }
    public int? OutAmt { get; private set; }
    public long? WCode { get; private set; }
    public string? RefNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? CshBnkNo { get; private set; }
    public string? LcNo { get; private set; }
    public string? ADesc { get; private set; }
    public short? AttachCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? BenName { get; private set; }
    public string? ExpACode { get; private set; }
    public string? ExpACy { get; private set; }
    public int? ExpAmt { get; private set; }
    public int? ExpRate { get; private set; }
    public bool? PurType { get; private set; }
    public long? OrdHotelNo { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public int? ExternalPost { get; private set; }
    public bool? Hung { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public bool? ConnWithSi { get; private set; }
    public bool? UseVat { get; private set; }
    public int? VatPer { get; private set; }
    public int? VatAmt { get; private set; }
    public bool? ProcecedSi { get; private set; }
    public bool? PrcssdFlg { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public string? MrpMrOrder { get; private set; }
    public long? MrpMrSq { get; private set; }
    public bool? MrpSt { get; private set; }
    public int? DocBrnNo { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? RepCode { get; private set; }
    public string? PrmCode { get; private set; }
}