public class IasPrmCst
{
    public string? CCode { get; private set; }
    public string? PrmCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? ICode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public long? RCode { get; private set; }
    public int? MrktPer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? PjCode { get; private set; }
    public string PjAName { get; private set; }
    public string? PjEName { get; private set; }
    public string? PjParent { get; private set; }
    public int? PjLevel { get; private set; }
    public bool PjSub { get; private set; }
    public int? GroupNo { get; private set; }
    public bool? Inactive { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? InactiveRes { get; private set; }
    public bool? ImpXls { get; private set; }
    public DateTime? StartDate { get; private set; }
    public DateTime? EndDate { get; private set; }
    public string? Address { get; private set; }
    public string? PjAdmin { get; private set; }
    public string? PjDesc { get; private set; }
    public string? PjNotes { get; private set; }
    public string? CurCode { get; private set; }
    public int? PjCost { get; private set; }
    public int? ExRate { get; private set; }
    public short? CntryNo { get; private set; }
    public long? CityNo { get; private set; }
    public long? ProvNo { get; private set; }
    public long? RCode { get; private set; }
    public DateTime? BidDate { get; private set; }
    public DateTime? ContractSpsDate { get; private set; }
    public string? CCode { get; private set; }
    public int? CodNoPjMngr { get; private set; }
    public short? CodTyp { get; private set; }
    public int? CodNoPjGSpcl { get; private set; }
    public int? CodNoPjSpcl { get; private set; }
    public short? PjSt { get; private set; }
    public int? PmsCondNo { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public DateTime? Field21 { get; private set; }
    public DateTime? Field22 { get; private set; }
    public DateTime? Field23 { get; private set; }
    public DateTime? Field24 { get; private set; }
    public DateTime? Field25 { get; private set; }
    public DateTime? Field26 { get; private set; }
    public DateTime? Field27 { get; private set; }
    public DateTime? Field28 { get; private set; }
    public DateTime? Field29 { get; private set; }
    public DateTime? Field30 { get; private set; }
    public int? Field31 { get; private set; }
    public int? Field32 { get; private set; }
    public int? Field33 { get; private set; }
    public int? Field34 { get; private set; }
    public int? Field35 { get; private set; }
    public int? Field36 { get; private set; }
    public int? Field37 { get; private set; }
    public int? Field38 { get; private set; }
    public int? Field39 { get; private set; }
    public int? Field40 { get; private set; }
    public bool? UseActv { get; private set; }
    public bool? AccntsCostFlg { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public decimal? MaxExectPcnt { get; private set; }
}