public class IasPrReqBillMst
{
    public short RtReqDocType { get; private set; }
    public long RtReqNo { get; private set; }
    public long RtReqSer { get; private set; }
    public int? PYear { get; private set; }
    public DateTime RtReqDate { get; private set; }
    public string? RtReqCurrency { get; private set; }
    public int? RtReqRate { get; private set; }
    public int? StockRate { get; private set; }
    public string? CCode { get; private set; }
    public string? VCode { get; private set; }
    public string? VName { get; private set; }
    public string? ACode { get; private set; }
    public long? ChequeNo { get; private set; }
    public int? ChequeAmt { get; private set; }
    public DateTime? ChequeDueDate { get; private set; }
    public DateTime? RtBillDueDate { get; private set; }
    public bool? Processed { get; private set; }
    public int? DiscAmtMst { get; private set; }
    public int? DiscAmtDtl { get; private set; }
    public int? DiscAmt { get; private set; }
    public int? ReqAmt { get; private set; }
    public int? VatAmt { get; private set; }
    public long? WCode { get; private set; }
    public long? CashNo { get; private set; }
    public long? CashNoFcc { get; private set; }
    public string? RefNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public bool? PrPriceType { get; private set; }
    public string? CashAcFcc { get; private set; }
    public string? ADesc { get; private set; }
    public short? PrevYear { get; private set; }
    public int? DiscAmtNotEffect { get; private set; }
    public string? PmanCode { get; private set; }
    public bool? UseVat { get; private set; }
    public int? ClcVatPriceTyp { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public bool? Approved { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? AprvDsc { get; private set; }
    public bool? Inactive { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? InactiveRes { get; private set; }
    public int? TypNo { get; private set; }
    public int? PrRep { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public bool? SrvcBill { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public long? RsrvSer { get; private set; }
    public long? RsrvNo { get; private set; }
    public string? AcCode { get; private set; }
    public int? AcAmt { get; private set; }
    public int? PymntAc { get; private set; }
    public bool? ClcTaxFreeQtyFlg { get; private set; }
}