public class IasPiBillMstAddDisc
{
    public bool AddDiscType { get; private set; }
    public long DocNo { get; private set; }
    public DateTime DocDate { get; private set; }
    public string ACy { get; private set; }
    public string? RefNo { get; private set; }
    public long? BillNo { get; private set; }
    public long? BillSer { get; private set; }
    public DateTime? BillDate { get; private set; }
    public string? VCode { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public int? AddDiscAmtMst { get; private set; }
    public int? AddDiscAmtMstPrev { get; private set; }
    public int? RetAmt { get; private set; }
    public string? DocDesc { get; private set; }
    public bool? DocPost { get; private set; }
    public string ACode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public short? AcDtlTyp { get; private set; }
    public bool? Hung { get; private set; }
    public bool? Processed { get; private set; }
    public bool? DocDiscType { get; private set; }
    public bool? NotEffectByVndrTrns { get; private set; }
    public string? ACodeIntrmDiscPi { get; private set; }
    public bool? PriceType { get; private set; }
    public int? DocNoRef { get; private set; }
    public int? DocSerRef { get; private set; }
    public int? DocTypeRef { get; private set; }
    public int? AddDiscAmtDtl { get; private set; }
    public int? AddVatAmt { get; private set; }
    public int? VatAmt { get; private set; }
    public bool? UseVat { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public short? BrnYear { get; private set; }
    public long DocSer { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public string? DiscACode { get; private set; }
    public int DocRate { get; private set; }
    public string? RepCode { get; private set; }
    public int? DocBrnNo { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public int? ExternalPost { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PrRep { get; private set; }
}