public class IasProvinces
{
    public long? ProvNo { get; private set; }
    public string? ProvAName { get; private set; }
    public string? ProvEName { get; private set; }
    public short? CntryNo { get; private set; }
    public string? ProvShrt { get; private set; }
    public short? ZoneNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? ItmUnt { get; private set; }
    public long? PSize { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public long? WCode { get; private set; }
    public long? RcrdNoRef { get; private set; }
    public int? IQty { get; private set; }
    public int? PQty { get; private set; }
    public int? DocTypeRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public string? KitItemNo { get; private set; }
    public int? KitItm { get; private set; }
    public int? KitIQty { get; private set; }
    public long? KitPSize { get; private set; }
    public string? KitItmUnt { get; private set; }
    public short? TypNo { get; private set; }
    public short? PrType { get; private set; }
    public int? RqQty { get; private set; }
    public string? IName { get; private set; }
    public string? BCode { get; private set; }
    public short? InOut { get; private set; }
    public int? KitOutQty { get; private set; }
    public int? DiQty { get; private set; }
    public string? Barcode { get; private set; }
    public int? PrQty { get; private set; }
    public long? DocNo { get; private set; }
    public long DocSer { get; private set; }
    public string ICode { get; private set; }
    public int? IQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int? PQty { get; private set; }
    public long? WCode { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? ItemDesc { get; private set; }
    public int? AvlQty { get; private set; }
    public int? LastIncomePrice { get; private set; }
    public string? Barcode { get; private set; }
    public long? ReqNo { get; private set; }
    public short? ReqType { get; private set; }
    public long? ReqSer { get; private set; }
    public long DocSequence { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? PurCnt { get; private set; }
    public int? LostDay { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? ReorderPoint { get; private set; }
    public int? LeadTime { get; private set; }
    public int? IRol { get; private set; }
    public int? IMinQty { get; private set; }
    public int? Sqty { get; private set; }
    public int? Poqty { get; private set; }
    public int? PoqtyOpen { get; private set; }
    public int? LastIncomeQty { get; private set; }
    public DateTime? LastIncomeDate { get; private set; }
    public DateTime? LastExpDate { get; private set; }
    public int? LastFreeQty { get; private set; }
    public int? PerLastFreeQty { get; private set; }
    public DateTime? FReqPrd { get; private set; }
    public DateTime? TReqPrd { get; private set; }
    public int? SaleDay { get; private set; }
    public string? WtUnt { get; private set; }
    public int? WtQty { get; private set; }
    public int? ArgmntNo { get; private set; }
    public long? UpCnt { get; private set; }
    public long? SoQty { get; private set; }
}