public class IasQutPrmMst
{
    public long? QuotNo { get; private set; }
    public long? QuotSer { get; private set; }
    public DateTime FDate { get; private set; }
    public DateTime TDate { get; private set; }
    public string? FTime { get; private set; }
    public string? TTime { get; private set; }
    public string QuotCur { get; private set; }
    public string? CcCode { get; private set; }
    public long? WCode { get; private set; }
    public string? RefNo { get; private set; }
    public string? ADesc { get; private set; }
    public bool? Inactive { get; private set; }
    public int? ExternalPost { get; private set; }
    public bool? FldDay1 { get; private set; }
    public bool? FldDay2 { get; private set; }
    public bool? FldDay3 { get; private set; }
    public bool? FldDay4 { get; private set; }
    public bool? FldDay5 { get; private set; }
    public bool? FldDay6 { get; private set; }
    public bool? FldDay7 { get; private set; }
    public short? QtPrmType { get; private set; }
    public short? QtPrmMethod { get; private set; }
    public short? QtPrmWcType { get; private set; }
    public short? QtPrmCstType { get; private set; }
    public int? ByCompQty { get; private set; }
    public int? CalcAllSlides { get; private set; }
    public short? BillDocType { get; private set; }
    public bool? ApprvdFreeqtyAsDscnt { get; private set; }
    public string? InactiveRes { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? InactiveUId { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public long? UpCnt { get; private set; }
    public short? CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PrRep { get; private set; }
    public short? QtPrmItmType { get; private set; }
    public int? CmltvMnthFlg { get; private set; }
    public DateTime? AdDateClk { get; private set; }
    public bool? UseQtnPrmInCssSysFlg { get; private set; }
}