public class IasRqVchrMst
{
    public bool VoucherType { get; private set; }
    public bool VoucherPayType { get; private set; }
    public long VoucherNo { get; private set; }
    public long? CashNo { get; private set; }
    public string ACy { get; private set; }
    public long? VSer { get; private set; }
    public DateTime VoucherDate { get; private set; }
    public int? CashAmt { get; private set; }
    public int? CashAmtf { get; private set; }
    public int? ExRate { get; private set; }
    public string? RefNo { get; private set; }
    public string? RefName { get; private set; }
    public string? ADesc { get; private set; }
    public bool? StandBy { get; private set; }
    public int? Transfer { get; private set; }
    public int? CheqType { get; private set; }
    public long? ColNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public short? AttachNo { get; private set; }
    public decimal? CommPer { get; private set; }
    public long? VoucherNoPy { get; private set; }
    public DateTime? VoucherDatePy { get; private set; }
    public bool? MoveCheqPy { get; private set; }
    public short? VTypeNo { get; private set; }
    public long? DocSequence { get; private set; }
    public string? ActvNo { get; private set; }
    public int? DocBrnNo { get; private set; }
    public bool? Procesed { get; private set; }
    public bool? Approved { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? AprvDsc { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? BenName { get; private set; }
    public string? RecName { get; private set; }
    public string? ReqSide { get; private set; }
    public string? ReqRes { get; private set; }
    public int? DocType { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? DocNoYr { get; private set; }
    public long? DocSrlYr { get; private set; }
    public bool? MovdYr { get; private set; }
    public int? ExternalPost { get; private set; }
}