public class IasRetBillDtlBr
{
    public long RetNo { get; private set; }
    public long RetSer { get; private set; }
    public long RtBillNo { get; private set; }
    public long RtBillSer { get; private set; }
    public int? SrType { get; private set; }
    public string ICode { get; private set; }
    public int? IQty { get; private set; }
    public int? FreeQty { get; private set; }
    public string ItmUnt { get; private set; }
    public int PSize { get; private set; }
    public int? PQty { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public long WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public bool? UseSerialno { get; private set; }
    public int? DisAmt { get; private set; }
    public decimal? DisPer { get; private set; }
    public long? RcrdNo { get; private set; }
    public int? VatAmt { get; private set; }
    public int? VatPer { get; private set; }
    public long? RtRcrdNo { get; private set; }
    public string? Barcode { get; private set; }
    public long? BillNo { get; private set; }
    public long? BillSer { get; private set; }
    public long? OutNo { get; private set; }
    public long? OutSer { get; private set; }
    public long? SiRcrdNo { get; private set; }
    public long DocSequence { get; private set; }
    public long? DocSequenceSi { get; private set; }
    public bool? UseAttch { get; private set; }
    public int? ExternalPost { get; private set; }
    public long? RecAttch { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public string? WtUnt { get; private set; }
    public int? WtQty { get; private set; }
    public string? PostCode { get; private set; }
    public string? ItemDesc { get; private set; }
    public short? CmpNo { get; private set; }
    public short? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? ArgmntNo { get; private set; }
}