public class IasReceiptWatches
{
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public long? RcrdNo { get; private set; }
    public DateTime? WatchDate { get; private set; }
    public string? WatchDesc { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public short? CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? ICode { get; private set; }
    public int? WCode { get; private set; }
    public int? WhgCode { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public int? DocSequence { get; private set; }
    public int? StkCost { get; private set; }
    public int? PSize { get; private set; }
    public int? InOut { get; private set; }
    public int? Rn { get; private set; }
    public int? Serial { get; private set; }
    public int? PsumQty { get; private set; }
    public int? KitQty { get; private set; }
    public int? StkCost0 { get; private set; }
    public int? SerialRef1 { get; private set; }
    public int? AvlQtyBfr { get; private set; }
    public int? AvlQtyBfrDvd { get; private set; }
    public int? WtAvgAfter { get; private set; }
    public int? WtAvgAfter1 { get; private set; }
    public int? WtAvgAfter2 { get; private set; }
    public int? SerialRef { get; private set; }
    public int? ICost { get; private set; }
    public int? ExpAmt { get; private set; }
    public int? DocTypeDtl { get; private set; }
    public int? SerialRefOut { get; private set; }
    public int? RecNo { get; private set; }
    public int? RcrdNo { get; private set; }
    public int? Processed { get; private set; }
    public int? LastReevalSerial { get; private set; }
    public int? InvWtavgFrc { get; private set; }
    public int? WtAvgBefore { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public string? IName { get; private set; }
    public string? Unit { get; private set; }
    public int? ICwtavg { get; private set; }
    public long? WCode { get; private set; }
    public long? WhgCode { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? KitItemRank { get; private set; }
    public long? RSer { get; private set; }
    public string? ICode { get; private set; }
    public long? WCode { get; private set; }
    public string? IName { get; private set; }
    public string ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public int? IQty { get; private set; }
    public string? Reason { get; private set; }
    public string? PartyName { get; private set; }
    public DateTime? OutDate { get; private set; }
    public DateTime? IncDate { get; private set; }
    public long? RcrdNo { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? RSer { get; private set; }
    public DateTime? RDate { get; private set; }
    public string? RefNo { get; private set; }
    public string? RDesc { get; private set; }
    public long? WCode { get; private set; }
    public string? VCode { get; private set; }
    public bool? ExitFlag { get; private set; }
    public bool? EntryFlag { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PrRep { get; private set; }
    public string? MvName { get; private set; }
    public string? TName { get; private set; }
    public string? CenterBranch { get; private set; }
    public int? BrnNo { get; private set; }
    public DateTime? LastUpdateDate { get; private set; }
    public int? TransCode { get; private set; }
    public string? MvName { get; private set; }
    public string? RefreshType { get; private set; }
    public string? TName { get; private set; }
    public string? Whr { get; private set; }
    public string? PkName { get; private set; }
    public string? PkField { get; private set; }
    public string? CenterBranch { get; private set; }
    public string? FieldDate { get; private set; }
    public int? TransCode { get; private set; }
    public bool? UsePeriod { get; private set; }
    public string? WhrDel { get; private set; }
    public string? WhrIns { get; private set; }
    public string? WhrMod { get; private set; }
    public bool? UseDel { get; private set; }
    public bool? UseMv { get; private set; }
}