public class IasRtBillDtlRqBr
{
    public short RtBillDocType { get; private set; }
    public long RtBillNo { get; private set; }
    public long RtBillSer { get; private set; }
    public long? BillNo { get; private set; }
    public short? BillDocType { get; private set; }
    public long? BillSer { get; private set; }
    public string ICode { get; private set; }
    public int? IQty { get; private set; }
    public long PSize { get; private set; }
    public int PQty { get; private set; }
    public int? IPrice { get; private set; }
    public int? StkCost { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? VCode { get; private set; }
    public int? SrType { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public int? FreeQty { get; private set; }
    public bool? FreeTyp { get; private set; }
    public bool? ServiceItem { get; private set; }
    public decimal? DisPer { get; private set; }
    public int? DisAmt { get; private set; }
    public int? DisAmtMst { get; private set; }
    public int? DisAmtDtl { get; private set; }
    public decimal? VatPer { get; private set; }
    public int? VatAmt { get; private set; }
    public int? OthrAmt { get; private set; }
    public bool? UseSerialno { get; private set; }
    public long? SiRcrdNo { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? DocSequenceSi { get; private set; }
    public string? ItemDesc { get; private set; }
    public string? Barcode { get; private set; }
    public int? ExternalPost { get; private set; }
    public bool? RtBillPy { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public int? DisPer2 { get; private set; }
    public int? DisAmtDtl2 { get; private set; }
    public int? DisPer3 { get; private set; }
    public int? DisAmtDtl3 { get; private set; }
    public int? DisAmtDtlVat { get; private set; }
    public int? DisAmtDtl2Vat { get; private set; }
    public int? DisAmtDtl3Vat { get; private set; }
    public int? DisAmtMstVat { get; private set; }
    public int? VatAmtDisDtlVat { get; private set; }
    public int? VatAmtDisDtl2Vat { get; private set; }
    public int? VatAmtDisDtl3Vat { get; private set; }
    public int? VatAmtAftrDis { get; private set; }
    public int? VatAmtBfrDis { get; private set; }
    public int? VatAmtDisMstVat { get; private set; }
    public int? DisAmtAftrVat { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public string? PostCode { get; private set; }
    public string? FieldDtl1 { get; private set; }
    public string? FieldDtl2 { get; private set; }
    public string? FieldDtl3 { get; private set; }
    public string? SubCCode { get; private set; }
    public short? CmpNo { get; private set; }
    public short BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? ItmUnt { get; private set; }
    public long? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public int? InsrnceLoadPer { get; private set; }
    public int? InsrnceLoadAmt { get; private set; }
    public int? InsrnceAddLmt { get; private set; }
    public long? EmpNo { get; private set; }
    public int? DocSequence { get; private set; }
    public int? ArgmntNo { get; private set; }
    public int? IPriceVat { get; private set; }
    public int? DocTypeRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public long? DocNoRef { get; private set; }
}