public class IasReserveDtl
{
    public int? DocType { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public long? DocNoRef { get; private set; }
    public int? DocTypeRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public string? CCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public long? WCode { get; private set; }
    public int? IQty { get; private set; }
    public int? PSize { get; private set; }
    public int? PQty { get; private set; }
    public int? CpQty { get; private set; }
    public bool? Reserved { get; private set; }
    public DateTime? TDate { get; private set; }
    public long? DocSequence { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? ItemDesc { get; private set; }
    public int? UnblkUId { get; private set; }
    public DateTime? UnblkDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? ExternalPost { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public int BrnNo { get; private set; }
    public short CmpNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public short? BrnYear { get; private set; }
    public long? UpCnt { get; private set; }
}