public class IasScalMovmnt
{
    public int DocNo { get; private set; }
    public int? DocSrl { get; private set; }
    public DateTime DocDate { get; private set; }
    public bool TrnsTyp { get; private set; }
    public bool DocTyp { get; private set; }
    public int? DocTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSrlRef { get; private set; }
    public int? BrnNo { get; private set; }
    public long? DriverNo { get; private set; }
    public string? CarNo { get; private set; }
    public int? TareWght { get; private set; }
    public DateTime? TareWghtDate { get; private set; }
    public int? TareWghtUId { get; private set; }
    public int? GrossWght { get; private set; }
    public DateTime? GrossWghtDate { get; private set; }
    public int? GrossWghtUId { get; private set; }
    public int? NetWght { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? IQty { get; private set; }
    public short? CmpNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? WCode { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public bool? PrcssFlg { get; private set; }
    public int? UnitWght { get; private set; }
    public int? WghtQty { get; private set; }
    public string? ADesc { get; private set; }
    public string? RefDocNo { get; private set; }
    public DateTime? DocDateRef { get; private set; }
    public bool? Approved { get; private set; }
    public string? AprvDsc { get; private set; }
    public int? AprvUId { get; private set; }
    public DateTime? AprvDate { get; private set; }
    public string? DrvrNm { get; private set; }
    public int? DiffAcutlWghtQty { get; private set; }
}