public class IasSalesCommission
{
    public string? CCode { get; private set; }
    public short? CClass { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public decimal? FPayPer { get; private set; }
    public decimal? TPayPer { get; private set; }
    public decimal? CommPer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? AudType { get; private set; }
    public string? GCode { get; private set; }
    public string? CCode { get; private set; }
    public short? CClass { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public bool? AmtType { get; private set; }
    public decimal? Amt { get; private set; }
    public string? ACy { get; private set; }
    public int? AcRate { get; private set; }
    public long? WCode { get; private set; }
    public long? WhgCode { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public short? LevNo { get; private set; }
    public int? DocNo { get; private set; }
    public DateTime? DocDate { get; private set; }
    public int? FQty { get; private set; }
    public int? TQty { get; private set; }
    public string? DocDesc { get; private set; }
    public short? BillDocType { get; private set; }
    public string? BatchNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? AudUId { get; private set; }
    public DateTime? AudDate { get; private set; }
    public int BrnNo { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? CstGrpCode { get; private set; }
    public bool? AudType { get; private set; }
    public int? AudUId { get; private set; }
    public DateTime? AudDate { get; private set; }
    public int? DocNo { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string? GCode { get; private set; }
    public string? CCode { get; private set; }
    public short? CClass { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public bool? PayType { get; private set; }
    public int? LowQty { get; private set; }
    public int? PerQty { get; private set; }
    public long? WCode { get; private set; }
    public long? WhgCode { get; private set; }
    public short? BillDocType { get; private set; }
    public int? FQty { get; private set; }
    public int? TQty { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int BrnNo { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PlanNo { get; private set; }
    public short? PlanType { get; private set; }
    public short? PlanDstrType { get; private set; }
    public short? PlanPrdType { get; private set; }
    public string? RepCode { get; private set; }
    public string? CCode { get; private set; }
    public int? CGCode { get; private set; }
    public short? CClass { get; private set; }
    public short? CntryNo { get; private set; }
    public long? ProvNo { get; private set; }
    public long? CityNo { get; private set; }
    public long? RCode { get; private set; }
    public long? ColNo { get; private set; }
    public string? GCode { get; private set; }
    public int? ItemType { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public short? Mnth { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int? IQty { get; private set; }
    public int? LocalAmt { get; private set; }
    public int? HighLmt { get; private set; }
    public int? LowLmt { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? PlanDesc { get; private set; }
    public int? SalesAmtPy { get; private set; }
    public string? AddPerPy { get; private set; }
    public long? EmpNo { get; private set; }
    public string? PrmCode { get; private set; }
    public int? CClassTyp { get; private set; }
    public int? GroupNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short CmpNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public string? MngCode { get; private set; }
    public string? SubgCode { get; private set; }
    public string? AssistantNo { get; private set; }
    public string? DetailNo { get; private set; }
    public short? PlanType { get; private set; }
    public short? PlanDstrType { get; private set; }
    public short? PlanPrdType { get; private set; }
    public string? RefNo { get; private set; }
    public string? PlanDesc { get; private set; }
    public bool? IncldFreeQtyFlg { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public long? PlanNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short CmpNo { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}