public class IasSmanCommDtl
{
    public string? RepCode { get; private set; }
    public short? CommType { get; private set; }
    public long? PlanNo { get; private set; }
    public int? PlanSer { get; private set; }
    public long? UpCnt { get; private set; }
    public int? FAmt { get; private set; }
    public int? TAmt { get; private set; }
    public int? CommPer { get; private set; }
    public string? RepCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short? SmanType { get; private set; }
    public int? CClass { get; private set; }
    public long? CGroupCode { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public string? GCode { get; private set; }
    public int? GroupNo { get; private set; }
    public string? RCode { get; private set; }
    public short? CntryNo { get; private set; }
    public long? ProvNo { get; private set; }
    public long? CityNo { get; private set; }
    public int? ItemType { get; private set; }
    public string? ItmCode { get; private set; }
    public short? BillDocTyp { get; private set; }
    public short? LevNo { get; private set; }
    public short? CommSliceNo { get; private set; }
    public bool? CommSliceType { get; private set; }
    public int? FAmtPer { get; private set; }
    public int? TAmtPer { get; private set; }
    public short? CommAmtType { get; private set; }
    public int? CommAmt { get; private set; }
    public string? CommDesc { get; private set; }
    public long? UpCnt { get; private set; }
    public string CommTypeAName { get; private set; }
    public string? CommTypeEName { get; private set; }
    public short? CommCalcMethod { get; private set; }
    public short? CommApprovedMethod { get; private set; }
    public bool? CalcCommIcode { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? InactiveUId { get; private set; }
    public string? CommDesc { get; private set; }
    public bool? SeparateTargetAddtarget { get; private set; }
    public short? CommCalcTrgtMethod { get; private set; }
    public short? CommCalcAddTrgtMethod { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}