public class IasSalesTypes
{
    public int? SiType { get; private set; }
    public string? SiAName { get; private set; }
    public string? SiEName { get; private set; }
    public int? SiSer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short? PriceLvl { get; private set; }
    public short? BillDocType { get; private set; }
    public long DocNo { get; private set; }
    public long DocSer { get; private set; }
    public long RcrdNo { get; private set; }
    public string? CpnBookNo { get; private set; }
    public string? CpnNo { get; private set; }
    public string? CCode { get; private set; }
    public int? IQty { get; private set; }
    public int? IPrice { get; private set; }
    public string? CpnDsc { get; private set; }
    public int? DocSeq { get; private set; }
    public bool? PrcssdFlg { get; private set; }
    public int? VatPer { get; private set; }
    public int? VatAmt { get; private set; }
    public bool? Inactive { get; private set; }
    public int? InactiveUId { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public string? InactiveRes { get; private set; }
    public bool? CpnTyp { get; private set; }
    public long? CpnTypNo { get; private set; }
    public int? AdUId { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
}