public class IasSalCpnMst
{
    public long DocNo { get; private set; }
    public long DocSer { get; private set; }
    public DateTime DocDate { get; private set; }
    public short BillDocType { get; private set; }
    public string ACy { get; private set; }
    public int CurRate { get; private set; }
    public string? CCode { get; private set; }
    public string? CName { get; private set; }
    public string? RcptNm { get; private set; }
    public string? ACode { get; private set; }
    public bool? DocPst { get; private set; }
    public int? DocAmt { get; private set; }
    public string? RefNo { get; private set; }
    public long? CashNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public DateTime? ChequeDueDate { get; private set; }
    public int? ChequeAmt { get; private set; }
    public long? ChequeNo { get; private set; }
    public DateTime? BillDueDate { get; private set; }
    public string? DocDsc { get; private set; }
    public int? VatAmt { get; private set; }
    public bool? StandBy { get; private set; }
    public int? ExternalPost { get; private set; }
    public int? DiscPer { get; private set; }
    public int? DiscAmtMst { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public bool? CpnTyp { get; private set; }
    public string? RepCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
}