public class IasWhtrnsMstBr
{
    public short TrInoutType { get; private set; }
    public short TrType { get; private set; }
    public long TrNo { get; private set; }
    public long? TrSer { get; private set; }
    public DateTime TrDate { get; private set; }
    public string? RefNo { get; private set; }
    public short? WCode { get; private set; }
    public short? TWCode { get; private set; }
    public short? FWCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? TrACode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public string? TrDesc { get; private set; }
    public int? StkRate { get; private set; }
    public bool? TrPost { get; private set; }
    public int? TrAmt { get; private set; }
    public string? TrRes { get; private set; }
    public long? LoadNo { get; private set; }
    public short? AttachCnt { get; private set; }
    public long? PrRep { get; private set; }
    public bool? Processed { get; private set; }
    public bool? StkProcessed { get; private set; }
    public bool? ProcessedSi { get; private set; }
    public bool? Hung { get; private set; }
    public short? TTrType { get; private set; }
    public decimal? ExpAmt { get; private set; }
    public string? CCode { get; private set; }
    public short? DocBrnNo { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public int? ExternalPost { get; private set; }
    public long FTrNo { get; private set; }
    public long FTrSer { get; private set; }
    public string? BoeNo { get; private set; }
    public bool? TrCostType { get; private set; }
    public string? DiffACode { get; private set; }
    public string? DiffACy { get; private set; }
    public int? DiffAmt { get; private set; }
    public int? RtnTr { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public long? DriverNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public short? CmpNo { get; private set; }
    public short? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
}