public class IasWorkOrderMst
{
    public long WoNo { get; private set; }
    public long? WoSer { get; private set; }
    public short? WoTypeNo { get; private set; }
    public DateTime WoDate { get; private set; }
    public string? ACy { get; private set; }
    public int AcRate { get; private set; }
    public int? StkRate { get; private set; }
    public string? CCode { get; private set; }
    public string? CName { get; private set; }
    public string? CcCode { get; private set; }
    public string? DocDesc { get; private set; }
    public string? RefNo { get; private set; }
    public long? RecNo { get; private set; }
    public int? EngCode { get; private set; }
    public bool? Processed { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public int? RecSer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? ClcTaxFreeQtyFlg { get; private set; }
    public DateTime? AdDateClk { get; private set; }
}