public class IasWorkOrderTypes
{
    public short? WoTypeNo { get; private set; }
    public string? WoAName { get; private set; }
    public string? WoEName { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? ICode { get; private set; }
    public string ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public string? IName { get; private set; }
    public int? Price { get; private set; }
    public string? GCode { get; private set; }
    public int? BrnNo { get; private set; }
    public string? ACode { get; private set; }
    public string? ACy { get; private set; }
    public int? ASM { get; private set; }
    public int? OBal { get; private set; }
    public int? OYear { get; private set; }
    public int? Balance { get; private set; }
    public short? Year { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? GCode { get; private set; }
    public string? MngCode { get; private set; }
    public short? WhgCode { get; private set; }
    public string? ACode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string IncomName { get; private set; }
    public string? IncomEName { get; private set; }
    public bool? IncRes { get; private set; }
    public bool? ConnWithPi { get; private set; }
    public bool? IncomSr { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? ClcTypNoTax { get; private set; }
}