public class InvItmCstOrdr
{
    public bool? CstCode { get; private set; }
    public bool? CstType { get; private set; }
    public short? CstOrdr { get; private set; }
    public long? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? ICode { get; private set; }
    public string? DscLNm { get; private set; }
    public string? DscFNm { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? ICode { get; private set; }
    public long? ExcdPer { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? UpUId { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public long? RcrdNo { get; private set; }
    public string? ICode { get; private set; }
    public string? QrCode { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public long? WCode { get; private set; }
    public long? FDocNo { get; private set; }
    public long? FDocSer { get; private set; }
    public long? FRcrdNo { get; private set; }
    public long? FWCode { get; private set; }
    public int? FreeFlg { get; private set; }
    public short? BillDocType { get; private set; }
    public int DocNo { get; private set; }
    public int? DocSer { get; private set; }
    public DateTime? DocDate { get; private set; }
    public string? ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public string? QrCode { get; private set; }
    public long WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public DateTime? ExpireDate { get; private set; }
    public string? BatchNo { get; private set; }
    public bool? FreeFlg { get; private set; }
    public int? OutNo { get; private set; }
    public int? OutGrSer { get; private set; }
    public bool? InOut { get; private set; }
    public long? RcrdNo { get; private set; }
    public long? RcrdNoDoc { get; private set; }
    public int? ExternalPost { get; private set; }
    public DateTime? AdDate { get; private set; }
    public DateTime? UpDate { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
}