public class InvQrCodeMthdDtl
{
    public int? RcrdNo { get; private set; }
    public long MthdNo { get; private set; }
    public int? FldNm { get; private set; }
    public long? FldLngth { get; private set; }
    public string? FldCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? MthdLNm { get; private set; }
    public string? MthdFNm { get; private set; }
    public int? MthdNoClmn { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? DocNo { get; private set; }
    public long? DocSer { get; private set; }
    public string? ICode { get; private set; }
    public string ItmUnt { get; private set; }
    public int? IQty { get; private set; }
    public int? PSize { get; private set; }
    public int? PQty { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public string? ItemDesc { get; private set; }
    public long? RcrdNo { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public string? Barcode { get; private set; }
    public int? ArgmntNo { get; private set; }
    public int? ExternalPost { get; private set; }
    public short? CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public int? DocTypeRef { get; private set; }
    public int? DocNoRef { get; private set; }
    public int? DocSerRef { get; private set; }
    public int? AvlQty { get; private set; }
    public int? DocSequence { get; private set; }
}