public class ItemTypes
{
    public int? TypeOfItem { get; private set; }
    public string? ItAName { get; private set; }
    public string? ItEName { get; private set; }
    public string? ItemTypeCode { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? JvTyp { get; private set; }
    public string? AcCode { get; private set; }
    public string? AcCodeDtl { get; private set; }
    public bool? AcDtlTyp { get; private set; }
    public bool? AcCodeSt { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public short CmpNo { get; private set; }
    public int? BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool DocGenJrs { get; private set; }
    public bool AllowDocDelNo { get; private set; }
    public bool? DateGenJrs { get; private set; }
    public bool DateSettingJrs { get; private set; }
    public bool? UseDelJrs { get; private set; }
    public bool UseModJrs { get; private set; }
    public bool? UseImpToJrnl { get; private set; }
    public bool? UseImpToPost { get; private set; }
    public bool? LinkWithExtrnlDirs { get; private set; }
    public bool? UseIntmdtDb { get; private set; }
    public string? DrSmbl { get; private set; }
    public string? CrSmbl { get; private set; }
    public string? DrCnfg { get; private set; }
    public string? CrCnfg { get; private set; }
    public bool? UseImpFExceel { get; private set; }
    public bool? UseImpFText { get; private set; }
    public bool? UseConnAccextBrn { get; private set; }
    public bool? ConnAccDocTyp { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}