public class MasterOutBills
{
    public long OutNo { get; private set; }
    public long? OutSer { get; private set; }
    public short BillDocType { get; private set; }
    public long? BillNo { get; private set; }
    public long BillSer { get; private set; }
    public DateTime OutDate { get; private set; }
    public string BillCurrency { get; private set; }
    public int? SiType { get; private set; }
    public int? BillRate { get; private set; }
    public int? StockRate { get; private set; }
    public string? CCode { get; private set; }
    public string? CName { get; private set; }
    public bool? OutPost { get; private set; }
    public long? WCode { get; private set; }
    public string? RefNo { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public long? CashNo { get; private set; }
    public string? ADesc { get; private set; }
    public long? PrRep { get; private set; }
    public string? RecName { get; private set; }
    public string ACode { get; private set; }
    public short? AttachCnt { get; private set; }
    public long? DriverNo { get; private set; }
    public long? RCode { get; private set; }
    public string? SubCCode { get; private set; }
    public int? DocBrnNo { get; private set; }
    public int? PaidAmt { get; private set; }
    public int? OutAmt { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public int? ExternalPost { get; private set; }
    public bool? StandBy { get; private set; }
    public bool? AuditRef { get; private set; }
    public string? AuditRefDesc { get; private set; }
    public int? AuditRefUId { get; private set; }
    public DateTime? AuditRefDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PostUId { get; private set; }
    public DateTime? PostDate { get; private set; }
    public int? UnpostUId { get; private set; }
    public DateTime? UnpostDate { get; private set; }
    public int? OutType { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? OutBillTyp { get; private set; }
    public DateTime? AdDateClk { get; private set; }
}