public class SEmpKnwldg
{
    public long EmpNo { get; private set; }
    public short CodeTyp { get; private set; }
    public long? CodeNo { get; private set; }
    public string? Notes { get; private set; }
    public short? GrdYrNo { get; private set; }
    public short? GrdMnthNo { get; private set; }
    public string? GrdSideNm { get; private set; }
    public short? FYrNo { get; private set; }
    public short? TYrNo { get; private set; }
    public short? FMnthNo { get; private set; }
    public short? TMnthNo { get; private set; }
    public long? CntryNo { get; private set; }
    public string? CtyNm { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public int AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int PrfssnNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public int? LblNo { get; private set; }
    public int PrfssnNo { get; private set; }
    public long EmpNo { get; private set; }
    public int AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public int? PrRep { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public bool? EmpPrvTyp { get; private set; }
    public long EmpnoHrchyno { get; private set; }
    public bool? AddFlag { get; private set; }
    public bool? ViewFlag { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}