public class SPrdBrnCls
{
    public bool PrdTyp { get; private set; }
    public short? PrdNo { get; private set; }
    public int? BrnNo { get; private set; }
    public DateTime? FDate { get; private set; }
    public DateTime? TDate { get; private set; }
    public short? YrNo { get; private set; }
    public bool? Inactv { get; private set; }
    public bool? PrdCls { get; private set; }
    public int? PrdClsUId { get; private set; }
    public DateTime? PrdClsDate { get; private set; }
    public int? PrdUnclsUId { get; private set; }
    public DateTime? PrdUnclsDate { get; private set; }
    public long? PrdClsCnt { get; private set; }
    public bool? PlCls { get; private set; }
    public int? PlClsCnt { get; private set; }
    public int? PlClsUId { get; private set; }
    public DateTime? PlClsDate { get; private set; }
    public int? PlUnclsUId { get; private set; }
    public DateTime? PlUnclsDate { get; private set; }
    public bool? InvCls { get; private set; }
    public int? InvClsUId { get; private set; }
    public DateTime? InvClsDate { get; private set; }
    public int? InvClsCnt { get; private set; }
    public int? InvUnclsUId { get; private set; }
    public DateTime? InvUnclsDate { get; private set; }
    public bool? DeprCls { get; private set; }
    public int? DeprClsUId { get; private set; }
    public DateTime? DeprClsDate { get; private set; }
    public int? DeprClsCnt { get; private set; }
    public int? DeprUnclsUId { get; private set; }
    public DateTime? DeprUnclsDate { get; private set; }
    public bool? MrpCls { get; private set; }
    public int? MrpClsCnt { get; private set; }
    public int? MrpClsUId { get; private set; }
    public DateTime? MrpClsDate { get; private set; }
    public int? MrpUnclsUId { get; private set; }
    public DateTime? MrpUnclsDate { get; private set; }
    public short? FasPrd { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? PlAcCodeCls { get; private set; }
    public int? PlAmtCls { get; private set; }
    public bool? RvrsCls { get; private set; }
    public DateTime? RvrsFDateCls { get; private set; }
    public DateTime? RvrsTDateCls { get; private set; }
    public bool? CurDiffCls { get; private set; }
    public bool? CurDiffClsWthCc { get; private set; }
    public bool? CurDiffClsWthPj { get; private set; }
    public bool? CurDiffClsWthActv { get; private set; }
    public short? CurRateFlgCls { get; private set; }
    public short? CurRateTypFlgCls { get; private set; }
}