public class SZone
{
    public short? ZoneNo { get; private set; }
    public string? ZoneLNm { get; private set; }
    public string? ZoneFNm { get; private set; }
    public string? ZoneShrt { get; private set; }
    public int AdUId { get; private set; }
    public DateTime AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? CmpnyLNm { get; private set; }
    public string? CmpnyFNm { get; private set; }
    public string? CmpnyPrefix { get; private set; }
    public string? CmpCode { get; private set; }
    public string? UsrCode { get; private set; }
    public string? UsrPass { get; private set; }
    public string? UsrTag { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string TrName { get; private set; }
    public string? TrEName { get; private set; }
    public bool? TrRes { get; private set; }
    public short? TrSr { get; private set; }
    public bool? TrRec { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
}