public class UserFngr
{
    public int? UId { get; private set; }
    public int? UFngrId { get; private set; }
    public int? UFngrNo { get; private set; }
    public string? UFngrStrng { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string UAName { get; private set; }
    public string? UEName { get; private set; }
    public int? UMng { get; private set; }
    public int? GroupNo { get; private set; }
    public string Password { get; private set; }
    public string? Password2 { get; private set; }
    public DateTime? SSdate { get; private set; }
    public DateTime? SEdate { get; private set; }
    public string? SStime { get; private set; }
    public string? SEtime { get; private set; }
    public bool? LgnMethod { get; private set; }
    public short? Dayactive { get; private set; }
    public bool? Inactive { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? InactiveUId { get; private set; }
    public string? InactiveRes { get; private set; }
    public string? ACode { get; private set; }
    public short? UserType { get; private set; }
    public bool? AdminUser { get; private set; }
    public bool? ChngPasswdAftrLgn { get; private set; }
    public bool? UserOnline { get; private set; }
    public bool? ConnWebSys { get; private set; }
    public long? UpdPwdCnt { get; private set; }
    public int? ScrThemeNo { get; private set; }
    public string? PrinterBarcodeDfltNm { get; private set; }
    public string? PrinterBarcodePath { get; private set; }
    public bool? HrsUserWebSystem { get; private set; }
    public string? TrmnlName { get; private set; }
    public string? TrmnlLgn { get; private set; }
    public string? Occupation { get; private set; }
    public string? Login { get; private set; }
    public string? Logout { get; private set; }
    public bool? LoggedOn { get; private set; }
    public long? LoginCnt { get; private set; }
    public int? ConnBrnNo { get; private set; }
    public bool? ConnectionType { get; private set; }
    public int? MachineNo { get; private set; }
    public long? WCodeDef { get; private set; }
    public string? CcCodeDef { get; private set; }
    public long? CashNoDef { get; private set; }
    public long? CashNo { get; private set; }
    public long? EmpNo { get; private set; }
    public string? RepCode { get; private set; }
    public string? LoanACode { get; private set; }
    public string? LoanACodeDtl { get; private set; }
    public int? InhrtUId { get; private set; }
    public bool? UseRsltnScr { get; private set; }
    public bool? WcodeKeeper { get; private set; }
    public long? ColNo { get; private set; }
    public bool? VrfctnTyp { get; private set; }
    public string? PdaNm { get; private set; }
    public string? WordPath { get; private set; }
    public string? ExcelPath { get; private set; }
    public bool? RmsUsrTyp { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public short? LowLvlPrice { get; private set; }
    public short? HighLvlPrice { get; private set; }
    public short? DfltLvlPrice { get; private set; }
    public int? RmsUsrDfltBillDocTyp { get; private set; }
    public int? RmsDfltHall { get; private set; }
    public string? ImgEdtrPath { get; private set; }
    public string? ExprolrPath { get; private set; }
    public bool? DfltClcVatPriceTyp { get; private set; }
    public string? MobileNo { get; private set; }
    public bool? CssUsrFlg { get; private set; }
    public long? DriverNo { get; private set; }
    public string? ExcssACode { get; private set; }
    public string? ExcssACodeDtl { get; private set; }
}