public class VDetails
{
    public string? VCode { get; private set; }
    public string VAName { get; private set; }
    public string? VEName { get; private set; }
    public string VACode { get; private set; }
    public long? VGroupCode { get; private set; }
    public short? VClass { get; private set; }
    public int? VDegree { get; private set; }
    public string? VTaxCode { get; private set; }
    public bool? Taxpayer { get; private set; }
    public string? VAddress { get; private set; }
    public short? CntryNo { get; private set; }
    public long? CityNo { get; private set; }
    public string? CcCode { get; private set; }
    public int? CcNo { get; private set; }
    public string? VPhone { get; private set; }
    public string? VFax { get; private set; }
    public string? VBox { get; private set; }
    public string? VPerson { get; private set; }
    public string? VEMail { get; private set; }
    public string? VWebSite { get; private set; }
    public string? VMobile { get; private set; }
    public DateTime? VSince { get; private set; }
    public bool? Inactive { get; private set; }
    public bool? InactivePur { get; private set; }
    public string? VNote { get; private set; }
    public bool? BlkLst { get; private set; }
    public string? BlkLstRes { get; private set; }
    public short? CreditPeriod { get; private set; }
    public long? AcOpNo { get; private set; }
    public bool? ImpXls { get; private set; }
    public int? ConnBrnNo { get; private set; }
    public int? ClcVatPriceTyp { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public bool? FavAc { get; private set; }
    public DateTime? ConfLastDate { get; private set; }
    public string? CrNo { get; private set; }
    public string? ActvtyNm { get; private set; }
    public string? NisNo { get; private set; }
    public string? NaiDsc { get; private set; }
    public string? EqCptl { get; private set; }
    public string? CTaxCode { get; private set; }
    public bool? VndGcc { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? PanCode { get; private set; }
    public long? ProvNo { get; private set; }
    public int? ClcTypNoTax { get; private set; }
    public bool? UseTdsFlg { get; private set; }
    public bool? UsePanNo { get; private set; }
    public int? UsePriceLstFlg { get; private set; }
    public string? GlnCode { get; private set; }
    public bool? UseAutoSyncVndr { get; private set; }
    public string? ExtrnlCCode { get; private set; }
    public string? UserNo { get; private set; }
    public string? Passwrd { get; private set; }
    public string? WebSrvcUrl { get; private set; }
    public short? UnitSrvcNo { get; private set; }
    public short? YearSrvcNo { get; private set; }
    public bool? CrdtPriodType { get; private set; }
    public bool? UseCrdtPriodItm { get; private set; }
    public short? LvlNoPrice { get; private set; }
}