CREATE TABLE "FAS_ASSETS_MST" ("AS_CODE" VARCHAR2(30), "EMP_NO" NUMBER(10, 0),
 "AS_A_NAME" VARCHAR2(100), "AS_E_NAME" VARCHAR2(100), "END_BLNC_QTY" NUMBER, "AS_ST"
 NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AUD_ITM_MST" ("AUD_NO" NUMBER(30, 0), "AUD_TYPE" NUMBER(2, 0),
 "DOC_TYPE" NUMBER(5, 0), "JV_TYPE" NUMBER(10, 0), "DOC_NO" NUMBER(15, 0), "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE, "A_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30),
 "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7), "C_CODE" VARCHAR2(15), "V_CODE"
 VARCHAR2(15), "C_V_NAME" VARCHAR2(60), "AMT" NUMBER, "DISC_AMT" NUMBER, "OTHR_AMT"
 NUMBER, "VAT_AMT" NUMBER, "COMM_PER" NUMBER(7, 4), "DOC_RATE" NUMBER, "STK_RATE" NUMBER,
 "A_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15), "CASH_NO" NUMBER(10, 0), "CHEQUE_NO"
 NUMBER(20, 0), "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "R_CODE" NUMBER(10, 0),
 "REP_CODE" VARCHAR2(15), "LC_NO" VARCHAR2(15), "LOAD_NO" NUMBER(15, 0), "LOAD_SER"
 NUMBER(38, 0), "F_DOC_NO" NUMBER(15, 0), "F_DOC_SER" NUMBER(38, 0), "REASON_DEL"
 VARCHAR2(250), "DOC_DUE_DATE" DATE, "EXTERNAL_POST" NUMBER(5, 0), "PR_REP" NUMBER(10, 0)
, "PROCESSED" NUMBER(1, 0), "BILL_PY" NUMBER(1, 0), "PUR_TYPE" NUMBER(1, 0), "EXP_A_CODE"
 VARCHAR2(30), "EXP_A_CY" VARCHAR2(7), "EXP_AMT" NUMBER, "EXP_RATE" NUMBER, "UP_CNT"
 NUMBER(10, 0), "U_ID" NUMBER(5, 0), "AUD_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "AD_DATE"
 DATE, "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0),
 "UNPOST_DATE" DATE, "TRMNL_NAME" VARCHAR2(100), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 196608 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_AUDIT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AUD_ITM_DTL" ("AUD_NO" NUMBER(30, 0), "AUD_TYPE" NUMBER(2, 0),
 "DOC_TYPE" NUMBER(5, 0), "JV_TYPE" NUMBER(10, 0), "DOC_NO" NUMBER(15, 0), "DOC_SER"
 NUMBER(38, 0), "I_CODE" VARCHAR2(30), "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT"
 VARCHAR2(10) NOT NULL ENABLE, "P_SIZE" NUMBER, "P_QTY" NUMBER, "I_PRICE" NUMBER,
 "STK_COST" NUMBER, "OUT_QTY" NUMBER, "OUT_FREE_QTY" NUMBER, "W_CODE" NUMBER(10, 0),
 "CC_CODE" VARCHAR2(30), "EXPIRE_DATE" DATE, "BATCH_NO" VARCHAR2(30), "DIS_AMT" NUMBER,
 "VAT_AMT" NUMBER, "OTHR_AMT" NUMBER, "USE_SERIALNO" NUMBER(1, 0), "SERVICE_ITEM"
 NUMBER(1, 0), "RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE" NUMBER(38, 0), "ITEM_DESC"
 VARCHAR2(4000), "BARCODE" VARCHAR2(30), "SO_NO" NUMBER(15, 0), "SO_SER" NUMBER(38, 0),
 "DOC_TYPE_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0),
 "TRMNL_NAME" VARCHAR2(100), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0)
 NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 131072 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_AUDIT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AUD_ITM_OTHR_MST" ("AUD_NO" NUMBER(30, 0), "AUD_TYPE" NUMBER(2, 0),
 "DOC_TYPE" NUMBER(5, 0), "JV_TYPE" NUMBER(10, 0), "DOC_NO" NUMBER(15, 0), "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE, "A_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30),
 "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7), "C_CODE" VARCHAR2(15), "V_CODE"
 VARCHAR2(15), "C_V_NAME" VARCHAR2(60), "DOC_AMT" NUMBER, "DISC_AMT" NUMBER, "OTHR_AMT"
 NUMBER, "VAT_AMT" NUMBER, "COMM_PER" NUMBER(7, 4), "DOC_RATE" NUMBER, "STK_RATE" NUMBER,
 "DOC_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15), "CASH_NO" NUMBER(10, 0), "CHEQUE_NO"
 NUMBER(20, 0), "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15),
 "ACTV_NO" VARCHAR2(15), "R_CODE" NUMBER(10, 0), "REP_CODE" VARCHAR2(15), "HRCHY_NO"
 NUMBER(20, 0), "LC_NO" VARCHAR2(15), "REASON_DEL" VARCHAR2(250), "DOC_DUE_DATE" DATE,
 "EXTERNAL_POST" NUMBER(5, 0), "PR_REP" NUMBER(10, 0), "PROCESSED" NUMBER(1, 0), "DOC_PY"
 NUMBER(1, 0), "PUR_TYPE" NUMBER(1, 0), "SIDE_REQ" VARCHAR2(60), "REQ_AVL_DATE" DATE,
 "DOC_TYPE_REF" NUMBER(5, 0), "DOC_JV_TYPE_REF" NUMBER(10, 0), "DOC_NO_REF" NUMBER(15, 0)
, "DOC_SER_REF" NUMBER(38, 0), "APPRVD" NUMBER(1, 0), "APPRVD_U_ID" NUMBER(5, 0),
 "APPRVD_DATE" DATE, "INACTIVE" NUMBER(1, 0), "INACTIVE_U_ID" NUMBER(5, 0),
 "INACTIVE_DATE" DATE, "INACTIVE_RES" VARCHAR2(250), "U_ID" NUMBER(5, 0), "AUD_DATE" DATE
, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE,
 "UP_CNT" NUMBER(10, 0), "TRMNL_NAME" VARCHAR2(100), "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_AUDIT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AUD_ITM_OTHR_DTL" ("AUD_NO" NUMBER(30, 0), "AUD_TYPE" NUMBER(2, 0),
 "DOC_TYPE" NUMBER(5, 0), "JV_TYPE" NUMBER(10, 0), "DOC_NO" NUMBER(15, 0), "DOC_SER"
 NUMBER(38, 0), "I_CODE" VARCHAR2(30), "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT"
 VARCHAR2(10), "P_SIZE" NUMBER, "P_QTY" NUMBER, "I_PRICE" NUMBER, "STK_COST" NUMBER,
 "FLW_QTY" NUMBER, "FLW_FREE_QTY" NUMBER, "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30),
 "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "EXPIRE_DATE" DATE, "BATCH_NO"
 VARCHAR2(30), "DIS_AMT" NUMBER, "VAT_AMT" NUMBER, "OTHR_AMT" NUMBER, "USE_SERIALNO"
 NUMBER(1, 0), "SERVICE_ITEM" NUMBER(1, 0), "RCRD_NO" NUMBER(10, 0), "DOC_SEQUENCE"
 NUMBER(38, 0), "ITEM_DESC" VARCHAR2(250), "BARCODE" VARCHAR2(30), "F_QTY" NUMBER,
 "T_QTY" NUMBER, "F_AMT" NUMBER, "T_AMT" NUMBER, "DISC_TYPE" NUMBER(2, 0), "QT_I_CODE"
 VARCHAR2(30), "DOC_TYPE_REF" NUMBER(5, 0), "DOC_JV_TYPE_REF" NUMBER(10, 0), "DOC_NO_REF"
 NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0), "DOC_SEQUENCE_REF" NUMBER(38, 0),
 "TRMNL_NAME" VARCHAR2(100), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0)
 NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_AUDIT" LOGGING NOCOMPRESS;

