CREATE TABLE "S_EMP" ("EMP_NO" NUMBER(10, 0), "EMP_L_NM" VARCHAR2(60) NOT NULL ENABLE,
 "EMP_F_NM" VARCHAR2(60), "EMP_NO_MNGR" NUMBER(10, 0), "EMP_IMG" VARCHAR2(100),
 "FRST_L_NM" VARCHAR2(50) NOT NULL ENABLE, "FRST_F_NM" VARCHAR2(50), "SCND_L_NM"
 VARCHAR2(50), "SCND_F_NM" VARCHAR2(50), "THRD_L_NM" VARCHAR2(50), "THRD_F_NM"
 VARCHAR2(50), "LST_L_NM" VARCHAR2(50), "LST_F_NM" VARCHAR2(50), "CUR_CODE" VARCHAR2(7),
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "HRCHY_NO"
 NUMBER(20, 0), "CLASS_NO" NUMBER(10, 0), "GNDR" NUMBER(10, 0), "RLGN_NO" NUMBER(10, 0),
 "NTNLTY_NO" NUMBER(10, 0), "SCL_ST" NUMBER(10, 0), "BLD_TYP" NUMBER(10, 0),
 "EMP_LANG_NO" NUMBER(10, 0), "BRTH_AD_DATE" VARCHAR2(10), "BRTH_HG_DATE" VARCHAR2(10),
 "BRTH_PLC" VARCHAR2(60), "BRTH_PLC_DTL" VARCHAR2(60), "DGHTR_NO" NUMBER(2, 0),
 "RTRMNT_PYMNT_PAID" NUMBER(1, 0), "SON_NO" NUMBER(2, 0), "PARNT_ST" NUMBER(10, 0),
 "RLTV_L_NM" VARCHAR2(100), "RLTV_F_NM" VARCHAR2(100), "CRD_TYP" NUMBER(10, 0), "CRD_NO"
 VARCHAR2(30), "NTNL_NO" VARCHAR2(30), "PLC_CRD_ISSUE" VARCHAR2(150), "CRD_DATE" DATE,
 "CRD_EXP_DATE" DATE, "NOTES" VARCHAR2(100), "GRD_NO" NUMBER(10, 0), "CTGRY_NO" NUMBER(10
, 0), "DCSN_DATE" DATE, "DCSN_ISSU_SD" NUMBER(10, 0), "RTRMNT_DATE" DATE, "OLD_WRK_DY"
 NUMBER(2, 0), "OLD_WRK_MNTH" NUMBER(2, 0), "OLD_WRK_YR" NUMBER(2, 0),
 "RTRMNT_DFRNT_SD_FLG" NUMBER(1, 0), "LNK_LST_WRK_FLG" NUMBER(1, 0), "RTRMNT_FLG"
 NUMBER(1, 0), "STRT_WRK_DATE" DATE, "CRNT_JOB_DATE" DATE, "DCSN_NO" NUMBER,
 "EMP_CRNT_ST" NUMBER(1, 0), "EMP_ST" NUMBER(1, 0), "EMP_JOB_NO" NUMBER(10, 0), "LVL_NO"
 NUMBER(10, 0), "LST_WRK_DATE" DATE, "CRNT_QLFCTN" NUMBER(10, 0), "QLFCTN_STRT_WRK"
 NUMBER(10, 0), "MJR_NO" NUMBER(10, 0), "EMPLYMNT_TYP" NUMBER(10, 0), "GRP_NO" NUMBER(10,
 0), "LST_STRT_DATE" DATE, "LST_MOV_DATE" DATE, "EVAL_LST" NUMBER(5, 0), "QLFCTN_CNTRY"
 NUMBER(10, 0), "QLFCTN_YR" NUMBER(4, 0), "DCSN_TYP" NUMBER(10, 0), "PJ_NO" VARCHAR2(30),
 "DY_WAGE" NUMBER, "AC_CODE" VARCHAR2(30), "HM_FCMP_FLG" NUMBER(1, 0), "HR_WAGE" NUMBER,
 "TAX_FLG" NUMBER(1, 0), "SLRY_ST" NUMBER(1, 0), "WRK_DY_MNTH" NUMBER(4, 2), "WRK_HRS_DY"
 NUMBER(4, 2), "MNGRL_NO" NUMBER(10, 0), "QLFCTN_ISSSUE" VARCHAR2(500), "ATTNDNC_TYP"
 NUMBER(1, 0), "STST_MAIN" NUMBER, "MNT_PSRC" NUMBER(1, 0), "TCKT_DSRV_CLC_TYP" NUMBER(1,
 0), "LST_TCKT_PYMNT_DATE" DATE, "SCL_INSRNCE_NO" VARCHAR2(100), "CC_CODE" VARCHAR2(30),
 "PAY_MTHD" NUMBER(10, 0), "WRK_HRS_MNTH" NUMBER(5, 2), "WRK_HRS_YR" NUMBER(6, 2),
 "WRK_DY_YR" NUMBER(5, 2), "ACTV_NO" VARCHAR2(30), "SLRY_PAY_WAY" NUMBER(1, 0), "MRP_TYP"
 NUMBER(2, 0), "MRP_RSRC" NUMBER(1, 0), "EMP_PSWRD" VARCHAR2(20), "USE_SLF_SRVC_SYS"
 NUMBER(1, 0), "E_MAIL" VARCHAR2(60), "WEB_SITE" VARCHAR2(60), "FAX_NO" VARCHAR2(30),
 "TEL_NO" VARCHAR2(30), "MOBILE_NO" VARCHAR2(30), "PO_BOX_NO" VARCHAR2(60), "ADDRS"
 VARCHAR2(150), "WRK_OFFC" VARCHAR2(200), "PORT_DSC" VARCHAR2(200), "ENTRY_VSA_NO"
 VARCHAR2(100), "ENTRY_VSA_JOB" NUMBER(4, 0), "INSRNCE_NO" VARCHAR2(100),
 "MDCL_INSRNCE_NO" VARCHAR2(100), "MDCL_INSRANCE_TYP" NUMBER(10, 0), "INSRNCE_SON_NO"
 NUMBER(2, 0), "INSRNCE_PARNT_NO" NUMBER(1, 0), "TCKTS_DSRVE" NUMBER(1, 0),
 "EMP_TCKTS_NO" NUMBER(2, 0), "TCKTS_COST" NUMBER(10, 0), "TCKTS_FOR_DAYS" NUMBER(4, 0),
 "EMP_TCKTS_RTIO" NUMBER(3, 0), "TCKT_PATH_NO" VARCHAR2(200), "CTZNSHP" NUMBER(30, 0),
 "EMP_NO_LAST" NUMBER(10, 0), "EMP_NO_MCHN" NUMBER(10, 0), "GNR_FLG" NUMBER(4, 0) NOT
 NULL ENABLE, "LAW_NO_DSRV_HLDY" NUMBER(10, 0), "RLTV_E_MAIL" VARCHAR2(60),
 "RLTV_MOBILE_NO" VARCHAR2(30), "RLTV_TEL_NO" VARCHAR2(30), "RTRMNT_AGE" NUMBER(3, 0),
 "RTRMNT_WRK_YR" NUMBER(3, 0), "SLRY_CALC" NUMBER(1, 0), "LST_INCRS_DATE" DATE,
 "LST_ALNC_DATE" DATE, "FNG_CALC" NUMBER(1, 0), "IMP_XLS" NUMBER(1, 0), "BNK_AC_CODE"
 VARCHAR2(30), "GPS_LNGITD_X" VARCHAR2(100), "GPS_LATITD_Y" VARCHAR2(100), "GPS_CITY"
 VARCHAR2(100), "LNK_TIMESHEET" NUMBER(1, 0), "EMP_NO_MNGR2" NUMBER(10, 0), "VALT_LST"
 NUMBER(1, 0), "CNTRY_NO" NUMBER(4, 0), "CITY_NO" NUMBER(10, 0), "R_CODE" NUMBER(10, 0),
 "PRBTNRY_PRD_END_DATE" DATE, "PRBTNRY_FLG" NUMBER(1, 0), "INSRNCE_OTHRS" NUMBER,
 "EMP_INSRNCE_RTO" NUMBER, "EMP_INSRNCE_AMT" NUMBER, "INSRNCE_CUR_CODE" VARCHAR2(7),
 "INACTIVE" NUMBER(1, 0), "INACTIVE_U_ID" NUMBER(5, 0), "INACTIVE_DATE" DATE,
 "INACTIVE_RES" VARCHAR2(250), "FIELD1" VARCHAR2(500), "FIELD10" VARCHAR2(500), "FIELD11"
 VARCHAR2(500), "FIELD12" VARCHAR2(500), "FIELD13" VARCHAR2(500), "FIELD14" VARCHAR2(500)
, "FIELD15" VARCHAR2(500), "FIELD16" VARCHAR2(500), "FIELD17" VARCHAR2(500), "FIELD18"
 VARCHAR2(500), "FIELD19" VARCHAR2(500), "FIELD2" VARCHAR2(500), "FIELD20" VARCHAR2(500),
 "FIELD3" VARCHAR2(500), "FIELD4" VARCHAR2(500), "FIELD5" VARCHAR2(500), "FIELD6"
 VARCHAR2(500), "FIELD7" VARCHAR2(500), "FIELD8" VARCHAR2(500), "FIELD9" VARCHAR2(500),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE NOT NULL ENABLE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "SCL_SCRTY_NO" NUMBER(20, 0),
 "REINSTTMNT_DATE" DATE, "PROV_NO" NUMBER(10, 0), "WRK_PRD_TYP" NUMBER(1, 0),
 "EMP_CNTRCT_TYP" NUMBER(1, 0), "EMP_TRCK_MTHD" NUMBER(1, 0), "FEED_LMT_AMT" NUMBER,
 "FEED_LMT_TYP" NUMBER(1, 0), "END_WRK_TYP" NUMBER(10, 0), "EMP_MDCL_STRT_DATE" DATE,
 "EMP_MDCL_END_DATE" DATE, "DFLT_LAW_ARTCL_VAL" NUMBER, "EMP_ATTNDNC_TYP" NUMBER(1, 0),
 "ATTNDNC_MOBILE_TYP" NUMBER(1, 0), "MOBILE_CPTR_IMG_TYP" NUMBER(1, 0),
 "ATTNDNC_TIMEZONE" VARCHAR2(20), "MOBILE_CNNCT_TYP" NUMBER(1, 0), "ATTNDNC_MOBILE_SRL"
 VARCHAR2(60), "USE_ATTNDNC_LOC" NUMBER(1, 0), "MOBILE_ATTNDNC_SYNC" NUMBER(1, 0),
 "FACEBOOK" VARCHAR2(100), "TWITTER" VARCHAR2(100), "INSTAGRAM" VARCHAR2(100), "TELEGRAM"
 VARCHAR2(100), "WEEKLY_DAYOFF_CALC_ST" NUMBER(1, 0), "WEEKLY_DAYOFF_SHFT_DAYS_RQRD"
 NUMBER(1, 0), "WEEKLY_DAYOFF_RGLR_DAYS_RQRD" NUMBER(1, 0), "WEEKLY_DAYOFF_COMPAR_EQL"
 NUMBER(1, 0), "WEEKLY_DAYOFF_REF_HLDY_NO" NUMBER(5, 0), "WEEK_DAYS" NUMBER(1, 0),
 "EMP_MDCL_AGE_LMT" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "S_EMP_BNK" ("EMP_NO" NUMBER(10, 0), "BNK_NO" NUMBER(10, 0), "BNK_BRN_NO"
 NUMBER(10, 0), "BNK_AC_TYP" NUMBER(2, 0), "AC_CODE_BNK" VARCHAR2(30), "SLRY_FLG"
 NUMBER(1, 0), "INACTIVE" NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(150), "INACTIVE_DATE"
 DATE, "INACTIVE_U_ID" NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE NOT NULL
 ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "GNR_ATTNDNC_LOC" ("LOC_NO" NUMBER(10, 0), "LOC_L_NM" VARCHAR2(100) NOT NULL
 ENABLE, "LOC_F_NM" VARCHAR2(100), "CONN_TYP" NUMBER(2, 0) NOT NULL ENABLE,
 "GPS_LNGITD_X" VARCHAR2(100), "GPS_LATITD_Y" VARCHAR2(100), "ALLW_DSTNC_GPS" NUMBER(5,
 0), "LOC_NETWRK_IP" VARCHAR2(500), "INACTIVE" NUMBER(1, 0) NOT NULL ENABLE,
 "INACTIVE_RES" VARCHAR2(150), "INACTIVE_U_ID" NUMBER(10, 0), "INACTIVE_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE" DATE NOT NULL ENABLE, "AD_TRMNL_NM"
 VARCHAR2(50), "UP_U_ID" NUMBER(5, 0), "UP_CNT" NUMBER(10, 0), "UP_DATE" DATE,
 "UP_TRMNL_NM" VARCHAR2(50), "PR_REP" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "S_EMP_FMLY" ("PRSN_NO" NUMBER(10, 0), "EMP_NO" NUMBER(10, 0), "PRSN_L_NM"
 VARCHAR2(60) NOT NULL ENABLE, "PRSN_F_NM" VARCHAR2(60), "PRSN_PRNT_L_NM" VARCHAR2(60),
 "PRSN_PRNT_F_NM" VARCHAR2(60), "PRSN_GRND_L_NM" VARCHAR2(60), "PRSN_GRND_F_NM"
 VARCHAR2(60), "PRSN_FMIL_L_NM" VARCHAR2(60), "PRSN_FMIL_F_NM" VARCHAR2(60), "NTNLTY_NO"
 NUMBER(10, 0), "RLGN_NO" NUMBER(10, 0), "BRTH_PLC" VARCHAR2(60), "BRTH_DATE" DATE,
 "RLTNSHP_NO" NUMBER(1, 0), "GNDR" NUMBER(1, 0), "MDCL_FLG" NUMBER(1, 0), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE NOT NULL ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE,
 "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "PRSN_MDCL_CTGRY" NUMBER(4, 0),
 "PRSN_MDCL_STRT_DATE" DATE, "PRSN_MDCL_END_DATE" DATE, "PRSN_MDCL_AMT" NUMBER,
 "PRSN_MDCL_MEMBRSHP" VARCHAR2(50), "EMP_MDCL_RTO" NUMBER, "BLD_TYP" NUMBER(10, 0),
 "PRSN_IMG" VARCHAR2(100), "PRSN_MDCL_DSRVD_AGE" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "S_EMP_PRV" ("U_ID" NUMBER(5, 0) NOT NULL ENABLE, "EMP_PRV_TYP" NUMBER(1, 0)
 NOT NULL ENABLE, "EMPNO_HRCHYNO" NUMBER(10, 0) NOT NULL ENABLE, "ADD_FLAG" NUMBER(1, 0),
 "VIEW_FLAG" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE NOT NULL ENABLE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "S_EMP_GRNTR" ("EMP_NO" NUMBER(10, 0), "GRNTR_NO" NUMBER(10, 0), "INACTIVE"
 NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(150), "INACTIVE_DATE" DATE, "INACTIVE_U_ID"
 NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE NOT NULL ENABLE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "SLRY_FLG"
 NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

