CREATE TABLE "IAS_PROJECTS" ("PJ_NO" VARCHAR2(15), "PJ_CODE" VARCHAR2(30), "PJ_A_NAME"
 VARCHAR2(100) NOT NULL ENABLE, "PJ_E_NAME" VARCHAR2(100), "PJ_PARENT" VARCHAR2(15) NOT
 NULL ENABLE, "PJ_LEVEL" NUMBER(5, 0), "PJ_SUB" NUMBER(1, 0) NOT NULL ENABLE, "GROUP_NO"
 NUMBER(5, 0), "INACTIVE" NUMBER(1, 0), "INACTIVE_U_ID" NUMBER(5, 0), "INACTIVE_DATE"
 DATE, "INACTIVE_RES" VARCHAR2(250), "IMP_XLS" NUMBER(1, 0), "START_DATE" DATE,
 "END_DATE" DATE, "ADDRESS" VARCHAR2(250), "PJ_ADMIN" VARCHAR2(100), "PJ_DESC"
 VARCHAR2(1000), "PJ_NOTES" VARCHAR2(4000), "CUR_CODE" VARCHAR2(7), "PJ_COST" NUMBER,
 "EX_RATE" NUMBER, "CNTRY_NO" NUMBER(4, 0), "CITY_NO" NUMBER(10, 0), "PROV_NO" NUMBER(10,
 0), "R_CODE" NUMBER(10, 0), "BID_DATE" DATE, "CONTRACT_SPS_DATE" DATE, "C_CODE"
 VARCHAR2(15), "COD_NO_PJ_MNGR" NUMBER(5, 0), "COD_TYP" NUMBER(3, 0), "COD_NO_PJ_G_SPCL"
 NUMBER(5, 0), "COD_NO_PJ_SPCL" NUMBER(5, 0), "PJ_ST" NUMBER(2, 0), "PMS_COND_NO"
 NUMBER(5, 0), "FIELD1" VARCHAR2(60), "FIELD2" VARCHAR2(60), "FIELD3" VARCHAR2(60),
 "FIELD4" VARCHAR2(60), "FIELD5" VARCHAR2(60), "FIELD6" VARCHAR2(60), "FIELD7"
 VARCHAR2(60), "FIELD8" VARCHAR2(60), "FIELD9" VARCHAR2(60), "FIELD10" VARCHAR2(60),
 "FIELD21" DATE, "FIELD22" DATE, "FIELD23" DATE, "FIELD24" DATE, "FIELD25" DATE,
 "FIELD26" DATE, "FIELD27" DATE, "FIELD28" DATE, "FIELD29" DATE, "FIELD30" DATE,
 "FIELD31" NUMBER, "FIELD32" NUMBER, "FIELD33" NUMBER, "FIELD34" NUMBER, "FIELD35" NUMBER
, "FIELD36" NUMBER, "FIELD37" NUMBER, "FIELD38" NUMBER, "FIELD39" NUMBER, "FIELD40"
 NUMBER, "USE_ACTV" NUMBER(1, 0), "ACCNTS_COST_FLG" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "MAX_EXECT_PCNT"
 NUMBER(5, 2))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PROJECTS_GROUP" ("GROUP_NO" NUMBER(5, 0), "GROUP_A_NAME" VARCHAR2(100)
 NOT NULL ENABLE, "GROUP_E_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AR_CNTRCT_MST" ("DOC_NO" NUMBER(15, 0), "DOC_SRL" NUMBER(38, 0) NOT
 NULL ENABLE, "CNTRCT_NO" VARCHAR2(60) NOT NULL ENABLE, "CNTRCT_DATE" DATE NOT NULL
 ENABLE, "CNTRCT_F_DATE" DATE, "CNTRCT_T_DATE" DATE, "C_CODE" VARCHAR2(15) NOT NULL
 ENABLE, "CSTMR_NM" VARCHAR2(60), "CNTRCT_AMT" NUMBER, "CNTRCT_A_CY" VARCHAR2(7),
 "CNTRCT_RATE" NUMBER, "CNTRCT_TYPE" NUMBER(1, 0), "CNTRCT_DESC" VARCHAR2(500),
 "CNTRCT_NOTE" VARCHAR2(2000), "CNTRCT_RENEW_AMT" NUMBER, "DISC_AMT" NUMBER,
 "DISC_AMT_MST" NUMBER, "DISC_AMT_DTL" NUMBER, "CNTRCT_NO_RENEW" VARCHAR2(60),
 "CNTRCT_SER_RENEW" VARCHAR2(60), "VAT_AMT" NUMBER, "EXPORT" NUMBER(1, 0), "CNTRCT_STAT"
 NUMBER(1, 0), "AMT_REM_NOTIFY" NUMBER, "DAY_EXPIR_NOTIFY" NUMBER, "ALOW_EXCD_AMT"
 NUMBER(1, 0), "PER_EXCD" NUMBER, "REF_NO" VARCHAR2(15), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "PROCESSED" NUMBER(1, 0), "INACTIVE" NUMBER(1, 0),
 "INACTIVE_U_ID" NUMBER(5, 0), "INACTIVE_DATE" DATE, "INACTIVE_RES" VARCHAR2(250),
 "APPROVED" NUMBER(1, 0), "APRV_U_ID" NUMBER(5, 0), "APRV_DATE" DATE, "APRV_DSC"
 VARCHAR2(500), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(6, 0), "PR_REP" NUMBER(6, 0), "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "CLC_TYP_NO_TAX"
 NUMBER(5, 0), "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0), "ADVNC_PYMNT_PRCNT_CNTRCT" NUMBER,
 "AD_DATE_CLK" DATE, "CLC_VAT_PRICE_TYP" NUMBER(1, 0), "DISC_AMT_MST_VAT" NUMBER,
 "CNTRCT_TYP" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AR_CNTRCT_DTL" ("DOC_NO" NUMBER(15, 0), "DOC_SRL" NUMBER(38, 0) NOT
 NULL ENABLE, "CNTRCT_NO" VARCHAR2(60) NOT NULL ENABLE, "RCRD_NO" NUMBER NOT NULL ENABLE,
 "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "I_NAME" VARCHAR2(60), "I_QTY" NUMBER, "P_SIZE"
 NUMBER NOT NULL ENABLE, "P_QTY" NUMBER NOT NULL ENABLE, "I_PRICE" NUMBER, "ITM_UNT"
 VARCHAR2(10), "DIS_AMT_MST" NUMBER, "DIS_PER" NUMBER, "DIS_AMT_DTL" NUMBER, "DIS_AMT"
 NUMBER, "INACTIVE" NUMBER(1, 0), "FREE_QTY" NUMBER, "CC_CODE" VARCHAR2(30), "VAT_AMT"
 NUMBER, "VAT_PER" NUMBER, "I_PRICE_VAT" NUMBER, "ITEM_DESC" VARCHAR2(250), "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4
, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "FIELD_DTL1" VARCHAR2(60), "FIELD_DTL2" VARCHAR2(60), "FIELD_DTL3"
 VARCHAR2(60), "FIELD_DTL4" VARCHAR2(60), "FIELD_DTL5" VARCHAR2(60), "FIELD_DTL6"
 VARCHAR2(60), "FIELD_DTL7" VARCHAR2(60), "FIELD_DTL8" VARCHAR2(60), "FIELD_DTL9"
 VARCHAR2(60), "FIELD_DTL10" VARCHAR2(60), "W_CODE" NUMBER(10, 0), "LEV_NO" NUMBER(3, 0),
 "DIS_AMT_DTL_VAT" NUMBER, "I_PRICE_LEV_NO" NUMBER, "VAT_AMT_DIS_DTL_VAT" NUMBER,
 "DIS_AMT_MST_VAT" NUMBER, "VAT_AMT_DIS_MST_VAT" NUMBER, "ARGMNT_NO" NUMBER, "I_HEIGHT"
 NUMBER, "I_LENGTH" NUMBER, "I_NUMBER" NUMBER, "I_WIDTH" NUMBER, "WT_QTY" NUMBER,
 "WT_UNT" VARCHAR2(10))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AR_CNTRCT_BTCH" ("CNTRCT_BTCH_NO" NUMBER(30, 0) NOT NULL ENABLE,
 "CNTRCT_BTCH_DATE" DATE NOT NULL ENABLE, "CNTRCT_NO" VARCHAR2(60) NOT NULL ENABLE,
 "DOC_NO" NUMBER(15, 0), "DOC_SRL" NUMBER(38, 0) NOT NULL ENABLE, "RCRD_NO" NUMBER NOT
 NULL ENABLE, "AMT" NUMBER NOT NULL ENABLE, "PROCESSED" NUMBER(1, 0), "CMP_NO" NUMBER(3,
 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0),
 "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "ADVNC_PYMNT" NUMBER(1, 0), "PRCSSD_FLG_GLS" NUMBER(1, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AR_CNTRCT_RENEW" ("RCRD_NO" NUMBER NOT NULL ENABLE, "CNTRCT_NO"
 VARCHAR2(60) NOT NULL ENABLE, "DOC_NO" NUMBER(15, 0), "DOC_SRL" NUMBER(38, 0) NOT NULL
 ENABLE, "CNTRCT_NEW_DATE" DATE, "INCRS_TYPE" NUMBER, "CNTRCT_F_DATE" DATE,
 "CNTRCT_T_DATE" DATE, "CNTRCT_AMT" NUMBER, "CNTRCT_DESC" VARCHAR2(150), "REF_NO"
 VARCHAR2(15), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(6, 0), "PR_REP" NUMBER(6, 0), "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING
 NOCOMPRESS;

