CREATE TABLE "P_ORDER" ("PO_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "PO_NO" NUMBER(15, 0) NOT
 NULL ENABLE, "PO_SER" NUMBER(38, 0), "PO_DATE" DATE NOT NULL ENABLE, "V_CODE"
 VARCHAR2(15), "V_NAME" VARCHAR2(100), "CUR_CODE" VARCHAR2(7) NOT NULL ENABLE, "CC_CODE"
 VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "PO_PROCESSED" NUMBER(1, 0),
 "PO_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15), "PO_PARTIAL" NUMBER(1, 0), "PO_CLOSED"
 NUMBER(1, 0), "DISC_AMT" NUMBER(24, 9), "INSPECT" NUMBER(1, 0), "ENTRY_NO" NUMBER(10, 0)
, "INACTIVE" NUMBER(1, 0), "INACTIVE_U_ID" NUMBER(5, 0), "INACTIVE_DATE" DATE,
 "INACTIVE_RES" VARCHAR2(250), "APPROVED" NUMBER(1, 0), "APRV_U_ID" NUMBER(5, 0),
 "APRV_DATE" DATE, "APRV_DSC" VARCHAR2(500), "RES_INACTIVE" VARCHAR2(250), "PUR_TYPE"
 NUMBER(1, 0), "INS_TERMS" VARCHAR2(500), "INS_NO" VARCHAR2(30), "INS_COMP" VARCHAR2(100)
, "INS_DATE" DATE, "PO_WITHOUT_OTHR_AMT" NUMBER(1, 0), "DELIVERY_DATE" DATE,
 "PLACE_DELIVERY" VARCHAR2(250), "PAY_TERMS" VARCHAR2(1000), "MODE_DISPATCH"
 VARCHAR2(250), "FREIGHT_CURR" VARCHAR2(7), "CNTCT_PERSON" VARCHAR2(300),
 "NEED_CHECK_QTY" NUMBER(1, 0), "VND_PI_NO" VARCHAR2(30), "RECEIVE_DATE" DATE,
 "PO_DOC_TYPE" NUMBER(5, 0), "DESC_INS_TEARMS" VARCHAR2(1000), "DISC_AMT_MST" NUMBER,
 "DISC_AMT_DTL" NUMBER, "PO_CHECKED" NUMBER(1, 0), "PO_LOCKED" NUMBER(1, 0),
 "BILL_NO_V_CODE" VARCHAR2(20), "BILL_DATE_V_CODE" DATE, "CLC_VAT_PRICE_TYP" NUMBER,
 "FIELD1" VARCHAR2(1000), "FIELD2" VARCHAR2(1000), "FIELD3" VARCHAR2(1000), "FIELD4"
 VARCHAR2(1000), "FIELD5" VARCHAR2(1000), "FIELD6" VARCHAR2(1000), "FIELD7"
 VARCHAR2(1000), "FIELD8" VARCHAR2(1000), "FIELD9" VARCHAR2(1000), "FIELD10"
 VARCHAR2(1000), "CNTRCT_NO" VARCHAR2(60), "CNTRCT_SER" VARCHAR2(60), "SRVC_BILL"
 NUMBER(1, 0), "ASSGN_TO_U_ID" NUMBER(5, 0), "ASSGN_U_ID" NUMBER(5, 0), "ASSGN_DATE" DATE
, "USE_VAT" NUMBER(1, 0), "RQRD_FRGHT_DATA" NUMBER(1, 0), "OTHR_AMT" NUMBER, "VAT_AMT"
 NUMBER, "CONTAINER_NO" NUMBER(10, 0), "FREIGHT_LST_DATE" DATE, "COSTING_TYPE_NO"
 NUMBER(5, 0), "PORT_OF_FREIGHT" VARCHAR2(60), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "CLC_TYP_NO_TAX" NUMBER(5, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "LVL_NO_PRICE" NUMBER(3, 0), "PO_COMP"
 VARCHAR2(50), "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0), "DOC_M_SQ" NUMBER, "PO_EXPIRE_DATE"
 DATE, "PO_TNDR_NO" VARCHAR2(30), "CUR_RATE" NUMBER, "PMAN_CODE" VARCHAR2(15))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_DATA_TRNS" LOGGING
 NOCOMPRESS;

CREATE TABLE "P_ORDER_DETAIL" ("PO_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "PO_NO" NUMBER(15,
 0) NOT NULL ENABLE, "PO_SER" NUMBER(38, 0), "I_CODE" VARCHAR2(30) NOT NULL ENABLE,
 "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "P_SIZE"
 NUMBER NOT NULL ENABLE, "P_QTY" NUMBER, "W_CODE" NUMBER(10, 0), "DOC_TYPE_REF" NUMBER(5,
 0), "PR_NO" NUMBER(15, 0), "PR_SER" NUMBER(38, 0), "QT_NO" NUMBER(15, 0), "QT_SER"
 NUMBER(38, 0), "I_PRICE" NUMBER(24, 9), "RCRD_NO" NUMBER(10, 0), "ITEM_DESC"
 VARCHAR2(1000), "BARCODE" VARCHAR2(30), "USE_ATTCH" NUMBER(1, 0), "REC_ATTCH" NUMBER(10,
 0), "PI_QTY" NUMBER, "PI_FREE_QTY" NUMBER, "AVL_QTY" NUMBER, "ITM_CWTAVG" NUMBER,
 "LAST_INCOME_PRICE" NUMBER, "DOC_SEQUENCE" NUMBER(38, 0), "DOC_SEQUENCE_PRQ" NUMBER(38,
 0), "CANCELED" NUMBER(1, 0), "EXPIRE_DATE" DATE, "BATCH_NO" VARCHAR2(30), "I_PRICE_VAT"
 NUMBER, "I_LENGTH" NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER,
 "DIS_AMT" NUMBER, "DIS_AMT_MST" NUMBER, "DIS_PER" NUMBER(20, 17), "DIS_AMT_DTL" NUMBER,
 "DIS_PER2" NUMBER(20, 17), "DIS_AMT_DTL2" NUMBER, "DIS_PER3" NUMBER(20, 17),
 "DIS_AMT_DTL3" NUMBER, "UNIT_SIZE" NUMBER, "U_QTY" NUMBER, "NOT_BILL_PRV_QTY" NUMBER,
 "BILL_PRV_QTY" NUMBER, "WT_QTY" NUMBER, "WT_UNT" VARCHAR2(10), "CC_CODE" VARCHAR2(30),
 "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "OTHR_AMT" NUMBER, "VAT_PER" NUMBER(7, 4),
 "VAT_AMT" NUMBER, "ARGMNT_NO" NUMBER, "DLVRY_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "PKG_UNT" VARCHAR2(10), "PKG_UNT_SIZE" NUMBER(10, 0), "PKG_QTY" NUMBER,
 "PKG_LENGTH" NUMBER, "PKG_WIDTH" NUMBER, "PKG_HEIGHT" NUMBER, "PKG_SIZE" NUMBER,
 "PKG_WEIGHT" NUMBER, "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0),
 "DOC_SEQUENCE_REF" NUMBER(38, 0), "UP_CNT" NUMBER(10, 0), "PJ_NO_REF" VARCHAR2(15),
 "SALE_PRICE" NUMBER, "DOC_SEQ_TMP" NUMBER, "FIELD_DTL1" VARCHAR2(60), "FIELD_DTL2"
 VARCHAR2(60), "FIELD_DTL3" VARCHAR2(60), "FIELD_DTL4" VARCHAR2(60), "FIELD_DTL5"
 VARCHAR2(60), "FIELD_DTL6" VARCHAR2(60), "FIELD_DTL7" VARCHAR2(60), "FIELD_DTL8"
 VARCHAR2(60), "FIELD_DTL9" VARCHAR2(60), "FIELD_DTL10" VARCHAR2(60))  PCTFREE 10 PCTUSED
 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_VND_QUOT_MST" ("QT_NO" NUMBER(15, 0), "QT_SER" NUMBER(38, 0), "QT_DATE"
 DATE NOT NULL ENABLE, "A_CY" VARCHAR2(7) NOT NULL ENABLE, "CUR_NO" NUMBER(4, 0) NOT NULL
 ENABLE, "V_CODE" VARCHAR2(15), "V_NAME" VARCHAR2(100), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "A_DESC" VARCHAR2(100), "PROCESSED" NUMBER(1, 0),
 "APPROVED" NUMBER(1, 0), "APRV_U_ID" NUMBER(5, 0), "APRV_DATE" DATE, "APRV_DSC"
 VARCHAR2(500), "REF_NO" VARCHAR2(15), "TEND_NO" VARCHAR2(15), "TEND_DATE" DATE,
 "REF_DATE" DATE, "PORT_OF_DEP" VARCHAR2(100), "REQ_DAYS" NUMBER(5, 0), "PAY_TERMS"
 VARCHAR2(500), "DISC_AMT" NUMBER(24, 9), "OTHR_AMT" NUMBER, "QT_WITHOUT_OTHR_AMT"
 NUMBER(1, 0), "CLC_VAT_PRICE_TYP" NUMBER, "FIELD1" VARCHAR2(250), "FIELD2" VARCHAR2(250)
, "FIELD3" VARCHAR2(250), "FIELD4" VARCHAR2(250), "FIELD5" VARCHAR2(250), "FIELD6"
 VARCHAR2(250), "FIELD7" VARCHAR2(250), "FIELD8" VARCHAR2(250), "FIELD9" VARCHAR2(250),
 "FIELD10" VARCHAR2(250), "DISC_AMT_MST" NUMBER, "DISC_AMT_DTL" NUMBER, "VAT_AMT" NUMBER,
 "USE_VAT" NUMBER(1, 0), "AUTO_RENEW" NUMBER(1, 0), "PR_REP" NUMBER(10, 0), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "CLC_TYP_NO_TAX" NUMBER(5, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "COST_TYPE" VARCHAR2(5),
 "QUOT_EXPIRE_DATE" DATE, "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0), "DLVRY_TIME_DYS" NUMBER) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_AP_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_VND_QUOT_DTL" ("QT_NO" NUMBER(15, 0) NOT NULL ENABLE, "QT_SER"
 NUMBER(38, 0), "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "I_QTY" NUMBER, "ITM_UNT"
 VARCHAR2(10) NOT NULL ENABLE, "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER, "I_PRICE"
 NUMBER(24, 9), "RCRD_NO" NUMBER(10, 0), "PR_NO" NUMBER(15, 0), "PR_SER" NUMBER(38, 0),
 "ITEM_DESC" VARCHAR2(1000), "DIS_AMT_MST" NUMBER, "DIS_AMT_DTL" NUMBER, "DIS_AMT" NUMBER
, "DIS_PER" NUMBER, "VAT_PER" NUMBER, "VAT_AMT" NUMBER, "FIELD_DTL1" VARCHAR2(60),
 "FIELD_DTL2" VARCHAR2(60), "FIELD_DTL3" VARCHAR2(60), "FIELD_DTL4" VARCHAR2(60),
 "FIELD_DTL5" VARCHAR2(60), "OTHR_AMT" NUMBER, "I_PRICE_VAT" NUMBER, "CMP_NO" NUMBER(3,
 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0),
 "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "FREE_QTY" NUMBER, "FIELD_DTL6" VARCHAR2(60),
 "FIELD_DTL7" VARCHAR2(60), "FIELD_DTL8" VARCHAR2(60), "FIELD_DTL9" VARCHAR2(60),
 "FIELD_DTL10" VARCHAR2(60))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PI_BILL_MST" ("PUR_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "BILL_DOC_TYPE"
 NUMBER(2, 0) NOT NULL ENABLE, "BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "BILL_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "BILL_DATE" DATE NOT NULL ENABLE, "BILL_CURRENCY"
 VARCHAR2(7) NOT NULL ENABLE, "BILL_RATE" NUMBER NOT NULL ENABLE, "STOCK_RATE" NUMBER,
 "V_CODE" VARCHAR2(15), "V_NAME" VARCHAR2(100), "LC_NO" VARCHAR2(15), "A_CODE"
 VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "CHEQUE_NO"
 NUMBER(20, 0), "CHEQUE_AMT" NUMBER, "CHEQUE_DUE_DATE" DATE, "BILL_DUE_DATE" DATE,
 "BILL_POST" NUMBER(1, 0), "BILL_GOOD_REC" NUMBER(1, 0), "DISC_AMT" NUMBER,
 "DISC_AMT_MST" NUMBER, "DISC_AMT_DTL" NUMBER, "VAT_AMT" NUMBER, "BILL_AMT" NUMBER,
 "OTHR_AMT" NUMBER, "BILL_WITHOUT_OTHR_AMT" NUMBER(1, 0), "W_CODE" NUMBER(10, 0),
 "REF_NO" VARCHAR2(15), "CASH_NO" NUMBER(10, 0), "CASH_NO_FCC" NUMBER(10, 0), "CC_CODE"
 VARCHAR2(30), "PJ_NO" VARCHAR2(15), "CASH_AC_FCC" VARCHAR2(30), "A_DESC" VARCHAR2(1000),
 "DRIVER_NAME" VARCHAR2(60), "CAR_NO" VARCHAR2(15), "CLC_VAT_PRICE_TYP" NUMBER, "FIELD1"
 VARCHAR2(250), "FIELD2" VARCHAR2(250), "FIELD3" VARCHAR2(250), "FIELD4" VARCHAR2(250),
 "FIELD5" VARCHAR2(250), "FIELD6" VARCHAR2(250), "FIELD7" VARCHAR2(250), "FIELD8"
 VARCHAR2(250), "FIELD9" VARCHAR2(250), "FIELD10" VARCHAR2(250), "PR_REP" NUMBER(10, 0),
 "EXP_AMT" NUMBER, "USE_VAT" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0), "BILL_TYPE_NO"
 NUMBER(5, 0), "CNCT_WTH_CNTRCT" NUMBER(1, 0), "CNTRCT_NO" VARCHAR2(60), "CNTRCT_SER"
 VARCHAR2(60), "ACTV_NO" VARCHAR2(15), "HUNG" NUMBER(1, 0), "FREIGHT_METHOD" NUMBER(1, 0)
, "UNDER_SELLING" NUMBER(1, 0), "BILL_NO_V_CODE" VARCHAR2(20), "PMAN_CODE" VARCHAR2(15),
 "ADD_AMT_TYPE" NUMBER(1, 0), "DISC_AMT_NOT_EFFECT" NUMBER, "ADD_DISC_AMT_MST" NUMBER,
 "ADD_DISC_AMT_DTL" NUMBER, "RCV_BILL_DATE" DATE, "BILL_DATE_V_CODE" DATE, "DOC_AMT"
 NUMBER, "DOC_BRN_NO" NUMBER(6, 0), "DOC_TYPE" NUMBER(5, 0), "BILL_NO_REF" NUMBER(15, 0),
 "BILL_SER_REF" NUMBER, "SRVC_BILL" NUMBER(1, 0), "CNTRCT_BTCH_NO" NUMBER(30, 0),
 "BILL_NO_CONN" NUMBER(15, 0), "BILL_SER_CONN" NUMBER(38, 0), "VND_GCC" NUMBER(1, 0),
 "V_ADDRESS" VARCHAR2(100), "V_TAX_CODE" VARCHAR2(30), "CR_NO" VARCHAR2(60),
 "OTHR_AMT_DISC" NUMBER, "VAT_AMT_OTHR" NUMBER, "AUDIT_REF" NUMBER(1, 0),
 "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0),
 "UNPOST_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT
 NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "CLC_TYP_NO_TAX" NUMBER(5,
 0), "ARV_DATE" DATE, "FRGHT_RGSTR_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "POST_TAX_DUE_AC_CODE" NUMBER(1, 0), "USE_TDS_FLG" NUMBER(1, 0), "AC_CODE"
 VARCHAR2(30), "AC_AMT" NUMBER, "PYMNT_AC" NUMBER, "LVL_NO_PRICE" NUMBER(3, 0),
 "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_PI" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PI_BILL_DTL" ("PUR_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "BILL_DOC_TYPE"
 NUMBER(2, 0) NOT NULL ENABLE, "BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "BILL_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "I_NM"
 VARCHAR2(60), "I_QTY" NUMBER, "FREE_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE,
 "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER NOT NULL ENABLE, "I_PRICE" NUMBER,
 "STK_COST" NUMBER, "INC_QTY" NUMBER, "INC_FREE_QTY" NUMBER, "W_CODE" NUMBER(10, 0),
 "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "EXPIRE_DATE" DATE
 NOT NULL ENABLE, "BATCH_NO" VARCHAR2(30) NOT NULL ENABLE, "DIS_AMT_MST" NUMBER,
 "DIS_PER" NUMBER(20, 17), "DIS_AMT_DTL" NUMBER, "DIS_PER2" NUMBER(20, 17),
 "DIS_AMT_DTL2" NUMBER, "DIS_PER3" NUMBER(20, 17), "DIS_AMT_DTL3" NUMBER, "DIS_AMT"
 NUMBER, "VAT_PER" NUMBER, "VAT_AMT" NUMBER, "ADD_AMT" NUMBER, "OTHR_AMT" NUMBER,
 "USE_SERIALNO" NUMBER(1, 0), "RCRD_NO" NUMBER(10, 0) NOT NULL ENABLE, "DOC_SEQUENCE"
 NUMBER(38, 0) NOT NULL ENABLE, "DOC_SEQUENCE_GRN_PO" NUMBER(38, 0), "ITEM_DESC"
 VARCHAR2(1000), "BARCODE" VARCHAR2(30), "PO_NO" NUMBER(15, 0), "PO_SER" NUMBER(38, 0),
 "GRN_NO" NUMBER(15, 0), "GRN_SER" NUMBER(38, 0), "USE_ATTCH" NUMBER(1, 0), "REC_ATTCH"
 NUMBER(10, 0), "DIS_AMT_NOT_EFFECT" NUMBER, "ADD_DIS_AMT_MST" NUMBER, "ADD_DIS_AMT_DTL"
 NUMBER, "I_LENGTH" NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER,
 "POST_CODE" VARCHAR2(10), "UNIT_SIZE" NUMBER, "U_QTY" NUMBER, "GR_REF" VARCHAR2(250),
 "DOC_TYPE" NUMBER(5, 0), "DOC_SEQUENCE_PO" NUMBER, "PO_ORDER_NO" VARCHAR2(30),
 "PO_ORDER_SER" VARCHAR2(60), "WT_QTY" NUMBER, "WT_UNT" VARCHAR2(10), "SERVICE_ITM"
 NUMBER(1, 0), "FREE_QTY_PROFT" NUMBER, "I_PRICE_VAT" NUMBER, "CNTRCT_NO" VARCHAR2(60),
 "CNTNR_NO" VARCHAR2(30), "CNTRCT_SER" VARCHAR2(60), "CNTRCT_BTCH_NO" NUMBER(30, 0),
 "FREIGHT_NO" VARCHAR2(30), "FREIGHT_SER" VARCHAR2(60), "FREIGHT_DOC_SEQUENCE" NUMBER(38,
 0), "OTHR_AMT_DISC" NUMBER, "VAT_AMT_OTHR" NUMBER, "DOC_NO_REF" NUMBER(15, 0),
 "DOC_SER_REF" NUMBER(38, 0), "DOC_TYP_REF" NUMBER(5, 0), "DOC_SEQUENCE_REF" NUMBER(38,
 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "ARGMNT_NO" NUMBER, "OTHR_AMT_ITM"
 NUMBER, "PKG_UNT" VARCHAR2(10), "PKG_UNT_SIZE" NUMBER(10, 0), "PKG_QTY" NUMBER,
 "PKG_LENGTH" NUMBER, "PKG_WIDTH" NUMBER, "PKG_HEIGHT" NUMBER, "PKG_SIZE" NUMBER,
 "PKG_WEIGHT" NUMBER, "UP_CNT" NUMBER(10, 0), "SALE_PRICE" NUMBER, "FIELD_DTL1"
 VARCHAR2(60), "FIELD_DTL2" VARCHAR2(60), "FIELD_DTL3" VARCHAR2(60), "FIELD_DTL4"
 VARCHAR2(60), "FIELD_DTL5" VARCHAR2(60), "FIELD_DTL6" VARCHAR2(60), "FIELD_DTL7"
 VARCHAR2(60), "FIELD_DTL8" VARCHAR2(60), "FIELD_DTL9" VARCHAR2(60), "FIELD_DTL10"
 VARCHAR2(60), "BARCODE_PRNT" NUMBER(1, 0), "LAST_INCOME_PRICE" NUMBER, "ACTUL_QTY"
 NUMBER, "LOS_QTY" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_DATA_PI" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_RT_BILL_MST" ("RT_BILL_DOC_TYPE" NUMBER(2, 0) NOT NULL ENABLE,
 "RT_BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "RT_BILL_SER" NUMBER(38, 0) NOT NULL ENABLE,
 "P_YEAR" NUMBER, "RT_BILL_DATE" DATE NOT NULL ENABLE, "RT_BILL_CURRENCY" VARCHAR2(7) NOT
 NULL ENABLE, "RT_BILL_RATE" NUMBER, "STOCK_RATE" NUMBER, "C_CODE" VARCHAR2(15), "C_NAME"
 VARCHAR2(100), "A_CODE" VARCHAR2(30), "CHEQUE_NO" NUMBER(20, 0), "CHEQUE_AMT" NUMBER,
 "CHEQUE_DUE_DATE" DATE, "RT_BILL_DUE_DATE" DATE, "RT_BILL_POST" NUMBER(1, 0), "DISC_AMT"
 NUMBER, "DISC_AMT_MST" NUMBER, "DISC_AMT_DTL" NUMBER, "DISC_AMT_MST_VAT" NUMBER,
 "VAT_AMT_DISC_MST" NUMBER, "BILL_AMT" NUMBER, "VAT_AMT" NUMBER, "OTHR_AMT" NUMBER,
 "W_CODE" NUMBER(10, 0), "R_CODE" NUMBER(10, 0), "CASH_NO" NUMBER(10, 0), "CC_CODE"
 VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "CASH_AC_FCC" VARCHAR2(30),
 "CASH_NO_FCC" NUMBER(10, 0), "REP_CODE" VARCHAR2(15), "EMP_NO" NUMBER(10, 0), "SR_TYPE"
 NUMBER(5, 0), "COMM_PER" NUMBER, "REF_NO" VARCHAR2(15), "A_DESC" VARCHAR2(1000),
 "ATTACH_CNT" NUMBER(3, 0), "RETURN_RES" VARCHAR2(250), "PROCESSED" NUMBER(1, 0),
 "PR_REP" NUMBER(10, 0), "PREV_YEAR" NUMBER(4, 0), "CLASSIFY_NO" NUMBER(10, 0),
 "CLASSIFY_SER" NUMBER(38, 0), "RT_BILL_PY" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0),
 "DISC_AMT_AFTR_VAT" NUMBER, "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC" VARCHAR2(500),
 "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "W_CODE_BILL" NUMBER(10, 0),
 "CC_CODE_BILL" VARCHAR2(30), "REP_CODE_BILL" VARCHAR2(15), "RETURN_TYPE" NUMBER(1, 0),
 "PAID_RT_BILL" NUMBER(1, 0), "PAID_U_ID" NUMBER(5, 0), "PAID_DATE" DATE,
 "REC_INV_RT_BILL" NUMBER(1, 0), "REC_INV_U_ID" NUMBER(5, 0), "REC_INV_DATE" DATE,
 "STAND_BY" NUMBER(1, 0), "NOTE_NO" VARCHAR2(30), "DRIVER_NO" NUMBER(10, 0), "DOC_BRN_NO"
 NUMBER(6, 0), "RES_TYP" NUMBER(5, 0), "PRM_CODE" VARCHAR2(15), "DOC_NO_PDA" NUMBER(15,
 0), "PDA_NM" VARCHAR2(50), "INSRNCE_CMP_NO" NUMBER(10, 0), "INSRNCE_BNF_NO" NUMBER(5, 0)
, "INSRNCE_PRSON_NM" VARCHAR2(100), "INSRNCE_CARD_NO" VARCHAR2(60),
 "INSRNCE_CARD_NO_FMLY" VARCHAR2(60), "INSRNCE_RLTN_TYP" NUMBER(2, 0), "INSRNCE_CLSS_NO"
 VARCHAR2(10), "INSRNCE_CSH_AMT" NUMBER, "COMM_AMT_DTL" NUMBER, "CST_GCC" NUMBER(1, 0),
 "EXPORT" NUMBER(1, 0), "VAT_AMT_OTHR" NUMBER, "ADD_DISC_AMT_MST" NUMBER,
 "ADD_DISC_AMT_DTL" NUMBER, "OTHR_AMT_DISC" NUMBER, "WITHOUT_VAT" NUMBER(1, 0),
 "RT_VAT_PRD_TYP" NUMBER(1, 0), "C_TEL" VARCHAR2(20), "C_CODE_CSH" VARCHAR2(15),
 "POINT_RPLC_AMT" NUMBER, "POINT_TYP_NO" NUMBER(5, 0), "POINT_CNT" NUMBER(5, 0),
 "POINT_RPLC_CNT" NUMBER(5, 0), "CREDIT_CARD" NUMBER(1, 0), "CR_CARD_NO" NUMBER(5, 0),
 "CR_CARD_AMT" NUMBER, "CR_CARD_COMM_PER" NUMBER, "CR_CARD_NO_SCND" NUMBER(5, 0),
 "CR_CARD_AMT_SCND" NUMBER, "CR_CARD_COMM_PER_SCND" NUMBER, "CR_CARD_NO_THRD" NUMBER(5,
 0), "CR_CARD_AMT_THRD" NUMBER, "CR_CARD_COMM_PER_THRD" NUMBER, "CLC_TYP_NO_TAX" NUMBER(5
, 0), "AC_AMT" NUMBER, "FIELD1" VARCHAR2(250), "FIELD2" VARCHAR2(250), "FIELD3"
 VARCHAR2(250), "FIELD4" VARCHAR2(250), "FIELD5" VARCHAR2(250), "FIELD6" VARCHAR2(250),
 "FIELD7" VARCHAR2(250), "FIELD8" VARCHAR2(250), "FIELD9" VARCHAR2(250), "FIELD10"
 VARCHAR2(250), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(10, 0), "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID"
 NUMBER(5, 0), "UNPOST_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "PTNT_NO" VARCHAR2(15),
 "DCTR_NO" VARCHAR2(15), "PTNT_TYP" NUMBER(1, 0), "DOC_NO_ADMSON" NUMBER(15, 0),
 "DOC_SRL_ADMSON" NUMBER(38, 0), "AC_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30),
 "AC_DTL_TYP" NUMBER(2, 0), "PYMNT_AC" NUMBER, "INSRNCE_LOAD_PER" NUMBER,
 "DOC_SER_EXTRNL" VARCHAR2(256), "CNCL_FLG" NUMBER(1, 0), "CLC_VAT_PRICE_TYP" NUMBER(1,
 0), "COL_NO" NUMBER(10, 0), "RMS_RT_BILL_DOC_TYPE" NUMBER(2, 0), "RMS_FREE_FLG" NUMBER(1
, 0), "HRS_DOC_NO_REF" NUMBER, "HRS_DOC_TYPE_REF" NUMBER, "HRS_DOC_SER_REF" NUMBER,
 "RT_BILL_TYP" NUMBER(1, 0), "CLC_TAX_FREE_QTY_FLG" NUMBER(1, 0), "INSRNCE_ADD_LMT_MST"
 NUMBER, "AD_DATE_CLK" DATE, "INSRNCE_ADD_LMT_DOC" NUMBER, "INSRNCE_ADD_LMT_DTL" NUMBER,
 "INSRNCE_LMT_AMT_LOC_DOC" NUMBER, "CR_CARD_DSC" VARCHAR2(500), "CR_CARD_DSC_SCND"
 VARCHAR2(500), "CR_CARD_DSC_THRD" VARCHAR2(500), "CR_CARD_CST_NO_THRD" VARCHAR2(60),
 "CR_CARD_CST_NO_SCND" VARCHAR2(60), "CR_CARD_CST_NO" VARCHAR2(60),
 "CR_CARD_DOC_NO_REF_SCND" NUMBER(15, 0), "CR_CARD_DOC_NO_REF" NUMBER(15, 0),
 "CR_CARD_DOC_NO_REF_THRD" NUMBER(15, 0), "CR_CARD_MAX_COMM_AMT" NUMBER,
 "CR_CARD_MAX_COMM_AMT_SCND" NUMBER, "CR_CARD_MAX_COMM_AMT_THRD" NUMBER, "DOC_M_SQ"
 NUMBER, "WEB_SRVC_TRNSFR_DATA_FLG" NUMBER(1, 0), "WEB_SRVC_UUID" VARCHAR2(100))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_RTBI" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_RT_BILL_DTL" ("RT_BILL_DOC_TYPE" NUMBER(2, 0) NOT NULL ENABLE,
 "RT_BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "RT_BILL_SER" NUMBER(38, 0) NOT NULL ENABLE,
 "BILL_NO" NUMBER(15, 0), "BILL_DOC_TYPE" NUMBER(2, 0), "BILL_SER" NUMBER(38, 0),
 "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "I_QTY" NUMBER, "ITM_UNT" VARCHAR2(10) NOT NULL
 ENABLE, "P_SIZE" NUMBER NOT NULL ENABLE, "P_QTY" NUMBER NOT NULL ENABLE, "I_PRICE"
 NUMBER, "STK_COST" NUMBER, "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "V_CODE" VARCHAR2(15), "SR_TYPE" NUMBER(5, 0),
 "EXPIRE_DATE" DATE NOT NULL ENABLE, "BATCH_NO" VARCHAR2(30) NOT NULL ENABLE, "FREE_QTY"
 NUMBER, "SERVICE_ITEM" NUMBER(1, 0), "DIS_PER" NUMBER(20, 17), "DIS_AMT" NUMBER,
 "DIS_AMT_MST" NUMBER, "DIS_AMT_DTL" NUMBER, "DIS_AMT_DTL_VAT" NUMBER, "DIS_AMT_MST_VAT"
 NUMBER, "VAT_AMT_DIS_DTL_VAT" NUMBER, "VAT_AMT_AFTR_DIS" NUMBER, "VAT_AMT_BFR_DIS"
 NUMBER, "VAT_AMT_DIS_MST_VAT" NUMBER, "DIS_AMT_AFTR_VAT" NUMBER, "VAT_PER" NUMBER,
 "VAT_AMT" NUMBER, "OTHR_AMT" NUMBER, "RET_QTY" NUMBER, "RET_FREE_QTY" NUMBER,
 "USE_SERIALNO" NUMBER(1, 0), "DIS_AFTR_VAT_MST" NUMBER, "SI_RCRD_NO" NUMBER(10, 0),
 "RCRD_NO" NUMBER(10, 0) NOT NULL ENABLE, "RCRD_NO_REF" NUMBER(10, 0), "DOC_SEQUENCE"
 NUMBER(38, 0) NOT NULL ENABLE, "DOC_SEQUENCE_SI" NUMBER(38, 0), "ITEM_DESC"
 VARCHAR2(1000), "BARCODE" VARCHAR2(30), "EXTERNAL_POST" NUMBER(5, 0), "RT_BILL_PY"
 NUMBER(1, 0), "USE_ATTCH" NUMBER(1, 0), "REC_ATTCH" NUMBER(10, 0), "DIS_PER2" NUMBER,
 "DIS_AMT_DTL2" NUMBER, "DIS_PER3" NUMBER, "DIS_AMT_DTL3" NUMBER, "I_PRICE_VAT" NUMBER,
 "I_LENGTH" NUMBER, "I_WIDTH" NUMBER, "I_HEIGHT" NUMBER, "I_NUMBER" NUMBER, "POST_CODE"
 VARCHAR2(10), "WT_UNT" VARCHAR2(10), "WT_QTY" NUMBER, "FIELD_DTL1" VARCHAR2(60),
 "FIELD_DTL2" VARCHAR2(60), "FIELD_DTL3" VARCHAR2(60), "INSRNCE_LOAD_PER" NUMBER,
 "INSRNCE_LOAD_AMT" NUMBER, "INSRNCE_ADD_LMT" NUMBER, "EMP_NO" NUMBER(10, 0),
 "DOC_TYPE_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER,
 "SUB_C_CODE" VARCHAR2(15), "COMM_PER" NUMBER, "COMM_AMT_DTL" NUMBER, "ARGMNT_NO" NUMBER,
 "USED_ITM" NUMBER(1, 0), "VAT_AMT_OTHR" NUMBER, "ADD_DIS_AMT_MST" NUMBER,
 "ADD_DIS_AMT_DTL" NUMBER, "OTHR_AMT_DISC" NUMBER, "QT_PRM_NO" NUMBER(15, 0),
 "QT_PRM_SER" NUMBER(38, 0), "QT_PRM_RCRD_NO" NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT
 NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "DIS_AMT_DTL2_VAT" NUMBER, "DIS_AMT_DTL3_VAT"
 NUMBER, "VAT_AMT_DIS_DTL2_VAT" NUMBER, "VAT_AMT_DIS_DTL3_VAT" NUMBER, "RET_QTY_YR"
 NUMBER, "RET_FREE_QTY_YR" NUMBER, "INSRNCE_ADD_LMT_MST" NUMBER, "FREE_TYP" NUMBER(1, 0))
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_RTBI" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_VNDR_ACCNT" ("RCRD_NO" NUMBER, "V_CODE" VARCHAR2(30), "A_CODE"
 VARCHAR2(30), "INACTIVE" NUMBER(1, 0), "INACTIVE_DATE" DATE, "INACTIVE_RES"
 VARCHAR2(250), "INACTIVE_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "AD_U_ID" NUMBER(5, 0),
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(6, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "VENDOR_GROUP" ("V_GROUP_CODE" NUMBER(10, 0), "V_GROUP_A_NAME" VARCHAR2(100)
 NOT NULL ENABLE, "V_GROUP_E_NAME" VARCHAR2(100), "V_A_CODE" VARCHAR2(30) NOT NULL ENABLE
, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE,
 "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "VENDOR_CLASS" ("V_CLASS" NUMBER(3, 0), "V_CLASS_NAME" VARCHAR2(60) NOT NULL
 ENABLE, "V_CLASS_E_NAME" VARCHAR2(60), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "VENDOR_CURR" ("V_CODE" VARCHAR2(15), "A_CY" VARCHAR2(7), "INACTIVE"
 NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(10, 0), "MAX_LMT_AMT_PR" NUMBER, "MAX_LMT_AMT_PO" NUMBER,
 "CUR_DFLT" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_AP_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_VENDOR_BANK" ("V_CODE" VARCHAR2(15), "BANK_NO" NUMBER(10, 0),
 "BANK_ACC" VARCHAR2(30), "BANK_NAME" VARCHAR2(60), "SWIFT_CODE" VARCHAR2(30), "CNTRY_NO"
 NUMBER(4, 0), "CITY_NO" NUMBER(10, 0), "BNFCRY_NAME" VARCHAR2(60), "BANK_KEY"
 VARCHAR2(30), "IBAN_NO" VARCHAR2(30), "A_CY" VARCHAR2(7), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_INPT" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_VENDOR_DEGREE" ("V_DEGREE" NUMBER(5, 0), "V_DEGREE_A_NAME"
 VARCHAR2(100) NOT NULL ENABLE, "V_DEGREE_E_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_VNDR_CLAIM_MST" ("BRN_NO" NUMBER(6, 0), "DOC_NO" NUMBER(15, 0),
 "DOC_SER" NUMBER(38, 0), "DOC_DATE" DATE, "V_CODE" VARCHAR2(30), "A_CY" VARCHAR2(7),
 "F_DATE" DATE, "T_DATE" DATE, "REF_NO" VARCHAR2(15), "DOC_DSC" VARCHAR2(500),
 "PROCESSED" NUMBER(1, 0), "DOC_AMT" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "AD_TRMNL_NM" VARCHAR2(50), "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_TRMNL_NM"
 VARCHAR2(50), "PR_REP" NUMBER(6, 0), "UP_CNT" NUMBER(10, 0), "BRN_USR" NUMBER(3, 0),
 "BRN_YEAR" NUMBER(4, 0), "CMP_NO" NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_VNDR_CLAIM_DTL" ("BRN_NO" NUMBER(6, 0), "DOC_NO" NUMBER(15, 0),
 "DOC_SER" NUMBER(38, 0), "BILL_NO" NUMBER(15, 0), "BILL_SER" NUMBER, "BILL_TYP" NUMBER(1
, 0), "BILL_DATE" DATE, "BILL_AMT" NUMBER, "DISC_AMT" NUMBER, "NET_AMT" NUMBER, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50), "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_TRMNL_NM" VARCHAR2(50), "UP_CNT" NUMBER(10, 0), "OTHR_AMT" NUMBER,
 "VAT_AMT" NUMBER, "NET_BILL_AMT" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AP_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_VNDR_ITM" ("I_CODE" VARCHAR2(30), "V_CODE" VARCHAR2(15), "I_PACKING"
 NUMBER(10, 0), "VNDR_PRICE" NUMBER, "MAIN_VNDR" NUMBER(1, 0), "A_CY" VARCHAR2(7),
 "ITM_UNT" VARCHAR2(10), "P_SIZE" NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "I_CODE_VNDR" VARCHAR2(30), "UP_CNT" NUMBER(10,
 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "UNT_VNDR" VARCHAR2(10),
 "ITM_MIN_QTY" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_AP_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "OTHER_CHARGES" ("BILL_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "BILL_DOC_TYPE"
 NUMBER(2, 0) NOT NULL ENABLE, "BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "BILL_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "DOC_DATE" DATE, "SC_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "A_CODE" VARCHAR2(30) NOT NULL ENABLE, "A_CY" VARCHAR2(7) NOT NULL ENABLE, "AC_RATE"
 NUMBER NOT NULL ENABLE, "PER" NUMBER, "AMT" NUMBER, "INV_ITEM" NUMBER(1, 0), "RCRD_NO"
 NUMBER(10, 0), "BILL_PY" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0), "VAT_AMT" NUMBER,
 "VAT_PER" NUMBER, "SC_AMT" NUMBER, "SC_AC_RATE" NUMBER, "SC_A_CY" VARCHAR2(7), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_BILLS" LOGGING NOCOMPRESS;

CREATE TABLE "OTHER_CHARGES_ITEMS" ("BILL_TYPE" NUMBER(5, 0), "BILL_DOC_TYPE" NUMBER(2,
 0), "BILL_NO" NUMBER(15, 0), "BILL_SER" NUMBER(38, 0) NOT NULL ENABLE, "DOC_DATE" DATE,
 "SC_NO" NUMBER(3, 0), "A_CODE" VARCHAR2(30), "A_CY" VARCHAR2(7), "AC_RATE" NUMBER, "PER"
 NUMBER, "AMT" NUMBER, "W_CODE" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "RCRD_NO" NUMBER(10, 0), "SI_TYPE" NUMBER(5, 0),
 "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "ITM_UNT" VARCHAR2(10) NOT NULL ENABLE, "P_SIZE"
 NUMBER NOT NULL ENABLE, "BILL_PY" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0), "UNIT_AMT"
 NUMBER, "POST_CODE" VARCHAR2(10), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_BILLS" LOGGING
 NOCOMPRESS;

