CREATE TABLE "ACCOUNT" ("A_CODE" VARCHAR2(30), "A_NAME" VARCHAR2(100) NOT NULL ENABLE,
 "A_NAME_ENG" VARCHAR2(100), "A_LEVEL" NUMBER(5, 0) CONSTRAINT "AC_NN_A_LEV" NOT NULL
 ENABLE, "A_PARENT" VARCHAR2(30) CONSTRAINT "AC_NN_A_PAR" NOT NULL ENABLE, "A_S_M"
 NUMBER(5, 0) CONSTRAINT "AC_NN_ASM" NOT NULL ENABLE, "A_GROUPING" NUMBER(5, 0),
 "A_REPORT" NUMBER(5, 0) CONSTRAINT "AC_NN_AREP" NOT NULL ENABLE, "A_ANALYSIS" NUMBER(10,
 0), "CLASS_NO" NUMBER(5, 0), "AC_CLOSE" NUMBER(1, 0), "DR" NUMBER(1, 0), "CURDIF_CODE"
 VARCHAR2(30), "USE_CC" NUMBER(1, 0), "USE_PJ" NUMBER(1, 0), "CONN_PRD" NUMBER(1, 0),
 "FAV_AC" NUMBER(1, 0), "FLOW_TYPE" NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(250),
 "INACTIVE_DATE" DATE, "CONF_LAST_DATE" DATE, "AC_OP_NO" NUMBER(15, 0), "AC_EXP_TYPE"
 NUMBER(2, 0), "USE_EXP_BRN" NUMBER(1, 0), "IMP_XLS" NUMBER(1, 0), "AC_DTL_TYP" NUMBER(2,
 0), "USE_ACTV" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5,
 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "USE_TDS_FLG" NUMBER(1, 0),
 "ADVNC_EXPNS_RVNU_FLG" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "ACCOUNT_CURR" ("A_CODE" VARCHAR2(30), "A_CY" VARCHAR2(7), "INACTIVE"
 NUMBER(1, 0), "USED" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "ACCOUNT_GROUPING" ("GROUP_NO" NUMBER(5, 0), "GROUP_NAME" VARCHAR2(100) NOT
 NULL ENABLE, "GROUP_E_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "ACCOUNT_REPORT_TYPE" ("REPORT_TYPE" NUMBER(5, 0), "REPORT_NAME"
 VARCHAR2(60) NOT NULL ENABLE, "REPORT_E_NAME" VARCHAR2(60), "REPORT_BS" NUMBER(1, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "ACCOUNT_TYPES" ("ACCOUNT_TYPE" NUMBER(5, 0), "ACCOUNT_NAME" VARCHAR2(60)
 NOT NULL ENABLE, "ACCOUNT_E_NAME" VARCHAR2(60), "AFFECTED_BY_TRANS" NUMBER(1, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_VCHR_MST_ACCNT" ("RCRD_NO" NUMBER(10, 0) NOT NULL ENABLE, "VCHR_TYP"
 NUMBER(1, 0) NOT NULL ENABLE, "VCHR_PAY_TYP" NUMBER(1, 0) NOT NULL ENABLE, "CASH_NO"
 NUMBER(10, 0) NOT NULL ENABLE, "DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SRL"
 NUMBER(38, 0), "AC_CODE" VARCHAR2(30) NOT NULL ENABLE, "AC_CODE_DTL" VARCHAR2(30),
 "AC_CODE_DTL_SUB" VARCHAR2(30), "AC_DTL_TYP" NUMBER(1, 0) NOT NULL ENABLE, "CUR_CODE"
 VARCHAR2(7) NOT NULL ENABLE, "CUR_RATE" NUMBER, "AMT_L" NUMBER, "AMT_F" NUMBER,
 "DOC_DSC" VARCHAR2(750), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "REP_CODE" VARCHAR2(15), "COL_NO" NUMBER(10, 0), "DOC_SEQ" NUMBER(38, 0),
 "DOC_BRN_NO" NUMBER(6, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0)
 NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0)
, "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_VCHR" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_VCHR_TYP_ACNT" ("V_TYPE" NUMBER(5, 0), "V_TYPE_NO" NUMBER(2, 0),
 "AC_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING
 NOCOMPRESS;

CREATE TABLE "GLS_VCHR_TYP_PRV" ("V_TYP" NUMBER(4, 0), "V_TYP_NO" NUMBER(4, 0), "U_ID"
 NUMBER(5, 0), "ADD_FLAG" NUMBER(1, 0), "VIEW_FLAG" NUMBER(1, 0), "AD_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "DETAIL_JOURNAL_V" ("JV_TYPE" NUMBER(4, 0) NOT NULL ENABLE, "J_DOC_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "J_SER" NUMBER(38, 0), "A_CODE" VARCHAR2(30) NOT NULL
 ENABLE, "AC_CODE_DTL" VARCHAR2(30), "AC_CODE_DTL_SUB" VARCHAR2(30), "AC_DTL_TYP"
 NUMBER(2, 0), "A_CY" VARCHAR2(7) NOT NULL ENABLE, "J_DESC" VARCHAR2(1000), "J_AMT"
 NUMBER, "J_AMT_F" NUMBER, "AC_RATE" NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15)
, "ACTV_NO" VARCHAR2(15), "C_CODE" VARCHAR2(15), "V_CODE" VARCHAR2(15), "REP_CODE"
 VARCHAR2(15), "COL_NO" NUMBER(10, 0), "LC_NO" VARCHAR2(15), "GR_NO" VARCHAR2(15),
 "CSH_BNK_NO" NUMBER(10, 0), "RCRD_NO" NUMBER(10, 0), "RCRD_NO_ORD" NUMBER(10, 0),
 "DOC_TYPE_REF" NUMBER(5, 0), "DOC_JV_TYPE_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0),
 "DOC_SER_REF" NUMBER(38, 0), "DOC_DUE_DATE" DATE, "BILL_NO" NUMBER(15, 0), "BILL_SER"
 NUMBER(38, 0), "CASHIER_NO" NUMBER(5, 0), "I_NO" NUMBER(15, 0), "WO_NO" NUMBER(15, 0),
 "WO_SER" NUMBER(38, 0), "REF_NO" VARCHAR2(15), "CNTRCT_NO" NUMBER(15, 0), "CNTRCT_SRL"
 NUMBER, "CNTRCT_BTCH" NUMBER(6, 0), "CHEQUE_NO" NUMBER(20, 0), "NOTE_NO" VARCHAR2(30),
 "DOC_SEQUENCE" NUMBER(38, 0), "EXTERNAL_POST" NUMBER(5, 0), "DOC_BRN_NO" NUMBER(6, 0),
 "NOTE" VARCHAR2(150), "DOC_SEQUENCE_REF" NUMBER(38, 0), "RCRD_NO_REF" NUMBER(10, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL
 ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "CLC_TYP_NO_TAX" NUMBER(5, 0), "TAX_PRCNT" NUMBER, "TAX_AMT"
 NUMBER, "HRS_DOC_TYP_REF" NUMBER, "HRS_DOC_SRL_REF" NUMBER, "HRS_DOC_NO_REF" NUMBER,
 "FLD1" VARCHAR2(60), "FLD2" VARCHAR2(60), "FLD3" VARCHAR2(60), "FLD4" VARCHAR2(60),
 "FLD5" VARCHAR2(60))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 983040 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_DATA_JV" LOGGING NOCOMPRESS;

CREATE TABLE "DETAIL_JOURNAL_V_BR" ("JV_TYPE" NUMBER(4, 0) NOT NULL ENABLE, "J_DOC_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "J_SER" NUMBER(38, 0), "A_CODE" VARCHAR2(30) NOT NULL
 ENABLE, "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7) NOT
 NULL ENABLE, "J_DESC" VARCHAR2(1000), "J_AMT" NUMBER, "J_AMT_F" NUMBER, "AC_RATE" NUMBER
, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "C_CODE"
 VARCHAR2(15), "V_CODE" VARCHAR2(15), "REP_CODE" VARCHAR2(15), "COL_NO" NUMBER(10, 0),
 "LC_NO" VARCHAR2(15), "GR_NO" VARCHAR2(15), "CSH_BNK_NO" NUMBER(10, 0), "RCRD_NO"
 NUMBER(10, 0), "RCRD_NO_ORD" NUMBER(10, 0), "DOC_TYPE_REF" NUMBER(5, 0),
 "DOC_JV_TYPE_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0),
 "DOC_DUE_DATE" DATE, "BILL_NO" NUMBER(15, 0), "BILL_SER" NUMBER(38, 0), "CASHIER_NO"
 NUMBER(5, 0), "I_NO" NUMBER(15, 0), "WO_NO" NUMBER(15, 0), "WO_SER" NUMBER(38, 0),
 "REF_NO" VARCHAR2(15), "CHEQUE_NO" NUMBER(20, 0), "NOTE_NO" VARCHAR2(30), "DOC_SEQUENCE"
 NUMBER(38, 0), "EXTERNAL_POST" NUMBER(5, 0), "DOC_BRN_NO" NUMBER(6, 0), "NOTE"
 VARCHAR2(150), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(10, 0), "CMP_NO" NUMBER(3, 0), "BRN_NO" NUMBER(6, 0), "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "CNTRCT_NO" NUMBER(15, 0), "CNTRCT_SRL" NUMBER,
 "CNTRCT_BTCH" NUMBER(6, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_JV"
 LOGGING NOCOMPRESS;

CREATE TABLE "MASTER_JOURNAL_V" ("JV_TYPE" NUMBER(4, 0) NOT NULL ENABLE, "J_DOC_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "J_SER" NUMBER(38, 0), "J_POST" NUMBER(1, 0), "J_DATE"
 DATE NOT NULL ENABLE, "BATCH_VAL" NUMBER, "REF_NO" VARCHAR2(15), "REVRS_JRNL" NUMBER(1,
 0), "PERIODICAL_JRNL" NUMBER(1, 0), "CASH_RESERVE" NUMBER(1, 0), "STAND_BY" NUMBER(1, 0)
, "LINK_USE" NUMBER(1, 0), "ATTACH_NO" NUMBER(3, 0), "BEN_NAME" VARCHAR2(150), "REC_NAME"
 VARCHAR2(150), "T_DESC" VARCHAR2(1000), "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC"
 VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "PR_REP" NUMBER(10,
 0), "CLS_ZERO_AC_BLNC" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0), "AD_U_ID" NUMBER(5,
 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE"
 DATE, "FIELD1" VARCHAR2(60), "FIELD2" VARCHAR2(60), "FIELD3" VARCHAR2(60), "FIELD4"
 VARCHAR2(60), "FIELD5" VARCHAR2(60), "FIELD6" VARCHAR2(60), "FIELD7" VARCHAR2(60),
 "FIELD8" VARCHAR2(60), "FIELD9" VARCHAR2(60), "FIELD10" VARCHAR2(60), "CMP_NO" NUMBER(3,
 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0),
 "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_JV" LOGGING
 NOCOMPRESS;

CREATE TABLE "MASTER_JOURNAL_V_BR" ("JV_TYPE" NUMBER(4, 0) NOT NULL ENABLE, "J_DOC_NO"
 NUMBER(15, 0) NOT NULL ENABLE, "J_SER" NUMBER(38, 0), "J_POST" NUMBER(1, 0), "J_DATE"
 DATE NOT NULL ENABLE, "BATCH_VAL" NUMBER, "REF_NO" VARCHAR2(15), "REVRS_JRNL" NUMBER(1,
 0), "PERIODICAL_JRNL" NUMBER(1, 0), "CASH_RESERVE" NUMBER(1, 0), "STAND_BY" NUMBER(1, 0)
, "LINK_USE" NUMBER(1, 0), "ATTACH_NO" NUMBER(3, 0), "BEN_NAME" VARCHAR2(150), "REC_NAME"
 VARCHAR2(150), "T_DESC" VARCHAR2(1000), "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC"
 VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "PR_REP" NUMBER(10,
 0), "CLS_ZERO_AC_BLNC" NUMBER(1, 0), "EXTERNAL_POST" NUMBER(5, 0), "AD_U_ID" NUMBER(5,
 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE"
 DATE, "FIELD1" VARCHAR2(60), "FIELD2" VARCHAR2(60), "FIELD3" VARCHAR2(60), "FIELD4"
 VARCHAR2(60), "FIELD5" VARCHAR2(60), "FIELD6" VARCHAR2(60), "FIELD7" VARCHAR2(60),
 "FIELD8" VARCHAR2(60), "FIELD9" VARCHAR2(60), "FIELD10" VARCHAR2(60), "CMP_NO" NUMBER(3,
 0), "BRN_NO" NUMBER(6, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_JV" LOGGING
 NOCOMPRESS;

CREATE TABLE "OPEN_BAL" ("A_CODE" VARCHAR2(30) NOT NULL ENABLE, "AC_CODE_DTL"
 VARCHAR2(30), "AC_CODE_DTL_SUB" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY"
 VARCHAR2(7) NOT NULL ENABLE, "CC_CODE" VARCHAR2(30), "FROM_CC_CODE" VARCHAR2(30),
 "LC_NO" VARCHAR2(15), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "REP_CODE"
 VARCHAR2(15), "J_AMT" NUMBER, "J_AMT_F" NUMBER, "AC_RATE" NUMBER, "VERIFY" NUMBER(1, 0),
 "OB_PY" NUMBER(1, 0), "COL_NO" NUMBER(10, 0), "DOC_SEQUENCE" NUMBER(38, 0) NOT NULL
 ENABLE, "EXTERNAL_POST" NUMBER(5, 0), "F_BRN_NO" NUMBER(6, 0), "VALUE_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4
, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "REF_NO" VARCHAR2(15), "AC_DSC"
 VARCHAR2(1000))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 262144
 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "VOUCHERS" ("VOUCHER_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "VOUCHER_PAY_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "VOUCHER_NO" NUMBER(15, 0) NOT NULL ENABLE, "CASH_NO"
 NUMBER(10, 0) NOT NULL ENABLE, "A_CY" VARCHAR2(7) NOT NULL ENABLE, "V_SER" NUMBER(38, 0)
, "VOUCHER_DATE" DATE NOT NULL ENABLE, "CASH_AMT" NUMBER, "CASH_AMTF" NUMBER, "EX_RATE"
 NUMBER, "VOUCHER_POST" NUMBER(1, 0), "REF_NO" VARCHAR2(15), "REF_NAME" VARCHAR2(60),
 "A_DESC" VARCHAR2(1000), "REC_NAME" VARCHAR2(150), "STAND_BY" NUMBER(1, 0), "TRANSFER"
 NUMBER, "CHEQ_TYPE" NUMBER, "COL_NO" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "ATTACH_NO" NUMBER(3, 0), "PR_REP" NUMBER(10, 0),
 "COMM_PER" NUMBER(7, 4), "VOUCHER_NO_PY" NUMBER(15, 0), "VOUCHER_DATE_PY" DATE,
 "MOVE_CHEQ_PY" NUMBER(1, 0), "MOVE_CHEQ_CY" NUMBER(1, 0), "V_TYPE_NO" NUMBER(2, 0),
 "EXTERNAL_POST" NUMBER(5, 0), "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC" VARCHAR2(500),
 "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "FIELD1" VARCHAR2(60), "FIELD2"
 VARCHAR2(60), "FIELD3" VARCHAR2(60), "FIELD4" VARCHAR2(60), "FIELD5" VARCHAR2(60),
 "FIELD6" VARCHAR2(60), "FIELD7" VARCHAR2(60), "FIELD8" VARCHAR2(60), "FIELD9"
 VARCHAR2(60), "FIELD10" VARCHAR2(60), "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE,
 "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE" DATE, "DOC_SEQUENCE" NUMBER(38, 0),
 "DOC_BRN_NO" NUMBER(6, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5,
 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "DOC_SER_EXTRNL" VARCHAR2(256),
 "REP_CODE" VARCHAR2(15), "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_VCHR" LOGGING
 NOCOMPRESS;

CREATE TABLE "VOUCHERS_BR" ("VOUCHER_TYPE" NUMBER(1, 0) NOT NULL ENABLE,
 "VOUCHER_PAY_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "VOUCHER_NO" NUMBER(15, 0) NOT NULL
 ENABLE, "CASH_NO" NUMBER(10, 0) NOT NULL ENABLE, "A_CY" VARCHAR2(7) NOT NULL ENABLE,
 "V_SER" NUMBER(38, 0), "VOUCHER_DATE" DATE NOT NULL ENABLE, "CASH_AMT" NUMBER,
 "CASH_AMTF" NUMBER, "EX_RATE" NUMBER, "VOUCHER_POST" NUMBER(1, 0), "REF_NO" VARCHAR2(15)
, "REF_NAME" VARCHAR2(60), "A_DESC" VARCHAR2(1000), "REC_NAME" VARCHAR2(150), "STAND_BY"
 NUMBER(1, 0), "TRANSFER" NUMBER(1, 0), "CHEQ_TYPE" NUMBER, "COL_NO" NUMBER(10, 0),
 "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "ATTACH_NO"
 NUMBER(3, 0), "PR_REP" NUMBER(10, 0), "COMM_PER" NUMBER(7, 4), "VOUCHER_NO_PY" NUMBER(15
, 0), "VOUCHER_DATE_PY" DATE, "MOVE_CHEQ_PY" NUMBER(1, 0), "MOVE_CHEQ_CY" NUMBER(1, 0),
 "V_TYPE_NO" NUMBER(2, 0), "EXTERNAL_POST" NUMBER(5, 0), "AUDIT_REF" NUMBER(1, 0),
 "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE,
 "FIELD1" VARCHAR2(60), "FIELD2" VARCHAR2(60), "FIELD3" VARCHAR2(60), "FIELD4"
 VARCHAR2(60), "FIELD5" VARCHAR2(60), "FIELD6" VARCHAR2(60), "FIELD7" VARCHAR2(60),
 "FIELD8" VARCHAR2(60), "FIELD9" VARCHAR2(60), "FIELD10" VARCHAR2(60), "POST_U_ID"
 NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE" DATE,
 "DOC_SEQUENCE" NUMBER(38, 0), "DOC_BRN_NO" NUMBER(3, 0), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "CMP_NO"
 NUMBER(2, 0), "BRN_NO" NUMBER(3, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_VCHR" LOGGING NOCOMPRESS;

CREATE TABLE "VOUCHER_DETAIL" ("VOUCHER_TYPE" NUMBER(1, 0) CONSTRAINT "VD_NN_VTYPE" NOT
 NULL ENABLE, "VOUCHER_PAY_TYPE" NUMBER(1, 0) CONSTRAINT "VD_NN_VPAYTYPE" NOT NULL ENABLE
, "VOUCHER_NO" NUMBER(15, 0) CONSTRAINT "VD_NN_VNO" NOT NULL ENABLE, "CASH_NO" NUMBER(10,
 0) CONSTRAINT "VD_NN_VCASHNO" NOT NULL ENABLE, "V_SER" NUMBER(38, 0) CONSTRAINT
 "VD_NN_VSER" NOT NULL ENABLE, "A_CODE" VARCHAR2(30) NOT NULL ENABLE, "AC_CODE_DTL"
 VARCHAR2(30), "AC_CODE_DTL_SUB" VARCHAR2(30), "AC_CODE_DTL_SUB_END" VARCHAR2(30),
 "AC_CODE_DTL_SUB_DR_COMM" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7)
 NOT NULL ENABLE, "AC_DESC" VARCHAR2(1000), "AC_AMT" NUMBER, "AC_AMTF" NUMBER, "EX_RATE"
 NUMBER, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "C_CODE"
 VARCHAR2(15), "V_CODE" VARCHAR2(15), "REP_CODE" VARCHAR2(15), "CSH_BNK_NO" NUMBER(10, 0)
, "CHEQUE_NO" NUMBER(20, 0), "VALUE_DATE" DATE, "CHEQUE_POST" NUMBER(1, 0),
 "CHEQUE_VALUED" NUMBER(1, 0), "ENDRSMNT" NUMBER(1, 0), "NOTE_NO" VARCHAR2(30), "BANK_NO"
 NUMBER(10, 0), "BANK_NM" VARCHAR2(60), "BANK_BRN_NO" NUMBER(6, 0), "A_CODE_END"
 VARCHAR2(30), "C_CODE_END" VARCHAR2(15), "V_CODE_END" VARCHAR2(15), "RETURN_RES"
 VARCHAR2(250), "LC_NO" VARCHAR2(15), "CI_NO" NUMBER(15, 0), "CI_SER" NUMBER(38, 0),
 "HRS_PAY_NO" NUMBER(15, 0), "K_NO" NUMBER(15, 0), "K_SER" NUMBER(38, 0), "BILL_NO"
 NUMBER(15, 0), "BILL_SER" NUMBER(38, 0), "I_NO" NUMBER(15, 0), "WO_NO" NUMBER(15, 0),
 "WO_SER" NUMBER(38, 0), "CNTRCT_NO" NUMBER(15, 0), "CNTRCT_SRL" NUMBER, "CNTRCT_BTCH"
 NUMBER(6, 0), "REP_COMM_AMT" NUMBER, "REF_NO" VARCHAR2(15), "RCRD_NO" NUMBER(10, 0),
 "CONN_V_NO" NUMBER(15, 0), "CONN_V_SER" NUMBER(38, 0), "CONN_V_AMT" NUMBER,
 "EXTERNAL_POST" NUMBER(5, 0), "BLMNT_DATE" DATE, "DOC_SEQUENCE_REF" NUMBER(38, 0),
 "DOC_SEQUENCE" NUMBER(38, 0), "CASHIER_NO" NUMBER(5, 0), "NOTE" VARCHAR2(150),
 "AC_CODE_DR_COMM" VARCHAR2(30), "AC_CODE_DTL_DR_COMM" VARCHAR2(30), "AC_DTL_TYP_DR_COMM"
 NUMBER(2, 0), "OTR_AMT_L" NUMBER, "OTR_AMT_F" NUMBER, "AUDIT_REF" NUMBER(1, 0),
 "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE,
 "AC_DTL_TYP_END" NUMBER(2, 0), "AC_CODE_DTL_END" VARCHAR2(30), "DOC_TYPE_REF" NUMBER(5,
 0), "DOC_JV_TYPE_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38,
 0), "DOC_BRN_NO" NUMBER(6, 0), "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID"
 NUMBER(5, 0), "UNPOST_DATE" DATE, "F_CNTRCT_DATE" DATE, "T_CNTRCT_DATE" DATE,
 "F_CNTRCT_DATE_AH" VARCHAR2(10), "T_CNTRCT_DATE_AH" VARCHAR2(10), "CRD_CARD_NO" NUMBER(5
, 0), "CRD_ACODE_REC_LETTER" VARCHAR2(30), "CRD_COMM_AC" VARCHAR2(30),
 "CRD_COMM_CALC_TYP" NUMBER(1, 0), "CRD_COMM_PER" NUMBER, "CRD_VAT_COMM_PER" NUMBER,
 "CRD_DUE_PRD" NUMBER, "CRD_PRSSES_NO" NUMBER(20, 0), "FLD1" VARCHAR2(60), "FLD2"
 VARCHAR2(60), "FLD3" VARCHAR2(60), "FLD4" VARCHAR2(60), "FLD5" VARCHAR2(60), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "CRD_COMM_AMT_L" NUMBER,
 "CRD_VAT_COMM_AMT_L" NUMBER, "CRD_WTHDRW_AMT_L" NUMBER, "CRD_CARD_TYP" NUMBER(2, 0),
 "ENDRSMNT_DATE" DATE, "ENDRSMNT_POST" NUMBER(2, 0), "ENDRSMNT_POST_U_ID" NUMBER(5, 0),
 "ENDRSMNT_UNPOST_U_ID" NUMBER(5, 0), "ENDRSMNT_POST_DATE" DATE, "ENDRSMNT_UNPOST_DATE"
 DATE, "ENDRSMNT_AUDIT_REF_U_ID" NUMBER(5, 0), "ENDRSMNT_AUDIT_REF" NUMBER(1, 0),
 "ENDRSMNT_AUDIT_REF_DESC" VARCHAR2(500), "ENDRSMNT_UAUDIT_REF_DATE" DATE,
 "ENDRSMNT_AUDIT_REF_DATE" DATE, "CLC_TYP_NO_TAX" NUMBER(5, 0), "TAX_PRCNT" NUMBER,
 "TAX_AMT" NUMBER, "CRD_COMM_AMT" NUMBER, "CRD_VAT_COMM_AMT" NUMBER, "CRD_ACY_MAX_COMM"
 VARCHAR2(10), "CRD_WTHDRW_AMT" NUMBER, "CRD_PRCSS_MAX_COMM_AMT" NUMBER)  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 655360 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_VCHR" LOGGING
 NOCOMPRESS;

CREATE TABLE "EX_RATE" ("CUR_NO" NUMBER(4, 0) NOT NULL ENABLE, "CUR_CODE" VARCHAR2(7),
 "CUR_NAME" VARCHAR2(60) NOT NULL ENABLE, "CUR_E_NAME" VARCHAR2(60), "CUR_RATE" NUMBER,
 "CUR_RATE_POS" NUMBER, "CUR_FRACTION" VARCHAR2(10), "CUR_E_FRACTION" VARCHAR2(10), "L_F"
 NUMBER(1, 0) NOT NULL ENABLE, "STOCK_CUR" NUMBER(1, 0), "MAX_CUR_RATE" NUMBER(24, 9),
 "MIN_CUR_RATE" NUMBER(24, 9), "CUR_FRC_NO" NUMBER(1, 0) NOT NULL ENABLE, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL KEEP) TABLESPACE "IAS_STP"
 LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CURRENCY_VALUE" ("A_CY" VARCHAR2(7), "CUR_VALUE" NUMBER, "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP"
 LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PERIOD_EX_RATE" ("PRD_NO" NUMBER(3, 0), "A_CY" VARCHAR2(7), "CUR_RATE"
 NUMBER, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_PERIOD_EX_RATE_DAY" ("F_DATE" DATE, "T_DATE" DATE, "A_CY" VARCHAR2(7),
 "CUR_RATE" NUMBER, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CUR_DIFF_TMP" ("A_CODE" VARCHAR2(30), "CMP_NO" NUMBER(3, 0), "BRN_NO"
 NUMBER(6, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_TMP_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_TAX_ACC" ("A_CODE" VARCHAR2(30) NOT NULL ENABLE, "TAX_NO" NUMBER(5, 0)
 NOT NULL ENABLE, "AGNCY_NO" NUMBER(5, 0) NOT NULL ENABLE, "TAX_PRCNT" NUMBER NOT NULL
 ENABLE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50), "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(6, 0), "UP_CNT" NUMBER(10, 0),
 "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "AUD" ("U_ID" NUMBER(5, 0), "FORM_NO" NUMBER(5, 0), "AUDIT_MOD" NUMBER(1, 0)
, "AUDIT_DEL" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5,
 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_AUDIT" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_AUDIT_DOC" ("DOC_TYPE" NUMBER(5, 0) NOT NULL ENABLE, "JV_TYPE"
 NUMBER(10, 0) NOT NULL ENABLE, "DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "DOC_DATE" DATE NOT NULL ENABLE, "A_CODE" VARCHAR2(30),
 "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7), "AMT" NUMBER,
 "AMT_F" NUMBER, "AUDIT_SEQ" NUMBER, "FROM_U_ID" NUMBER(5, 0), "TO_U_ID" NUMBER(5, 0),
 "PROCESSED" NUMBER(1, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "DOC_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15), "C_CODE" VARCHAR2(15),
 "V_CODE" VARCHAR2(15), "DOC_TYPE_NO" NUMBER(10, 0), "DOC_POST" NUMBER(1, 0),
 "TRMNL_NAME" VARCHAR2(30), "AUDIT_REF_OLD" NUMBER(1, 0), "AUDIT_REF" NUMBER(1, 0),
 "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE,
 "W_CODE" NUMBER(10, 0), "CASH_NO" NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "AUD_U_ID" NUMBER(5, 0), "AUD_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0)
 NOT NULL ENABLE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AUD_ACC_DTL" ("AUD_NO" NUMBER(30, 0), "AUD_TYPE" NUMBER(2, 0),
 "DOC_TYPE" NUMBER(5, 0), "JV_TYPE" NUMBER(10, 0), "DOC_NO" NUMBER(15, 0), "DOC_SER"
 NUMBER(38, 0), "A_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2,
 0), "A_CY" VARCHAR2(7), "AC_RATE" NUMBER, "C_CODE" VARCHAR2(15), "V_CODE" VARCHAR2(15),
 "AMT" NUMBER, "AMTF" NUMBER, "AC_DESC" VARCHAR2(250), "CC_CODE" VARCHAR2(30), "LC_NO"
 VARCHAR2(15), "REF_NO" VARCHAR2(15), "REP_CODE" VARCHAR2(15), "CASH_NO" NUMBER(10, 0),
 "CHEQUE_NO" NUMBER(20, 0), "VALUE_DATE" DATE, "EXTERNAL_POST" NUMBER(5, 0), "TRMNL_NAME"
 VARCHAR2(100), "RCRD_NO" NUMBER(10, 0), "DOC_DUE_DATE" DATE, "BILL_NO" NUMBER(15, 0),
 "BILL_SER" NUMBER(38, 0), "I_NO" NUMBER(15, 0), "WO_NO" NUMBER(15, 0), "WO_SER"
 NUMBER(38, 0), "K_NO" NUMBER(15, 0), "K_SER" NUMBER(38, 0), "CMP_NO" NUMBER(3, 0) NOT
 NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "UP_CNT" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_AUDIT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_AUD_ACC_MST" ("AUD_NO" NUMBER(30, 0), "AUD_TYPE" NUMBER(2, 0),
 "DOC_TYPE" NUMBER(5, 0), "JV_TYPE" NUMBER(10, 0), "DOC_NO" NUMBER(15, 0), "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE, "A_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30),
 "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7), "EX_RATE" NUMBER, "AMT" NUMBER, "AMTF"
 NUMBER, "C_CODE" VARCHAR2(15), "V_CODE" VARCHAR2(15), "CC_CODE" VARCHAR2(30), "COL_NO"
 NUMBER(10, 0), "A_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15), "REF_NAME" VARCHAR2(60),
 "CASH_NO" NUMBER(10, 0), "CHEQ_TYPE" NUMBER(2, 0), "REC_NAME" VARCHAR2(150), "BEN_NAME"
 VARCHAR2(150), "STAND_BY" NUMBER(1, 0), "ATTACH_NO" NUMBER(3, 0), "REASON_DEL"
 VARCHAR2(250), "EXTERNAL_POST" NUMBER(5, 0), "PR_REP" NUMBER(10, 0), "UP_CNT" NUMBER(10,
 0), "U_ID" NUMBER(5, 0), "AUD_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE"
 DATE, "TRMNL_NAME" VARCHAR2(100), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_AUDIT" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_AUD_HIST" ("OPR_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "OPR_SER" NUMBER(15
, 0) NOT NULL ENABLE, "FORM_NO" NUMBER(5, 0), "TRMNL_NAME" VARCHAR2(100), "TAB_NM"
 VARCHAR2(30) NOT NULL ENABLE, "COL_NM" VARCHAR2(60) NOT NULL ENABLE, "OLD_VAL"
 VARCHAR2(1000), "NEW_VAL" VARCHAR2(1000), "COL_PK1" VARCHAR2(500), "COL_PK2"
 VARCHAR2(500), "COL_PK3" VARCHAR2(500), "AUD_U_ID" NUMBER(5, 0), "AUD_DATE" DATE,
 "CMP_NO" NUMBER(3, 0), "BRN_NO" NUMBER(6, 0), "BRN_USR" NUMBER(3, 0), "BRN_YEAR"
 NUMBER(4, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 3145728
 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_DATA_AUD_SYS" LOGGING NOCOMPRESS;

