CREATE TABLE "S_RPRT_USR_TMPLT_MST" ("FORM_NO" NUMBER(5, 0), "U_ID" NUMBER(5, 0),
 "TMPLT_NO" NUMBER(38, 0), "ORDR_NO" NUMBER(38, 0) NOT NULL ENABLE, "NOTES" VARCHAR2(500)
, "INACTIVE" NUMBER(1, 0) NOT NULL ENABLE, "INACTIVE_RES" VARCHAR2(150), "INACTIVE_U_ID"
 NUMBER(10, 0), "INACTIVE_DATE" DATE, "AD_U_ID" NUMBER(10, 0) NOT NULL ENABLE, "AD_DATE"
 DATE NOT NULL ENABLE, "AD_TRMNL_NM" VARCHAR2(50), "UP_U_ID" NUMBER(10, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(30, 0), "UP_TRMNL_NM" VARCHAR2(50), "TMPLT_NM" VARCHAR2(100) NOT
 NULL ENABLE, "DFLT_FLG" NUMBER(1, 0), "GNR_FOR_ALL_USR_FLG" NUMBER(1, 0))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING
 NOCOMPRESS;

CREATE TABLE "S_RPRT_USR_TMPLT_DTL" ("FORM_NO" NUMBER(5, 0), "U_ID" NUMBER(5, 0),
 "TMPLT_NO" NUMBER(38, 0), "BLK_NM" VARCHAR2(100), "ITM_NM" VARCHAR2(100), "VAL"
 VARCHAR2(4000), "SQ_NO" NUMBER(5, 0), "NOTES" VARCHAR2(500), "AD_U_ID" NUMBER(5, 0) NOT
 NULL ENABLE, "AD_DATE" DATE NOT NULL ENABLE, "AD_TRMNL_NM" VARCHAR2(50), "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "UP_TRMNL_NM" VARCHAR2(50)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PARA_GEN" ("PARA_NO" NUMBER(1, 0), "CC_AVAIL" NUMBER(1, 0) NOT NULL
 ENABLE, "CC_POST" NUMBER(1, 0) NOT NULL ENABLE, "USE_PROJECTS" NUMBER(1, 0) NOT NULL
 ENABLE, "USE_ACTVTY" NUMBER(1, 0) NOT NULL ENABLE, "TYPE_OF_POSTING" NUMBER(1, 0) NOT
 NULL ENABLE, "POST_DISC_PER_ITEMS" NUMBER(1, 0) NOT NULL ENABLE, "USE_EXCEL" NUMBER(1,
 0), "PATH_EXCEL" VARCHAR2(100), "USE_INDV_GL_SYSTEM" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_INDV_INV_SYSTEM" NUMBER(1, 0) NOT NULL ENABLE, "SP_PROGRAM" NUMBER(3, 0), "USE_VAT"
 NUMBER(1, 0) NOT NULL ENABLE, "ACTIVE_VAT_DATE" DATE, "USE_UNPOSTING" NUMBER(1, 0) NOT
 NULL ENABLE, "HEAD_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "CONN_DETER_TRMNL" NUMBER(1, 0)
 NOT NULL ENABLE, "CONN_NOT_MORE_ONE" NUMBER(1, 0) NOT NULL ENABLE, "USE_AUDIT_DOC"
 NUMBER(1, 0) NOT NULL ENABLE, "SHOW_ENGINE_REP" NUMBER(1, 0) NOT NULL ENABLE,
 "SHOW_PARAMTR_REP" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_XLSBTN_REP" NUMBER(1, 0) NOT NULL
 ENABLE, "LAST_UPDATE" DATE, "USE_VAT_PROFIT" NUMBER(1, 0), "VAT_PROFIT_PER" NUMBER,
 "MIN_PROFIT_AMT" NUMBER, "USE_BALANCED_CC" NUMBER(1, 0), "USE_BALANCED_BRN" NUMBER(1, 0)
, "INACTV_USR_FAIL_ENTR_CNT" NUMBER(2, 0), "MIN_USR_PWD_LEN" NUMBER(2, 0),
 "LAST_DATE_LGN" DATE, "MAX_POST_DATE" DATE, "PJ_POST" NUMBER(1, 0), "ACTV_POST" NUMBER(1
, 0), "EMP_NO_AUTO" NUMBER(1, 0) NOT NULL ENABLE, "EMP_NO_MAX_LEN" NUMBER(2, 0) NOT NULL
 ENABLE, "EMP_NO_MIN_LEN" NUMBER(2, 0) NOT NULL ENABLE, "EMP_PRV_TYP" NUMBER(1, 0) NOT
 NULL ENABLE, "RPRT_FRC_NO" NUMBER(1, 0), "USE_PRICE_INCLUDE_VAT" NUMBER(1, 0),
 "MOB_FILE_PATH" VARCHAR2(250), "VAT_PRD_TYP" NUMBER(1, 0),
 "NOT_ALLW_MORE_BRN_USR_LGHT_PRV" NUMBER(1, 0), "LST_NM_STRT_EMP_NM" NUMBER(1, 0),
 "NO_CHK_F_CC_CODE" NUMBER(1, 0), "AC_DTL_SEQ" NUMBER(2, 0), "TAX_PST_MTHD" NUMBER(2, 0),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "STRT_CRT_VIEW_YEAR" NUMBER(4, 0), "TAX_CODE_LNGTH" NUMBER(2, 0),
 "STRT_CRT_VIEW_YEAR_INV" NUMBER(4, 0), "EMP_NO_SQ_FLD" NUMBER(10, 0),
 "DFLT_EXP_DIR_PATH" VARCHAR2(255), "DFLT_EXP_DIR_PATH_DTL" VARCHAR2(4000), "WEB_DOC_LNK"
 VARCHAR2(4000), "BLNC_BRN_TYP" NUMBER(2, 0), "VAT_PST_MTHD" NUMBER(2, 0), "USE_TDS_FLG"
 NUMBER(1, 0), "MIN_USR_PWD_LETTER" NUMBER(2, 0), "MIN_USR_PWD_UPPER" NUMBER(2, 0),
 "MIN_USR_PWD_LOWER" NUMBER(2, 0), "MIN_USR_PWD_DIGIT" NUMBER(2, 0),
 "MIN_USR_PWD_SPECIAL" NUMBER(2, 0), "USE_CONN_SDFA" NUMBER(1, 0), "EMP_NO_SQ_TYP"
 NUMBER(1, 0), "USE_DOC_APPRVD_BY_USR_LVL" NUMBER(1, 0), "USE_SND_WEB_MSG" NUMBER(1, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL KEEP) TABLESPACE "IAS_STP"
 LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PARA_GL" ("PARA_NO" NUMBER(1, 0), "DOC_GEN_GL" NUMBER(1, 0) NOT NULL
 ENABLE, "ALLOW_DOC_DEL_NO" NUMBER(1, 0) NOT NULL ENABLE, "DATE_GEN_GL" NUMBER(1, 0) NOT
 NULL ENABLE, "DATE_SETTING_GL" NUMBER(1, 0) NOT NULL ENABLE, "A_CODE_LENGTH" NUMBER(2,
 0) NOT NULL ENABLE, "A_CODE_D_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "CC_LENGTH" NUMBER(2,
 0) NOT NULL ENABLE, "CC_D_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "ACCOUNT_SUB" NUMBER(1, 0)
 NOT NULL ENABLE, "J_STAND_BY" NUMBER(1, 0) NOT NULL ENABLE, "FOR_CURRENCY" NUMBER(1, 0)
 NOT NULL ENABLE, "NO_OF_DECIMAL" NUMBER(2, 0) NOT NULL ENABLE, "REQUEST_REFNO_GL"
 NUMBER(1, 0) NOT NULL ENABLE, "REQUEST_DESC_GL" NUMBER(1, 0) NOT NULL ENABLE,
 "CASH_RESERVE" NUMBER(1, 0) NOT NULL ENABLE, "HANDLY_LOCAL_AMT" NUMBER(1, 0) NOT NULL
 ENABLE, "CURR_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "USE_CASH_INCOME" NUMBER(1, 0) NOT
 NULL ENABLE, "POST_CHEQUE_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "POST_CHEQ_TYPE_VNDR"
 NUMBER(1, 0), "USE_DEL_GL" NUMBER(1, 0) NOT NULL ENABLE, "USE_MOD_GL" NUMBER(1, 0) NOT
 NULL ENABLE, "USE_GUARN" NUMBER(1, 0) NOT NULL ENABLE, "CONN_AC_CC" NUMBER(1, 0) NOT
 NULL ENABLE, "CONN_AC_PJ" NUMBER(1, 0) NOT NULL ENABLE, "POST_CHEQ_TYPE_REC" NUMBER(1,
 0) NOT NULL ENABLE, "POST_CHEQ_TYPE_PAY" NUMBER(1, 0) NOT NULL ENABLE, "USE_KIMB"
 NUMBER(1, 0) NOT NULL ENABLE, "USE_CASH_IN_JV" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_BANK_MDTR_IN_JV" NUMBER(1, 0) NOT NULL ENABLE, "USE_INVAC_IN_JV" NUMBER(1, 0) NOT
 NULL ENABLE, "MULTI_FILL_JV_NOTE" NUMBER(1, 0) NOT NULL ENABLE,
 "A_PARENT_NOT_INCLUDE_AC" NUMBER(1, 0) NOT NULL ENABLE, "C_PARENT_NOT_INCLUDE_CC"
 NUMBER(1, 0) NOT NULL ENABLE, "NOTE_SERIAL" NUMBER(1, 0) NOT NULL ENABLE, "GL_LMT_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "DESC_INCLUDE_CC_NAME" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_CHEQ_JV" NUMBER(1, 0) NOT NULL ENABLE, "PL_CLS_TYPE" NUMBER(1, 0) NOT NULL ENABLE,
 "DIFF_CUR_CLS_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "ALLOW_DUP_CASH_AC" NUMBER(1, 0) NOT
 NULL ENABLE, "ALLOW_DUP_BANK_AC" NUMBER(1, 0) NOT NULL ENABLE, "CSHBNK_CONN_BRN"
 NUMBER(1, 0) NOT NULL ENABLE, "USE_PAY_VCHR_MST_AC_PRV" NUMBER(1, 0),
 "USE_RCV_VCHR_MST_AC_PRV" NUMBER(1, 0), "REQUEST_COL_NO_REC" NUMBER(1, 0),
 "REQUEST_V_TYP_NO_VCHR" NUMBER(1, 0), "CONN_PYMNT_REQUST" NUMBER(1, 0),
 "CONN_RCPT_REQUST" NUMBER(1, 0), "P_RATE_TYPE" NUMBER(1, 0), "RCPT_SRL_TYP" NUMBER(2, 0)
, "CONN_CC_PJ" NUMBER(1, 0), "CONN_PJ_ACTV" NUMBER(1, 0), "ALLOW_VCHR_ZERO" NUMBER(1, 0),
 "SUB_AC_LVL" NUMBER(2, 0), "FILL_HRS_PAYFORM_MTHD" NUMBER(1, 0), "FILL_HRS_RECFORM_MTHD"
 NUMBER(1, 0), "JRNL_RQ_SEQ" NUMBER(1, 0), "PAY_RQ_SEQ" NUMBER(1, 0), "REC_RQ_SEQ"
 NUMBER(1, 0), "USE_MULTI_CUR_BDGT" NUMBER(1, 0), "USE_MULTI_CUR_LMT" NUMBER,
 "FILL_HRS_JRNLFORM_MTHD" NUMBER(1, 0), "DUP_CHQ_NO_PAYMNT" NUMBER(1, 0),
 "DFLT_POST_DSPLY_IN_ASTMT" NUMBER(1, 0), "NOT_CLOSE_DIFF_CUUR_PL_ACC" NUMBER(1, 0),
 "DESC_INCLUDE_PJ_NAME" NUMBER(1, 0), "SHOW_COL_NO" NUMBER(1, 0), "SHOW_REP_CODE"
 NUMBER(1, 0), "CONN_CSHNO_REP_CODE" NUMBER(1, 0), "CONN_CCODE_REP_CODE" NUMBER(1, 0),
 "ALLW_DIFF_RATE_MST_DTL" NUMBER(1, 0), "POST_ACC_DSC_IN_PAY_CHQ" NUMBER(1, 0),
 "USE_MULTI_RQ_IN_JV" NUMBER(1, 0), "CHK_BGT_AMT" NUMBER(1, 0), "CRT_NOTE_MOV_BGT_BRN"
 NUMBER(1, 0), "SHW_DOC_BRN_NO" NUMBER(1, 0), "USE_ALL_ACC_BDGT" NUMBER(1, 0),
 "CALL_CST_REPCODE" NUMBER(1, 0), "USE_BGT_APPRVL" NUMBER(1, 0), "USE_BRN_LMT" NUMBER(1,
 0), "JRNL_SEQ_TYP" NUMBER(2, 0), "MNDTRY_RCPT_REP_CODE" NUMBER(1, 0), "ADD_FLD_DTL_CNT"
 NUMBER(1, 0), "CONN_AC_ACTV" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "EXCHHG_CUR_SEQ" NUMBER(2, 0),
 "USE_EXPNS_TAX" NUMBER(1, 0), "USE_MULTI_RQ_IN_PYMNT" NUMBER(1, 0),
 "USE_MULTI_RQ_IN_RCPT" NUMBER(1, 0), "USE_BNK_DPST_AC_INTRMDT" NUMBER(1, 0))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL KEEP) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PARA_INV" ("PARA_NO" NUMBER(1, 0), "DOC_GEN_INV" NUMBER(1, 0) NOT NULL
 ENABLE, "ALLOW_DOC_DEL_NO" NUMBER(1, 0) NOT NULL ENABLE, "DATE_GEN_INV" NUMBER(1, 0) NOT
 NULL ENABLE, "DATE_SETTING_INV" NUMBER(1, 0) NOT NULL ENABLE, "LINK_WITH_GL" NUMBER(1,
 0) NOT NULL ENABLE, "I_CODE_LEN" NUMBER(2, 0) NOT NULL ENABLE, "I_CODE_D_TYPE" NUMBER(1,
 0) NOT NULL ENABLE, "USE_ALT_CODE" NUMBER(1, 0) NOT NULL ENABLE, "USE_EXPIRE_DATE"
 NUMBER(1, 0) NOT NULL ENABLE, "USE_BATCH_NO" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_MULTI_WC" NUMBER(1, 0) NOT NULL ENABLE, "INCOMING_W_HOUSE_TYPE" NUMBER(1, 0) NOT
 NULL ENABLE, "OUTGOING_W_HOUSE_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "INCOMING_CS_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "OUTGOING_CS_TYPE" NUMBER(1, 0) NOT NULL ENABLE,
 "STK_ADJUST_CS_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "TR_CS_TYPE" NUMBER(1, 0) NOT NULL
 ENABLE, "OUT_PJ_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "INC_PJ_TYPE" NUMBER(1, 0) NOT NULL
 ENABLE, "STK_PJ_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "TR_PJ_TYPE" NUMBER(1, 0) NOT NULL
 ENABLE, "OUT_ACTV_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "INC_ACTV_TYPE" NUMBER(1, 0) NOT
 NULL ENABLE, "STK_ACTV_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "TR_ACTV_TYPE" NUMBER(1, 0)
 NOT NULL ENABLE, "USE_COSTING" NUMBER(1, 0) NOT NULL ENABLE, "COSTING_TYPE" NUMBER(1, 0)
 NOT NULL ENABLE, "WTAVG_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "ITEM_POSTING_FLAG" NUMBER(1
, 0) NOT NULL ENABLE, "USE_NEGATIVE_INV" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_I_DESC"
 NUMBER(1, 0) NOT NULL ENABLE, "SHOW_ITEM_DESC" NUMBER(1, 0) NOT NULL ENABLE,
 "NO_OF_DECIMAL_INV" NUMBER(2, 0) NOT NULL ENABLE, "UPDATE_BALANCE" NUMBER(1, 0) NOT NULL
 ENABLE, "USE_SERIALNO" NUMBER(1, 0) NOT NULL ENABLE, "USE_CONS_ITM" NUMBER(1, 0) NOT
 NULL ENABLE, "USE_COMPOUND_ITEMS" NUMBER(1, 0) NOT NULL ENABLE, "INCOMING_SERIAL"
 NUMBER(1, 0) NOT NULL ENABLE, "OUTGOING_SERIAL" NUMBER(1, 0) NOT NULL ENABLE,
 "TRANSFER_SERIAL" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_I_SIZE" NUMBER(1, 0) NOT NULL
 ENABLE, "HIDE_OUTGOING_AC" NUMBER(1, 0) NOT NULL ENABLE, "REQUEST_SERIAL" NUMBER(1, 0)
 NOT NULL ENABLE, "USE_DUPITM_MANINV" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_STANDARD_ITEM_COST" NUMBER(1, 0) NOT NULL ENABLE, "USE_REQ_MOD_PRICE" NUMBER(1, 0),
 "USE_DEL_INV" NUMBER(1, 0) NOT NULL ENABLE, "USE_MOD_INV" NUMBER(1, 0) NOT NULL ENABLE,
 "PRICE_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "ROI_TYPE" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_MIN_UNIT_PRICE" NUMBER(1, 0), "GENERATE_I_CODE" NUMBER(1, 0) NOT NULL ENABLE,
 "CONN_GRPS" NUMBER(1, 0) NOT NULL ENABLE, "CONN_DTL_GRP_BY_GRPS" NUMBER(1, 0) NOT NULL
 ENABLE, "CONN_ASSTNT_GRP_BY_GRPS" NUMBER(1, 0) NOT NULL ENABLE, "INSRT_ITM_MAN" NUMBER(1
, 0) NOT NULL ENABLE, "STKCOST_FRACTION" NUMBER(2, 0) NOT NULL ENABLE,
 "USE_TRNSFER_EXPENSE" NUMBER(1, 0) NOT NULL ENABLE, "ALLOW_MOD_REC_QTY" NUMBER(1, 0) NOT
 NULL ENABLE, "ALLOW_MOD_REC_WCODE" NUMBER(1, 0) NOT NULL ENABLE, "USE_ITM_ATTACH"
 NUMBER(1, 0) NOT NULL ENABLE, "CONN_REQ_WHTRNSFR" NUMBER(1, 0) NOT NULL ENABLE,
 "CONN_REQ_OUTGOING" NUMBER(1, 0) NOT NULL ENABLE, "CONN_GR_INCOMING" NUMBER(1, 0) NOT
 NULL ENABLE, "MIN_LMT_COST_PER" NUMBER(3, 0), "MAX_LMT_COST_PER" NUMBER(3, 0),
 "MIN_LMT_PRICE_PER" NUMBER(3, 0), "MAX_LMT_PRICE_PER" NUMBER(3, 0), "PRICE_CST_TYPE"
 NUMBER(1, 0), "REQUEST_REFNO_INV" NUMBER(1, 0) NOT NULL ENABLE, "REQUEST_DESC_INV"
 NUMBER(1, 0) NOT NULL ENABLE, "GENERATE_BARCODE" VARCHAR2(250),
 "CONN_ITEM_BY_ATTACH_AUTO" NUMBER(1, 0), "CONN_ITM_ACT_BY_USR_PRIV" NUMBER(1, 0),
 "DEALING_UNDER_SELLING" NUMBER(1, 0), "ALLOW_UPD_TR_A_CODE" NUMBER(1, 0),
 "ALLOW_EXCEED_TR_QTY" NUMBER(1, 0), "USE_MULTI_WHTRNS" NUMBER(1, 0),
 "USE_GOOD_ON_CONSIGNMENT" NUMBER(1, 0), "ALLOW_DEL_REC_ITM" NUMBER(1, 0),
 "MAN_INV_SERAIL" NUMBER(1, 0), "USE_WT_SYS" NUMBER(1, 0), "DFLT_WT_ARGMNT" NUMBER(1, 0),
 "INV_SYS_TYPE" NUMBER(1, 0), "INV_SYS_CLOSE_TYPE" NUMBER(1, 0), "INV_CLOSE_CST_TYPE"
 NUMBER(1, 0), "USE_PRICE_WHTRNS_REC_COST" NUMBER(1, 0), "CONN_WC_CC_MANDTRY" NUMBER(1,
 0), "SHOW_PARENT_ITM_ONLY" NUMBER(1, 0), "APPRVD_BRACODE_SAME_BATCHNO" NUMBER,
 "APPRVD_BRACODE_SAME_SERIALNO" NUMBER, "NOT_INSTALL_ITEM_HAS_PRICE" NUMBER(1, 0),
 "CONN_ACTIVITY_BY_WCODE_CC_CODE" NUMBER(1, 0), "PRINT_ITM_BARCODE_NOT_PRICE" NUMBER(1,
 0), "BATCHNO_COL_NO" NUMBER(2, 0), "BATCH_NM_COL1" VARCHAR2(60), "BATCH_NM_COL2"
 VARCHAR2(60), "BATCH_NM_COL3" VARCHAR2(60), "BATCH_NM_COL4" VARCHAR2(60),
 "BATCH_NM_COL5" VARCHAR2(60), "SHOW_BAT_COL1_IN_SCREEN" NUMBER(1, 0),
 "SHOW_BAT_COL2_IN_SCREEN" NUMBER(1, 0), "SHOW_BAT_COL3_IN_SCREEN" NUMBER(1, 0),
 "SHOW_BAT_COL4_IN_SCREEN" NUMBER(1, 0), "SHOW_BAT_COL5_IN_SCREEN" NUMBER(1, 0),
 "ACTIVE_SERIALNO" NUMBER(1, 0), "GENERATE_AUTO_ITM_BARCODE" NUMBER(1, 0),
 "USE_PER_COST_KIT_ITM" NUMBER(1, 0), "INSTALL_POS_KIT_ITM_IN_STK_ADJ" NUMBER(1, 0),
 "SIZE_COL1" NUMBER(2, 0), "SIZE_COL2" NUMBER(2, 0), "SIZE_COL3" NUMBER(2, 0),
 "SIZE_COL4" NUMBER(2, 0), "SIZE_COL5" NUMBER(2, 0), "ITEM_NO_COL1" NUMBER(1, 0),
 "ITEM_NO_COL2" NUMBER(1, 0), "ITEM_NO_COL3" NUMBER(1, 0), "ITEM_NO_COL4" NUMBER(1, 0),
 "ITEM_NO_COL5" NUMBER(1, 0), "DUP_ITEM_TR_REC" NUMBER(1, 0), "BARCODE_FIRST" NUMBER(2,
 0), "BARCODE_SECOND" NUMBER(2, 0), "BARCODE_THIRD" NUMBER(2, 0), "BARCODE_FOURTH"
 NUMBER(2, 0), "BARCODE_FIFTH" NUMBER(2, 0), "BARCODE_SIXTH" NUMBER(2, 0),
 "BARCODE_FIRST_LENGTH" NUMBER(2, 0), "BARCODE_SECOND_LENGTH" NUMBER(2, 0),
 "BARCODE_THIRD_LENGTH" NUMBER(2, 0), "BARCODE_FOURTH_LENGTH" NUMBER(2, 0),
 "BARCODE_FIFTH_LENGTH" NUMBER(2, 0), "BARCODE_SIXTH_LENGTH" NUMBER(2, 0),
 "BARCODE_FIRST_DIR" NUMBER(1, 0), "BARCODE_SECOND_DIR" NUMBER(1, 0), "BARCODE_THIRD_DIR"
 NUMBER(1, 0), "BARCODE_FOURTH_DIR" NUMBER(1, 0), "BARCODE_FIFTH_DIR" NUMBER(1, 0),
 "BARCODE_SIXTH_DIR" NUMBER(1, 0), "APPV_DFLT_PRC_FOR_ALL_LVL" NUMBER(1, 0),
 "MAN_INV_BY_ONE" NUMBER(1, 0), "CALC_LOST_DAY" NUMBER(1, 0),
 "INCLUDE_G_CODE_IN_ITM_CODE" NUMBER(1, 0), "USE_INCOM_ITM_EXPIRE_DATE" NUMBER(1, 0),
 "SHOW_NOTE_EXCEED_QTY_IN_WHTRNS" NUMBER(1, 0), "DUP_ITM_IN_INCOMING" NUMBER(1, 0),
 "DUP_ITM_IN_OUTGOING" NUMBER(1, 0), "USE_AUTO_REC_WHTRNS_BY_WCODE" NUMBER(1, 0),
 "CHK_WCODE_REQ_IN_WHTRNS" NUMBER(1, 0), "BARCODE_DATA_TYPE" NUMBER(1, 0),
 "INPT_UNT_FACTOR_WT" NUMBER, "USE_SEQ_ITM_AUTO" NUMBER(1, 0), "SHOW_ITM_BARCODE_INV"
 NUMBER(1, 0), "USE_ONE_BARCODE_FOR_ITM" NUMBER(1, 0), "CONN_SUB_GRPS" NUMBER(1, 0),
 "APPRV_ITMNO_BATCHNO_IN_BARCODE" NUMBER(1, 0), "GENERATE_BARCODE_MIN_UNIT" NUMBER(1, 0),
 "USE_INV_REEVALUATE" NUMBER(1, 0), "SHOW_WT_UNT_ARGMNT_IN_TRNS" NUMBER,
 "DEAL_WITH_ITEM_USED" NUMBER(1, 0), "MTHD_VAT_CALC_ITM_USED" NUMBER(1, 0),
 "CNCT_ITM_BY_BTCH" NUMBER, "PRINT_PRICE_WITH_TAX" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "APPRVD_KIT_ITM_PRICE_ASSMBLE" NUMBER(1, 0), "HIDE_INCOMING_AC" NUMBER(1, 0),
 "APPRVD_BTCHNO_ITMCODE_SQ" NUMBER(1, 0), "ASSMBL_DOC_SRL" NUMBER(1, 0) NOT NULL ENABLE,
 "STK_ADJSTMNT_SRL" NUMBER(1, 0) NOT NULL ENABLE, "USE_QR_CODE_SRL_NO" NUMBER(1, 0),
 "USE_ITM_PRICE_BY_EXPIRE_DATE" NUMBER(1, 0), "USE_ITM_PRICE_BY_BATCH_NO" NUMBER(1, 0),
 "WGHT_PRFX" VARCHAR2(3), "WGHT_BARCODE_LNGTH" NUMBER(2, 0), "WGHT_ITM_LNGTH" NUMBER(2,
 0), "WGHT_VAL" NUMBER(5, 0), "WGHT_FLG" NUMBER(1, 0), "WGHT_INCLD_ITM_UNT" NUMBER(1, 0),
 "REMOVE_WGHT_DGT" NUMBER(1, 0), "USE_CHCK_SUM" NUMBER(1, 0), "QR_PRFX_LNGTH" NUMBER(1,
 0), "QR_GTIN_LNGTH_ARGMNT" NUMBER(1, 0), "NO_OF_BARCODE_DIGIT_IN_QR_CODE" NUMBER(2, 0),
 "QR_GTIN_LNGTH" NUMBER(3, 0), "USE_SERIALNO_FOR_SALES_ONLY" NUMBER(1, 0),
 "QR_CODE_MTHD_TYP" NUMBER(1, 0), "NO_OF_MAN_QTY" NUMBER(2, 0), "USE_BATCH_NO_AUTO_SQ"
 NUMBER(1, 0), "NOT_ALLW_DEL_DOC_CONN_SERIALNO" NUMBER(1, 0),
 "ALLW_ENTR_PART_QTY_SERIALNO" NUMBER(1, 0), "USE_KIT_ITM_WC_TYP_OUT" NUMBER(1, 0),
 "USE_KIT_ITM_CLSSFCTN" NUMBER(1, 0), "USE_PRP_QTY_BY_BARCODE" NUMBER(1, 0),
 "MNDTRY_ENTR_PART_ITM_CODE_SRCH" NUMBER(1, 0), "WGHT_VAL_SRVC" NUMBER(5, 0),
 "PRICE_INCLD_VAT_SRVC_ITM" NUMBER(1, 0), "USE_PRPRTN_QTY" NUMBER(1, 0),
 "USE_SO_MNDTRY_IN_OUTGOIN" NUMBER(1, 0), "SHW_GRP_QTY_LMT_ALRT" NUMBER(1, 0),
 "ALLW_DUP_ITM_UNT_SIZE" NUMBER(1, 0), "CONN_CC_ITM_ACTVTY" NUMBER(1, 0),
 "CONN_ACTV_AC_ITM_ACTVTY" NUMBER(1, 0), "CHK_INCMNG_CST_PER_OPRTN" NUMBER(1, 0),
 "DUP_ITM_IN_OPEN_STOCK" NUMBER(1, 0), "USE_ITM_BIN_MOV" NUMBER(1, 0),
 "WGHT_CLC_QTY_BY_INCLD_PRICE" NUMBER(1, 0), "WGHT_PRICE_FRC_LNGTH" NUMBER(2, 0),
 "NOT_ALLW_PRNT_ITM_WITHOT_BARC" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS
 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL KEEP) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PARA_AR" ("PARA_NO" NUMBER(1, 0), "DOC_GEN_AR" NUMBER(1, 0) NOT NULL
 ENABLE, "ALLOW_DOC_DEL_NO" NUMBER(1, 0) NOT NULL ENABLE, "DATE_GEN_AR" NUMBER(1, 0) NOT
 NULL ENABLE, "DATE_SETTING_AR" NUMBER(1, 0) NOT NULL ENABLE, "CUST_LENGTH" NUMBER(2, 0)
 NOT NULL ENABLE, "CUST_D_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "AR_AC_LINK_TYPE" NUMBER(1,
 0) NOT NULL ENABLE, "AR_USE_FREE_QTY" NUMBER(1, 0) NOT NULL ENABLE, "AR_CS_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "AR_PJ_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "AR_ACTV_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "AR_WC_TYPE" NUMBER(1, 0) NOT NULL ENABLE,
 "INVOICING_SERIALS" NUMBER(2, 0) NOT NULL ENABLE, "INVOICING_SERIALS_SR" NUMBER(2, 0)
 NOT NULL ENABLE, "AR_QUOT_SERIAL" NUMBER(1, 0) NOT NULL ENABLE, "AR_SORDER_SERIAL"
 NUMBER(1, 0) NOT NULL ENABLE, "SHOW_DISC_PER_ITEMS_AR" NUMBER(1, 0) NOT NULL ENABLE,
 "MUST_RET_SAME_WCODE" NUMBER(1, 0) NOT NULL ENABLE, "AR_LINK_INV" NUMBER(1, 0) NOT NULL
 ENABLE, "NO_OF_DECIMAL_AR" NUMBER(2, 0) NOT NULL ENABLE, "SALES_DUPLICATE_ITEM" NUMBER(1
, 0) NOT NULL ENABLE, "USE_RET_WITHOUT_BILLNO" NUMBER(1, 0) NOT NULL ENABLE,
 "FILL_SO_WITHOUT_PRICE" NUMBER(1, 0) NOT NULL ENABLE, "USE_CNCRT_SYS" NUMBER(1, 0),
 "USE_SHPNG_LST_AR" NUMBER, "PAID_SCR_TYP" NUMBER(1, 0), "SC_ITEM_TYPE" NUMBER(2, 0) NOT
 NULL ENABLE, "USE_OUT_BILLS" NUMBER(1, 0) NOT NULL ENABLE, "SALES_POST_FREE_QTY"
 NUMBER(1, 0) NOT NULL ENABLE, "SALES_POST_DISCOUNT" NUMBER(1, 0) NOT NULL ENABLE,
 "POST_OUT_BILLS_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "CUST_PRICE_FIXED" NUMBER(1, 0) NOT
 NULL ENABLE, "SI_HIDE_DISC_PER" NUMBER(1, 0) NOT NULL ENABLE, "SI_HIDE_FREE_PER"
 NUMBER(1, 0) NOT NULL ENABLE, "SALES_DISC_WCODE" NUMBER(1, 0) NOT NULL ENABLE,
 "SALES_DISC_PERIODIC" NUMBER(1, 0) NOT NULL ENABLE, "SALES_DISC_TYPE" NUMBER(2, 0) NOT
 NULL ENABLE, "SALES_FREE_QTY_TYPE" NUMBER(2, 0) NOT NULL ENABLE, "SALES_FREE_QTY_WCODE"
 NUMBER(1, 0) NOT NULL ENABLE, "SALES_FREE_QTY_PERIODIC" NUMBER(1, 0) NOT NULL ENABLE,
 "SHOW_I_DESC_AR" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_ITEM_DESC" NUMBER(1, 0) NOT NULL
 ENABLE, "POST_REP_COMM" NUMBER(1, 0) NOT NULL ENABLE, "CREDIT_LIMIT_TYPE" NUMBER(1, 0)
 NOT NULL ENABLE, "ITM_DISC_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "USE_STAND_BY" NUMBER(1,
 0) NOT NULL ENABLE, "USE_WORK_ORDER" NUMBER(1, 0) NOT NULL ENABLE, "USE_REC_CHECK"
 NUMBER(1, 0) NOT NULL ENABLE, "AR_WO_SERIAL" NUMBER(1, 0) NOT NULL ENABLE,
 "SI_REPCODE_MANDTRY" NUMBER(1, 0) NOT NULL ENABLE, "SI_RCODE_MANDTRY" NUMBER(1, 0) NOT
 NULL ENABLE, "SI_COL_MANDTRY" NUMBER(1, 0) NOT NULL ENABLE, "SI_DRIVER_MANDTRY" NUMBER(1
, 0) NOT NULL ENABLE, "SI_ADDFIELDS_MANDTRY" NUMBER(1, 0) NOT NULL ENABLE,
 "USE_BILLNO_RTSALE_PY" NUMBER(1, 0) NOT NULL ENABLE, "PAID_INSTLLMNT_MAN" NUMBER(1, 0)
 NOT NULL ENABLE, "USE_DEL_AR" NUMBER(1, 0) NOT NULL ENABLE, "USE_MOD_AR" NUMBER(1, 0)
 NOT NULL ENABLE, "REQUEST_REFNO_AR" NUMBER(1, 0) NOT NULL ENABLE, "REQUEST_DESC_AR"
 NUMBER(1, 0) NOT NULL ENABLE, "USE_BILLNO_CONN" NUMBER(1, 0) NOT NULL ENABLE,
 "LGHT_POST_TYPE" NUMBER(1, 0), "SHOW_ITM_BARCODE_AR" NUMBER(1, 0), "CHK_ALLW_ITM_DSCNT"
 NUMBER(1, 0), "CHECK_LMT_SORDER" NUMBER(1, 0) NOT NULL ENABLE, "CHECK_SORDER_QTY"
 NUMBER(1, 0) NOT NULL ENABLE, "ADD_PORDER_QTY" NUMBER NOT NULL ENABLE,
 "USE_SALE_INVOICE_AS_POS" NUMBER NOT NULL ENABLE, "SHOW_SIZE_ITEM_IN_BILLS" NUMBER(1, 0)
, "SHOW_WEIGHT_ITEM_IN_BILLS" NUMBER(1, 0), "SHOW_SUM_QTY_IN_SALES" NUMBER(1, 0),
 "USE_LGHT_WITHOUT_STORE" NUMBER(1, 0), "USE_MNDATA_MST_SR_PY" NUMBER(1, 0), "DISC_COUNT"
 NUMBER(1, 0), "ADD_FRC_INTO_DISC_INVOICE" NUMBER, "CALC_VAT_AMT_TYPE" NUMBER(1, 0),
 "ALLOW_GRP_CR_CARD_AMT" NUMBER(1, 0), "RET_FREE_QTY_PER" NUMBER(1, 0),
 "POST_ADD_DISC_ITM_TYPE" NUMBER(1, 0), "LGHT_SHOW_QTY_ALL_WCODE" NUMBER(1, 0),
 "SR_RT_REASON_MANDTRY" NUMBER(1, 0), "SI_DUE_DATE_MANDTRY" NUMBER(1, 0),
 "SI_CHK_AVLQTY_SORDER" NUMBER(1, 0), "CST_SEQ_TYPE" NUMBER(1, 0),
 "ALLOW_SO_WITHOUT_STORE" NUMBER(1, 0), "MAX_RESERVE_SO_ITM_DAY" NUMBER(5, 0),
 "SO_EXP_DATE_MANDTRY" NUMBER(1, 0), "MAX_PRD_EXP_DATE_SO_DAY" NUMBER(5, 0),
 "CHK_LMT_QUOT_PRM_SI" NUMBER, "CHK_STK_QUOT_PRM_SI" NUMBER,
 "CHK_LMT_PRICE_MINUS_DISC_SI" NUMBER, "LGHT_POST_SALES_AVLQTY" NUMBER,
 "CNCL_RSRVD_SO_TRNS_BRN_LGHT" NUMBER(1, 0), "SC_WCODE_TYPE" NUMBER(1, 0),
 "SHOW_PAID_SCR" NUMBER, "CONN_SO_INC" NUMBER(1, 0), "USE_SC_PRD" NUMBER(1, 0),
 "SHOW_SMAN_COMM_SI" NUMBER, "MAX_PRD_RESERVE_SO_DAY" NUMBER(5, 0), "AR_RCPT_DOC_SERIAL"
 NUMBER(1, 0), "AR_USE_PAID_RCPT" NUMBER(1, 0), "ALLOW_MOD_WCODE_SO_SI" NUMBER,
 "ALLOW_MOD_PAY_TYPE_SO_SI" NUMBER, "CALC_SI_DISC_WITHOUT_ITM_DISC" NUMBER,
 "USE_SMAN_SLICES_COMM_AUTO_SI" NUMBER(1, 0), "CONN_SMAN_ITM_ACTVTY" NUMBER(1, 0),
 "CONN_SMAN_WC_CSH_CC" NUMBER(1, 0), "CONN_CST_MULTI_SMAN" NUMBER(1, 0),
 "SHW_ITM_AVLQTY_ONLY" NUMBER(1, 0), "SHW_ADD_FLD_IN_DTL" NUMBER(2, 0),
 "COPY_PRICE_FROM_PREV_BILL" NUMBER(1, 0), "MAX_PRD_EXP_DATE_SLS_QUOT_DAY" NUMBER(3, 0),
 "QUOT_EXP_DATE_MANDTRY" NUMBER(1, 0), "USE_CHRG_INSTANT_TELECOM" NUMBER,
 "SI_PAY_CSH_CST_MANDTRY" NUMBER(1, 0), "CONN_CST_MULTI_COL" NUMBER(1, 0),
 "MNDTRY_CONN_CST_COL" NUMBER(1, 0), "CNVRT_SI_INCDPST_AUTO" NUMBER(1, 0),
 "USE_APPRV_SLS_MNG_SO" NUMBER(1, 0), "USE_INSRNCE_SYS" NUMBER(1, 0),
 "MNDTRY_REQ_IN_ADD_DISC" NUMBER(1, 0), "AR_ADD_DISC_SERIAL" NUMBER(1, 0),
 "AR_RQ_ADD_DISC_SERIAL" NUMBER(1, 0), "CONN_OUT_BILL_INV_REC" NUMBER(1, 0),
 "SI_CST_TEL_MANDTRY" NUMBER(1, 0), "AR_EMP_TYPE" NUMBER(1, 0), "PST_SMAN_COMM_VCHR_RCPT"
 NUMBER(1, 0), "USE_MEASUR_DSC_ITM" NUMBER(1, 0), "AR_USE_RT_BILL_RQ_TYP" NUMBER(1, 0),
 "USE_SUB_CUSTOMER" NUMBER(1, 0), "SI_CST_NM_MANDTRY" NUMBER(1, 0), "SHW_ITM_COMM_PER"
 NUMBER(1, 0), "SHW_ALL_ITM_UNT_TRNS" NUMBER(1, 0), "USE_SO_PRPRTON_QTY" NUMBER(1, 0),
 "CALC_MEASUR_PRICE" NUMBER(1, 0), "USE_CST_CR_LMT_LOCAL" NUMBER(1, 0),
 "ADD_DSCNT_ITM_QT_PRM_DSCNT" NUMBER(1, 0), "BILL_LMT_PRNT_SMPL_FORM" NUMBER,
 "USE_DISC_CARD_SAL" NUMBER(1, 0), "USE_POINT_SYS_SAL" NUMBER(1, 0),
 "LNGTH_CSH_CSTMR_CODE" NUMBER(2, 0), "LNGTH_CSH_CSTMR_MOBIL_NO" NUMBER(2, 0),
 "POINT_CALC_TYP" NUMBER(1, 0), "POINT_APRVD_BY_DAY" NUMBER(3, 0),
 "POINT_AGE_EXPIRED_TYP" NUMBER(2, 0), "POINT_AGE_EXPIRED_PRD" NUMBER(3, 0),
 "CUST_NOTE_JOIN_POINT" VARCHAR2(500), "CUST_NOTE_NOT_JOIN_POINT" VARCHAR2(500),
 "SEND_MSG_TYP" NUMBER(1, 0), "SEND_MSG_CST_TYP" NUMBER(1, 0), "MSG_TXT_CST_BILL"
 VARCHAR2(1000), "MSG_TXT_CST_RTBILL" VARCHAR2(1000), "MSG_TXT_CST_POINT" VARCHAR2(1000),
 "MSG_TXT_CST_WELCOME" VARCHAR2(1000), "USE_ASSCTN_ACCNT" NUMBER(1, 0), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "USE_SO_RSRVD_TIME" NUMBER, "DSCNT_AFTR_VAT_FRC_CTGRY" NUMBER, "LNK_WITH_SCAL_SO"
 NUMBER(1, 0), "PER_DIFF_ACTUL_WGHT_QTY_SO" NUMBER, "RETURN_PERIOD" NUMBER(5, 0),
 "ALLW_DUP_REF_NO" NUMBER(1, 0), "USE_OUT_BILL_DIRECT" NUMBER(1, 0),
 "SHOW_NET_PRICE_TRNS" NUMBER(1, 0), "USE_CNDTN_CNTRCT" NUMBER(1, 0),
 "USE_INTRFC_SAL_RVNU" NUMBER(1, 0), "USE_SRCH_ITM_NM_ARABIC" NUMBER(1, 0),
 "AR_QT_WC_TYP" NUMBER(1, 0), "CLC_TAX_DSCNT2" NUMBER(1, 0), "CLC_TAX_DSCNT3" NUMBER(1,
 0), "SHW_LVL_PRICE_IN_TRNS" NUMBER(1, 0), "USE_BILLS_FLLWUP" NUMBER(1, 0),
 "USE_CSTMR_CLIM" NUMBER(1, 0), "USE_CLC_TAX_FREE_QTY" NUMBER(1, 0),
 "APPRVD_FREEQTY_DSCNT_RTRN_SI" NUMBER(1, 0), "USE_AUTO_RSRV_ITM_TRNS_INPT" NUMBER(1, 0),
 "USE_RQ_ITM_CSTMR" NUMBER(1, 0), "CHK_CRD_BNK_AMT" NUMBER(1, 0), "TIME_CHK_CRD_BNK_SCND"
 NUMBER(3, 0), "USE_ADVNC_PYMNT" NUMBER(1, 0), "CLC_TAX_ADVNC_PYMNT" NUMBER(1, 0),
 "CHK_PRICE_COST_LMT_SO_SI" NUMBER(1, 0), "ALLW_UPD_RTRN_INSRNCE_SI" NUMBER(1, 0),
 "USE_SP_SMAN" NUMBER(1, 0), "USE_SCAL_MOVMNT" NUMBER(1, 0), "LGHT_OUT_BILL_TYP" NUMBER(1
, 0), "APPRVD_SO_NO_BTCH_NO_AUTO" NUMBER(1, 0), "ALLW_ENTR_CSTMR_IN_LGHT" NUMBER(1, 0),
 "GRNT_CST_PRIV_BY_BRN" NUMBER(1, 0), "CLC_DSCNT_AUTO_MOD_ITM_TOT" NUMBER(1, 0),
 "SI_CSH_CST_MANDTRY" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL KEEP) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_PARA_AP" ("PARA_NO" NUMBER(1, 0), "DOC_GEN_AP" NUMBER(1, 0) NOT NULL
 ENABLE, "ALLOW_DOC_DEL_NO" NUMBER(1, 0) NOT NULL ENABLE, "DATE_GEN_AP" NUMBER(1, 0) NOT
 NULL ENABLE, "DATE_SETTING_AP" NUMBER(1, 0) NOT NULL ENABLE, "VENDOR_LENGTH" NUMBER(2,
 0) NOT NULL ENABLE, "VENDOR_D_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "AP_AC_LINK_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "AP_USE_FREE_QTY" NUMBER(1, 0) NOT NULL ENABLE,
 "SHOW_DISC_PER_ITEMS_AP" NUMBER(1, 0) NOT NULL ENABLE, "ITM_DISC_TYPE" NUMBER(1, 0) NOT
 NULL ENABLE, "DISC_COUNT" NUMBER(1, 0) NOT NULL ENABLE, "AP_CS_TYPE" NUMBER(1, 0) NOT
 NULL ENABLE, "AP_PJ_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "AP_ACTV_TYPE" NUMBER(1, 0) NOT
 NULL ENABLE, "AP_WC_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "AP_LINK_INV" NUMBER(1, 0) NOT
 NULL ENABLE, "NO_OF_DECIMAL_AP" NUMBER(2, 0) NOT NULL ENABLE, "LC_TYPE" NUMBER(1, 0) NOT
 NULL ENABLE, "LC_STATUS" NUMBER(1, 0) NOT NULL ENABLE, "PURCHASE_DISC_TYPE" NUMBER(1, 0)
 NOT NULL ENABLE, "PUR_FREE_QTY_COSTING" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_G_NAME"
 NUMBER(1, 0) NOT NULL ENABLE, "USE_LOC_GRN" NUMBER(1, 0) NOT NULL ENABLE, "USE_DEL_AP"
 NUMBER(1, 0) NOT NULL ENABLE, "USE_MOD_AP" NUMBER(1, 0) NOT NULL ENABLE,
 "AP_PREQ_SERIAL" NUMBER(1, 0) NOT NULL ENABLE, "AP_PO_SERIAL" NUMBER(1, 0) NOT NULL
 ENABLE, "GRN_SERIAL" NUMBER(1, 0) NOT NULL ENABLE, "AP_PI_SERIAL" NUMBER(1, 0) NOT NULL
 ENABLE, "AP_PRI_SERIAL" NUMBER(1, 0) NOT NULL ENABLE, "USE_BOE" NUMBER(1, 0) NOT NULL
 ENABLE, "CONN_PR_PO_PI" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_I_DESC_AP" NUMBER(1, 0) NOT
 NULL ENABLE, "SHOW_ITEM_DESC" NUMBER(1, 0) NOT NULL ENABLE, "REQUEST_REFNO_AP" NUMBER(1,
 0) NOT NULL ENABLE, "REQUEST_DESC_AP" NUMBER(1, 0) NOT NULL ENABLE, "SHOW_WCODE_IN_PREQ"
 NUMBER(1, 0) NOT NULL ENABLE, "USER_APPROVED_IN_PREQ" NUMBER(1, 0) NOT NULL ENABLE,
 "INSRT_VNDR_ITM" NUMBER(1, 0) NOT NULL ENABLE, "FILL_LC_IN_JV" NUMBER(1, 0) NOT NULL
 ENABLE, "PAID_INSTLLMNT_MAN" NUMBER(1, 0) NOT NULL ENABLE, "USE_PINO_RT_PR_PY" NUMBER(1,
 0) NOT NULL ENABLE, "DISC1_NOT_EFFECT_VND_TRNS" NUMBER(1, 0),
 "DISC2_NOT_EFFECT_VND_TRNS" NUMBER(1, 0), "DISC3_NOT_EFFECT_VND_TRNS" NUMBER(1, 0),
 "AP_DISC_TYPE" NUMBER(1, 0), "VENDOR_SERIAL" NUMBER(1, 0), "SHOW_SUM_QTY" NUMBER,
 "ALLOW_DUPL_ITM" NUMBER(1, 0), "PUR_MAN_MANDTRY" NUMBER(1, 0), "USE_SRVC_BILL" NUMBER(1,
 0), "NOTIFY_ITM_PRQST_NOT_PRCSS" NUMBER, "NOTIFY_ITM_PORDR_NOT_PRCSS" NUMBER,
 "USE_AP_CHECK_QTY" NUMBER(1, 0), "USE_KIMB_AP" NUMBER(1, 0), "EFFCT_KIMB_VNDR" NUMBER(1,
 0), "CALC_VAT_AMT_TYPE_AP" NUMBER(1, 0), "CONN_ITM_WITH_MORE_VNDR" NUMBER(1, 0),
 "ADD_ITM_PRICE_FROM_BILL" NUMBER(1, 0), "AP_USE_SRVC_ITM" NUMBER(1, 0),
 "PO_CHK_MAX_LMT_COST" NUMBER(1, 0), "SHOW_TOT_AMT" NUMBER(1, 0), "CONN_CNTRCT_PO_TYPE"
 NUMBER(1, 0), "CHK_ITM_CONN_BY_VNDR" NUMBER(1, 0), "USE_AP_OTHR_CHRG" NUMBER,
 "SHOW_ITM_BARCODE_AP" NUMBER(1, 0), "BILL_DUE_DATE_LAST_MNTH" NUMBER(1, 0),
 "SHW_ADD_FLD_DTL_CNT" NUMBER(2, 0), "SHW_CST_IN_PRQST_ORDR" NUMBER(1, 0),
 "USE_RT_BILL_RQST" NUMBER(1, 0), "USE_LOC_GRN_MORE_ONE" NUMBER(1, 0),
 "REQUEST_VNDR_BILL_NO" NUMBER(1, 0), "USE_ASSGN_TO_USR" NUMBER(1, 0),
 "SHOW_FREE_QTY_PROFT" NUMBER(1, 0), "CLC_DISC_WITHOUT_ITM_DISC" NUMBER(1, 0),
 "SHW_TOT_ITM_PRICE_BY_NET" NUMBER(1, 0), "RQRD_CNTNR_NO" NUMBER(1, 0),
 "NOT_CHK_LC_BLNC_IN_BILL_CST" NUMBER(1, 0), "CONN_PO_PI_TYP" NUMBER(1, 0),
 "USE_VNDR_VAT_TYPE" NUMBER(1, 0), "PRICE_VNDR_ITM_UNT_TYP" NUMBER(1, 0),
 "ALLW_UPDT_VNDR_INBILL" NUMBER, "AUTO_UPDATE_VNDR_PRICE" NUMBER(1, 0),
 "USE_RET_WITHOUT_PI_BILLNO" NUMBER(1, 0), "AP_ITEM_CHRG_CALC_TYPE" NUMBER(1, 0),
 "AP_ITEM_CHRG_WCODE_TYPE" NUMBER(1, 0), "AP_ITEM_CHRG_USE_PRD" NUMBER(1, 0),
 "ALLWD_RE_PUR_SERIALNO" NUMBER(1, 0), "USE_SHPNG_LST" NUMBER, "AP_DISC_PRD" NUMBER,
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE,
 "UPDATE_QT_PRM_SAL" NUMBER, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "AP_ITEM_CHRG_CALC_AMT_TYPE"
 NUMBER(1, 0), "USE_POST_TAX_DUE" NUMBER(1, 0), "USE_VNDR_PRICE_LST" NUMBER,
 "SHW_ITEM_SIZE" NUMBER, "CONN_VNDR_PRICE_PO" NUMBER, "ADD_FRC_INVOICE_PI" NUMBER(1, 0),
 "USE_ARBIC_SRCH_ICODE" NUMBER(1, 0), "USE_SAL_PRICE_AS_PUR_PRICE" NUMBER(1, 0),
 "LVL_NO_PRICE" NUMBER(3, 0), "USE_VNDR_CLAIM" NUMBER(1, 0), "RET_PI_FREE_QTY_PER"
 NUMBER(1, 0), "USE_PI_CLC_TAX_FREE_QTY" NUMBER(1, 0), "ADD_ITM_PRICE_FROM_PO" NUMBER(1,
 0), "USE_DELIVERD" NUMBER(1, 0), "SHOW_ICODE_VNDR_AP" NUMBER(1, 0))  PCTFREE 10 PCTUSED
 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL KEEP) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_MOBILE_NTFCTN" ("SYS_NO" NUMBER(5, 0), "U_ID" NUMBER(5, 0), "DVC_TOKEN"
 VARCHAR2(300), "DVS_TYP" NUMBER, "HND_DVC_SRL" VARCHAR2(60), "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "HND_DVS_SRL" VARCHAR2(60))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

