CREATE TABLE "CNTRY" ("CNTRY_NO" NUMBER(4, 0), "CNTRY_A_NAME" VARCHAR2(100) NOT NULL
 ENABLE, "CNTRY_E_NAME" VARCHAR2(100), "CNTRY_SHRT" VARCHAR2(10), "CNTRY_CNTNT"
 VARCHAR2(20), "CUR_NO" NUMBER(4, 0), "CUR_CODE" VARCHAR2(7), "CNTRY_ANTION" VARCHAR2(15)
, "CNTRY_ENTION" VARCHAR2(15), "NTION_SHRT" VARCHAR2(10), "ZONE_NO" NUMBER(4, 0),
 "NOT_ALLW_DEAL_WTH" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "PHONE_KEY" VARCHAR2(10)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP"
 LOGGING NOCOMPRESS;

CREATE TABLE "CITIES" ("CITY_NO" NUMBER(10, 0), "CITY_A_NAME" VARCHAR2(100) NOT NULL
 ENABLE, "CITY_E_NAME" VARCHAR2(100), "PROV_NO" NUMBER(10, 0), "CNTRY_NO" NUMBER(4, 0),
 "CITY_SHRT" VARCHAR2(10), "ZONE_NO" NUMBER(4, 0), "CITY_SER" NUMBER, "AD_U_ID" NUMBER(5,
 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING
 NOCOMPRESS;

CREATE TABLE "REGIONS" ("R_CODE" NUMBER(10, 0), "R_A_NAME" VARCHAR2(100) NOT NULL ENABLE,
 "R_E_NAME" VARCHAR2(100), "CNTRY_NO" NUMBER(4, 0), "PROV_NO" NUMBER(10, 0), "CITY_NO"
 NUMBER(10, 0), "RGN_SHRT" VARCHAR2(10), "ZONE_NO" NUMBER(4, 0), "AD_U_ID" NUMBER(5, 0),
 "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING
 NOCOMPRESS;

CREATE TABLE "CREDIT_CARD_TYPES" ("CR_CARD_NO" NUMBER(5, 0), "CR_CARD_NAME" VARCHAR2(100)
 NOT NULL ENABLE, "CR_CARD_E_NAME" VARCHAR2(100), "BANK_AC" VARCHAR2(30), "COMM_AC"
 VARCHAR2(30), "COMM_PER" NUMBER(7, 4), "COMM_CALC_TYPE" NUMBER(1, 0), "DUE_PERIOD"
 NUMBER(3, 0), "CR_CARD_TYPE" NUMBER(2, 0), "MACHINE_NO_BANK" NUMBER(10, 0), "MACHINE_NO"
 NUMBER(5, 0), "W_CODE" NUMBER(10, 0), "ACODE_REC_LETTER" VARCHAR2(30), "BANK_NO"
 NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "COMM_AMT" NUMBER, "MAX_COMM_PER" NUMBER, "MAX_COMM_AMT"
 NUMBER, "A_CY_MAX_COMM" VARCHAR2(7), "CONN_BRN_NO" NUMBER(6, 0), "CONN_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_CRNCY_USR_LMT" ("CUR_CODE" VARCHAR2(7), "USER_NO" NUMBER(5, 0),
 "MAX_CUR_RATE" NUMBER, "MIN_CUR_RATE" NUMBER, "CUR_RATE" NUMBER, "MIN_PYMNT_RATE" NUMBER
, "MAX_PYMNT_RATE" NUMBER, "MIN_RCVD_RATE" NUMBER, "MAX_RCVD_RATE" NUMBER, "CONN_BRN_NO"
 NUMBER(6, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE"
 DATE, "PR_REP" NUMBER(6, 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

