CREATE TABLE "IAS_ATTACH_MST" ("ATTCH_NO" NUMBER(1, 0), "ATTCH_A_NAME" VARCHAR2(30),
 "ATTCH_E_NAME" VARCHAR2(30), "OPTIONAL" NUMBER, "CONN_C_CODE" NUMBER, "AD_U_ID" NUMBER(5
, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE
 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ATTCH" LOGGING
 NOCOMPRESS;

CREATE TABLE "IAS_ATTACH_DTL" ("ATTCH_NO" NUMBER(1, 0), "ATTCH_DESC_NO" NUMBER(3, 0),
 "ATTCH_DESC_A_NAME" VARCHAR2(100), "ATTCH_DESC_E_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5
, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ATTCH"
 LOGGING NOCOMPRESS;

CREATE TABLE "S_LIB_FILE" ("FILE_NAME" VARCHAR2(100), "LIB_VERSION_UPDT" VARCHAR2(100),
 "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_TRMNL_NM" VARCHAR2(50), "CREATED_DATE" DATE,
 "ACCESSED_DATE" DATE, "MODIFIED_DATE" DATE, "FILE_SIZE" NUMBER)  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "S_SEQ_CTL" ("S_TAB_NAME" VARCHAR2(30) NOT NULL ENABLE, "S_COL_NAME"
 VARCHAR2(30) NOT NULL ENABLE, "S_SEQ_TYP" NUMBER(1, 0), "S_COL1" VARCHAR2(30), "S_COL2"
 VARCHAR2(30), "S_COL3" VARCHAR2(30), "S_COL4" VARCHAR2(30), "S_COL5" VARCHAR2(30),
 "S_COL6" VARCHAR2(30), "S_INCRBY_VAL" NUMBER(3, 0), "S_INIT_VAL" NUMBER(3, 0),
 "S_SEQ_CONC" VARCHAR2(300), "TRIG_NAME" VARCHAR2(50), "ONLY_IF_NULL" NUMBER(1, 0),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0) NOT NULL ENABLE, "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "S_SEQ_VALUES" ("S_TAB_NAME" VARCHAR2(30), "S_COL_NAME" VARCHAR2(30),
 "S_VAL1" NUMBER(20, 0), "S_VAL2" NUMBER(20, 0), "S_VAL3" NUMBER(20, 0), "S_VAL4"
 NUMBER(20, 0), "S_VAL5" NUMBER(20, 0), "S_VAL6" NUMBER(20, 0), "S_INCRBY_VAL" NUMBER(3,
 0), "S_INIT_VAL" NUMBER(3, 0), "S_SEQ_VAL" NUMBER(20, 0), "S_SEQ_TYP" NUMBER(1, 0),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "NOTE" ("NOTE_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "NOTE_TYPE_NO" NUMBER(3,
 0), "NOTE_NO" NUMBER(15, 0) NOT NULL ENABLE, "NOTE_SER" NUMBER(38, 0), "NOTE_DATE" DATE,
 "A_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY"
 VARCHAR2(7), "C_CODE" VARCHAR2(15), "V_CODE" VARCHAR2(15), "PROCESSED" NUMBER(1, 0),
 "APPROVED" NUMBER(1, 0), "APRV_U_ID" NUMBER(5, 0), "APRV_DATE" DATE, "APRV_DSC"
 VARCHAR2(500), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15),
 "FIELD1" VARCHAR2(100), "FIELD2" VARCHAR2(100), "FIELD3" VARCHAR2(100), "FIELD4"
 VARCHAR2(100), "FIELD5" VARCHAR2(100), "FIELD6" VARCHAR2(100), "FIELD7" VARCHAR2(100),
 "FIELD8" VARCHAR2(100), "FIELD9" VARCHAR2(100), "FIELD10" VARCHAR2(100), "AD_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT
 NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50)
, "UP_TRMNL_NM" VARCHAR2(50), "EXTERNAL_POST" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "NOTE_DETAIL" ("NOTE_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "NOTE_TYPE_NO"
 NUMBER(3, 0), "NOTE_NO" NUMBER(15, 0) NOT NULL ENABLE, "NOTE_SER" NUMBER(38, 0),
 "NOTE_DESC" VARCHAR2(250), "NOTE_AMT" NUMBER, "NOTE_AMTF" NUMBER, "NOTE_RATE" NUMBER,
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "EXTERNAL_POST" NUMBER(5,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GL_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_LOGS" ("F_SYS" VARCHAR2(15), "DOC_TYPE" NUMBER(5, 0), "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE, "LOG_DATE" DATE, "LOG_DESC" VARCHAR2(250), "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50)
, "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "S_LOGS" ("AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50)
, "FORM_NO" NUMBER, "LOG_CNT" NUMBER, "LOG_DESC" VARCHAR2(4000))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "BACKUP" ("BK_NO" NUMBER(15, 0), "BK_NAME" VARCHAR2(100), "FILE_NAME"
 VARCHAR2(100), "BK_DATE" DATE, "ENC_PASSWD" VARCHAR2(30), "AD_U_ID" NUMBER(5, 0),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_ADM_DATA" LOGGING NOCOMPRESS;

