CREATE TABLE "STN_COUNTERS" ("CUNTR_NO" NUMBER(10, 0), "CUNTR_L_NM" VARCHAR2(60),
 "CUNTR_F_NM" VARCHAR2(60), "FUEL_TYP_NO" NUMBER(5, 0), "W_CODE" NUMBER(10, 0),
 "PRIMARY_READ" NUMBER, "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE" DATE NOT NULL
 ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "PR_REP" NUMBER(10, 0), "UP_CNT" NUMBER(10, 0), "INACTIVE" NUMBER(1, 0), "INACTIVE_DATE"
 DATE, "INACTIVE_RES" VARCHAR2(250), "INACTIVE_U_ID" NUMBER(5, 0), "CUNTR_CODE"
 VARCHAR2(60), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "STN_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STN_BILL_MST" ("DOC_NO" NUMBER(15, 0), "DOC_SER" NUMBER(38, 0), "CASH_NO"
 NUMBER(10, 0), "A_CY" VARCHAR2(7), "A_CODE" VARCHAR2(30), "INC_A_CODE" VARCHAR2(30),
 "CUR_RATE" NUMBER, "COL_NO" NUMBER(10, 0), "EMP_NO" NUMBER(10, 0), "REF_NO" VARCHAR2(15)
, "DOC_DSC" VARCHAR2(500), "FIELD1" VARCHAR2(250), "FIELD2" VARCHAR2(250), "FIELD3"
 VARCHAR2(250), "FIELD4" VARCHAR2(250), "FIELD5" VARCHAR2(250), "FIELD6" VARCHAR2(250),
 "FIELD7" VARCHAR2(250), "FIELD8" VARCHAR2(250), "FIELD9" VARCHAR2(250), "FIELD10"
 VARCHAR2(250), "CSH_AMT" NUMBER, "CR_AMT" NUMBER, "CPN_AMT" NUMBER, "BILL_AMT" NUMBER,
 "DEC_AMT" NUMBER, "INC_AMT" NUMBER, "W_CODE" NUMBER(10, 0), "STAND_BY" NUMBER(1, 0),
 "DISC_AMT" NUMBER, "VAT_AMT" NUMBER, "CLC_TYP_NO_TAX" NUMBER(5, 0), "WHTRNS_AMT" NUMBER,
 "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE" DATE NOT NULL ENABLE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(10, 0), "UP_CNT" NUMBER(10, 0), "CMP_NO"
 NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4
, 0), "BRN_USR" NUMBER(3, 0), "DOC_DATE" DATE, "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC"
 VARCHAR2(500), "AUDIT_REF_U_ID" NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "SI_TYPE" NUMBER(5,
 0), "INC_AC_CODE_DTL" VARCHAR2(30), "INC_AC_DTL_TYP" NUMBER(2, 0), "DOC_PST" NUMBER(1,
 0), "PRD_NO" NUMBER(5, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "REP_CODE" VARCHAR2(15), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50), "OUT_AMT" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "STN_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STN_BILL_DTL" ("DOC_NO" NUMBER(15, 0), "DOC_SER" NUMBER(38, 0), "RCRD_NO"
 NUMBER(10, 0), "CUNTR_NO" NUMBER(10, 0), "CUNTR_READ_PREV" NUMBER, "CUNTR_READ_CRNT"
 NUMBER, "I_QTY" NUMBER, "I_PRICE" NUMBER, "LAST_READ_DATE" DATE, "CUNTR_DSC"
 VARCHAR2(250), "BATCH_NO" VARCHAR2(30), "DIS_PER" NUMBER(20, 17), "DIS_AMT" NUMBER,
 "DISC_AMT_MST" NUMBER, "CRNT_READ_DATE" DATE, "SI_TYPE" NUMBER(5, 0), "I_CODE"
 VARCHAR2(30), "W_CODE" NUMBER(10, 0), "FUEL_TYP_NO" NUMBER(5, 0), "EMP_NO" NUMBER(10, 0)
, "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "VAT_AMT"
 NUMBER(24, 9), "VAT_PER" NUMBER(7, 4), "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE"
 DATE NOT NULL ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "STN_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STN_BILL_COUPON" ("DOC_NO" NUMBER(15, 0), "DOC_SER" NUMBER(38, 0), "CPN_NO"
 NUMBER(20, 0), "FUEL_TYP_NO" NUMBER(5, 0), "C_CODE" VARCHAR2(15), "I_QTY" NUMBER,
 "I_PRICE" NUMBER, "ISSUE_DATE" DATE, "EXPIRE_DATE" DATE, "CPN_DSC" VARCHAR2(250),
 "BATCH_NO" VARCHAR2(30), "DIS_PER" NUMBER(20, 17), "DIS_AMT" NUMBER, "DISC_AMT_MST"
 NUMBER, "EMP_NO" NUMBER(10, 0), "I_CODE" VARCHAR2(30), "W_CODE" NUMBER(10, 0),
 "CUNTR_NO" NUMBER(10, 0), "RCRD_NO" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO"
 VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "VAT_AMT" NUMBER(24, 9), "VAT_PER" NUMBER(7, 4),
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(10, 0), "UP_CNT" NUMBER(10, 0),
 "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR"
 NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "STN_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STN_BILL_CRDT" ("DOC_NO" NUMBER(15, 0), "DOC_SER" NUMBER(38, 0), "BILL_NO"
 NUMBER(15, 0), "FUEL_TYP_NO" NUMBER(5, 0), "C_CODE" VARCHAR2(15), "I_QTY" NUMBER,
 "I_PRICE" NUMBER, "ISSUE_DATE" DATE, "EXPIRE_DATE" DATE, "BILL_DSC" VARCHAR2(250),
 "EMP_NO" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "I_CODE" VARCHAR2(30), "W_CODE" NUMBER(10, 0), "CUNTR_NO" NUMBER(10, 0),
 "RCRD_NO" NUMBER(10, 0), "BATCH_NO" VARCHAR2(30), "DIS_PER" NUMBER(20, 17), "DIS_AMT"
 NUMBER, "DISC_AMT_MST" NUMBER, "VAT_AMT" NUMBER(24, 9), "VAT_PER" NUMBER(7, 4),
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL
 ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "STN_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STN_CRDT_BILL_MST" ("DOC_SER" NUMBER(38, 0) NOT NULL ENABLE, "DOC_DATE"
 DATE NOT NULL ENABLE, "FUEL_TYP_NO" NUMBER(5, 0), "DOC_NO" NUMBER(5, 0), "F_BILL_NO"
 NUMBER(15, 0), "T_BILL_NO" NUMBER(15, 0), "REF_NO" VARCHAR2(15), "DOC_DSC" VARCHAR2(500)
, "C_CODE" VARCHAR2(15), "ISSUE_DATE" DATE, "EXPIRE_DATE" DATE, "T_FUEL_TYP_NO" NUMBER(6,
 0), "MOVE_DOC_PY" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE" DATE
 NOT NULL ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "PR_REP" NUMBER(10, 0), "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50)
, "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "STN_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "STN_CRDT_BILL_DTL" ("BILL_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0) NOT NULL ENABLE, "DOC_NO" NUMBER(15, 0), "PRCSSD_FLG" NUMBER(1, 0),
 "INACTIVE" NUMBER(1, 0), "INACTIVE_U_ID" NUMBER(5, 0), "INACTIVE_DATE" DATE,
 "INACTIVE_RES" VARCHAR2(250), "MOVE_BILL_PY" NUMBER(1, 0), "DOC_NO_PY" NUMBER(15, 0),
 "DOC_SER_PY" NUMBER(38, 0), "P_YEAR" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0) NOT NULL
 ENABLE, "AD_DATE" DATE NOT NULL ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL
 ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "C_CODE" VARCHAR2(15),
 "FUEL_TYP_NO" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "STN_DATA_TRNS" LOGGING NOCOMPRESS;

