CREATE TABLE "CASH_IN_HAND" ("CASH_NO" NUMBER(10, 0), "CASH_NAME" VARCHAR2(100) NOT NULL
 ENABLE, "CASH_E_NAME" VARCHAR2(100), "A_CODE" VARCHAR2(30) NOT NULL ENABLE, "CASH_SR"
 NUMBER(10, 0) NOT NULL ENABLE, "CASH_TYPE" NUMBER(1, 0), "USE_CASH_INCOME" NUMBER(1, 0),
 "POS_SYS" NUMBER(1, 0), "CONN_BRN_NO" NUMBER(6, 0), "CONF_LAST_DATE" DATE, "INACTIVE"
 NUMBER(1, 0), "INACTIVE_DATE" DATE, "INACTIVE_RES" VARCHAR2(250), "AD_U_ID" NUMBER(5, 0)
, "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "RCPT_SRL_TYP" NUMBER(2, 0), "PYMNT_TYP_NO_DFLT" NUMBER(2, 0), "RCVD_TYP_NO_DFLT"
 NUMBER(2, 0), "MEDIATOR" NUMBER(1, 0), "GROUP_NO" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CASH_IN_HAND_DTL" ("CASH_NO" NUMBER(10, 0), "A_CODE" VARCHAR2(30) NOT
 NULL ENABLE, "A_CY" VARCHAR2(7), "OPEN_BAL_L" NUMBER, "OPEN_BAL_F" NUMBER, "CURR_BAL_L"
 NUMBER, "CURR_BAL_F" NUMBER, "INACTIVE" NUMBER(1, 0), "MIN_LMT_AMT" NUMBER,
 "MAX_LMT_AMT" NUMBER, "MAX_LMT_TRNS_AMT" NUMBER, "MIN_LMT_TRNS_AMT" NUMBER, "PASS_LMT"
 NUMBER(1, 0), "INACTIVE_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "CASH_AT_BANK" ("BANK_NO" NUMBER(10, 0), "A_CODE" VARCHAR2(30) NOT NULL
 ENABLE, "BANK_NAME" VARCHAR2(100) NOT NULL ENABLE, "BANK_E_NAME" VARCHAR2(100),
 "BANK_SR" NUMBER(10, 0) NOT NULL ENABLE, "GROUP_NO" NUMBER(10, 0), "BANK_ACC"
 VARCHAR2(30), "CONN_BRN_NO" NUMBER(6, 0), "B_TEL" VARCHAR2(30), "B_FAX" VARCHAR2(30),
 "B_BOX" VARCHAR2(10), "B_ADDRESS" VARCHAR2(60), "B_E_MAIL" VARCHAR2(50), "B_WEB_SITE"
 VARCHAR2(50), "CNTRY_NO" NUMBER(4, 0), "CITY_NO" NUMBER(10, 0), "MEDIATOR" NUMBER(1, 0),
 "INACTIVE" NUMBER(1, 0), "INACTIVE_DATE" DATE, "INACTIVE_RES" VARCHAR2(250), "BANK_IMG"
 VARCHAR2(30), "REC_LETTER" VARCHAR2(30), "PAY_LETTER" VARCHAR2(30), "CHQ_PAY_INTRM_AC"
 VARCHAR2(30), "REP_SMPLE" NUMBER(2, 0), "CONF_LAST_DATE" DATE, "OCHK_AUTO_SER" NUMBER(38
, 0), "BANK_CODE" NUMBER(30, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "RCPT_SRL_TYP" NUMBER(2, 0),
 "PYMNT_TYP_NO_DFLT" NUMBER(2, 0), "RCVD_TYP_NO_DFLT" NUMBER(2, 0), "BNK_NTWRK_CODE"
 VARCHAR2(200))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CASH_AT_BANK_DTL" ("BANK_NO" NUMBER(10, 0), "A_CODE" VARCHAR2(30) NOT
 NULL ENABLE, "A_CY" VARCHAR2(7), "OPEN_BAL_L" NUMBER, "OPEN_BAL_F" NUMBER, "CURR_BAL_L"
 NUMBER, "CURR_BAL_F" NUMBER, "INACTIVE" NUMBER(1, 0), "INACTIVE_DATE" DATE,
 "MIN_LMT_AMT" NUMBER, "MAX_LMT_AMT" NUMBER, "MAX_LMT_TRNS_AMT" NUMBER,
 "MIN_LMT_TRNS_AMT" NUMBER, "PASS_LMT" NUMBER(1, 0), "BNK_AC" VARCHAR2(30), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10
, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT"
 LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CASH_AT_BANK_BRN" ("BRN_BANK_NO" NUMBER(3, 0), "BANK_NO" NUMBER(10, 0),
 "A_CODE" VARCHAR2(30) NOT NULL ENABLE, "OPEN_BAL_L" NUMBER, "OPEN_BAL_F" NUMBER,
 "CURR_BAL_L" NUMBER, "CURR_BAL_F" NUMBER, "INACTIVE" NUMBER(1, 0), "INACTIVE_DATE" DATE,
 "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT"
 NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM"
 VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CASH_GROUP" ("GROUP_NO" NUMBER(10, 0), "GROUP_NAME" VARCHAR2(60),
 "GROUP_E_NAME" VARCHAR2(60), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "AD_TRMNL_NM"
 VARCHAR2(50), "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_TRMNL_NM" VARCHAR2(50),
 "PR_REP" NUMBER(6, 0), "UP_CNT" NUMBER(10, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_BANK_GROUP" ("GROUP_NO" NUMBER(10, 0), "GROUP_NAME" VARCHAR2(60) NOT
 NULL ENABLE, "GROUP_E_NAME" VARCHAR2(60), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_BANK_ADJUST_MST" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "DOC_DATE" DATE, "BANK_NO" NUMBER(10, 0) NOT NULL ENABLE, "A_CODE"
 VARCHAR2(30) NOT NULL ENABLE, "A_CY" VARCHAR2(7) NOT NULL ENABLE, "BRN_BANK_NO" NUMBER(3
, 0), "BANK_BAL_IN_BANK" NUMBER, "BANK_BAL_IN_CMP" NUMBER, "PROCESSED" NUMBER(1, 0),
 "JV_DOC" NUMBER(1, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "PR_REP" NUMBER(10, 0), "TYP_NO"
 NUMBER(10, 0), "REF_NO" VARCHAR2(15), "EX_RATE" NUMBER, "STAND_BY" NUMBER(1, 0),
 "ATTACH_NO" NUMBER(3, 0), "DOC_SQ" NUMBER(38, 0), "DOC_TYP_REF" NUMBER(10, 0),
 "DOC_JV_TYP_REF" NUMBER(10, 0), "DOC_NO_REF" NUMBER(30, 0), "DOC_SRL_REF" NUMBER(38, 0),
 "DOC_SQ_REF" NUMBER(38, 0), "DOC_DSC" VARCHAR2(750), "DOC_POST" NUMBER(1, 0),
 "POST_U_ID" NUMBER(5, 0), "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE"
 DATE, "AUDIT_REF" NUMBER(1, 0), "AUDIT_REF_DESC" VARCHAR2(500), "AUDIT_REF_U_ID"
 NUMBER(5, 0), "AUDIT_REF_DATE" DATE, "EXTERNAL_POST" NUMBER(5, 0), "CC_CODE"
 VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_BANK_ADJUST_DTL" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SER"
 NUMBER(38, 0), "BANK_NO" NUMBER(10, 0), "A_CODE" VARCHAR2(30) NOT NULL ENABLE,
 "AC_CODE_DTL" VARCHAR2(30), "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7) NOT NULL
 ENABLE, "BRN_BANK_NO" NUMBER(3, 0), "BANK_BAL" NUMBER, "DOC_DESC" VARCHAR2(250), "J_AMT"
 NUMBER, "J_AMT_F" NUMBER, "RCRD_NO" NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_DATE"
 DATE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE,
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0),
 "UP_CNT" NUMBER(10, 0), "CC_CODE" VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO"
 VARCHAR2(15), "REF_NO" VARCHAR2(15), "DOC_BRN_NO" NUMBER, "DOC_TYP_REF" NUMBER(10, 0),
 "DOC_JV_TYP_REF" NUMBER(10, 0), "DOC_NO_REF" NUMBER(30, 0), "DOC_SRL_REF" NUMBER(38, 0),
 "DOC_SQ_REF" NUMBER(38, 0), "DOC_SQ" NUMBER(38, 0), "EX_RATE" NUMBER, "AC_CODE_DTL_SUB"
 VARCHAR2(30))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_GL_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_BNK_CHQ_MST" ("BANK_NO" NUMBER(10, 0), "BOOK_NO" NUMBER(10, 0) NOT NULL
 ENABLE, "F_CHQ_NO" NUMBER(20, 0), "T_CHQ_NO" NUMBER(20, 0), "REF_NO" VARCHAR2(30),
 "CUR_CODE" VARCHAR2(7), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GL_INPT" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_BNK_CHQ_DTL" ("BANK_NO" NUMBER(10, 0), "CUR_CODE" VARCHAR2(7),
 "BOOK_NO" NUMBER(10, 0) NOT NULL ENABLE, "CHQ_NO" NUMBER(20, 0), "CHQ_ST" NUMBER(1, 0)
 NOT NULL ENABLE, "DOC_NO_REF" NUMBER(30, 0), "DOC_SRL_REF" NUMBER(38, 0), "DOC_DATE_REF"
 DATE, "NOTES" VARCHAR2(250), "CHQ_SGNTR" NUMBER(1, 0), "SGNTR_DATE" DATE, "SGNTR_PRSN"
 VARCHAR2(60), "RCVD_PRSN" VARCHAR2(60), "NOTES_CHQ_ST" VARCHAR2(250), "DOC_TYP_REF"
 NUMBER(10, 0), "DOC_JV_TYP_REF" NUMBER(10, 0), "USR_NO_CHQ_ST" NUMBER(10, 0),
 "DATE_CHQ_ST" DATE, "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED
 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_JV" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_BNK_IDNTF_MST" ("DOC_TYP" NUMBER(5, 0) NOT NULL ENABLE, "DOC_JV_TYP"
 NUMBER(10, 0) NOT NULL ENABLE, "DOC_NO" NUMBER(30, 0) NOT NULL ENABLE, "DOC_SRL"
 NUMBER(38, 0), "DOC_M_SQ" NUMBER(38, 0), "DOC_DATE" DATE NOT NULL ENABLE, "F_DATE" DATE,
 "T_DATE" DATE, "AC_CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, "AC_CODE_DTL" VARCHAR2(30
 CHAR), "AC_CODE_DTL_SUB" VARCHAR2(30 CHAR), "AC_DTL_TYP" NUMBER(2, 0), "IDNTF_CHQ_NO"
 NUMBER(1, 0), "IDNTF_NT_NO_BNK" NUMBER(1, 0), "IDNTF_REF_NO" NUMBER(1, 0), "CUR_CODE"
 VARCHAR2(7 CHAR) NOT NULL ENABLE, "DOC_DSC" VARCHAR2(1000 CHAR), "REF_NO" VARCHAR2(15
 CHAR), "MNL_NO" VARCHAR2(20 CHAR), "FLD1" VARCHAR2(250 CHAR), "FLD2" VARCHAR2(250 CHAR),
 "FLD3" VARCHAR2(250 CHAR), "FLD4" VARCHAR2(250 CHAR), "FLD5" VARCHAR2(250 CHAR), "FLD6"
 VARCHAR2(250 CHAR), "FLD7" VARCHAR2(250 CHAR), "FLD8" VARCHAR2(250 CHAR), "FLD9"
 VARCHAR2(250 CHAR), "FLD10" VARCHAR2(250 CHAR), "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE,
 "AD_DATE" DATE NOT NULL ENABLE, "AD_TRMNL_NM" VARCHAR2(50 CHAR), "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_TRMNL_NM" VARCHAR2(50 CHAR), "UP_CNT" NUMBER(10, 0), "BRN_NO"
 NUMBER(6, 0) NOT NULL ENABLE, "BRN_USR" NUMBER(10, 0), "BRN_YEAR" NUMBER(4, 0) NOT NULL
 ENABLE, "CC_CODE" VARCHAR2(30 CHAR), "PJ_NO" VARCHAR2(15 CHAR), "ACTV_NO" VARCHAR2(15
 CHAR), "PR_REP" NUMBER(6, 0), "TYP_SRL" NUMBER(5, 0), "APPROVED" NUMBER(1, 0),
 "APRV_U_ID" NUMBER(5, 0), "APRV_DATE" DATE, "APRV_DSC" VARCHAR2(500 CHAR), "PRCSSD_FLG"
 NUMBER(1, 0), "INACTIVE" NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(250 CHAR),
 "INACTIVE_U_ID" NUMBER(5, 0), "INACTIVE_DATE" DATE, "STNDBY_FLG" NUMBER(1, 0) NOT NULL
 ENABLE, "STNDBY_U_ID" NUMBER(10, 0), "STNDBY_DATE" DATE, "STNDBY_DSC" VARCHAR2(500 CHAR)
, "CRT_DATE_CLK" DATE, "ATTACH_NO" NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1
 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS
 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_VCHR" LOGGING NOCOMPRESS;

CREATE TABLE "GLS_BNK_IDNTF_DTL" ("STMNT_TYP" NUMBER(1, 0), "DOC_NO" NUMBER(15, 0) NOT
 NULL ENABLE, "DOC_SRL" NUMBER(38, 0) NOT NULL ENABLE, "DOC_M_SQ" NUMBER(38, 0),
 "DOC_D_SQ" NUMBER(38, 0), "RCRD_NO" NUMBER(10, 0), "AC_CODE" VARCHAR2(30 CHAR),
 "AC_CODE_DTL" VARCHAR2(30 CHAR), "AC_DTL_TYP" NUMBER(2, 0), "CUR_CODE" VARCHAR2(7 CHAR)
 NOT NULL ENABLE, "CHQ_NO" NUMBER(20, 0), "CHQ_DATE" DATE, "DR_AMT" NUMBER, "CR_AMT"
 NUMBER, "NT_NO_BNK" VARCHAR2(20 CHAR), "REF_NO" VARCHAR2(30 CHAR), "DOC_D_DSC"
 VARCHAR2(500 CHAR), "IDNTF_FLG" NUMBER(1, 0), "IDNTF_MNL_FLG" NUMBER(1, 0), "AD_U_ID"
 NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE" DATE NOT NULL ENABLE, "AD_TRMNL_NM" VARCHAR2(50
 CHAR), "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_TRMNL_NM" VARCHAR2(50 CHAR), "UP_CNT"
 NUMBER(10, 0), "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0) NOT NULL
 ENABLE, "BRN_USR" NUMBER(3, 0), "CC_CODE" VARCHAR2(30 CHAR), "PJ_NO" VARCHAR2(15 CHAR),
 "ACTV_NO" VARCHAR2(15 CHAR), "DOC_TYP_REF" NUMBER(5, 0), "DOC_NO_REF" NUMBER(30, 0),
 "DOC_SRL_REF" NUMBER(38, 0), "DOC_D_SQ_REF" NUMBER(38, 0))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_DATA_VCHR" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_CHEQ_TRACE" ("AUD_TYPE" NUMBER(1, 0) NOT NULL ENABLE, "VOUCHER_TYPE"
 NUMBER(1, 0) NOT NULL ENABLE, "VOUCHER_PAY_TYPE" NUMBER(1, 0) NOT NULL ENABLE,
 "VOUCHER_NO" NUMBER(15, 0) NOT NULL ENABLE, "CASH_NO" NUMBER(10, 0) NOT NULL ENABLE,
 "V_SER" NUMBER(38, 0) NOT NULL ENABLE, "A_CODE" VARCHAR2(30), "AC_CODE_DTL" VARCHAR2(30)
, "AC_DTL_TYP" NUMBER(2, 0), "A_CY" VARCHAR2(7), "AC_DESC" VARCHAR2(250), "RETURN_RES"
 VARCHAR2(250), "AC_AMT" NUMBER, "AC_AMTF" NUMBER, "CC_CODE" VARCHAR2(30), "C_CODE"
 VARCHAR2(15), "V_CODE" VARCHAR2(15), "CHEQ_TYPE" NUMBER(2, 0), "CSH_BNK_NO" NUMBER(10,
 0), "CHEQUE_NO" VARCHAR2(20), "VALUE_DATE" DATE, "CHEQUE_POST" NUMBER(1, 0),
 "CHEQUE_VALUED" NUMBER(1, 0), "NOTE_NO" VARCHAR2(30), "BANK_NO" NUMBER(10, 0), "REF_NO"
 VARCHAR2(15), "RCRD_NO" NUMBER(10, 0), "ENDRSMNT" NUMBER(1, 0), "A_CODE_END"
 VARCHAR2(30), "AC_CODE_DTL_END" VARCHAR2(30), "AC_DTL_TYP_END" NUMBER(2, 0),
 "C_CODE_END" VARCHAR2(15), "V_CODE_END" VARCHAR2(15), "EXTERNAL_POST" NUMBER(5, 0),
 "DOC_SEQUENCE" NUMBER(38, 0), "DOC_TYPE_REF" NUMBER(5, 0), "DOC_JV_TYPE_REF" NUMBER(5,
 0), "DOC_NO_REF" NUMBER(15, 0), "DOC_SER_REF" NUMBER(38, 0), "POST_U_ID" NUMBER(5, 0),
 "POST_DATE" DATE, "UNPOST_U_ID" NUMBER(5, 0), "UNPOST_DATE" DATE, "AUD_U_ID" NUMBER(5,
 0), "AUD_DATE" DATE, "CMP_NO" NUMBER(3, 0) NOT NULL ENABLE, "BRN_NO" NUMBER(6, 0) NOT
 NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0), "UP_CNT" NUMBER(10, 0),
 "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50),
 "ENDRSMNT_DATE" DATE)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_DATA_VCHR" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_TRUST_MST" ("TRUST_NO" NUMBER(15, 0) NOT NULL ENABLE, "TRUST_SER"
 NUMBER(38, 0), "TRUST_DATE" DATE, "A_DESC" VARCHAR2(250), "REF_NO" VARCHAR2(15),
 "EMP_NO" NUMBER(10, 0), "W_CODE" NUMBER(3, 0), "PROCESSED" NUMBER(1, 0), "PR_REP"
 NUMBER(10, 0), "AD_U_ID" NUMBER(5, 0), "AD_TRMNL_NM" VARCHAR2(50), "AD_DATE" DATE,
 "UP_TRMNL_NM" VARCHAR2(50), "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10,
 0), "CMP_NO" NUMBER(2, 0), "BRN_NO" NUMBER(3, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT
 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_DATA_TRNS" LOGGING NOCOMPRESS;

CREATE TABLE "IAS_TRUST_DTL" ("TRUST_NO" NUMBER(15, 0) NOT NULL ENABLE, "TRUST_SER"
 NUMBER(38, 0), "I_CODE" VARCHAR2(30), "W_CODE" NUMBER(3, 0), "I_QTY" NUMBER, "ITM_UNT"
 VARCHAR2(10) NOT NULL ENABLE, "P_SIZE" NUMBER, "RCRD_NO" NUMBER(10, 0), "CMP_NO"
 NUMBER(2, 0), "BRN_NO" NUMBER(3, 0), "BRN_YEAR" NUMBER(4, 0), "BRN_USR" NUMBER(3, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_INV_DATA_TRNS" LOGGING NOCOMPRESS;

