CREATE TABLE "ALL_BRANCHES" ("CMP_GRP" NUMBER(1, 0), "CMP_NO" NUMBER(3, 0) NOT NULL
 ENABLE, "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_USR"
 NUMBER(3, 0), "BRN_LNAME" VARCHAR2(40), "BRN_FNAME" VARCHAR2(40))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_ADM_DATA" LOGGING NOCOMPRESS;

CREATE TABLE "APX_FVRT_SCR" ("SCR_NO" NUMBER(5, 0), "U_ID" NUMBER(5, 0), "ORDR_NO"
 NUMBER(10, 0), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "APX_SCR" ("SCR_NO" NUMBER(5, 0), "LABEL_NO" NUMBER(10, 0), "SCR_PARNT_NO"
 NUMBER(5, 0), "INACTIVE" NUMBER(1, 0), "ORDR_NO" NUMBER(5, 0), "SCR_TYP" NUMBER(2, 0),
 "FILE_NM" VARCHAR2(50), "SCR_ICON" VARCHAR2(100), "DFLT_FLG" NUMBER(1, 0), "MOB_FILE_NM"
 VARCHAR2(50), "MOB_SCR_ICON" VARCHAR2(100), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10,
 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1
 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING NOCOMPRESS;

CREATE TABLE "APX_SCR_PRV" ("SCR_NO" NUMBER(5, 0), "U_ID" NUMBER(5, 0), "INC_FLG"
 NUMBER(1, 0), "AD_DATE" DATE, "AD_U_ID" NUMBER(5, 0), "UP_CNT" NUMBER(10, 0), "PR_REP"
 NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10
 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_GEN" LOGGING
 NOCOMPRESS;

CREATE TABLE "ARS_ANSWR_QUESTNNR_DTL" ("RCRD_NO" NUMBER, "MODL_NO" NUMBER(5, 0) NOT NULL
 ENABLE, "ANSWR_NO" NUMBER(15, 0) NOT NULL ENABLE, "ANSWR_L_NAME" VARCHAR2(1000) NOT NULL
 ENABLE, "ANSWR_F_NAME" VARCHAR2(1000), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE, "UP_U_ID"
 NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "ARS_ANSWR_QUESTNNR_MST" ("MODL_NO" NUMBER(5, 0), "MODL_L_NAME"
 VARCHAR2(100), "MODL_F_NAME" VARCHAR2(100), "AD_U_ID" NUMBER(5, 0), "AD_DATE" DATE,
 "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "PR_REP" NUMBER(6, 0), "UP_CNT" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;

CREATE TABLE "ARS_AUTO_SLS_ORDR_DTL" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SRL"
 NUMBER(38, 0) NOT NULL ENABLE, "I_CODE" VARCHAR2(30) NOT NULL ENABLE, "ITM_UNT"
 VARCHAR2(10), "I_QTY" NUMBER)  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;


CREATE TABLE "ARS_AUTO_SLS_ORDR_MST" ("DOC_NO" NUMBER(15, 0) NOT NULL ENABLE, "DOC_SRL"
 NUMBER(38, 0), "C_CODE" VARCHAR2(15), "DOC_SRL_REF" NUMBER(38, 0), "AD_U_ID" NUMBER(5,
 0), "AD_DATE" DATE, "PRCSS_FLG" NUMBER, "DOC_DATE" DATE, "DOC_NO_REF" NUMBER(15, 0)) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE
 "IAS_AR_DATA_TRNS" LOGGING NOCOMPRESS;


CREATE TABLE "ARS_CODE_DTL" ("CODE_TYP" NUMBER(5, 0), "CODE_NO" NUMBER(5, 0), "CODE_L_NM"
 VARCHAR2(60) NOT NULL ENABLE, "CODE_F_NM" VARCHAR2(60), "ORDR_NO" NUMBER(10, 0), "NOTES"
 VARCHAR2(250), "INACTIVE" NUMBER(1, 0), "INACTIVE_RES" VARCHAR2(250), "INACTIVE_DATE"
 DATE, "INACTIVE_U_ID" NUMBER(5, 0), "AD_U_ID" NUMBER(5, 0) NOT NULL ENABLE, "AD_DATE"
 DATE NOT NULL ENABLE, "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "UP_CNT" NUMBER(10, 0),
 "AD_TRMNL_NM" VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50))  PCTFREE 10 PCTUSED 40 INITRANS
 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;


CREATE TABLE "ARS_CODE_MST" ("CODE_TYP" NUMBER(5, 0), "TYP_L_NM" VARCHAR2(60) NOT NULL
 ENABLE, "TYP_F_NM" VARCHAR2(60) NOT NULL ENABLE, "ORDR_NO" NUMBER(10, 0), "AD_TRMNL_NM"
 VARCHAR2(50), "UP_TRMNL_NM" VARCHAR2(50), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0)
, "INACTIVE" NUMBER(1, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL
 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
 TABLESPACE "IAS_AR_INPT" LOGGING NOCOMPRESS;



CREATE TABLE "ARS_NEWS_CSS" ("NEWS_NO" NUMBER(38, 0), "NEWS_L_DSC" VARCHAR2(1000),
 "NEWS_F_DSC" VARCHAR2(1000), "F_DATE" DATE, "T_DATE" DATE, "INACTIVE" NUMBER(1, 0),
 "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE, "IMG_PATH" VARCHAR2(250), "LNK_YOUTUBE"
 VARCHAR2(250), "NEWS_DSC" VARCHAR2(3000), "LNK_WEB_SITE" VARCHAR2(250), "AD_U_ID"
 NUMBER(5, 0), "AD_DATE" DATE, "AD_TRMNL_NM" VARCHAR2(50), "UP_U_ID" NUMBER(5, 0),
 "UP_DATE" DATE, "UP_TRMNL_NM" VARCHAR2(50), "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10,
 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576
 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "IAS_AR_INPT"
 LOGGING NOCOMPRESS;



CREATE TABLE "ARS_PARA_CSS" ("PARA_NO" NUMBER(1, 0), "SHW_PSTD_ONLY_CST_STMNT" NUMBER(1,
 0), "AUTO_APPROVD" NUMBER(1, 0), "CUR_CODE" VARCHAR2(7), "SO_EXPIRE_AFTR_DAY" NUMBER(3,
 0), "QT_EXPIRE_AFTR_DAY" NUMBER(3, 0), "RSRVD_PRD_DAY" NUMBER(5, 0), "SO_TYPE" NUMBER(5,
 0), "SO_DSC" VARCHAR2(1000), "QT_TYPE" NUMBER(5, 0), "QT_DSC" VARCHAR2(1000), "CC_CODE"
 VARCHAR2(30), "PJ_NO" VARCHAR2(15), "ACTV_NO" VARCHAR2(15), "W_CODE" VARCHAR2(10),
 "BRN_USR" NUMBER(3, 0), "UP_U_ID" NUMBER(5, 0), "UP_DATE" DATE, "CMP_NO" NUMBER(3, 0)
 NOT NULL ENABLE, "BRN_YEAR" NUMBER(4, 0), "BRN_NO" NUMBER(6, 0) NOT NULL ENABLE,
 "UP_CNT" NUMBER(10, 0), "PR_REP" NUMBER(10, 0), "AD_TRMNL_NM" VARCHAR2(50),
 "UP_TRMNL_NM" VARCHAR2(50), "NEW_ITM_PRD_DAY" NUMBER(5, 0), "ITM_NOT_STORE_PRD_DAY"
 NUMBER(5, 0), "CONN_CST_ITM_ACTVTY" NUMBER(1, 0), "SO_QTY_STORE_MTHD" NUMBER(2, 0),
 "CST_LMT_SO_UNPRCSSD" NUMBER(5, 0))  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT) TABLESPACE "IAS_STP" LOGGING NOCOMPRESS;
