public class ItemLevelMeasure
{
    public short? IlevNo { get; private set; }
    public int? FlgValue { get; private set; }
    public string? FlgCode { get; private set; }
    public int? CompType { get; private set; }
    public short? ArgType { get; private set; }
    public int? FromAmtPer { get; private set; }
    public int? ToAmtPer { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? DocNo { get; private set; }
    public long DocSer { get; private set; }
    public bool? Used { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long DocSer { get; private set; }
    public string ICode { get; private set; }
    public string? ItmUnt { get; private set; }
    public int? PSize { get; private set; }
    public short? IlevNo { get; private set; }
    public int? ItmRatio { get; private set; }
    public short? ItmRatioDeg { get; private set; }
    public int? ProfitMarginRate { get; private set; }
    public short? ProfitMarginRateDeg { get; private set; }
    public int? DailySalesRate { get; private set; }
    public short? DailySalesRateDeg { get; private set; }
    public int? GenSalesRate { get; private set; }
    public short? GenSalesRateDeg { get; private set; }
    public int? NetSalesQty { get; private set; }
    public short? NetSalesQtyDeg { get; private set; }
    public int? NetSalesAmt { get; private set; }
    public short? NetSalesAmtDeg { get; private set; }
    public int? SaleRateFInc { get; private set; }
    public short? SaleRateFIncDeg { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public long DocSer { get; private set; }
    public DateTime DocDate { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public bool? UpCst { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string IName { get; private set; }
    public string? IEName { get; private set; }
    public string GCode { get; private set; }
    public string? GrpClassCode { get; private set; }
    public string? MngCode { get; private set; }
    public string? SubgCode { get; private set; }
    public int? ItemSize { get; private set; }
    public int? ItemType { get; private set; }
    public int? PrimaryCost { get; private set; }
    public int? ICwtavg { get; private set; }
    public string? IDesc { get; private set; }
    public string? AlterCode { get; private set; }
    public string? ManfCode { get; private set; }
    public bool? Blocked { get; private set; }
    public bool? Inactive { get; private set; }
    public string? InactiveRes { get; private set; }
    public DateTime? InactiveDate { get; private set; }
    public int? InactiveUId { get; private set; }
    public bool? ServiceItm { get; private set; }
    public bool? CashSale { get; private set; }
    public bool? NoReturnSale { get; private set; }
    public int? ReturnPeriod { get; private set; }
    public bool? KitItm { get; private set; }
    public bool? UseExpDate { get; private set; }
    public bool? UseBatchNo { get; private set; }
    public bool? UseSerialno { get; private set; }
    public bool? UseAttch { get; private set; }
    public bool? VatType { get; private set; }
    public decimal? VatPer { get; private set; }
    public bool? AllowDisc { get; private set; }
    public decimal? DiscPer { get; private set; }
    public bool? AllowDiscPi { get; private set; }
    public bool? RestItm { get; private set; }
    public decimal? DiscPerPi { get; private set; }
    public bool? AllowFreeQty { get; private set; }
    public decimal? FreeQtyPer { get; private set; }
    public bool? UseQtyFraction { get; private set; }
    public bool? UnderSelling { get; private set; }
    public int? GroupNo { get; private set; }
    public short? IlevNo { get; private set; }
    public string? IImg { get; private set; }
    public short? DayItmExpire { get; private set; }
    public short? MinLmtCostPer { get; private set; }
    public short? MaxLmtCostPer { get; private set; }
    public string? Field1 { get; private set; }
    public string? Field2 { get; private set; }
    public string? Field3 { get; private set; }
    public string? Field4 { get; private set; }
    public string? Field5 { get; private set; }
    public string? Field6 { get; private set; }
    public string? Field7 { get; private set; }
    public string? Field8 { get; private set; }
    public string? Field9 { get; private set; }
    public string? Field10 { get; private set; }
    public string? AssistantNo { get; private set; }
    public string? DetailNo { get; private set; }
    public int? LengthItm { get; private set; }
    public int? WidthItm { get; private set; }
    public int? HeightItm { get; private set; }
    public int? SizeItm { get; private set; }
    public int? AreaItm { get; private set; }
    public int? WeightItm { get; private set; }
    public string? SeasonItm { get; private set; }
    public string? OreItm { get; private set; }
    public string? MarkItm { get; private set; }
    public string? CompanyItm { get; private set; }
    public string? CountryItm { get; private set; }
    public DateTime? IncomeDate { get; private set; }
    public bool? Requirement { get; private set; }
    public bool? ItemStore { get; private set; }
    public bool? Assets { get; private set; }
    public bool? HasComm { get; private set; }
    public bool? CommType { get; private set; }
    public int? CommAmt { get; private set; }
    public int? ActivityNo { get; private set; }
    public string? VCode { get; private set; }
    public string? VndrACy { get; private set; }
    public int? VndrPrice { get; private set; }
    public string? VndrICode { get; private set; }
    public long? HotKey { get; private set; }
    public int? LowLmtPrntFrst { get; private set; }
    public int? LowLmtPrntScnd { get; private set; }
    public int? LowLmtAppReqAttch { get; private set; }
    public int? LowLmtNotAppReqAttch { get; private set; }
    public bool? ImpXls { get; private set; }
    public int? DocTypeRef { get; private set; }
    public long? DocNoRef { get; private set; }
    public long? DocSerRef { get; private set; }
    public bool? Weighted { get; private set; }
    public int? BalanceNo { get; private set; }
    public short? RetItmBeforExpPrd { get; private set; }
    public string? MsurUntRep { get; private set; }
    public int? PiBillNo { get; private set; }
    public bool? UseGrant { get; private set; }
    public short? GrantPeriod { get; private set; }
    public string? ItmColor { get; private set; }
    public string? ItmMeasure { get; private set; }
    public bool? UseWeight { get; private set; }
    public bool? ConnItmSoInc { get; private set; }
    public string? LnkBrchr { get; private set; }
    public string? LnkYoutube { get; private set; }
    public bool? UseEmpFlg { get; private set; }
    public bool? AltrMltFlg { get; private set; }
    public string? IFDesc { get; private set; }
    public bool? RestItmCombo { get; private set; }
    public bool? UsedItm { get; private set; }
    public bool? MrpItm { get; private set; }
    public short? MrpItmClss { get; private set; }
    public bool? CstPer { get; private set; }
    public int? PrftMrgnPrcnt { get; private set; }
    public bool? ChkAvlQtyInRes { get; private set; }
    public string? FoodGrpNo { get; private set; }
    public bool? UseAutoPstRmsDataToInv { get; private set; }
    public bool? HpsItm { get; private set; }
    public bool? GnrItmFlg { get; private set; }
    public int? PrcdrTyp { get; private set; }
    public string? HsnCode { get; private set; }
    public int? CstStandr { get; private set; }
    public int? CstLastProd { get; private set; }
    public int? ItmOrdrNo { get; private set; }
    public int? AdUId { get; private set; }
    public DateTime? AdDate { get; private set; }
    public int? UpUId { get; private set; }
    public DateTime? UpDate { get; private set; }
    public long? UpCnt { get; private set; }
    public int? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public string? ShrtItmLNm { get; private set; }
    public string? ShrtItmFNm { get; private set; }
    public int? ItmMinQty { get; private set; }
    public int? ItmMaxQty { get; private set; }
    public string? SubFoodGrpNo { get; private set; }
    public int? SmplTyp { get; private set; }
    public bool? RntSrvc { get; private set; }
    public bool? PstWithAdmt { get; private set; }
    public bool? PstWithRnt { get; private set; }
    public bool? HasPrcnt { get; private set; }
    public bool? BrthSrvc { get; private set; }
    public bool? EqpmntSrvc { get; private set; }
    public int? SrgryClss { get; private set; }
    public int? SrvcSort { get; private set; }
    public bool? CssdFlg { get; private set; }
    public bool? LndryFlg { get; private set; }
    public bool? UseQrCode { get; private set; }
    public int? ItmMinLmtQty { get; private set; }
    public int? ItmMaxLmtQty { get; private set; }
    public int? ItmRolLmtQty { get; private set; }
    public int? DfltAsmOrdQty { get; private set; }
    public bool? FillItmCmpnntInRmsInvc { get; private set; }
    public bool? UsePriceExpireDateOptional { get; private set; }
    public bool? UsePriceBatchNoOptional { get; private set; }
    public string? PrchsSrvcAcCode { get; private set; }
    public bool? FeedItmFlg { get; private set; }
    public bool? InsrncFlg { get; private set; }
    public string? GtinCode { get; private set; }
    public bool? UseSrlnoType { get; private set; }
    public bool? UseQrCodeType { get; private set; }
    public bool? QrCodeMthdNo { get; private set; }
    public bool? UseBatchNoAutoSqFlg { get; private set; }
    public long? BatchNoMthdNoSq { get; private set; }
    public int? ExecTat { get; private set; }
    public int? ExecTatUnt { get; private set; }
    public bool? HideItmChfScrFlg { get; private set; }
    public bool? KitItmClssfctnTyp { get; private set; }
    public int? StatclClss { get; private set; }
    public bool? GetAvlQtyFromCmpnntFlg { get; private set; }
    public int? KitItemRank { get; private set; }
    public int? LmtQtySalCst { get; private set; }
    public int? WghtValItm { get; private set; }
    public bool? UseItmInCssSysFlg { get; private set; }
    public int? InitPrimaryCost { get; private set; }
    public bool? ChkItmPcsMndtryFlg { get; private set; }
    public long? ExcdPer { get; private set; }
    public bool? UsedInKitItm { get; private set; }
    public bool? MwsChkFlg { get; private set; }
    public long? DfltTimeMnt { get; private set; }
    public int? LostPrcntInPrchs { get; private set; }
}