public class ItemGroupTree
{
    public string? GrpCode { get; private set; }
    public string? GrpCodeTree { get; private set; }
    public string? GrpName { get; private set; }
    public int? GrpLvl { get; private set; }
    public long? UpCnt { get; private set; }
    public long? PrRep { get; private set; }
    public string? AdTrmnlNm { get; private set; }
    public string? UpTrmnlNm { get; private set; }
    public long? IncNo { get; private set; }
    public long? IncSer { get; private set; }
    public string? ICode { get; private set; }
    public string ItmUnt { get; private set; }
    public int? IQty { get; private set; }
    public int? PSize { get; private set; }
    public int? PQty { get; private set; }
    public long? WCode { get; private set; }
    public string? CcCode { get; private set; }
    public string? PjNo { get; private set; }
    public string? ActvNo { get; private set; }
    public DateTime ExpireDate { get; private set; }
    public string BatchNo { get; private set; }
    public string? ItemDesc { get; private set; }
    public long? RcrdNo { get; private set; }
    public bool? UseAttch { get; private set; }
    public long? RecAttch { get; private set; }
    public int? ILength { get; private set; }
    public int? IWidth { get; private set; }
    public int? IHeight { get; private set; }
    public int? INumber { get; private set; }
    public int? WtQty { get; private set; }
    public string? WtUnt { get; private set; }
    public string? Barcode { get; private set; }
    public int? ArgmntNo { get; private set; }
    public int? ExternalPost { get; private set; }
    public short CmpNo { get; private set; }
    public int BrnNo { get; private set; }
    public short? BrnYear { get; private set; }
    public short? BrnUsr { get; private set; }
    public long? UpCnt { get; private set; }
    public int? DocSequence { get; private set; }
}